import { Question } from './types';

export const alkoholDrogerQuestions: Question[] = [
  {
    id: 'alk-1',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Vilken är promillegränsen för rattfylleri i Sverige?',
    options: ['0.0 promille', '0.2 promille', '0.5 promille'],
    correctIndex: 1,
    explanation: 'I Sverige är gränsen för rattfylleri 0,2 promille. Det räcker alltså med mycket lite alkohol för att det ska vara olagligt att köra.',
  },
  {
    id: 'alk-2',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Vid vilken promillehalt räknas det som grovt rattfylleri?',
    options: ['0.5 promille', '0.8 promille', '1.0 promille'],
    correctIndex: 2,
    explanation: 'Grovt rattfylleri gäller från 1,0 promille. Det kan även bedömas som grovt vid lägre promille om körningen var påtagligt påverkad eller farlig.',
  },
  {
    id: 'alk-3',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad är straffet för rattfylleri (0,2–1,0 promille)?',
    options: [
      'Enbart böter',
      'Böter eller fängelse i högst 6 månader',
      'Fängelse i minst 1 år',
    ],
    correctIndex: 1,
    explanation: 'Rattfylleri kan ge böter eller fängelse i högst 6 månader. Dessutom återkallas normalt körkortet.',
  },
  {
    id: 'alk-4',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad är straffet för grovt rattfylleri?',
    options: [
      'Böter och körkortsåterkallelse',
      'Fängelse i högst 2 år',
      'Fängelse i högst 6 månader',
    ],
    correctIndex: 1,
    explanation: 'Grovt rattfylleri kan ge fängelse i högst 2 år. Körkortet återkallas alltid och spärrtiden är normalt minst 24 månader.',
  },
  {
    id: 'alk-5',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Hur länge återkallas körkortet normalt vid rattfylleri (inte grovt)?',
    options: ['6 månader', '12 månader', '24 månader'],
    correctIndex: 1,
    explanation: 'Vid rattfylleri återkallas körkortet normalt i 12 månader. Tiden kan variera beroende på omständigheterna.',
  },
  {
    id: 'alk-6',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Hur länge återkallas körkortet normalt vid grovt rattfylleri?',
    options: ['12 månader', '24 månader', '36 månader'],
    correctIndex: 1,
    explanation: 'Vid grovt rattfylleri är den normala spärrtiden (återkallelsetiden) 24 månader. I allvarliga fall kan den bli längre.',
  },
  {
    id: 'alk-7',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad gäller om du kör bil efter att ha tagit narkotikaklassade läkemedel?',
    options: [
      'Det är alltid tillåtet om läkare skrivit ut dem',
      'Det kan räknas som drograttfylleri även om de är utskrivna',
      'Det är bara förbjudet om du tar mer än ordinerad dos',
    ],
    correctIndex: 1,
    explanation: 'Även läkemedel utskrivna av läkare kan ge drograttfylleri om de påverkar din körförmåga. Du ansvarar själv för att bedöma om du kan köra säkert.',
  },
  {
    id: 'alk-8',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad är en alkobom (alkolås vid färjeterminal)?',
    options: [
      'En bom som hindrar rattfulla förare vid en gränskontroll',
      'En slumpmässig alkoholkontroll vid färjeterminaler där förare blåser i ett alkolås för att få passera',
      'En poliskontroll som alltid finns vid alla hamnar',
    ],
    correctIndex: 1,
    explanation: 'Alkobommar finns vid vissa färjeterminaler i Sverige. Förare får blåsa i ett alkolås och bommen öppnas bara om provet visar godkänt resultat.',
  },
  {
    id: 'alk-9',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad innebär villkor om alkolås efter rattfylleri?',
    options: [
      'Du får köra bil med ett alkolås installerat istället för att få körkortet helt återkallat',
      'Du måste ha alkolås i 10 år',
      'Alkolås installeras automatiskt i alla bilar vid rattfylleridom',
    ],
    correctIndex: 0,
    explanation: 'Du kan ansöka om körkort med villkor om alkolås. Då får du köra med ett alkolås installerat i bilen under spärrtiden, istället för att helt sakna körkort.',
  },
  {
    id: 'alk-10',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Kan du dömas för rattfylleri om du kör med droger i blodet men inte känner dig påverkad?',
    options: [
      'Nej, du måste vara synbart påverkad',
      'Ja, det räcker med att ha narkotika i blodet',
      'Nej, det krävs ett vittnesmål',
    ],
    correctIndex: 1,
    explanation: 'Det råder nollgräns för narkotika i trafiken. Det räcker att narkotiskt ämne påvisas i blodet för att dömas för drograttfylleri.',
  },
  {
    id: 'alk-11',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad händer om du vägrar att lämna utandningsprov vid en poliskontroll?',
    options: [
      'Ingenting, det är frivilligt',
      'Polisen kan begära blodprov istället',
      'Du får automatiskt böter',
    ],
    correctIndex: 1,
    explanation: 'Om du vägrar utandningsprov kan polisen begära att du lämnar blodprov. Du kan inte undvika kontroll genom att vägra blåsa.',
  },
  {
    id: 'alk-12',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Hur lång tid tar det ungefär för kroppen att bryta ner en "starköl" (50 cl, 5%)?',
    options: [
      'Cirka 30 minuter',
      'Cirka 1,5–2 timmar',
      'Cirka 4 timmar',
    ],
    correctIndex: 1,
    explanation: 'Kroppen bryter ner cirka 0,1 promille per timme. En starköl (50 cl, 5%) ger ungefär 0,2–0,3 promille och tar ca 1,5–2 timmar att bryta ner helt.',
  },
  {
    id: 'alk-13',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Kan passageraren dömas för brott om föraren är berusad?',
    options: [
      'Nej, bara föraren ansvarar',
      'Ja, den som medvetet låter en berusad person köra kan dömas för medhjälp',
      'Ja, passageraren döms automatiskt',
    ],
    correctIndex: 1,
    explanation: 'Den som medvetet låter en berusad person köra, exempelvis genom att lämna över bilnycklarna, kan dömas för medhjälp till rattfylleri.',
  },
  {
    id: 'alk-14',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad gäller om du dricker alkohol kvällen innan och kör morgonen efter?',
    options: [
      'Du är alltid nykter efter en natts sömn',
      'Du kan fortfarande ha alkohol kvar i kroppen och riskerar rattfylleri',
      'Det är bara ett problem om du drack mer än 5 glas',
    ],
    correctIndex: 1,
    explanation: 'Alkoholen kan finnas kvar i kroppen långt efter att du slutat dricka. Många rattfyllerifall sker på morgonen efter en kväll med alkohol.',
  },
  {
    id: 'alk-15',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad krävs för att få tillbaka körkortet efter grovt rattfylleri?',
    options: [
      'Du ansöker bara om nytt körkort efter spärrtiden',
      'Du måste genomgå lämplighetsprövning och i vissa fall uppvisa nykterhetsintyg',
      'Du får automatiskt tillbaka körkortet efter spärrtiden',
    ],
    correctIndex: 1,
    explanation: 'Efter grovt rattfylleri krävs normalt en lämplighetsprövning hos Transportstyrelsen. Du kan behöva visa läkarintyg, nykterhetsintyg och genomgå nytt körkortsprov.',
  },
  {
    id: 'alk-16',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Hur påverkar alkohol din reaktionstid?',
    options: ['Den förkortas', 'Den förlängs avsevärt', 'Ingen påverkan'],
    correctIndex: 1,
    explanation: 'Alkohol försämrar reaktionsförmågan markant. Redan vid 0,2 promille påverkas uppmärksamheten.',
  },
  {
    id: 'alk-17',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Vad innebär "nollgränsen" för droger i trafiken?',
    options: ['Du får ha lite droger i blodet', 'Alla spår av narkotika i blodet ger drograttfylleri', 'Det beror på drogen'],
    correctIndex: 1,
    explanation: 'I Sverige gäller nolltolerans för narkotika i trafiken. Alla spår av narkotika ger drograttfylleri.',
  },
  {
    id: 'alk-18',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Hur lång tid tar det ungefär att bryta ner 1 glas vin (15 cl)?',
    options: ['Cirka 30 minuter', 'Cirka 1,5-2 timmar', 'Cirka 4 timmar'],
    correctIndex: 1,
    explanation: 'Kroppen bryter ner alkohol med ca 0,1 g/kg/timme. Ett glas vin tar ungefär 1,5-2 timmar att bryta ner.',
  },
  {
    id: 'alk-19',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Kan du förlora körkortet för drograttfylleri även om du inte kände dig påverkad?',
    options: ['Nej, bara om du kände dig påverkad', 'Ja, det räcker med att narkotika hittas i blodet', 'Bara vid upprepade tillfällen'],
    correctIndex: 1,
    explanation: 'Det spelar ingen roll om du känner dig påverkad — spår av narkotika i blodprovet räcker för fällande dom.',
  },
  {
    id: 'alk-20',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad är skillnaden mellan rattfylleri och grovt rattfylleri gällande promillegräns?',
    options: ['0,2-0,5 resp 0,5-1,0', '0,2-1,0 resp 1,0 och uppåt', '0,5-1,0 resp 1,5 och uppåt'],
    correctIndex: 1,
    explanation: 'Rattfylleri: 0,2-1,0 promille. Grovt rattfylleri: 1,0 promille och uppåt, eller om körningen var farlig.',
  },
  {
    id: 'alk-21',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Hur påverkar alkohol ditt omdöme i trafiken?',
    options: ['Du blir bättre på att bedöma risker', 'Du underskattar risker och överskattar din förmåga', 'Ingen påverkan på omdömet'],
    correctIndex: 1,
    explanation: 'Alkohol gör att du tar fler risker, överskattar din förmåga och underskattar faror.',
  },
  {
    id: 'alk-22',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad gäller om du tar receptbelagda sömnmedel och kör bil dagen efter?',
    options: ['Det är alltid okej', 'Du kan fortfarande vara påverkad — kontrollera bipacksedeln', 'Det gäller bara sömntabletter'],
    correctIndex: 1,
    explanation: 'Många sömnmedel kan påverka körförmågan långt in på dagen efter. Läs alltid bipacksedeln.',
  },
  {
    id: 'alk-23',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad innebär "alkolås-program" efter rattfylleri?',
    options: ['Du får köra utan körkort', 'Du kan ansöka om villkorligt körkort med alkolås i bilen', 'Det är obligatoriskt för alla'],
    correctIndex: 1,
    explanation: 'Efter rattfylleri kan du ansöka om villkorligt körkort med alkolås istället för att vara utan körkort under spärrtiden.',
  },
  {
    id: 'alk-24',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Kan man snabba på nedbrytningen av alkohol?',
    options: ['Ja, genom att dricka kaffe', 'Nej, levern bryter ner alkohol i fast takt', 'Ja, genom motion'],
    correctIndex: 1,
    explanation: 'Det finns inget sätt att snabba på alkoholnedbrytningen. Levern bryter ner ca 0,1 g/kg/timme oavsett vad du gör.',
  },
  {
    id: 'alk-25',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad gäller om du som förare misstänks vara påverkad av droger vid en kontroll?',
    options: ['Du kan vägra test', 'Polisen kan kräva blodprov', 'Bara utandningsprov krävs'],
    correctIndex: 1,
    explanation: 'Vid misstanke om drograttfylleri kan polisen beordra blodprov. Narkotika syns inte i utandningsprov.',
  },
  {
    id: 'alk-26',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Hur påverkar cannabis körförmågan?',
    options: ['Ingen märkbar påverkan', 'Sämre reaktionsförmåga, tidsuppfattning och koncentration', 'Bara positiv påverkan'],
    correctIndex: 1,
    explanation: 'Cannabis påverkar reaktionsförmåga, tidsuppfattning, koncentration och beslutsfattande — allvarligt i trafiken.',
  },
  {
    id: 'alk-27',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Vad är den vanligaste konsekvensen av rattfylleri (inte grovt)?',
    options: ['Fängelse', 'Böter eller villkorlig dom samt körkortsåterkallelse', 'Bara en varning'],
    correctIndex: 1,
    explanation: 'Rattfylleri ger vanligen böter eller villkorlig dom. Körkortet återkallas normalt i minst 12 månader.',
  },
  {
    id: 'alk-28',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Hur lång tid innan körning bör du sluta dricka alkohol?',
    options: ['4 timmar', 'Räkna inte med tid — räkna om du har 0,0 promille', '2 timmar'],
    correctIndex: 1,
    explanation: 'Tid räcker inte som mått. Räkna ut ungefärlig promille baserat på mängd, vikt och tid sedan sista alkoholen.',
  },
  {
    id: 'alk-29',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad händer med ditt försäkringsskydd om du orsakar en olycka under alkoholpåverkan?',
    options: ['Inget ändras', 'Försäkringsbolaget kan kräva regresskrav (betala tillbaka ersättningen)', 'Försäkringen gäller inte alls'],
    correctIndex: 1,
    explanation: 'Vid alkoholpåverkan kan försäkringsbolaget kräva dig på regress — du kan bli återbetalningsskyldig.',
  },
  {
    id: 'alk-30',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Vad ska du göra om en kompis som druckit vill köra?',
    options: ['Låta dem köra om de känner sig bra', 'Hindra dem och ordna alternativ transport', 'Det är deras val'],
    correctIndex: 1,
    explanation: 'Du bör hindra en berusad person från att köra. Erbjud alternativ: taxi, kollektivtrafik eller annan nykter förare.',
  },
  {
    id: 'alk-31',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Varför är risken för singelolyckor högre vid alkoholpåverkan?',
    options: ['Vägen blir halare', 'Alkoholen försämrar balans, koordination och riskbedömning', 'Det är bara en myt'],
    correctIndex: 1,
    explanation: 'Alkohol försämrar alla aspekter av körning — du håller sämre fil, missbedömer kurvor och reagerar sent.',
  },
  {
    id: 'alk-32',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vilken effekt har kombination av alkohol och läkemedel?',
    options: ['De tar ut varandra', 'Effekten kan förstärkas kraftigt — extremt farligt', 'Läkemedlet tar bort alkoholeffekten'],
    correctIndex: 1,
    explanation: 'Alkohol och många läkemedel förstärker varandras effekt. Kombinationen kan vara livsfarlig vid körning.',
  },
  {
    id: 'alk-33',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Hur påverkar en "bakfull" körförmågan?',
    options: ['Inte alls om du sovit', 'Bakfylla försämrar reaktionstid, koncentration och omdöme', 'Bara om du fortfarande har promille'],
    correctIndex: 1,
    explanation: 'Bakfylla påverkar körförmågan negativt oavsett kvarvarande promille. Trötthet och huvudvärk försämrar prestationen.',
  },
  {
    id: 'alk-34',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad gäller om du kör i ett annat EU-land — gäller Svenska promillegränsen?',
    options: ['Ja, svenska regler gäller alltid', 'Nej, det landets gräns gäller', 'EU har en gemensam gräns'],
    correctIndex: 1,
    explanation: 'I utlandet gäller det landets promillegräns. Många EU-länder har 0,5 promille, men det varierar.',
  },
  {
    id: 'alk-35',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad är "toleransutveckling" och varför är det farligt i trafiksammanhang?',
    options: ['Att man tål mer sol', 'Att man känner sig nykter trots hög promille — kroppen anpassar sig men förmågan är lika nedsatt', 'Att man kör bättre med övning'],
    correctIndex: 1,
    explanation: 'Vid toleransutveckling känner man sig mindre påverkad men körförmågan är lika nedsatt. Falsk trygghet leder till fler risker.',
  },
  {
    id: 'alk-36',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vilken promille har en normalstor man efter 2 starköl (à 50 cl, 5%)?',
    options: ['Cirka 0,3 promille', 'Cirka 0,6-0,8 promille', 'Cirka 1,2 promille'],
    correctIndex: 1,
    explanation: 'Ungefärlig promille beror på vikt och tid, men 2 starköl ger normalt 0,6-0,8 promille hos en man på ca 80 kg.',
  },
  {
    id: 'alk-37',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Kan man bli av med körkortet för narkotikabrott även om man inte kört bil?',
    options: ['Nej, bara vid rattfylleri', 'Ja, narkotikabrott kan påverka körkortsbedömningen', 'Bara vid upprepade brott'],
    correctIndex: 1,
    explanation: 'Transportstyrelsen kan ifrågasätta din lämplighet att ha körkort vid narkotikabrott, även utan koppling till körning.',
  },
  {
    id: 'alk-38',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Hur påverkar kokain körförmågan?',
    options: ['Gör dig till en bättre förare', 'Ger falsk självsäkerhet, aggressivitet och sämre omdöme — extremt farligt', 'Ingen påverkan'],
    correctIndex: 1,
    explanation: 'Kokain ger falsk känsla av kontroll, ökar aggressivitet och risktagande. Nedgången efteråt är också farlig.',
  },
  {
    id: 'alk-39',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad gör polisen vid en nykterhetskontroll (razzia)?',
    options: ['Kontrollerar körkortet', 'Utandningsprov för att mäta eventuell alkohol', 'Kontrollerar hastigheten'],
    correctIndex: 1,
    explanation: 'Vid nykterhetskontroll blåser du i en alkometer som mäter alkoholhalten i utandningsluften.',
  },
  {
    id: 'alk-40',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Påverkar alkohol din syn?',
    options: ['Nej, bara reaktionstiden', 'Ja, alkohol försämrar mörkerseende och ger tunnelseende', 'Bara vid hög promille'],
    correctIndex: 1,
    explanation: 'Alkohol försämrar mörkerseende, ögats anpassning, djupseende och ger tunnelseende — redan vid låg promille.',
  },
  {
    id: 'alk-41',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Kan du dömas för rattfylleri om du sitter och sover i bilen med motorn på?',
    options: ['Nej, du kör ju inte', 'Ja, du kan anses ha haft uppsåt att köra', 'Bara om bilen rörde sig'],
    correctIndex: 1,
    explanation: 'Du kan dömas om omständigheterna tyder på att du haft uppsåt att köra — t.ex. motor på, sittande i förarplats.',
  },
  {
    id: 'alk-42',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad gäller för mediciner med varningstriangel på förpackningen?',
    options: ['Du får inte köra bil alls', 'Du ska kontrollera med läkare om du kan köra', 'Varningstriangeln handlar inte om körning'],
    correctIndex: 1,
    explanation: 'Varningstriangel på läkemedel betyder att det KAN påverka körförmågan. Fråga läkare eller apotekspersonal.',
  },
  {
    id: 'alk-43',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Vid vilken tidpunkt på dygnet sker flest alkoholrelaterade olyckor?',
    options: ['Lunchtid', 'Natt och tidig morgon (fredag-söndag)', 'Eftermiddag'],
    correctIndex: 1,
    explanation: 'De flesta alkoholrelaterade olyckor sker på nätter och tidiga morgnar under helger.',
  },
  {
    id: 'alk-44',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad innebär "drograttfylleri av normalgraden"?',
    options: ['Små mängder droger i blodet', 'Narkotika i blodet utan att det anses grovt — samma straffskala som rattfylleri', 'Att man kört under drogpåverkan många gånger'],
    correctIndex: 1,
    explanation: 'Drograttfylleri av normalgraden behandlas som rattfylleri med liknande straff: böter/fängelse + körkortsåterkallelse.',
  },
  {
    id: 'alk-45',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Hur påverkar energidrycker i kombination med alkohol körförmågan?',
    options: ['Energidrycken motverkar alkoholens effekt', 'Man känner sig piggare men är lika påverkad — farlig falsk trygghet', 'Ingen extra risk'],
    correctIndex: 1,
    explanation: 'Koffeinet i energidrycken maskerar tröttheten men alkoholens effekt på omdöme och reaktion kvarstår.',
  },
  {
    id: 'alk-46',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Hur många procent av dödsolyckorna i Sverige involverar alkohol eller droger?',
    options: ['Cirka 5%', 'Cirka 20-25%', 'Cirka 50%'],
    correctIndex: 1,
    explanation: 'Ungefär 20-25% av alla dödsolyckor i trafiken involverar alkohol- eller drogpåverkan.',
  },
  {
    id: 'alk-47',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Kan passageraren bli straffad om föraren är berusad och orsakar en olycka?',
    options: ['Ja, medhjälp till rattfylleri kan ge straff', 'Nej, bara föraren döms', 'Bara om passageraren ägde alkoholen'],
    correctIndex: 0,
    explanation: 'En passagerare som uppmuntrar en berusad person att köra kan i teorin dömas för medhjälp till brott.',
  },
  {
    id: 'alk-48',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad ska du göra om du inser att du druckit för mycket och redan kört halvvägs?',
    options: ['Köra färdigt snabbt', 'Stanna bilen säkert och ordna alternativ transport', 'Köra sakta'],
    correctIndex: 1,
    explanation: 'Stanna bilen på en säker plats omedelbart och ordna taxi eller annan transport.',
  },
  {
    id: 'alk-49',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad innebär "bakfylle-rattfylleri"?',
    options: ['En myt', 'Att man fortfarande har promille morgonen efter drickande och kör — det är fortfarande rattfylleri', 'Att man kör bakfull men utan promille'],
    correctIndex: 1,
    explanation: 'Om du har kvar promille morgonen efter räknas det som rattfylleri. Många underskattar hur länge alkohol finns kvar.',
  },
  {
    id: 'alk-50',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Vad bör du göra om du ska köra och blir erbjuden alkohol?',
    options: ['Ta ett litet glas — det gör inget', 'Tacka nej — som förare ska du vara helt nykter', 'Bara om det är vin'],
    correctIndex: 1,
    explanation: 'Ska du köra ska du inte dricka alls. Redan en liten mängd påverkar ditt omdöme och kan ge promille.',
  },
];
