import { Question } from './types';

export const alkoholDrogerQuestions: Question[] = [
  {
    id: 'alk-1',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Vilken är promillegränsen för rattfylleri i Sverige?',
    options: ['0.0 promille', '0.2 promille', '0.5 promille'],
    correctIndex: 1,
    explanation: 'I Sverige är gränsen för rattfylleri 0,2 promille. Det räcker alltså med mycket lite alkohol för att det ska vara olagligt att köra.',
  },
  {
    id: 'alk-2',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Vid vilken promillehalt räknas det som grovt rattfylleri?',
    options: ['0.5 promille', '0.8 promille', '1.0 promille'],
    correctIndex: 2,
    explanation: 'Grovt rattfylleri gäller från 1,0 promille. Det kan även bedömas som grovt vid lägre promille om körningen var påtagligt påverkad eller farlig.',
  },
  {
    id: 'alk-3',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad är straffet för rattfylleri (0,2–1,0 promille)?',
    options: [
      'Enbart böter',
      'Böter eller fängelse i högst 6 månader',
      'Fängelse i minst 1 år',
    ],
    correctIndex: 1,
    explanation: 'Rattfylleri kan ge böter eller fängelse i högst 6 månader. Dessutom återkallas normalt körkortet.',
  },
  {
    id: 'alk-4',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad är straffet för grovt rattfylleri?',
    options: [
      'Böter och körkortsåterkallelse',
      'Fängelse i högst 2 år',
      'Fängelse i högst 6 månader',
    ],
    correctIndex: 1,
    explanation: 'Grovt rattfylleri kan ge fängelse i högst 2 år. Körkortet återkallas alltid och spärrtiden är normalt minst 24 månader.',
  },
  {
    id: 'alk-5',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Hur länge återkallas körkortet normalt vid rattfylleri (inte grovt)?',
    options: ['6 månader', '12 månader', '24 månader'],
    correctIndex: 1,
    explanation: 'Vid rattfylleri återkallas körkortet normalt i 12 månader. Tiden kan variera beroende på omständigheterna.',
  },
  {
    id: 'alk-6',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Hur länge återkallas körkortet normalt vid grovt rattfylleri?',
    options: ['12 månader', '24 månader', '36 månader'],
    correctIndex: 1,
    explanation: 'Vid grovt rattfylleri är den normala spärrtiden (återkallelsetiden) 24 månader. I allvarliga fall kan den bli längre.',
  },
  {
    id: 'alk-7',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad gäller om du kör bil efter att ha tagit narkotikaklassade läkemedel?',
    options: [
      'Det är alltid tillåtet om läkare skrivit ut dem',
      'Det kan räknas som drograttfylleri även om de är utskrivna',
      'Det är bara förbjudet om du tar mer än ordinerad dos',
    ],
    correctIndex: 1,
    explanation: 'Även läkemedel utskrivna av läkare kan ge drograttfylleri om de påverkar din körförmåga. Du ansvarar själv för att bedöma om du kan köra säkert.',
  },
  {
    id: 'alk-8',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad är en alkobom (alkolås vid färjeterminal)?',
    options: [
      'En bom som hindrar rattfulla förare vid en gränskontroll',
      'En slumpmässig alkoholkontroll vid färjeterminaler där förare blåser i ett alkolås för att få passera',
      'En poliskontroll som alltid finns vid alla hamnar',
    ],
    correctIndex: 1,
    explanation: 'Alkobommar finns vid vissa färjeterminaler i Sverige. Förare får blåsa i ett alkolås och bommen öppnas bara om provet visar godkänt resultat.',
  },
  {
    id: 'alk-9',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad innebär villkor om alkolås efter rattfylleri?',
    options: [
      'Du får köra bil med ett alkolås installerat istället för att få körkortet helt återkallat',
      'Du måste ha alkolås i 10 år',
      'Alkolås installeras automatiskt i alla bilar vid rattfylleridom',
    ],
    correctIndex: 0,
    explanation: 'Du kan ansöka om körkort med villkor om alkolås. Då får du köra med ett alkolås installerat i bilen under spärrtiden, istället för att helt sakna körkort.',
  },
  {
    id: 'alk-10',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Kan du dömas för rattfylleri om du kör med droger i blodet men inte känner dig påverkad?',
    options: [
      'Nej, du måste vara synbart påverkad',
      'Ja, det räcker med att ha narkotika i blodet',
      'Nej, det krävs ett vittnesmål',
    ],
    correctIndex: 1,
    explanation: 'Det råder nollgräns för narkotika i trafiken. Det räcker att narkotiskt ämne påvisas i blodet för att dömas för drograttfylleri.',
  },
  {
    id: 'alk-11',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad händer om du vägrar att lämna utandningsprov vid en poliskontroll?',
    options: [
      'Ingenting, det är frivilligt',
      'Polisen kan begära blodprov istället',
      'Du får automatiskt böter',
    ],
    correctIndex: 1,
    explanation: 'Om du vägrar utandningsprov kan polisen begära att du lämnar blodprov. Du kan inte undvika kontroll genom att vägra blåsa.',
  },
  {
    id: 'alk-12',
    category: 'alkohol-droger',
    difficulty: 'easy',
    question: 'Hur lång tid tar det ungefär för kroppen att bryta ner en "starköl" (50 cl, 5%)?',
    options: [
      'Cirka 30 minuter',
      'Cirka 1,5–2 timmar',
      'Cirka 4 timmar',
    ],
    correctIndex: 1,
    explanation: 'Kroppen bryter ner cirka 0,1 promille per timme. En starköl (50 cl, 5%) ger ungefär 0,2–0,3 promille och tar ca 1,5–2 timmar att bryta ner helt.',
  },
  {
    id: 'alk-13',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Kan passageraren dömas för brott om föraren är berusad?',
    options: [
      'Nej, bara föraren ansvarar',
      'Ja, den som medvetet låter en berusad person köra kan dömas för medhjälp',
      'Ja, passageraren döms automatiskt',
    ],
    correctIndex: 1,
    explanation: 'Den som medvetet låter en berusad person köra, exempelvis genom att lämna över bilnycklarna, kan dömas för medhjälp till rattfylleri.',
  },
  {
    id: 'alk-14',
    category: 'alkohol-droger',
    difficulty: 'medium',
    question: 'Vad gäller om du dricker alkohol kvällen innan och kör morgonen efter?',
    options: [
      'Du är alltid nykter efter en natts sömn',
      'Du kan fortfarande ha alkohol kvar i kroppen och riskerar rattfylleri',
      'Det är bara ett problem om du drack mer än 5 glas',
    ],
    correctIndex: 1,
    explanation: 'Alkoholen kan finnas kvar i kroppen långt efter att du slutat dricka. Många rattfyllerifall sker på morgonen efter en kväll med alkohol.',
  },
  {
    id: 'alk-15',
    category: 'alkohol-droger',
    difficulty: 'hard',
    question: 'Vad krävs för att få tillbaka körkortet efter grovt rattfylleri?',
    options: [
      'Du ansöker bara om nytt körkort efter spärrtiden',
      'Du måste genomgå lämplighetsprövning och i vissa fall uppvisa nykterhetsintyg',
      'Du får automatiskt tillbaka körkortet efter spärrtiden',
    ],
    correctIndex: 1,
    explanation: 'Efter grovt rattfylleri krävs normalt en lämplighetsprövning hos Transportstyrelsen. Du kan behöva visa läkarintyg, nykterhetsintyg och genomgå nytt körkortsprov.',
  },
];
