import { Question } from './types';

export const cykelMopedQuestions: Question[] = [
  {
    id: 'cym-1',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Vilken ålder krävs för att köra moped klass I?',
    options: ['14 år', '15 år', '16 år'],
    correctIndex: 1,
    explanation: 'Moped klass I (max 45 km/h) kräver AM-körkort och minst 15 års ålder.',
  },
  {
    id: 'cym-2',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Vilken ålder krävs för att köra moped klass II?',
    options: ['12 år', '15 år', '18 år'],
    correctIndex: 1,
    explanation: 'Moped klass II (max 25 km/h) kräver minst 15 års ålder men inget körkort.',
  },
  {
    id: 'cym-3',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Måste cyklister följa samma trafikregler som bilar?',
    options: ['Nej, cyklister har egna regler', 'Ja, i princip — cykeln är ett fordon', 'Bara i korsningar'],
    correctIndex: 1,
    explanation: 'Cykeln räknas som fordon och cyklister ska följa trafikregler — högerregel, signaler, väjningsplikt osv.',
  },
  {
    id: 'cym-4',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Måste du ha hjälm när du cyklar?',
    options: ['Ja, alla måste', 'Barn under 15 år måste, för vuxna är det frivilligt', 'Nej, aldrig'],
    correctIndex: 1,
    explanation: 'Hjälmlagen gäller barn under 15 år. Vuxna rekommenderas starkt att använda hjälm.',
  },
  {
    id: 'cym-5',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Var ska en moped klass II köra?',
    options: ['På körbanan med bilarna', 'På cykelbanan om det finns, annars körbanan', 'Bara på trottoaren'],
    correctIndex: 1,
    explanation: 'Moped klass II ska köra på cykelbana om det finns. Om inte, körbanan så långt till höger som möjligt.',
  },
  {
    id: 'cym-6',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Var ska en moped klass I köra?',
    options: ['På cykelbanan', 'På körbanan med övrig trafik', 'På trottoaren'],
    correctIndex: 1,
    explanation: 'Moped klass I (snabbare) ska köra på körbanan med övrig trafik, inte på cykelbanan.',
  },
  {
    id: 'cym-7',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Vilken belysning krävs på en cykel i mörker?',
    options: ['Bara reflex', 'Vitt ljus fram, rött ljus bak, reflexer', 'Inget krävs'],
    correctIndex: 1,
    explanation: 'I mörker krävs vitt/gult ljus fram, rött ljus bak, reflexer (fram, bak, sidor, pedaler).',
  },
  {
    id: 'cym-8',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Får en cyklist köra mot enkelriktat?',
    options: ['Ja, alltid', 'Bara om tilläggstavla "Gäller ej cykel" finns', 'Nej, aldrig'],
    correctIndex: 1,
    explanation: 'Cyklister får bara köra mot enkelriktat om en tilläggstavla undantar dem.',
  },
  {
    id: 'cym-9',
    category: 'cykel-moped',
    difficulty: 'hard',
    question: 'Vad gäller om en cyklist cyklar på vägen trots att det finns cykelbana?',
    options: ['Det är tillåtet', 'Cyklisten ska använda cykelbanan om det finns en', 'Bara om cykelbanan är full'],
    correctIndex: 1,
    explanation: 'Om det finns en skyltad cykelbana ska cyklister använda den. Det är inte tillåtet att cykla på körbanan istället.',
  },
  {
    id: 'cym-10',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Får du cykla med hörlurar?',
    options: ['Ja, det är lagligt men inte rekommenderat', 'Nej, det är förbjudet', 'Bara med en hörlur'],
    correctIndex: 0,
    explanation: 'Det finns inget förbud mot hörlurar vid cykling, men det rekommenderas inte då det minskar din hörsel.',
  },
  {
    id: 'cym-11',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Krävs hjälm vid mopedkörning klass I?',
    options: ['Nej', 'Ja, godkänd hjälm krävs', 'Bara utanför tätort'],
    correctIndex: 1,
    explanation: 'Vid körning av moped klass I krävs godkänd hjälm.',
  },
  {
    id: 'cym-12',
    category: 'cykel-moped',
    difficulty: 'hard',
    question: 'Vad gäller om en moped klass I är trimmad att gå fortare än 45 km/h?',
    options: ['Det är okej', 'Den räknas som motorcykel och kräver A-körkort', 'Bara böter'],
    correctIndex: 1,
    explanation: 'En trimmad moped klass I som överstiger 45 km/h klassas om till motorcykel. Det är olagligt och kräver annat körkort.',
  },
  {
    id: 'cym-13',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Får du ha passagerare på cykeln?',
    options: ['Ja, alltid', 'Bara om cykeln har en godkänd passagerarsits', 'Nej, aldrig'],
    correctIndex: 1,
    explanation: 'Du får ha passagerare bara om cykeln har en godkänd sits (t.ex. barnsits eller pakethållarsits).',
  },
  {
    id: 'cym-14',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Vad är en "elcykel" och vilka regler gäller?',
    options: ['Samma som motorcykel', 'Cykel med elmotor max 250W som assisterar upp till 25 km/h — samma regler som vanlig cykel', 'Kräver körkort'],
    correctIndex: 1,
    explanation: 'En elcykel (max 250W, assisterar till 25 km/h) räknas som vanlig cykel. Inget körkort eller hjälmplikt (för vuxna).',
  },
  {
    id: 'cym-15',
    category: 'cykel-moped',
    difficulty: 'hard',
    question: 'Vad gäller för elsparkcyklar i trafiken?',
    options: ['Samma som bilar', 'Räknas som cykel — ska följa cykelregler och ha belysning', 'Inga regler finns'],
    correctIndex: 1,
    explanation: 'Elsparkcyklar klassas som cyklar om de har max 250W motor och 20 km/h. De ska följa cykelreglerna.',
  },
  {
    id: 'cym-16',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Ska en cyklist blinka med handen vid sväng?',
    options: ['Nej, det behövs inte', 'Ja, cyklister ska visa tecken vid sväng', 'Bara i korsningar'],
    correctIndex: 1,
    explanation: 'Cyklister ska visa tecken med handen vid sväng och filbyte för att varna andra trafikanter.',
  },
  {
    id: 'cym-17',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Får du cykla på trottoaren?',
    options: ['Ja, alltid', 'Nej, om du inte är barn (under ca 8 år) eller det är enda säkra alternativet', 'Ja, om du cyklar sakta'],
    correctIndex: 1,
    explanation: 'Vuxna får normalt inte cykla på trottoaren. Små barn kan göra det men ska visa hänsyn för gående.',
  },
  {
    id: 'cym-18',
    category: 'cykel-moped',
    difficulty: 'hard',
    question: 'Vad gäller vid en cykelöverfart (markerad med vita fyrkanter och cykelljus)?',
    options: ['Bilisten har alltid företräde', 'Cyklisten har företräde — bilister ska stanna', 'Ingen har företräde'],
    correctIndex: 1,
    explanation: 'Vid en cykelöverfart (signalreglerad eller skyltad med särskilt märke) har cyklister företräde.',
  },
  {
    id: 'cym-19',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Får du cykla bredvid en annan cyklist?',
    options: ['Ja, alltid', 'Ja, om det inte hindrar annan trafik', 'Nej, aldrig'],
    correctIndex: 1,
    explanation: 'Cyklister får cykla bredvid varandra om det inte skapar fara eller hinder för andra trafikanter.',
  },
  {
    id: 'cym-20',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Vilken maxhastighet gäller för moped klass II?',
    options: ['45 km/h', '25 km/h', '30 km/h'],
    correctIndex: 1,
    explanation: 'Moped klass II är konstruerad för max 25 km/h.',
  },
  {
    id: 'cym-21',
    category: 'cykel-moped',
    difficulty: 'hard',
    question: 'Vad gäller om du som bilist ska svänga höger och en cyklist cyklar rakt fram i cykelfältet till höger?',
    options: ['Du har företräde', 'Cyklisten har företräde — du ska väja vid sväng', 'Den som kom först'],
    correctIndex: 1,
    explanation: 'Vid sväng har du väjningsplikt mot cyklister som kör rakt fram i cykelfält eller på cykelbana.',
  },
  {
    id: 'cym-22',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Vad ska du som bilist tänka på vid omkörning av en cyklist?',
    options: ['Kör förbi nära', 'Håll gott avstånd (minst 1,5 m) och sänk hastigheten', 'Tuta och kör om'],
    correctIndex: 1,
    explanation: 'Ge cyklisten gott utrymme — minst 1,5 meter sidoavstånd. Sänk hastigheten vid passering.',
  },
  {
    id: 'cym-23',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Får cyklister köra i rondeller?',
    options: ['Nej', 'Ja, cyklar är fordon och får köra i rondeller', 'Bara om det finns cykelfält'],
    correctIndex: 1,
    explanation: 'Cyklister får köra i rondeller på körbanan. De följer samma regler — väjningsplikt vid infart.',
  },
  {
    id: 'cym-24',
    category: 'cykel-moped',
    difficulty: 'hard',
    question: 'Vad händer juridiskt om du kör en oregistrerad moped klass I på vägen?',
    options: ['Bara böter', 'Det kan räknas som olovlig körning och mopeden kan beslagtas', 'Inget händer'],
    correctIndex: 1,
    explanation: 'Moped klass I ska vara registrerad och försäkrad. Oregistrerad moped kan leda till beslag och böter.',
  },
  {
    id: 'cym-25',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Får du prata i mobiltelefon medan du cyklar?',
    options: ['Ja, det finns inget förbud', 'Nej, det är förbjudet', 'Bara med handsfree'],
    correctIndex: 0,
    explanation: 'Det finns inget specifikt förbud mot mobilanvändning vid cykling, men det rekommenderas starkt att låta bli.',
  },
  {
    id: 'cym-26',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Gäller promillegränsen för cyklister?',
    options: ['Nej', 'Ja, men det är inte rattfylleri — det kan vara "cykling i berusat tillstånd"', 'Samma som för bilister'],
    correctIndex: 1,
    explanation: 'Du kan bötfällas för cykling i berusat tillstånd, men det ger inte rattfylleridom som vid bilkörning.',
  },
  {
    id: 'cym-27',
    category: 'cykel-moped',
    difficulty: 'hard',
    question: 'Vad är en "speed pedelec" och vilka regler gäller?',
    options: ['Vanlig elcykel', 'Elcykel med motorassistans upp till 45 km/h — räknas som moped klass I', 'En snabb cykel'],
    correctIndex: 1,
    explanation: 'En speed pedelec assisterar upp till 45 km/h och klassas som moped klass I. Kräver AM-körkort, hjälm och registrering.',
  },
  {
    id: 'cym-28',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Vad ska du göra om du cyklar och närmar dig ett övergångsställe?',
    options: ['Cykla över snabbt', 'Kliva av cykeln och leda den om du vill ha fotgängarens företräde', 'Cykla bredvid övergångsstället'],
    correctIndex: 1,
    explanation: 'Om du vill ha företräde som fotgängare på ett övergångsställe ska du kliva av och leda cykeln.',
  },
  {
    id: 'cym-29',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Krävs försäkring för moped klass I?',
    options: ['Nej', 'Ja, trafikförsäkring krävs', 'Bara om den kör på motorväg'],
    correctIndex: 1,
    explanation: 'Moped klass I ska ha trafikförsäkring. Det är olagligt att köra utan.',
  },
  {
    id: 'cym-30',
    category: 'cykel-moped',
    difficulty: 'hard',
    question: 'Vad gäller om en cyklist orsakar en trafikolycka?',
    options: ['Cyklisten har inget ansvar', 'Cyklisten kan bli skadeståndsskyldig precis som en bilist', 'Bara bilisten bär ansvar'],
    correctIndex: 1,
    explanation: 'Cyklister har samma ansvar som andra trafikanter. Vid vållande av olycka kan de bli skadestånds- och straffrättsligt ansvariga.',
  },
  {
    id: 'cym-31',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Ska du kontrollera bromsarna på cykeln regelbundet?',
    options: ['Nej, det behövs inte', 'Ja, cykeln ska ha fungerande bromsar', 'Bara om du cyklar i trafik'],
    correctIndex: 1,
    explanation: 'En cykel ska ha fungerande bromsar. Kontrollera dem regelbundet — det är ett lagkrav.',
  },
  {
    id: 'cym-32',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Gäller högerregeln för cyklister?',
    options: ['Nej', 'Ja, cyklister är fordon och högerregeln gäller', 'Bara på cykelbanor'],
    correctIndex: 1,
    explanation: 'Högerregeln gäller för cyklister precis som för alla andra fordon i korsningar utan skyltar.',
  },
  {
    id: 'cym-33',
    category: 'cykel-moped',
    difficulty: 'hard',
    question: 'Vad gäller för "cykelfält" (del av körbanan markerad för cyklar)?',
    options: ['Bilar får köra där', 'Bilar får normalt inte köra i cykelfältet', 'Det är bara dekorativt'],
    correctIndex: 1,
    explanation: 'Cykelfält är en del av körbanan reserverad för cyklar. Bilar får normalt inte köra eller parkera i cykelfältet.',
  },
  {
    id: 'cym-34',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Måste moped klass I ha fungerande belysning?',
    options: ['Nej', 'Ja, halvljus, bakljus, blinkers och bromsljus krävs', 'Bara blinkers'],
    correctIndex: 1,
    explanation: 'Moped klass I ska ha fullständig belysning: halvljus, bakljus, blinkers och bromsljus.',
  },
  {
    id: 'cym-35',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Du öppnar bildörren och en cyklist krockar med dörren. Vems fel är det?',
    options: ['Cyklistens', 'Ditt — du ska kontrollera att det är fritt innan du öppnar dörren', 'Ingens'],
    correctIndex: 1,
    explanation: 'Den som öppnar dörren ansvarar för att det är säkert. "Dörrning" av cyklister är ett vanligt problem.',
  },
  {
    id: 'cym-36',
    category: 'cykel-moped',
    difficulty: 'hard',
    question: 'Vad innebär "cykelbox" vid en korsning med trafikljus?',
    options: ['Låda för cykelreparation', 'Markerat område framför bilarna där cyklister kan ställa sig vid rött ljus', 'Cykelparkering'],
    correctIndex: 1,
    explanation: 'Cykelboxen ger cyklister plats framför bilkön vid rött ljus — de blir synliga och kan starta före bilarna.',
  },
  {
    id: 'cym-37',
    category: 'cykel-moped',
    difficulty: 'easy',
    question: 'Ska du använda ringklocka på cykeln?',
    options: ['Nej, det är bara artigt', 'Ja, det är ett lagkrav att ha ringklocka', 'Bara om du vill'],
    correctIndex: 1,
    explanation: 'Enligt lag ska en cykel ha ringklocka eller signalhorn.',
  },
  {
    id: 'cym-38',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Får du dra en cykelvagn (barnvagn/lastvagn) efter cykeln?',
    options: ['Nej', 'Ja, om den har reflex och belysning vid mörker', 'Bara på cykelbana'],
    correctIndex: 1,
    explanation: 'Cykelvagnar är tillåtna men ska ha reflexer och belysning i mörker.',
  },
  {
    id: 'cym-39',
    category: 'cykel-moped',
    difficulty: 'hard',
    question: 'Vad gäller om en moped klass II kör på väg med 70 km/h?',
    options: ['Det är okej', 'Moped klass II får normalt inte köra på vägar med högre hastighetsgräns än 50 km/h', 'Bara om det inte finns cykelbana'],
    correctIndex: 1,
    explanation: 'Moped klass II ska normalt inte köra på vägar med hastighetsbegränsning högre än 50 km/h.',
  },
  {
    id: 'cym-40',
    category: 'cykel-moped',
    difficulty: 'medium',
    question: 'Hur ska du som bilist bete dig vid en "cykelgata"?',
    options: ['Kör som vanligt', 'Cyklister har företräde — du ska anpassa dig efter cyklisterna', 'Cyklister ska väja för dig'],
    correctIndex: 1,
    explanation: 'På en cykelgata har cyklister företräde. Bilar som är tillåtna ska anpassa hastighet och beteende efter cykeltrafiken.',
  },
];
