import { Question } from './types';

export const fordonTeknikQuestions: Question[] = [
  {
    id: 'ftk-1',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad är det lagliga minimikravet för mönsterdjup på däck?',
    options: [
      '1,0 mm',
      '1,6 mm',
      '3,0 mm',
    ],
    correctIndex: 1,
    explanation:
      'Enligt lag måste mönsterdjupet vara minst 1,6 mm. Vid vinterväglag rekommenderas dock minst 3 mm för bra grepp.',
  },
  {
    id: 'ftk-2',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Under vilken period måste vinterdäck användas vid vinterväglag?',
    options: [
      '1 november – 31 mars',
      '1 december – 31 mars',
      '1 oktober – 30 april',
    ],
    correctIndex: 1,
    explanation:
      'Vinterdäck är obligatoriska vid vinterväglag under perioden 1 december – 31 mars. Utanför denna period krävs de enbart om det råder vinterväglag.',
  },
  {
    id: 'ftk-3',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad kan felaktigt däcktryck leda till?',
    options: [
      'Bättre väggrepp',
      'Ökad bränsleförbrukning och ojämnt däckslitage',
      'Snabbare acceleration',
    ],
    correctIndex: 1,
    explanation:
      'För lågt däcktryck ökar rullmotståndet, bränsleförbrukningen och ger ojämnt slitage. Det försämrar även köregenskaper och kan orsaka överhettning.',
  },
  {
    id: 'ftk-4',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad betyder en röd varningslampa i instrumentpanelen?',
    options: [
      'Ett mindre fel som kan åtgärdas senare',
      'Ett allvarligt fel – stanna och kontrollera fordonet',
      'Normal driftindikation',
    ],
    correctIndex: 1,
    explanation:
      'Röda varningslampor indikerar allvarliga fel som kräver omedelbar åtgärd, till exempel oljetryck, laddning eller bromsfel.',
  },
  {
    id: 'ftk-5',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Varför ska du kontrollera motoroljan regelbundet?',
    options: [
      'För att oljan påverkar bilens färg',
      'För att otillräcklig olja kan orsaka allvarliga motorskador',
      'Det behöver bara göras vid besiktning',
    ],
    correctIndex: 1,
    explanation:
      'Motoroljan smörjer och kyler motorn. För låg oljenivå kan leda till överhettning och allvarliga skador. Kontrollera nivån regelbundet.',
  },
  {
    id: 'ftk-6',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad händer om kylvätskenivån är för låg?',
    options: [
      'Bilen går tystare',
      'Motorn kan överhettas och skadas allvarligt',
      'Bränsleförbrukningen minskar',
    ],
    correctIndex: 1,
    explanation:
      'Kylvätskan reglerar motorns temperatur. Om nivån är för låg riskerar motorn att överhettas, vilket kan leda till motorhaveri.',
  },
  {
    id: 'ftk-7',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är skillnaden mellan skivbromsar och trumbromsar?',
    options: [
      'Skivbromsar finns bara på bakhjulen',
      'Skivbromsar kyls effektivare och ger jämnare bromskraft',
      'Trumbromsar är alltid bättre vid höga hastigheter',
    ],
    correctIndex: 1,
    explanation:
      'Skivbromsar är öppna och kyls bättre, vilket ger jämnare och mer tillförlitlig bromskraft. Trumbromsar kan överhettas vid upprepad bromsning.',
  },
  {
    id: 'ftk-8',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Varför måste alla i bilen använda bilbälte?',
    options: [
      'Det är bara en rekommendation',
      'Det är lagkrav och minskar risken för allvarliga skador vid olycka drastiskt',
      'Det behövs bara på motorväg',
    ],
    correctIndex: 1,
    explanation:
      'Bilbälte är lagkrav för alla passagerare. Det minskar risken att dödas i en olycka med upp till 60 % och förhindrar att man slungas runt.',
  },
  {
    id: 'ftk-9',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Hur fungerar en krockkudde (airbag)?',
    options: [
      'Den ersätter bilbältet vid olycka',
      'Den blåses upp vid kollision och fungerar som komplement till bilbältet',
      'Den skyddar bara föraren',
    ],
    correctIndex: 1,
    explanation:
      'Krockkudden utlöses vid kraftig kollision och fungerar som ett komplement till bilbältet. Utan bälte kan krockkudden orsaka skador istället.',
  },
  {
    id: 'ftk-10',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Hur ska barn under 135 cm säkras i bilen?',
    options: [
      'Med vanligt bilbälte räcker',
      'Med godkänd barnstol eller bälteskudde anpassad efter barnets storlek',
      'Barn behöver inte bälte i baksätet',
    ],
    correctIndex: 1,
    explanation:
      'Barn under 135 cm ska använda godkänd barnstol eller bälteskudde. Skyddet ska vara anpassat efter barnets vikt och längd.',
  },
  {
    id: 'ftk-11',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad betyder en gul varningslampa som visar en motor?',
    options: [
      'Motorn behöver mer olja omedelbart',
      'Motorstyrningen har registrerat ett fel – boka verkstadsbesök',
      'Bilen behöver tankas',
    ],
    correctIndex: 1,
    explanation:
      'En gul motorlampa (check engine) betyder att motorstyrningen upptäckt ett fel. Det kräver inte omedelbart stopp men bör kontrolleras snarast.',
  },
  {
    id: 'ftk-12',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad är nackstödets funktion?',
    options: [
      'Det ger enbart komfort vid långa resor',
      'Det skyddar nacken mot pisksnärtskada vid påkörning bakifrån',
      'Det stödjer huvudet under sömn',
    ],
    correctIndex: 1,
    explanation:
      'Nackstödet ska skydda mot pisksnärtskador vid påkörning bakifrån. Det ska vara inställt så att överkanten är i nivå med huvudets ovansida.',
  },
  {
    id: 'ftk-13',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vilka krav gäller för avgaser vid besiktning?',
    options: [
      'Det finns inga krav på avgaser',
      'Avgasutsläppen måste understiga gällande gränsvärden för fordonets miljöklass',
      'Bara dieselbilar kontrolleras',
    ],
    correctIndex: 1,
    explanation:
      'Vid besiktning kontrolleras avgasutsläpp och de måste ligga inom gränsvärdena för fordonets specifika miljöklass.',
  },
  {
    id: 'ftk-14',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad ska du tänka på vid koppling av släpvagn med dragkrok?',
    options: [
      'Det räcker att koppla draganordningen',
      'Koppla draganordning, elkontakt, vajer/kedja och kontrollera att lamporna fungerar',
      'Bara elkontakten behövs för att det ska vara lagligt',
    ],
    correctIndex: 1,
    explanation:
      'Vid tillkoppling ska du säkra draganordningen, ansluta elkontakten, fästa säkerhetsvajer eller -kedja och kontrollera att alla lampor fungerar.',
  },
  {
    id: 'ftk-15',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad krävs för att få köra personbil i Sverige?',
    options: [
      'Bara ett godkänt syntest',
      'B-körkort och godkänt syntest',
      'Man behöver bara ha fyllt 18 år',
    ],
    correctIndex: 1,
    explanation:
      'För att köra personbil krävs B-körkort. I samband med körkortsansökan genomförs ett syntest som ska vara godkänt.',
  },
  {
    id: 'ftk-16',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Hur ofta ska en personbil besiktigas?',
    options: [
      'Varje år från att bilen är ny',
      'Första gången efter 4 år, sedan vartannat år (efter 8 år: varje år)',
      'Bara vid ägarbyten',
    ],
    correctIndex: 1,
    explanation:
      'Nya personbilar besiktigas första gången senast 4 år efter registrering, därefter vartannat år. Bilar äldre än 8 år besiktigas varje år.',
  },
  {
    id: 'ftk-17',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad kontrollerar ABS-systemet?',
    options: [
      'Att airbagen löser ut vid kollision',
      'Att hjulen inte låser sig vid hård inbromsning',
      'Att bilen håller rätt fil på vägen',
    ],
    correctIndex: 1,
    explanation:
      'ABS (Anti-lock Braking System) förhindrar att hjulen låser sig vid hård inbromsning, så att du behåller styrförmågan.',
  },
  {
    id: 'ftk-18',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Varför ska strålkastarna vara rena och rätt inställda?',
    options: [
      'Det påverkar bara utseendet',
      'Smutsiga eller felinställda lampor minskar sikten och kan blända mötande',
      'Det spelar ingen roll om lamporna lyser',
    ],
    correctIndex: 1,
    explanation:
      'Smutsiga strålkastare kan minska ljusstyrkan med upp till 50 %. Felinställda lampor bländar mötande trafik och försämrar din egen sikt.',
  },
  {
    id: 'ftk-19',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad ska du göra innan en lång resa med bilen?',
    options: [
      'Tvätta bilen',
      'Kontrollera däcktryck, vätskenivåer, lampor och bromsar',
      'Det räcker att tanka fullt',
    ],
    correctIndex: 1,
    explanation:
      'Innan en längre resa bör du kontrollera däcktryck, olja, kylvätska, spolarvätska, att lamporna fungerar och att bromsarna är i gott skick.',
  },
  {
    id: 'ftk-20',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad innebär ESC (Electronic Stability Control)?',
    options: [
      'Ett system som automatiskt bromsar bilen i nödsituationer',
      'Ett system som motverkar sladd genom att bromsa enskilda hjul och justera motoreffekten',
      'Ett system som håller bilen i rätt fil',
    ],
    correctIndex: 1,
    explanation:
      'ESC upptäcker sladd och ingriper genom att bromsa enskilda hjul och justera motoreffekten för att stabilisera bilen.',
  },
  {
    id: 'ftk-21',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad ska du göra om oljelampan tänds under körning?',
    options: ['Köra till närmaste verkstad', 'Stanna direkt och kontrollera oljenivån', 'Ignorera den'],
    correctIndex: 1,
    explanation: 'Oljelampan anger kritiskt låg oljenivå/tryck. Fortsatt körning kan förstöra motorn. Stanna omedelbart.',
  },
  {
    id: 'ftk-22',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad är bromsvätskan till för?',
    options: ['Kyla bromsarna', 'Överföra tryck från bromspedalen till hjulbromsarna', 'Smörja bromsskivorna'],
    correctIndex: 1,
    explanation: 'Bromsvätska överför det hydrauliska trycket från pedalen till bromskolvar vid hjulen.',
  },
  {
    id: 'ftk-23',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad händer om bromsvätska läcker?',
    options: ['Inget farligt', 'Bromsverkan försämras eller försvinner helt', 'Bilen stannar av sig själv'],
    correctIndex: 1,
    explanation: 'Utan bromsvätska kan hydraultrycket inte byggas upp — du förlorar bromskraft.',
  },
  {
    id: 'ftk-24',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad gör servostyrningen?',
    options: ['Styr bilen automatiskt', 'Hjälper till att vrida ratten med mindre kraft', 'Stabiliserar bilen i kurvor'],
    correctIndex: 1,
    explanation: 'Servostyrning gör det lättare att vrida ratten, särskilt vid låga hastigheter som vid parkering.',
  },
  {
    id: 'ftk-25',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är skillnaden mellan sommardäck och vinterdäck?',
    options: ['Bara mönstret', 'Gummiblandningen — vinterdäck har mjukare gummi som fungerar i kyla', 'Storleken'],
    correctIndex: 1,
    explanation: 'Vinterdäck har mjukare gummi som behåller greppet i kyla. Sommardäck härdnar och tappar grepp under ca 7°C.',
  },
  {
    id: 'ftk-26',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Var hittar du rätt däcktryck för din bil?',
    options: ['På däcken', 'I instruktionsboken eller på en dekal i dörrkarm/lucka', 'Det finns inget specificerat'],
    correctIndex: 1,
    explanation: 'Rätt däcktryck anges i instruktionsboken och ofta på en dekal i förardörren eller tankluckan.',
  },
  {
    id: 'ftk-27',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad innebär "dubbdäck" och när får de användas?',
    options: ['Däck med metalldubb som ger extra grepp — tillåtna 1 oktober till 15 april', 'Alltid tillåtna', 'Förbjudna i Sverige'],
    correctIndex: 0,
    explanation: 'Dubbdäck har metalldubb för bättre grepp på is. De är tillåtna 1 oktober-15 april (1 okt-30 april om vinterväglag).',
  },
  {
    id: 'ftk-28',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad gör en katalysator?',
    options: ['Filtrerar luft till motorn', 'Omvandlar skadliga avgaser till mindre farliga ämnen', 'Minskar ljudet'],
    correctIndex: 1,
    explanation: 'Katalysatorn omvandlar kolmonoxid, kväveoxider och kolväten till vatten och koldioxid.',
  },
  {
    id: 'ftk-29',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Varför ska du inte köra med för lite kylvätska?',
    options: ['Bilen drar mer bränsle', 'Motorn kan överhettas och ta allvarlig skada', 'AC fungerar sämre'],
    correctIndex: 1,
    explanation: 'Kylvätska håller motorn på rätt temperatur. För lite vätska kan leda till överhettning och motorhaveri.',
  },
  {
    id: 'ftk-30',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad är TPMS (Tire Pressure Monitoring System)?',
    options: ['Ett GPS-system', 'System som varnar om däcktrycket är för lågt', 'Parkeringshjälp'],
    correctIndex: 1,
    explanation: 'TPMS övervakar däcktrycket och varnar med en lampa i instrumentpanelen om trycket sjunker.',
  },
  {
    id: 'ftk-31',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad innebär regenerativ bromsning i en elbil/hybrid?',
    options: ['Bromsarna reparerar sig själva', 'Rörelseenergi omvandlas till elektrisk energi vid bromsning', 'Bromsarna byts ut automatiskt'],
    correctIndex: 1,
    explanation: 'Vid regenerativ bromsning agerar elmotorn generator och återvinner rörelseenergi som laddning till batteriet.',
  },
  {
    id: 'ftk-32',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Varför ska du kontrollera spolarvätska regelbundet?',
    options: ['Det påverkar motorn', 'Utan den kan du inte rengöra vindrutan — farligt i smutsigt/salt väglag', 'Det är bara för komfort'],
    correctIndex: 1,
    explanation: 'Utan spolarvätska kan du inte rengöra vindrutan vid smuts och salt, vilket kraftigt försämrar sikten.',
  },
  {
    id: 'ftk-33',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad ska du göra om temperaturmätaren visar rött (överhettning)?',
    options: ['Fortsätt köra lugnt', 'Stanna säkert, stäng av motorn och låt den svalna', 'Fyll på kallt vatten direkt'],
    correctIndex: 1,
    explanation: 'Stanna omedelbart vid överhettning. Öppna inte kylarlocket direkt — vätskan är under tryck och extremt het.',
  },
  {
    id: 'ftk-34',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är turbo/turboladdare?',
    options: ['En extra motor', 'En kompressor driven av avgaser som ökar motorns effekt', 'Ett bromssystem'],
    correctIndex: 1,
    explanation: 'Turboladdaren drivs av avgasflödet och pressar in mer luft i motorn, vilket ökar effekten.',
  },
  {
    id: 'ftk-35',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Hur vet du att handbromsen inte är helt lossad?',
    options: ['Bilen accelererar långsammare', 'En varningslampa lyser i instrumentpanelen', 'Du märker det inte'],
    correctIndex: 1,
    explanation: 'Om handbromsen fortfarande är i — även delvis — lyser handbromsvarningslampan i instrumentpanelen.',
  },
  {
    id: 'ftk-36',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad gör en partikelfilter (DPF)?',
    options: ['Filtrerar bränslet', 'Fångar sotpartiklar från dieselmotorn', 'Renar kabinluften'],
    correctIndex: 1,
    explanation: 'Partikelfiltret fångar sotpartiklar från avgaserna. Det måste regenereras (brännas rent) regelbundet.',
  },
  {
    id: 'ftk-37',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad innebär "fjärrljusassistent"?',
    options: ['Fjärrkontroll för bilens ljus', 'System som automatiskt byter mellan helljus och halvljus', 'Extra lampor på taket'],
    correctIndex: 1,
    explanation: 'Fjärrljusassistenten byter automatiskt till halvljus när mötande trafik upptäcks och tillbaka till helljus när det är fritt.',
  },
  {
    id: 'ftk-38',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad ska du göra om en glödlampa i strålkastaren går sönder?',
    options: ['Byta så snart som möjligt', 'Vänta till nästa service', 'Köra med bara en lampa'],
    correctIndex: 0,
    explanation: 'En trasig strålkastare minskar din synlighet och sikt. Byt omedelbart — det är dessutom olagligt att köra utan.',
  },
  {
    id: 'ftk-39',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad är "lane keeping assist" (filhållningsassistent)?',
    options: ['Navigeringssystem', 'System som varnar eller styr tillbaka om du oavsiktligt lämnar din fil', 'Automatisk parkering'],
    correctIndex: 1,
    explanation: 'Filhållningsassistenten registrerar vägmarkeringar och varnar (eller korrigerar) om bilen börjar driva ur filen.',
  },
  {
    id: 'ftk-40',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad innebär "adaptiv farthållare" (ACC)?',
    options: ['Vanlig farthållare', 'Farthållare som automatiskt anpassar avståndet till framförvarande fordon', 'Snabbhetsbegränsare'],
    correctIndex: 1,
    explanation: 'ACC använder radar/kamera för att hålla inställd hastighet OCH säkert avstånd till bilen framför.',
  },
  {
    id: 'ftk-41',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad gör man om bilen inte startar?',
    options: ['Prova starta flera gånger snabbt', 'Kontrollera batteri, kolla att bränsle finns, prova startkablar', 'Ge upp och ring bärgning direkt'],
    correctIndex: 1,
    explanation: 'Kontrollera grunderna: batteri (lampor/radio funkar?), bränsle, kontakter. Starthjälp med kablar kan lösa batteriproblem.',
  },
  {
    id: 'ftk-42',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad indikerar en ABS-varningslampa som lyser konstant?',
    options: ['ABS fungerar normalt', 'Fel på ABS-systemet — vanliga bromsar fungerar men ABS är ur funktion', 'Ingen broms alls'],
    correctIndex: 1,
    explanation: 'Lysande ABS-lampa betyder att ABS är ur funktion. Vanliga bromsar fungerar men du tappar ABS-skyddet.',
  },
  {
    id: 'ftk-43',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är skillnaden mellan framhjulsdrift, bakhjulsdrift och fyrhjulsdrift?',
    options: ['Ingen praktisk skillnad', 'De driver olika hjul, vilket påverkar köregenskaper och grepp', 'Bara prisskillnad'],
    correctIndex: 1,
    explanation: 'Framhjulsdrift drar, bakhjulsdrift skjuter, fyrhjulsdrift ger bäst grepp. Varje drivlinje beter sig olika vid sladd och i kurvor.',
  },
  {
    id: 'ftk-44',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad är batteriet till för i en bil?',
    options: ['Bara för radion', 'Starta motorn och driva elektrisk utrustning', 'Bara för belysning'],
    correctIndex: 1,
    explanation: 'Batteriet startar motorn och driver all elektrisk utrustning. Generatorn laddar batteriet under körning.',
  },
  {
    id: 'ftk-45',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Varför ska du inte köra med slitna bromsbelägg?',
    options: ['Bilen drar mer bränsle', 'Bromskraften minskar kraftigt och bromssträckan ökar', 'Det låter illa'],
    correctIndex: 1,
    explanation: 'Slitna bromsbelägg ger avsevärt sämre bromskraft och kan till slut skada bromsskivan.',
  },
  {
    id: 'ftk-46',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad innebär "blindspot detection" (dödvinkelsvarning)?',
    options: ['Parkeringssensor', 'System som varnar om fordon finns i din dödvinkel', 'Backkamera'],
    correctIndex: 1,
    explanation: 'Dödvinkelsvarning använder sensorer för att upptäcka fordon i din dödvinkel och varnar dig med ljus/ljud.',
  },
  {
    id: 'ftk-47',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad ska du göra om du ser att ett däck är platt?',
    options: ['Köra sakta till verkstad', 'Stanna och byt till reservdäck eller ring hjälp', 'Pumpa upp med fotpump och köra vidare'],
    correctIndex: 1,
    explanation: 'Att köra med platt däck förstör fälgen och är farligt. Stanna och åtgärda.',
  },
  {
    id: 'ftk-48',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad gör en "kollisionsvarnare" (forward collision warning)?',
    options: ['Reparerar bilen efter krock', 'Varnar föraren och kan bromsa automatiskt vid kollisionsrisk', 'Minskar hastigheten'],
    correctIndex: 1,
    explanation: 'Kollisionsvarnaren använder sensorer för att upptäcka risken för frontalkollision och kan initiera automatisk nödbromsning.',
  },
  {
    id: 'ftk-49',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är "mild hybrid" (MHEV)?',
    options: ['En liten elbil', 'Bil med liten elmotor som assisterar bensin/dieselmotorn men inte kan köra på el ensam', 'En hybrid med litet batteri'],
    correctIndex: 1,
    explanation: 'MHEV har en liten elmotor som hjälper förbränningsmotorn vid acceleration och start/stopp, men kan inte köra på bara el.',
  },
  {
    id: 'ftk-50',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad ska alla bilar ha för utrustning enligt lag?',
    options: ['Bara bilbälten', 'Bilbälten, varningstriangel och halvljus', 'Brandsläckare'],
    correctIndex: 1,
    explanation: 'Enligt lag ska bilar ha fungerande bilbälten, varningstriangel och fungerande belysning (halvljus).',
  },
  {
    id: 'ftk-51',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad innebär "run-flat-däck"?',
    options: ['Däck som aldrig punkterar', 'Däck som kan köras en kortare sträcka även efter punktering', 'Extra breda däck'],
    correctIndex: 1,
    explanation: 'Run-flat-däck har förstärkta sidor och kan köras i ca 80 km med låg hastighet även efter punktering.',
  },
  {
    id: 'ftk-52',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är "ISOFIX" för barnstolar?',
    options: ['En barnstolstillverkare', 'Ett standardiserat fästsystem som kopplar barnstolen direkt till bilens kaross', 'En typ av bälte'],
    correctIndex: 1,
    explanation: 'ISOFIX är ett fast fästsystem i bilen där barnstolen klickas fast direkt — säkrare och enklare än bältesfäste.',
  },
  {
    id: 'ftk-53',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad ska du göra om ratten vibrerar vid körning?',
    options: ['Det är normalt', 'Kontrollera hjulbalansen — obalanserade hjul kan vibrera', 'Köra fortare så försvinner det'],
    correctIndex: 1,
    explanation: 'Vibrerande ratt kan bero på obalanserade hjul, slitna däck eller styrningsfel. Kontrollera snarast.',
  },
  {
    id: 'ftk-54',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad är en "head-up display" (HUD)?',
    options: ['Backkamera', 'Projicering av hastighet och information på vindrutan', 'Extra instrumentbräda'],
    correctIndex: 1,
    explanation: 'HUD projicerar viktig information (hastighet, navigation) direkt på vindrutan så du inte behöver titta ner.',
  },
  {
    id: 'ftk-55',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är skillnaden mellan automatväxellåda och manuell?',
    options: ['Bara bekvämlighet', 'Automatväxellådan sköter växling själv medan manuell kräver att föraren kopplar och växlar', 'Automatisk är snabbare'],
    correctIndex: 1,
    explanation: 'Automatväxellåda växlar själv baserat på hastighet/varvtal. Manuell kräver att föraren aktivt kopplar och växlar.',
  },
  {
    id: 'ftk-56',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Varför ska backspeglar vara rena och rätt inställda?',
    options: ['För utseendets skull', 'Du behöver kunna se trafiken bakom och vid sidan', 'Det krävs inte'],
    correctIndex: 1,
    explanation: 'Rena, korrekt inställda speglar är avgörande för att du ska ha uppsikt över trafiken runt bilen.',
  },
  {
    id: 'ftk-57',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad indikerar en varningslampa med bild av batteri?',
    options: ['Batteriet är fullt', 'Problem med laddningssystemet — generatorn kanske inte laddar', 'Batteriet behöver bytas direkt'],
    correctIndex: 1,
    explanation: 'Batterilampan anger att laddningssystemet inte fungerar normalt. Generatorn kan ha slutat ladda.',
  },
  {
    id: 'ftk-58',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är "steer-by-wire"?',
    options: ['Trådlös rattfjärrkontroll', 'Elektronisk styrning utan mekanisk koppling mellan ratt och hjul', 'Extra ratt för passageraren'],
    correctIndex: 1,
    explanation: 'Steer-by-wire ersätter mekanisk styrning med elektronik. Rattrörelsen översätts till signaler som styr hjulen.',
  },
  {
    id: 'ftk-59',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad ska du tänka på vid laddning av elbil?',
    options: ['Ladda alltid till 100%', 'Följ tillverkarens rekommendationer, undvik att ladda i extrem kyla/värme utan förberedelse', 'Använd bara snabbladdare'],
    correctIndex: 1,
    explanation: 'Elbilar mår bäst av att laddas till 80% vid daglig användning. Extrem temperatur kan påverka laddningen.',
  },
  {
    id: 'ftk-60',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad händer om du kör utan fungerande bromsljus?',
    options: ['Inget problem', 'Bakomvarande ser inte att du bromsar — risk för påkörning', 'Du får en varningslampa'],
    correctIndex: 1,
    explanation: 'Utan bromsljus kan bakomvarande trafik inte se att du bromsar, vilket ökar risken för påkörning bakifrån.',
  },
  {
    id: 'ftk-61',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är "torque vectoring"?',
    options: ['En typ av fälgar', 'System som fördelar drivkraft till olika hjul för bättre kurvkörning', 'Motorns rotationshastighet'],
    correctIndex: 1,
    explanation: 'Torque vectoring fördelar drivkraften asymmetriskt till hjulen, vilket ger bättre stabilitet och väggrepp i kurvor.',
  },
  {
    id: 'ftk-62',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Varför ska du kontrollera hjulmuttrarna efter hjulbyte?',
    options: ['De kan ha fel färg', 'De kan losna efter en tid — efterdra efter ca 10-20 mil', 'Det behövs inte'],
    correctIndex: 1,
    explanation: 'Nya hjul kan sätta sig och muttrarna kan losna. Efterdra alltid efter 10-20 mils körning.',
  },
  {
    id: 'ftk-63',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad händer om du kör med för högt däcktryck?',
    options: ['Bättre grepp', 'Mindre kontaktyta med vägen och ojämnt slitage', 'Inget negativt'],
    correctIndex: 1,
    explanation: 'För högt tryck ger mindre kontaktyta (bara mitten slits), sämre komfort och sämre grepp.',
  },
  {
    id: 'ftk-64',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad innebär OBD (On-Board Diagnostics)?',
    options: ['Navigeringssystem', 'Inbyggt diagnostiksystem som övervakar fordonets system och lagrar felkoder', 'Oljebytesinformation'],
    correctIndex: 1,
    explanation: 'OBD övervakar motor, avgaser och andra system. Vid fel lagras en kod som kan läsas av verkstad.',
  },
  {
    id: 'ftk-65',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad är en "backkamera" till för?',
    options: ['Att filma resan', 'Att visa vad som finns bakom bilen vid backning', 'Att övervaka passagerarna'],
    correctIndex: 1,
    explanation: 'Backkameran visar bild av området bakom bilen och hjälper att undvika kollisioner vid backning.',
  },
  {
    id: 'ftk-66',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad indikerar en blinkande varningslampa med bild av en bil med sladdsymbol?',
    options: ['Antisladdsystemet (ESC) är aktivt och arbetar', 'Bilen sladdar okontrollerat', 'Felaktiga däck'],
    correctIndex: 0,
    explanation: 'En blinkande ESC-lampa visar att systemet aktivt hjälper till att motverka sladd.',
  },
  {
    id: 'ftk-67',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad innebär "vehicle-to-everything" (V2X)-kommunikation?',
    options: ['Bilradio', 'Teknik som låter fordon kommunicera med andra fordon, infrastruktur och nätverk', 'GPS-uppdateringar'],
    correctIndex: 1,
    explanation: 'V2X-kommunikation gör att fordon kan utbyta data med omgivningen — varningar, trafikinformation osv.',
  },
  {
    id: 'ftk-68',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Varför ska du inte använda mobiltelefon vid tankning?',
    options: ['Det tar för lång tid', 'Teoretisk risk för gnistor — och du bör fokusera på tankningen', 'Det stör andra kunder'],
    correctIndex: 1,
    explanation: 'Även om risken är mycket liten finns en teoretisk möjlighet till statisk urladdning. Dessutom ska du vara fokuserad vid tankning.',
  },
  {
    id: 'ftk-69',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad gör "start-stopp-automatik"?',
    options: ['Stänger av bilen vid lång parkering', 'Stänger av motorn vid stopp (t.ex. rödljus) och startar när du släpper bromsen', 'Startar bilen automatiskt'],
    correctIndex: 1,
    explanation: 'Start-stopp stänger av motorn vid stillastående och startar den automatiskt igen — sparar bränsle i stadstrafik.',
  },
  {
    id: 'ftk-70',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är "pre-collision braking" (autobroms)?',
    options: ['Att bromsa före en korsning', 'System som automatiskt bromsar om det upptäcker en oundviklig kollision', 'Att kontrollera bromsarna'],
    correctIndex: 1,
    explanation: 'Pre-collision braking bromsar automatiskt om systemet bedömer att en kollision är oundviklig — minskar kollisionskraften.',
  },
  {
    id: 'ftk-71',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad ska du göra om varningslampan för krockkudde (airbag) lyser?',
    options: ['Ignorera den', 'Kontakta verkstad — krockkudden kanske inte fungerar vid olycka', 'Stanna direkt'],
    correctIndex: 1,
    explanation: 'En lysande airbag-lampa betyder att krockkuddesystemet kan ha fel. Besök verkstad snarast.',
  },
  {
    id: 'ftk-72',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad är "hill start assist" (backstartshjälp)?',
    options: ['Automatisk backning', 'Håller bromsarna i 2-3 sekunder i uppförsbacke vid start', 'Motorbroms i nedförsbacke'],
    correctIndex: 1,
    explanation: 'Hill start assist förhindrar att bilen rullar bakåt när du släpper bromsen i en uppförsbacke.',
  },
  {
    id: 'ftk-73',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad innebär "Level 2 autonom körning"?',
    options: ['Helt självkörande', 'Bilen kan styra och bromsa själv men föraren måste vara redo att ta över', 'Fjärrstyrd körning'],
    correctIndex: 1,
    explanation: 'Level 2 innebär att bilen kan hantera styrning och hastighet men föraren måste alltid övervaka och vara redo att ingripa.',
  },
  {
    id: 'ftk-74',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad är avgassystemet till för?',
    options: ['Att kyla motorn', 'Att leda ut avgaserna och rena dem', 'Att ge bilen ljud'],
    correctIndex: 1,
    explanation: 'Avgassystemet leder ut avgaserna från motorn, dämpar ljudet och renar dem via katalysator.',
  },
  {
    id: 'ftk-75',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad ska du tänka på vid byte av glödlampor i strålkastaren?',
    options: ['Ta på lampan med bara fingrar', 'Använd handskar eller duk — fett från fingrar kan skada lampan', 'Det spelar ingen roll'],
    correctIndex: 1,
    explanation: 'Fett från fingrar kan orsaka ojämn upphettning och spricka halogenlampor. Använd handskar eller duk.',
  },
  {
    id: 'ftk-76',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är "elektronisk parkeringsbroms" (EPB)?',
    options: ['Automatisk parkering', 'Eldriven handbroms som aktiveras med en knapp istället för spak', 'Parkeringsradar'],
    correctIndex: 1,
    explanation: 'EPB ersätter den mekaniska handbromsen med en elektrisk motor som spänner bromsarna via knapp.',
  },
  {
    id: 'ftk-77',
    category: 'fordon-teknik',
    difficulty: 'easy',
    question: 'Vad händer om du inte byter luftfilter i bilen?',
    options: ['Inget märkbart', 'Motorn presterar sämre och förbrukar mer bränsle', 'Bilen går sönder direkt'],
    correctIndex: 1,
    explanation: 'Ett smutsigt luftfilter begränsar luftflödet till motorn, vilket ger sämre effekt och högre förbrukning.',
  },
  {
    id: 'ftk-78',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Vad gör "trötthetsvarning" (drowsiness detection)?',
    options: ['Spelar musik', 'Analyserar körmönster och varnar om du visar tecken på trötthet', 'Mäter puls'],
    correctIndex: 1,
    explanation: 'Systemet analyserar rattrörelse och andra mönster. Om det upptäcker tecken på trötthet varnar det föraren.',
  },
  {
    id: 'ftk-79',
    category: 'fordon-teknik',
    difficulty: 'hard',
    question: 'Vad är "vehicle dynamics control" (VDC)?',
    options: ['GPS-styrning', 'Samlingsnamn för system som övervakar och stabiliserar bilens rörelse', 'Motorstyrning'],
    correctIndex: 1,
    explanation: 'VDC är ett övergripande system som inkluderar ABS, ESC och traction control för att hålla bilen stabil.',
  },
  {
    id: 'ftk-80',
    category: 'fordon-teknik',
    difficulty: 'medium',
    question: 'Varför ska du inte förvara lösa föremål på instrumentbrädan?',
    options: ['Det ser ostädigt ut', 'De kan bli projektiler vid krock och blockera krockkudden', 'Det påverkar inte säkerheten'],
    correctIndex: 1,
    explanation: 'Lösa föremål på instrumentbrädan kan kastas runt vid krock och förhindra krockkuddeutlösning.',
  },
];
