import { Question } from './types';

export const forstaHjalpenQuestions: Question[] = [
  {
    id: 'fhj-1',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Vilket nummer ringer du vid en allvarlig olycka i Sverige?',
    options: ['113 13', '112', '114 14'],
    correctIndex: 1,
    explanation: '112 är det nationella nödnumret i Sverige. Det kopplar dig till SOS Alarm.',
  },
  {
    id: 'fhj-2',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Vad är det första du ska göra vid en trafikolycka?',
    options: ['Flytta de skadade', 'Säkra olycksplatsen och varna andra trafikanter', 'Ring försäkringsbolaget'],
    correctIndex: 1,
    explanation: 'Säkra platsen först — slå på varningsblinkers, ställ ut varningstriangel och varna trafiken.',
  },
  {
    id: 'fhj-3',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Vad ska du berätta när du ringer 112?',
    options: ['Bara ditt namn', 'Vad som hänt, var det hänt, hur många skadade och deras tillstånd', 'Bilens registreringsnummer'],
    correctIndex: 1,
    explanation: 'Ge SOS Alarm: VAD har hänt, VAR, HUR MÅNGA skadade, VILKA skador, VEM ringer.',
  },
  {
    id: 'fhj-4',
    category: 'forsta-hjalpen',
    difficulty: 'medium',
    question: 'Vad ska du göra om en skadad person är medvetslös men andas?',
    options: ['Ge hjärt-lungräddning', 'Lägg personen i stabilt sidoläge', 'Skaka dem tills de vaknar'],
    correctIndex: 1,
    explanation: 'Stabilt sidoläge håller luftvägarna öppna och förhindrar att personen kvävs av t.ex. uppkastningar.',
  },
  {
    id: 'fhj-5',
    category: 'forsta-hjalpen',
    difficulty: 'medium',
    question: 'Vad ska du göra om en person inte andas och är medvetslös?',
    options: ['Vänta på ambulans', 'Påbörja hjärt-lungräddning (HLR)', 'Ge vatten'],
    correctIndex: 1,
    explanation: 'Utan andning ska du omedelbart påbörja HLR: 30 bröstkompressioner + 2 inblåsningar. Ring 112 först.',
  },
  {
    id: 'fhj-6',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Hur många bröstkompressioner ska du ge innan inblåsningar vid HLR?',
    options: ['15', '30', '10'],
    correctIndex: 1,
    explanation: 'HLR-rytmen är 30 kompressioner följt av 2 inblåsningar. Tryck minst 5 cm djupt.',
  },
  {
    id: 'fhj-7',
    category: 'forsta-hjalpen',
    difficulty: 'medium',
    question: 'Var på bröstkorgen ska du trycka vid HLR?',
    options: ['Överst på bröstet', 'Mitt på bröstbenet', 'På magen'],
    correctIndex: 1,
    explanation: 'Placera handens klack mitt på bröstbenet. Tryck med raka armar, minst 5 cm djupt.',
  },
  {
    id: 'fhj-8',
    category: 'forsta-hjalpen',
    difficulty: 'hard',
    question: 'Vad är en hjärtstartare (AED) och hur används den?',
    options: ['Startmotor för hjärtat — kräver utbildning', 'Apparat som ger elstöt vid hjärtstopp — den talar om vad du ska göra', 'Medicin mot hjärtattack'],
    correctIndex: 1,
    explanation: 'En AED analyserar hjärtrytmen och ger röstinstruktioner. Vem som helst kan använda den — den ger bara stöt om det behövs.',
  },
  {
    id: 'fhj-9',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Ska du flytta en person som skadats i en bilolycka?',
    options: ['Ja, alltid', 'Nej, flytta bara vid livsfara (brand, drunkningsrisk)', 'Ja, om de är medvetslösa'],
    correctIndex: 1,
    explanation: 'Flytta aldrig skadade om det inte finns omedelbar livsfara — t.ex. brand. Ryggradsskador kan förvärras.',
  },
  {
    id: 'fhj-10',
    category: 'forsta-hjalpen',
    difficulty: 'medium',
    question: 'Vad ska du göra vid kraftig blödning?',
    options: ['Vänta på ambulans', 'Tryck hårt mot såret med ren duk/förband och ring 112', 'Använd tourniquét direkt'],
    correctIndex: 1,
    explanation: 'Tryck hårt mot såret med ren duk eller förband. Höj den skadade kroppsdelen om möjligt. Ring 112.',
  },
  {
    id: 'fhj-11',
    category: 'forsta-hjalpen',
    difficulty: 'hard',
    question: 'Vad är chock och vilka symtom ska du se upp med?',
    options: ['Elektrisk stöt', 'Kroppens reaktion på allvarlig skada — blek, kallsvettig, snabb puls, förvirrad', 'Allergisk reaktion'],
    correctIndex: 1,
    explanation: 'Chock uppstår vid allvarlig skada/blödning. Symtom: blek, kall, svettig hud, snabb puls, yrsel. Lägg personen ner med benen högt.',
  },
  {
    id: 'fhj-12',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Vad ska du göra om en person har brännskador?',
    options: ['Smör med smör', 'Kyl med ljummet vatten i minst 20 minuter', 'Lägg is direkt på brännskadan'],
    correctIndex: 1,
    explanation: 'Kyl brännskadan med ljummet/svalt rinnande vatten i minst 20 minuter. Använd inte is.',
  },
  {
    id: 'fhj-13',
    category: 'forsta-hjalpen',
    difficulty: 'medium',
    question: 'Hur lägger du en person i stabilt sidoläge?',
    options: ['På magen', 'På sidan med översta benet böjt och huvudet bakåtlutat', 'Sittande'],
    correctIndex: 1,
    explanation: 'Stabilt sidoläge: person på sidan, översta benet böjt, huvudet böjt bakåt för att hålla luftvägen öppen.',
  },
  {
    id: 'fhj-14',
    category: 'forsta-hjalpen',
    difficulty: 'hard',
    question: 'Vad ska du göra om en person verkar ha nackskada efter en krock?',
    options: ['Vrida på huvudet', 'Stabilisera nacken — håll huvudet stilla, flytta inte personen', 'Skaka personen'],
    correctIndex: 1,
    explanation: 'Vid misstänkt nackskada: håll huvudet stilla i neutral position. Flytta inte personen om det inte är livsfara.',
  },
  {
    id: 'fhj-15',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Vad ska finnas i bilens första hjälpen-utrustning?',
    options: ['Bara plåster', 'Förband, kompresser, sax, handskar och varningstriangel', 'Bara varningstriangel'],
    correctIndex: 1,
    explanation: 'En bra första hjälpen-väska innehåller förband, kompresser, sax, handskar, plåster och rengöring.',
  },
  {
    id: 'fhj-16',
    category: 'forsta-hjalpen',
    difficulty: 'medium',
    question: 'Vad innebär "L-ABC" vid första hjälpen?',
    options: ['En typ av förband', 'Livsfarligt läge-Andning-Blödning-Chock — prioriteringsordning', 'En bilmodell'],
    correctIndex: 1,
    explanation: 'L-ABC: kontrollera Livsfarligt läge, sedan Andning, sedan stor Blödning, sedan Chock. Det anger prioritet.',
  },
  {
    id: 'fhj-17',
    category: 'forsta-hjalpen',
    difficulty: 'hard',
    question: 'Hur snabbt kan en person med hjärtstopp få hjärnskador utan HLR?',
    options: ['Inom 30 minuter', 'Redan efter 4-6 minuter', 'Först efter 15 minuter'],
    correctIndex: 1,
    explanation: 'Hjärnan tål bara 4-6 minuter utan syre innan permanent skada uppstår. Varje sekund räknas.',
  },
  {
    id: 'fhj-18',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Vad ska du göra om en person sitter fastspänd i en bil efter en olycka och är vid medvetande?',
    options: ['Dra ut dem direkt', 'Låt dem sitta kvar, prata lugnt och vänta på räddningstjänst', 'Ta loss bältet'],
    correctIndex: 1,
    explanation: 'Om det inte finns omedelbar fara (brand), låt personen sitta kvar. Bältet ger stöd. Vänta på proffs.',
  },
  {
    id: 'fhj-19',
    category: 'forsta-hjalpen',
    difficulty: 'medium',
    question: 'Vad ska du göra om en person har ett föremål fastkilat i kroppen?',
    options: ['Dra ut det direkt', 'Lämna det — tryck runt det med förband och ring 112', 'Ignorera det'],
    correctIndex: 1,
    explanation: 'Dra aldrig ut fastkilade föremål — de kan hindra blödning. Stabilisera runt föremålet och ring 112.',
  },
  {
    id: 'fhj-20',
    category: 'forsta-hjalpen',
    difficulty: 'hard',
    question: 'Hur gör du HLR på ett litet barn (under 1 år)?',
    options: ['Samma som vuxen', 'Använd 2 fingrar istället för hela handen, 30:2, blås försiktigt', 'Det ska man inte göra'],
    correctIndex: 1,
    explanation: 'På spädbarn: tryck med 2 fingrar mitt på bröstbenet, ca 4 cm djupt. 30 kompressioner, 2 små inblåsningar.',
  },
  {
    id: 'fhj-21',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Är du skyldig att stanna och hjälpa till vid en olycka?',
    options: ['Nej, det är frivilligt', 'Ja, du har en skyldighet att stanna och hjälpa efter förmåga', 'Bara om du var inblandad'],
    correctIndex: 1,
    explanation: 'Enligt lag har du en skyldighet att stanna och hjälpa till vid en olycka, efter din förmåga.',
  },
  {
    id: 'fhj-22',
    category: 'forsta-hjalpen',
    difficulty: 'medium',
    question: 'Vad ska du göra om en person är i chock men inte blöder?',
    options: ['Ge dem alkohol', 'Lägg dem ner, höj benen, håll dem varma och lugna', 'Ge dem mat'],
    correctIndex: 1,
    explanation: 'Vid chock: lägg personen ner, höj benen 20-30 cm, täck med filt/jacka, prata lugnt och ring 112.',
  },
  {
    id: 'fhj-23',
    category: 'forsta-hjalpen',
    difficulty: 'hard',
    question: 'Hur snabbt bör du komprimera vid HLR (takt)?',
    options: ['Cirka 60 per minut', 'Cirka 100-120 per minut', 'Så fort som möjligt'],
    correctIndex: 1,
    explanation: 'Komprimera i en takt av 100-120 per minut. Tänk takten till "Stayin\' Alive" av Bee Gees.',
  },
  {
    id: 'fhj-24',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Ska du ta av hjälmen på en motorcyklist som är medvetslös?',
    options: ['Ja, alltid', 'Bara om personen inte andas — annars låt hjälmen sitta', 'Nej, aldrig'],
    correctIndex: 1,
    explanation: 'Hjälmen ska normalt sitta kvar. Ta bara av den om personen inte andas och du behöver ge HLR.',
  },
  {
    id: 'fhj-25',
    category: 'forsta-hjalpen',
    difficulty: 'medium',
    question: 'Hur kontrollerar du om en person andas?',
    options: ['Fråga dem', 'Titta efter bröströrelser, lyssna och känn efter luftström i 10 sekunder', 'Kolla pulsen'],
    correctIndex: 1,
    explanation: 'Böj huvudet bakåt, lyft hakan. Titta efter bröströrelser, lyssna och känn efter utandning i max 10 sekunder.',
  },
  {
    id: 'fhj-26',
    category: 'forsta-hjalpen',
    difficulty: 'hard',
    question: 'Vad innebär "kedjan som räddar liv"?',
    options: ['En typ av räddningsutrustning', 'Tidigt larm → tidigt HLR → tidig defibrillering → tidig vård', 'Att flera hjälper till'],
    correctIndex: 1,
    explanation: 'Kedjan som räddar liv: 1) Ring 112, 2) Starta HLR, 3) Använd hjärtstartare, 4) Professionell vård tar vid.',
  },
  {
    id: 'fhj-27',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Vad ska du göra om det brinner i en bil vid en olycka?',
    options: ['Vänta på brandkåren', 'Om möjligt, hjälp personerna ut ur bilen och håll avstånd', 'Släck med vatten'],
    correctIndex: 1,
    explanation: 'Vid brand: hjälp alla ur bilen om det är säkert. Håll avstånd — tanken kan explodera. Ring 112.',
  },
  {
    id: 'fhj-28',
    category: 'forsta-hjalpen',
    difficulty: 'medium',
    question: 'Vad ska du göra om en person får krampanfall efter en olycka?',
    options: ['Håll fast dem', 'Skydda huvudet, lägg inget i munnen, vänta tills krampen går över', 'Ge vatten'],
    correctIndex: 1,
    explanation: 'Vid kramper: skydda personen från att skada sig. Lägg något mjukt under huvudet. Lägg INTE något i munnen.',
  },
  {
    id: 'fhj-29',
    category: 'forsta-hjalpen',
    difficulty: 'hard',
    question: 'Vad är "golden hour" (gyllene timmen)?',
    options: ['Bästa tiden att köra', 'Den första timmen efter allvarlig skada — chansen att överleva minskar kraftigt efter detta', 'Soluppgången'],
    correctIndex: 1,
    explanation: 'Den gyllene timmen syftar på att svårt skadade har bäst chans att överleva om de får kirurgisk vård inom en timme.',
  },
  {
    id: 'fhj-30',
    category: 'forsta-hjalpen',
    difficulty: 'easy',
    question: 'Vad ska du göra om du ser en person som ligger vid sidan av vägen?',
    options: ['Köra förbi', 'Stanna säkert, kontrollera om personen behöver hjälp och ring 112', 'Tuta'],
    correctIndex: 1,
    explanation: 'Stanna säkert och kontrollera situationen. Personen kan vara skadad eller sjuk och behöva akut hjälp.',
  },
];
