import { Question } from './types';

export const hastighetQuestions: Question[] = [
  {
    id: 'has-1',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vilken är den generella hastighetsgränsen inom tättbebyggt område (tätort)?',
    options: ['30 km/h', '50 km/h', '70 km/h'],
    correctIndex: 1,
    explanation: 'Inom tättbebyggt område gäller generellt 50 km/h om inget annat anges med vägmärke.',
  },
  {
    id: 'has-2',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vilken är den generella hastighetsgränsen på landsväg utanför tättbebyggt område?',
    options: ['50 km/h', '70 km/h', '90 km/h'],
    correctIndex: 1,
    explanation: 'Utanför tättbebyggt område gäller generellt 70 km/h om inget annat anges.',
  },
  {
    id: 'has-3',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vilken är den vanligaste högsta tillåtna hastigheten på motorväg i Sverige?',
    options: ['90 km/h', '110 km/h', '130 km/h'],
    correctIndex: 1,
    explanation: 'På de flesta motorvägar i Sverige är hastighetsgränsen 110 km/h. Vissa sträckor har 120 km/h.',
  },
  {
    id: 'has-4',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken högsta hastighet gäller på motortrafikled om inget annat anges?',
    options: ['70 km/h', '90 km/h', '100 km/h'],
    correctIndex: 0,
    explanation: 'På motortrafikled gäller generellt 70 km/h om inget annat anges med vägmärke. Många motortrafiksleder har dock skyltat högre hastighet.',
  },
  {
    id: 'has-5',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad innebär en 30-zon?',
    options: [
      'Att hastigheten är 30 km/h bara vid skolor',
      'Att högsta tillåtna hastighet är 30 km/h inom hela zonen',
      'Att man bör hålla ungefär 30 km/h',
    ],
    correctIndex: 1,
    explanation: '30-zon innebär att högsta tillåtna hastighet är 30 km/h inom hela det markerade området, oavsett tid på dygnet.',
  },
  {
    id: 'has-6',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken hastighet gäller ofta i skolzoner under skoltid?',
    options: ['20 km/h', '30 km/h', '40 km/h'],
    correctIndex: 1,
    explanation: 'Vid skolor gäller ofta 30 km/h, ibland markerat med tilläggstavla som anger tider. Var extra uppmärksam på barn.',
  },
  {
    id: 'has-7',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken är den högsta tillåtna hastigheten som förekommer på motorväg i Sverige?',
    options: ['110 km/h', '120 km/h', '130 km/h'],
    correctIndex: 1,
    explanation: 'Den högsta tillåtna hastigheten på motorväg i Sverige är 120 km/h, vilket förekommer på vissa utvalda sträckor.',
  },
  {
    id: 'has-8',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Du kör i 90 km/h på en väg med hastighetsgräns 70 km/h. Ungefär hur mycket ökar bromssträckan jämfört med om du körde i rätt hastighet?',
    options: ['Med ca 30%', 'Med ca 65%', 'Den fördubblas'],
    correctIndex: 1,
    explanation: 'Bromssträckan ökar med hastigheten i kvadrat. Från 70 till 90 km/h ökar bromssträckan med ungefär 65%. Högre hastighet ger avsevärt längre stoppsträcka.',
  },
  {
    id: 'has-9',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vad bör du göra med hastigheten vid kraftigt regn och vattenplaning?',
    options: [
      'Bromsa kraftigt för att sänka hastigheten snabbt',
      'Sänka hastigheten försiktigt och undvika plötsliga rattrörelse',
      'Behålla hastigheten men öka avståndet till framförvarande',
    ],
    correctIndex: 1,
    explanation: 'Vid risk för vattenplaning ska du sakta ner försiktigt utan häftiga ratt- eller bromsrörelser. Hastighetsminskning minskar risken för vattenplaning.',
  },
  {
    id: 'has-10',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken hastighet bör du anpassa dig till vid dimma och mycket dålig sikt?',
    options: [
      'Kör i högst 50 km/h oavsett väg',
      'Anpassa hastigheten så att du kan stanna inom den sträcka du överblickar',
      'Kör i halva den skyltade hastigheten',
    ],
    correctIndex: 1,
    explanation: 'Grundregeln är att alltid kunna stanna inom den sträcka du kan överblicka. Vid dimma kan det innebära mycket låg hastighet.',
  },
  {
    id: 'has-11',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad gäller kring hastighetskameror (ATK) i Sverige?',
    options: [
      'De finns bara i tätorter',
      'De är alltid föranmärkta med skyltar',
      'De kan finnas på alla typer av vägar och behöver inte alltid vara föranmärkta',
    ],
    correctIndex: 1,
    explanation: 'Automatisk trafiksäkerhetskontroll (ATK) ska vara föranmärkt med skyltar enligt svensk lag. Kamerorna finns på olika vägtyper.',
  },
  {
    id: 'has-12',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vilken påföljd riskerar du om du kör 31–40 km/h för fort?',
    options: [
      'Penningböter på 3 000 kr',
      'Penningböter på 4 000 kr',
      'Penningböter på 3 200 kr',
    ],
    correctIndex: 0,
    explanation: 'Fortkörning 31–40 km/h över gränsen ger normalt penningböter på 3 000 kr. Beloppet ökar med hastighetsöverträdelsens storlek.',
  },
  {
    id: 'has-13',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken böter gäller normalt vid fortkörning 1–10 km/h över hastighetsgränsen?',
    options: ['1 500 kr', '2 000 kr', '2 500 kr'],
    correctIndex: 1,
    explanation: 'Vid fortkörning 1–10 km/h över gränsen är penningboten normalt 2 000 kr.',
  },
  {
    id: 'has-14',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vid vilken grad av fortkörning kan du riskera att förlora körkortet?',
    options: [
      'Mer än 20 km/h över gränsen',
      'Mer än 30 km/h över gränsen',
      'Mer än 40 km/h över gränsen',
    ],
    correctIndex: 1,
    explanation: 'Vid hastighetsöverträdelser på mer än 30 km/h över gränsen kan Transportstyrelsen återkalla körkortet. Exakta gränser kan variera beroende på omständigheter.',
  },
  {
    id: 'has-15',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad gäller om ett vägmärke visar 80 km/h men den generella gränsen är 70 km/h?',
    options: [
      'Den generella gränsen 70 km/h gäller alltid',
      'Vägmärket gäller och du får köra 80 km/h',
      'Du får köra max 75 km/h som en kompromiss',
    ],
    correctIndex: 1,
    explanation: 'Vägmärken gäller före de generella hastighetsgränserna. Om ett märke visar 80 km/h får du köra 80 km/h på den sträckan.',
  },
  {
    id: 'has-16',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Varför är det extra viktigt att hålla låg hastighet i bostadsområden?',
    options: [
      'För att spara bränsle',
      'För att barn kan dyka upp plötsligt och stoppsträckan måste vara kort',
      'För att vägen ofta är smal',
    ],
    correctIndex: 1,
    explanation: 'I bostadsområden kan barn springa ut oväntat. Vid 30 km/h är risken att ett barn dör vid påkörning ca 10%, men vid 50 km/h stiger den till ca 80%.',
  },
  {
    id: 'has-17',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad händer med din stoppsträcka om du fördubblar hastigheten?',
    options: [
      'Den fördubblas',
      'Den tredubblas',
      'Den fyrdubblas',
    ],
    correctIndex: 2,
    explanation: 'Bromssträckan ökar med kvadraten på hastigheten. Dubbel hastighet ger fyra gånger längre bromssträcka. Reaktionssträckan fördubblas dessutom.',
  },
  {
    id: 'has-18',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Du närmar dig ett vägarbete. Vad gäller kring hastigheten?',
    options: [
      'Du ska alltid köra max 30 km/h förbi vägarbeten',
      'Du ska följa den tillfälliga hastighetsbegränsning som skyltas',
      'Du behöver bara sakta ner om arbetare syns',
    ],
    correctIndex: 1,
    explanation: 'Vid vägarbeten sätts tillfälliga hastighetsbegränsningar upp med vägmärken. Dessa gäller oavsett om arbetare syns eller inte.',
  },
  {
    id: 'has-19',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad menas med "anpassad hastighet"?',
    options: [
      'Att alltid köra under hastighetsgränsen',
      'Att anpassa hastigheten efter rådande förhållanden, även om det innebär att köra långsammare än hastighetsgränsen',
      'Att köra i samma hastighet som övrig trafik',
    ],
    correctIndex: 1,
    explanation: 'Anpassad hastighet innebär att du ska anpassa farten efter väder, väglag, sikt, trafikförhållanden och andra omständigheter, även om det innebär lägre hastighet än den skyltade.',
  },
  {
    id: 'has-20',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vilken hastighet gäller för tunga lastbilar (över 3,5 ton) på motorväg om inget annat anges?',
    options: ['80 km/h', '90 km/h', '110 km/h'],
    correctIndex: 1,
    explanation: 'Tunga lastbilar (totalvikt över 3,5 ton) har en generell hastighetsgräns på 90 km/h på motorväg, om inte lägre hastighet anges med vägmärke.',
  },
];
