import { Question } from './types';

export const hastighetQuestions: Question[] = [
  {
    id: 'has-1',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vilken är den generella hastighetsgränsen inom tättbebyggt område (tätort)?',
    options: ['30 km/h', '50 km/h', '70 km/h'],
    correctIndex: 1,
    explanation: 'Inom tättbebyggt område gäller generellt 50 km/h om inget annat anges med vägmärke.',
  },
  {
    id: 'has-2',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vilken är den generella hastighetsgränsen på landsväg utanför tättbebyggt område?',
    options: ['50 km/h', '70 km/h', '90 km/h'],
    correctIndex: 1,
    explanation: 'Utanför tättbebyggt område gäller generellt 70 km/h om inget annat anges.',
  },
  {
    id: 'has-3',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vilken är den vanligaste högsta tillåtna hastigheten på motorväg i Sverige?',
    options: ['90 km/h', '110 km/h', '130 km/h'],
    correctIndex: 1,
    explanation: 'På de flesta motorvägar i Sverige är hastighetsgränsen 110 km/h. Vissa sträckor har 120 km/h.',
  },
  {
    id: 'has-4',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken högsta hastighet gäller på motortrafikled om inget annat anges?',
    options: ['70 km/h', '90 km/h', '100 km/h'],
    correctIndex: 0,
    explanation: 'På motortrafikled gäller generellt 70 km/h om inget annat anges med vägmärke. Många motortrafiksleder har dock skyltat högre hastighet.',
  },
  {
    id: 'has-5',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad innebär en 30-zon?',
    options: [
      'Att hastigheten är 30 km/h bara vid skolor',
      'Att högsta tillåtna hastighet är 30 km/h inom hela zonen',
      'Att man bör hålla ungefär 30 km/h',
    ],
    correctIndex: 1,
    explanation: '30-zon innebär att högsta tillåtna hastighet är 30 km/h inom hela det markerade området, oavsett tid på dygnet.',
  },
  {
    id: 'has-6',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken hastighet gäller ofta i skolzoner under skoltid?',
    options: ['20 km/h', '30 km/h', '40 km/h'],
    correctIndex: 1,
    explanation: 'Vid skolor gäller ofta 30 km/h, ibland markerat med tilläggstavla som anger tider. Var extra uppmärksam på barn.',
  },
  {
    id: 'has-7',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken är den högsta tillåtna hastigheten som förekommer på motorväg i Sverige?',
    options: ['110 km/h', '120 km/h', '130 km/h'],
    correctIndex: 1,
    explanation: 'Den högsta tillåtna hastigheten på motorväg i Sverige är 120 km/h, vilket förekommer på vissa utvalda sträckor.',
  },
  {
    id: 'has-8',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Du kör i 90 km/h på en väg med hastighetsgräns 70 km/h. Ungefär hur mycket ökar bromssträckan jämfört med om du körde i rätt hastighet?',
    options: ['Med ca 30%', 'Med ca 65%', 'Den fördubblas'],
    correctIndex: 1,
    explanation: 'Bromssträckan ökar med hastigheten i kvadrat. Från 70 till 90 km/h ökar bromssträckan med ungefär 65%. Högre hastighet ger avsevärt längre stoppsträcka.',
  },
  {
    id: 'has-9',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vad bör du göra med hastigheten vid kraftigt regn och vattenplaning?',
    options: [
      'Bromsa kraftigt för att sänka hastigheten snabbt',
      'Sänka hastigheten försiktigt och undvika plötsliga rattrörelse',
      'Behålla hastigheten men öka avståndet till framförvarande',
    ],
    correctIndex: 1,
    explanation: 'Vid risk för vattenplaning ska du sakta ner försiktigt utan häftiga ratt- eller bromsrörelser. Hastighetsminskning minskar risken för vattenplaning.',
  },
  {
    id: 'has-10',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken hastighet bör du anpassa dig till vid dimma och mycket dålig sikt?',
    options: [
      'Kör i högst 50 km/h oavsett väg',
      'Anpassa hastigheten så att du kan stanna inom den sträcka du överblickar',
      'Kör i halva den skyltade hastigheten',
    ],
    correctIndex: 1,
    explanation: 'Grundregeln är att alltid kunna stanna inom den sträcka du kan överblicka. Vid dimma kan det innebära mycket låg hastighet.',
  },
  {
    id: 'has-11',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad gäller kring hastighetskameror (ATK) i Sverige?',
    options: [
      'De finns bara i tätorter',
      'De är alltid föranmärkta med skyltar',
      'De kan finnas på alla typer av vägar och behöver inte alltid vara föranmärkta',
    ],
    correctIndex: 1,
    explanation: 'Automatisk trafiksäkerhetskontroll (ATK) ska vara föranmärkt med skyltar enligt svensk lag. Kamerorna finns på olika vägtyper.',
  },
  {
    id: 'has-12',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vilken påföljd riskerar du om du kör 31–40 km/h för fort?',
    options: [
      'Penningböter på 3 000 kr',
      'Penningböter på 4 000 kr',
      'Penningböter på 3 200 kr',
    ],
    correctIndex: 0,
    explanation: 'Fortkörning 31–40 km/h över gränsen ger normalt penningböter på 3 000 kr. Beloppet ökar med hastighetsöverträdelsens storlek.',
  },
  {
    id: 'has-13',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken böter gäller normalt vid fortkörning 1–10 km/h över hastighetsgränsen?',
    options: ['1 500 kr', '2 000 kr', '2 500 kr'],
    correctIndex: 1,
    explanation: 'Vid fortkörning 1–10 km/h över gränsen är penningboten normalt 2 000 kr.',
  },
  {
    id: 'has-14',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vid vilken grad av fortkörning kan du riskera att förlora körkortet?',
    options: [
      'Mer än 20 km/h över gränsen',
      'Mer än 30 km/h över gränsen',
      'Mer än 40 km/h över gränsen',
    ],
    correctIndex: 1,
    explanation: 'Vid hastighetsöverträdelser på mer än 30 km/h över gränsen kan Transportstyrelsen återkalla körkortet. Exakta gränser kan variera beroende på omständigheter.',
  },
  {
    id: 'has-15',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad gäller om ett vägmärke visar 80 km/h men den generella gränsen är 70 km/h?',
    options: [
      'Den generella gränsen 70 km/h gäller alltid',
      'Vägmärket gäller och du får köra 80 km/h',
      'Du får köra max 75 km/h som en kompromiss',
    ],
    correctIndex: 1,
    explanation: 'Vägmärken gäller före de generella hastighetsgränserna. Om ett märke visar 80 km/h får du köra 80 km/h på den sträckan.',
  },
  {
    id: 'has-16',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Varför är det extra viktigt att hålla låg hastighet i bostadsområden?',
    options: [
      'För att spara bränsle',
      'För att barn kan dyka upp plötsligt och stoppsträckan måste vara kort',
      'För att vägen ofta är smal',
    ],
    correctIndex: 1,
    explanation: 'I bostadsområden kan barn springa ut oväntat. Vid 30 km/h är risken att ett barn dör vid påkörning ca 10%, men vid 50 km/h stiger den till ca 80%.',
  },
  {
    id: 'has-17',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad händer med din stoppsträcka om du fördubblar hastigheten?',
    options: [
      'Den fördubblas',
      'Den tredubblas',
      'Den fyrdubblas',
    ],
    correctIndex: 2,
    explanation: 'Bromssträckan ökar med kvadraten på hastigheten. Dubbel hastighet ger fyra gånger längre bromssträcka. Reaktionssträckan fördubblas dessutom.',
  },
  {
    id: 'has-18',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Du närmar dig ett vägarbete. Vad gäller kring hastigheten?',
    options: [
      'Du ska alltid köra max 30 km/h förbi vägarbeten',
      'Du ska följa den tillfälliga hastighetsbegränsning som skyltas',
      'Du behöver bara sakta ner om arbetare syns',
    ],
    correctIndex: 1,
    explanation: 'Vid vägarbeten sätts tillfälliga hastighetsbegränsningar upp med vägmärken. Dessa gäller oavsett om arbetare syns eller inte.',
  },
  {
    id: 'has-19',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad menas med "anpassad hastighet"?',
    options: [
      'Att alltid köra under hastighetsgränsen',
      'Att anpassa hastigheten efter rådande förhållanden, även om det innebär att köra långsammare än hastighetsgränsen',
      'Att köra i samma hastighet som övrig trafik',
    ],
    correctIndex: 1,
    explanation: 'Anpassad hastighet innebär att du ska anpassa farten efter väder, väglag, sikt, trafikförhållanden och andra omständigheter, även om det innebär lägre hastighet än den skyltade.',
  },
  {
    id: 'has-20',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vilken hastighet gäller för tunga lastbilar (över 3,5 ton) på motorväg om inget annat anges?',
    options: ['80 km/h', '90 km/h', '110 km/h'],
    correctIndex: 1,
    explanation: 'Tunga lastbilar (totalvikt över 3,5 ton) har en generell hastighetsgräns på 90 km/h på motorväg, om inte lägre hastighet anges med vägmärke.',
  },
  {
    id: 'has-21',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad gäller om hastighetsgränsen är 50 km/h men det är halt och dålig sikt?',
    options: ['Du ska köra i 50 km/h', 'Du ska anpassa och köra långsammare', 'Du ska köra i 30 km/h alltid'],
    correctIndex: 1,
    explanation: 'Hastighetsgränsen är en övre gräns. Vid dåliga förhållanden ska du anpassa och köra lägre.',
  },
  {
    id: 'has-22',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vilken hastighet gäller vid en gångfartsväg?',
    options: ['30 km/h', 'Gångfart (ca 5-7 km/h)', '20 km/h'],
    correctIndex: 1,
    explanation: 'På gångfartsvägar ska du köra i gångfart — det vill säga ca 5-7 km/h.',
  },
  {
    id: 'has-23',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken hastighet gäller på motortrafikled om inget annat anges?',
    options: ['70 km/h', '90 km/h', '110 km/h'],
    correctIndex: 0,
    explanation: 'Generella hastighetsgränsen på motortrafikled är 70 km/h om inget annat anges med vägmärke.',
  },
  {
    id: 'has-24',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Hur mycket ökar bromssträckan om hastigheten ökar från 30 km/h till 60 km/h?',
    options: ['Fördubblas', 'Fyrdubblas', 'Sexdubblas'],
    correctIndex: 1,
    explanation: 'Bromssträckan ökar med hastigheten i kvadrat. Dubblad hastighet = fyrdubblad bromssträcka.',
  },
  {
    id: 'has-25',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vilken hastighet gäller om du kör en personbil med släpvagn på motorväg?',
    options: ['110 km/h', '80 km/h', '90 km/h'],
    correctIndex: 1,
    explanation: 'Personbil med släpvagn har en maxhastighet på 80 km/h om inte annat anges.',
  },
  {
    id: 'has-26',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad händer om du kör 15 km/h för fort?',
    options: ['Inget straff', 'Böter (fortkörning)', 'Fängelse'],
    correctIndex: 1,
    explanation: 'Fortkörning leder till böter. Beloppen varierar beroende på hur mycket du överskrider gränsen.',
  },
  {
    id: 'has-27',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vid vilken fortkörning kan polisen omhänderta ditt körkort på plats?',
    options: ['1-10 km/h för fort', '30+ km/h för fort', '50+ km/h för fort'],
    correctIndex: 1,
    explanation: 'Vid fortkörning 30 km/h eller mer över gränsen kan polisen omhänderta körkortet omedelbart.',
  },
  {
    id: 'has-28',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Hur lång är bromssträckan vid 50 km/h på torr asfalt?',
    options: ['Cirka 5 meter', 'Cirka 13 meter', 'Cirka 25 meter'],
    correctIndex: 1,
    explanation: 'Vid 50 km/h på torr asfalt är bromssträckan cirka 13 meter (ren bromsning, utan reaktionstid).',
  },
  {
    id: 'has-29',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Hur snabbt får du köra vid en järnvägskorsning utan bommar?',
    options: ['50 km/h', 'Anpassad hastighet så du kan stanna', '30 km/h'],
    correctIndex: 1,
    explanation: 'Du ska anpassa hastigheten så du kan stanna framför spåret om ett tåg kommer. Det finns ingen fast gräns utöver skyltning.',
  },
  {
    id: 'has-30',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vilken böter gäller normalt för fortkörning 11-15 km/h?',
    options: ['1 200 kr', '2 000 kr', '2 400 kr'],
    correctIndex: 1,
    explanation: 'Vid fortkörning 11-15 km/h är böterna normalt 2 000 kronor.',
  },
  {
    id: 'has-31',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad innebär "2+1-väg" för hastighetsbegränsningar?',
    options: ['Alltid 90 km/h', 'Vanligen 90 km/h men beror på skyltning', 'Alltid 70 km/h'],
    correctIndex: 1,
    explanation: '2+1-vägar har vanligen 90 km/h men hastigheten kan variera beroende på skyltning.',
  },
  {
    id: 'has-32',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad gäller om du kör på en grusväg utan hastighetsskyltning utanför tätort?',
    options: ['50 km/h', '70 km/h', '30 km/h'],
    correctIndex: 1,
    explanation: 'Utanför tätbebyggt område gäller 70 km/h generellt, men på grusväg bör du anpassa efter väglag.',
  },
  {
    id: 'has-33',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Hur påverkar en liten hastighetsökning den kinetiska energin?',
    options: ['Linjärt — dubbel hastighet ger dubbel energi', 'Kvadratiskt — dubbel hastighet ger fyra gånger energi', 'Ingen skillnad'],
    correctIndex: 1,
    explanation: 'Kinetisk energi växer med hastigheten i kvadrat. Därav den drastiska ökningen av skaderisk vid högre hastigheter.',
  },
  {
    id: 'has-34',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vilken är den maximala tillåtna hastigheten i Sverige?',
    options: ['120 km/h', '130 km/h', '110 km/h'],
    correctIndex: 0,
    explanation: 'Den högsta tillåtna hastigheten i Sverige är 120 km/h, och den gäller på vissa motorvägssträckor.',
  },
  {
    id: 'has-35',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad gäller om du passerar en hastighetsskylt med "50" i en röd ring?',
    options: ['Rekommendation 50 km/h', 'Högsta tillåtna hastighet 50 km/h', 'Minsta hastighet 50 km/h'],
    correctIndex: 1,
    explanation: 'En röd ring runt siffran anger ett förbud — högsta tillåtna hastighet 50 km/h.',
  },
  {
    id: 'has-36',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Du kör med vinterdäck på sommaren. Hur påverkar det bromssträckan?',
    options: ['Ingen skillnad', 'Bromssträckan blir längre', 'Bromssträckan blir kortare'],
    correctIndex: 1,
    explanation: 'Vinterdäck på sommaren ger sämre grepp och längre bromssträcka — gummit är för mjukt för varma vägar.',
  },
  {
    id: 'has-37',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'En hastighetskamera (ATK) tar foto av din bil. Vem blir ansvarig?',
    options: ['Ägaren alltid', 'Föraren — ägaren tillfrågas om vem som körde', 'Ingen om du inte erkänner'],
    correctIndex: 1,
    explanation: 'Ägaren kontaktas och frågas vem som körde. Ansvaret ligger på föraren, inte nödvändigtvis ägaren.',
  },
  {
    id: 'has-38',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad innebär hastighetsdämpande åtgärder som gupp i vägen?',
    options: ['Att vägen behöver repareras', 'Att hastigheten ska sänkas för säkerhetens skull', 'Att området är avstängt'],
    correctIndex: 1,
    explanation: 'Gupp och farthinder placeras för att tvinga ner hastigheten, ofta vid skolor och bostadsområden.',
  },
  {
    id: 'has-39',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Hur långt kör du per sekund i 50 km/h?',
    options: ['Cirka 14 meter', 'Cirka 10 meter', 'Cirka 20 meter'],
    correctIndex: 0,
    explanation: '50 km/h ÷ 3,6 = ca 14 meter per sekund.',
  },
  {
    id: 'has-40',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad gäller vid "variabel hastighet" (elektroniska skyltar som ändras)?',
    options: ['De gäller inte, bara fasta skyltar gäller', 'Den aktuella visade hastigheten gäller', 'Du kan välja vilken som helst'],
    correctIndex: 1,
    explanation: 'Variabla hastighetsvisningar gäller när de är aktiva och kan ändras efter trafiksituation, väder m.m.',
  },
  {
    id: 'has-41',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vilken hastighet bör du anpassa dig till i ett bostadsområde med lekande barn?',
    options: ['50 km/h', 'Mycket lägre — vara beredd att stanna direkt', '70 km/h'],
    correctIndex: 1,
    explanation: 'I bostadsområden med barn ska du köra så sakta att du hinner stanna om ett barn springer ut.',
  },
  {
    id: 'has-42',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vad innebär det att "reaktionssträckan" ökar med hastigheten?',
    options: ['Ingenting speciellt', 'Ju fortare du kör, desto längre kör du under reaktionstiden innan du börjar bromsa', 'Att du reagerar långsammare vid hög hastighet'],
    correctIndex: 1,
    explanation: 'Reaktionssträckan = hastighet × reaktionstid. Vid högre hastighet kör du längre under den tid det tar att reagera.',
  },
  {
    id: 'has-43',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vilken total stoppsträcka har du vid 70 km/h med 1 sekunds reaktionstid på torr väg?',
    options: ['Cirka 35 meter', 'Cirka 50 meter', 'Cirka 70 meter'],
    correctIndex: 1,
    explanation: 'Reaktionssträcka ≈ 19 m + bromssträcka ≈ 26 m = total ≈ 45-50 meter vid 70 km/h.',
  },
  {
    id: 'has-44',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad gäller om du kör in i en 20-zon?',
    options: ['Det är en rekommendation', 'Du får köra max 20 km/h i hela zonen', 'Det gäller bara dagtid'],
    correctIndex: 1,
    explanation: '20-zoner har en maxhastighet på 20 km/h och gäller i hela zonen tills slutmärke.',
  },
  {
    id: 'has-45',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Varför har Sverige infört 40 km/h-gränser i vissa tätorter?',
    options: ['För att spara bränsle', 'Forskning visar dramatisk minskning av dödsolyckor jämfört med 50 km/h', 'Det var ett tillfälligt test'],
    correctIndex: 1,
    explanation: 'Skillnaden mellan 40 och 50 km/h är avgörande för fotgängares överlevnad vid en kollision.',
  },
  {
    id: 'has-46',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad gäller om du kör med tungt lass på taket?',
    options: ['Du ska köra snabbare för att kompensera', 'Bromssträckan ökar och du ska anpassa hastigheten', 'Ingen skillnad'],
    correctIndex: 1,
    explanation: 'Tung last ökar bilens vikt och höjder tyngdpunkten, vilket ökar bromssträckan och påverkar stabilitet i kurvor.',
  },
  {
    id: 'has-47',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad händer om du blir tagen för fortkörning av en hastighetskamera?',
    options: ['Du får ett brev hem med böter', 'Du stoppas på plats', 'Ingenting händer'],
    correctIndex: 0,
    explanation: 'Hastighetskameror fotograferar och bilägaren får brev med böter eller fråga om vem som körde.',
  },
  {
    id: 'has-48',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Hur påverkar regn bromssträckan?',
    options: ['Ingen påverkan', 'Bromssträckan kan fördubblas', 'Bromssträckan minskar'],
    correctIndex: 1,
    explanation: 'Vatten på vägen minskar friktionen avsevärt. Bromssträckan kan bli dubbelt så lång vid våt vägbana.',
  },
  {
    id: 'has-49',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'En bil med ABS-bromsar — förkortas bromssträckan jämfört med utan ABS?',
    options: ['Ja, alltid', 'Inte nödvändigtvis — ABS förhindrar hjullåsning men förkortar inte alltid sträckan', 'ABS har ingen effekt'],
    correctIndex: 1,
    explanation: 'ABS förhindrar hjullåsning och gör att du kan styra under inbromsning, men bromssträckan blir inte alltid kortare — ibland längre på grus/snö.',
  },
  {
    id: 'has-50',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Hur snabbt får du köra i en miljözon?',
    options: ['Alltid 30 km/h', 'Enligt vanlig skyltning — miljözon reglerar utsläpp, inte hastighet', '50 km/h alltid'],
    correctIndex: 1,
    explanation: 'Miljözoner reglerar vilka fordon som får köra där baserat på utsläpp, inte hastighet.',
  },
  {
    id: 'has-51',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vad gäller om du befinner dig på en 90-väg och det börjar snöa kraftigt?',
    options: ['90 km/h gäller fortfarande', 'Du ska anpassa och köra långsammare', 'Stanna tills det slutar snöa'],
    correctIndex: 1,
    explanation: 'Hastighetsgränsen är ett maximum. Vid snö ska du anpassa hastigheten efter förhållandena.',
  },
  {
    id: 'has-52',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Hur beräknar man ungefärlig bromssträcka med formeln?',
    options: ['Hastighet × 2', 'Hastighet i km/h², dividerat med 250 (torr väg)', 'Hastighet × reaktionstid'],
    correctIndex: 1,
    explanation: 'En tumregel: bromssträcka ≈ (hastighet i km/h)² / 250 meter på torr väg. Vid 100 km/h: 10000/250 = 40 m.',
  },
  {
    id: 'has-53',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad gäller kring hastighet på en parkeringsplats?',
    options: ['50 km/h', 'Anpassad, ofta mycket låg hastighet (ca 10-20 km/h)', '30 km/h'],
    correctIndex: 1,
    explanation: 'På parkeringsplatser ska du köra mycket sakta — fotgängare, barn och backning förekommer hela tiden.',
  },
  {
    id: 'has-54',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vad gäller om hastighetsskylten visar 80 km/h men det är en skola i närheten?',
    options: ['80 km/h gäller', 'Du ska anpassa efter situationen, särskilt vid skoltider', 'Alltid 30 km/h'],
    correctIndex: 1,
    explanation: 'Även om skylten visar 80 ska du visa extra försiktighet vid skolor. Anpassad hastighet gäller alltid.',
  },
  {
    id: 'has-55',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad händer juridiskt om du orsakar en olycka i 50 km/h i en 50-zon men vägförhållandena krävde lägre?',
    options: ['Du frias — du höll hastighetsgränsen', 'Du kan fällas — du ska anpassa hastigheten', 'Oklart rättsläge'],
    correctIndex: 1,
    explanation: 'Att hålla hastighetsgränsen frikänner inte automatiskt. Du har alltid skyldighet att anpassa efter förhållanden.',
  },
  {
    id: 'has-56',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Hur lång är ungefärlig total stoppsträcka vid 30 km/h på torr väg?',
    options: ['Cirka 5 meter', 'Cirka 13 meter', 'Cirka 25 meter'],
    correctIndex: 1,
    explanation: 'Vid 30 km/h: reaktionssträcka ca 8 m + bromssträcka ca 5 m = total ca 13 meter.',
  },
  {
    id: 'has-57',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vad händer om du kör 25 km/h för fort?',
    options: ['Varning utan böter', 'Böter på cirka 3 200 kr', 'Körkortet återkallas'],
    correctIndex: 1,
    explanation: 'Vid fortkörning 21-25 km/h ligger böterna runt 3 200 kronor.',
  },
  {
    id: 'has-58',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad menas med "85:e percentilen" i trafiksäkerhetssammanhang?',
    options: ['Att 85% av förarna kör snabbare', 'Hastigheten som 85% av trafikanterna inte överskrider', 'Att 85% av bromsarna fungerar'],
    correctIndex: 1,
    explanation: '85:e percentilen används för att bestämma lämplig hastighetsgräns — den hastighet som 85% av förarna naturligt håller sig under.',
  },
  {
    id: 'has-59',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Du kör i dimma med sikt på ca 50 meter. Vilken hastighet bör du hålla?',
    options: ['50 km/h', 'Max 30-40 km/h — du ska kunna stanna inom siktsträckan', '70 km/h med dimljus'],
    correctIndex: 1,
    explanation: 'Du ska kunna stanna inom den sträcka du kan se. Vid 50 m sikt bör du inte köra mer än 30-40 km/h.',
  },
  {
    id: 'has-60',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vilken hastighet gäller generellt vid utfart ur tätort (utan skyltning)?',
    options: ['70 km/h', '90 km/h', '50 km/h'],
    correctIndex: 0,
    explanation: 'Utanför tätort gäller generellt 70 km/h på landsväg om inget annat anges.',
  },
  {
    id: 'has-61',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Hur påverkar nedförsbacke bromssträckan?',
    options: ['Ingen påverkan', 'Bromssträckan ökar', 'Bromssträckan minskar'],
    correctIndex: 1,
    explanation: 'I nedförsbacke verkar tyngdkraften och ökar bilens hastighet. Bromssträckan blir längre.',
  },
  {
    id: 'has-62',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad händer om du under prövotiden (2 år med nytt körkort) blir tagen för grov fortkörning?',
    options: ['Bara böter', 'Körkortet återkallas och du måste ta om hela körkortsproceduren', 'Varning'],
    correctIndex: 1,
    explanation: 'Under prövotiden är kraven striktare. Grov fortkörning kan leda till att körkortet återkallas och du måste ta om allt.',
  },
  {
    id: 'has-63',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad bör du tänka på om du kör på en väg med farthinder/gupp?',
    options: ['Kör i samma hastighet', 'Sänk hastigheten rejält före guppet', 'Öka farten för att komma över snabbt'],
    correctIndex: 1,
    explanation: 'Farthinder ska passeras i låg hastighet. Att köra för fort över gupp skadar bilen och kan vara farligt.',
  },
  {
    id: 'has-64',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vad innebär "speed management" i trafikplanering?',
    options: ['Att alla ska köra lika fort', 'Att anpassa hastighetsgränser för att minska olyckor', 'Att ta bort alla hastighetsskyltar'],
    correctIndex: 1,
    explanation: 'Speed management handlar om att rätt hastighetsgräns sätts baserat på vägtyp, omgivning och trafikflöde.',
  },
  {
    id: 'has-65',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Hur stor är skillnaden i krockenergi mellan 50 km/h och 70 km/h?',
    options: ['40% mer', 'Nästan dubbelt (96% mer)', 'Trippelt'],
    correctIndex: 1,
    explanation: 'Kinetisk energi = ½mv². (70/50)² = 1,96. Krockenergin nästan fördubblas — trots bara 20 km/h skillnad.',
  },
  {
    id: 'has-66',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Du kör bakom en stor lastbil i 90 km/h. Hur bör du anpassa?',
    options: ['Ligga nära för att se bättre', 'Hålla stort avstånd — du ser inte vad som händer framför lastbilen', 'Köra om direkt'],
    correctIndex: 1,
    explanation: 'Bakom en lastbil ser du ingenting framåt. Håll extra avstånd och var beredd.',
  },
  {
    id: 'has-67',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Hur påverkar bilvikten bromssträckan?',
    options: ['Tyngre bil = kortare bromssträcka', 'Tyngre bil = längre bromssträcka', 'Ingen påverkan'],
    correctIndex: 1,
    explanation: 'En tyngre bil har mer rörelseenergi som ska bromsas bort, vilket ger längre bromssträcka.',
  },
  {
    id: 'has-68',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad gäller kring hastighet för buss med stående passagerare?',
    options: ['Samma som alla andra', 'Max 50 km/h', 'Max 70 km/h'],
    correctIndex: 1,
    explanation: 'Buss med stående passagerare får köra max 50 km/h av säkerhetsskäl.',
  },
  {
    id: 'has-69',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Vad är viktigt att tänka på om du kör sent på kvällen?',
    options: ['Du kan köra fortare för det är mindre trafik', 'Anpassa hastigheten — trötthet, mörker och viltolyckor ökar risken', 'Kör med helljus hela tiden'],
    correctIndex: 1,
    explanation: 'Natt och kväll innebär ökade risker: trötthet, sämre sikt och fler viltolyckor. Anpassa hastigheten.',
  },
  {
    id: 'has-70',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vad gäller om du kommer från en 70-väg och kör in i en 30-zon?',
    options: ['Du anpassar gradvis', '30 km/h gäller omedelbart efter skylten', 'Du har 100 meter att bromsa ner'],
    correctIndex: 1,
    explanation: 'Hastighetsgränsen gäller direkt vid skylten. Du ska vara nere i 30 km/h vid skyltens placering.',
  },
  {
    id: 'has-71',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad innebär en "ISA-system" (Intelligent Speed Adaptation)?',
    options: ['En typ av airbag', 'System som varnar eller begränsar hastigheten baserat på GPS och skyltdata', 'En motortyp'],
    correctIndex: 1,
    explanation: 'ISA-system använder GPS/kamera för att identifiera hastighetsgräns och kan varna föraren eller begränsa hastigheten.',
  },
  {
    id: 'has-72',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Du kör på en våt gata i 50 km/h. Bör du öka avståndet till framförvarande?',
    options: ['Nej, 50 km/h är tillräckligt sakta', 'Ja, våt väg kräver längre bromssträcka', 'Bara om det regnar mycket'],
    correctIndex: 1,
    explanation: 'Våt väg ger längre bromssträcka. Öka alltid avståndet vid våt vägbana.',
  },
  {
    id: 'has-73',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vad gäller om du passerar slutmärke för 30-zon inne i tätort?',
    options: ['70 km/h gäller', '50 km/h gäller (tätort)', '30 km/h gäller fortfarande'],
    correctIndex: 1,
    explanation: 'Efter en 30-zon inne i tätort gäller den generella tätortshastigheten 50 km/h om inget annat anges.',
  },
  {
    id: 'has-74',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Hur beräknas reaktionssträckan?',
    options: ['Hastighet i km/h × 3', 'Hastighet i km/h / 3,6 × reaktionstid i sekunder', 'Hastighet i km/h × 10'],
    correctIndex: 1,
    explanation: 'Reaktionssträcka = (km/h ÷ 3,6) × reaktionstid. Vid 90 km/h och 1 sek: 25 m/s × 1 = 25 meter.',
  },
  {
    id: 'has-75',
    category: 'hastighet',
    difficulty: 'easy',
    question: 'Du kör på en motorväg med skyltning 110 km/h. Vad gäller om du vill köra i 100 km/h?',
    options: ['Det är förbjudet att köra under gränsen', 'Det är tillåtet — gränsen är ett maximum', 'Du måste hålla 110'],
    correctIndex: 1,
    explanation: 'Hastighetsgränsen anger det maximala. Du får alltid köra långsammare (minst 40 km/h på motorväg).',
  },
  {
    id: 'has-76',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Varför är hastigheten den viktigaste faktorn för trafiksäkerhet?',
    options: ['Snabbare bilar har sämre bromsar', 'Högre hastighet ger längre stoppsträcka OCH kraftigare kollisioner', 'Det är bara en myt'],
    correctIndex: 1,
    explanation: 'Hastigheten påverkar dubbelt: mer tid att reagera behövs OCH krockenergin ökar kraftigt. Det är trafiksäkerhetens viktigaste faktor.',
  },
  {
    id: 'has-77',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad gäller för moped klass I på väg med 50 km/h?',
    options: ['Mopeden får köra i 50 km/h', 'Moped klass I max 45 km/h enligt konstruktion', 'Moped klass I max 25 km/h'],
    correctIndex: 1,
    explanation: 'Moped klass I är konstruerad för max 45 km/h. Den får köra på 50-vägar men inte snabbare än 45 km/h.',
  },
  {
    id: 'has-78',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vad gäller om du kör genom en tunnel?',
    options: ['Alltid 30 km/h', 'Följ skyltningen — tunnlar har ofta nedsatt hastighet', 'Samma som utanför tunneln'],
    correctIndex: 1,
    explanation: 'Tunnlar har ofta särskild hastighetsbegränsning. Följ skyltningen och var extra uppmärksam.',
  },
  {
    id: 'has-79',
    category: 'hastighet',
    difficulty: 'hard',
    question: 'Vad innebär "fartblindhet" och när uppstår det?',
    options: ['Att man inte ser hastighetsskyltar', 'Att man underskattar hastigheten efter att ha kört länge i hög hastighet', 'Att ögonen påverkas av fart'],
    correctIndex: 1,
    explanation: 'Fartblindhet uppstår t.ex. efter motorvägskörning — man vänjer sig vid hastigheten och underskattar den, kör för fort vid avfarten.',
  },
  {
    id: 'has-80',
    category: 'hastighet',
    difficulty: 'medium',
    question: 'Vad gäller om en digital hastighetsskylt visar "blankt" (inget tal)?',
    options: ['Ingen hastighet gäller', 'Den generella gränsen gäller', 'Du ska stanna'],
    correctIndex: 1,
    explanation: 'Om en digital skylt är avstängd eller blank gäller den generella hastighetsgränsen för vägtypen.',
  },
];
