import { Question } from './types';

export const miljoBransleQuestions: Question[] = [
  {
    id: 'mil-1',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Vad är ecodriving?',
    options: [
      'Att köra så fort som möjligt för att spara tid',
      'Ett bränsleeffektivt körsätt som minskar utsläpp och förbrukning',
      'Att bara köra elbil',
    ],
    correctIndex: 1,
    explanation:
      'Ecodriving innebär ett mjukt och framsynt körsätt som minskar bränsleförbrukningen med upp till 10–15 % och sänker utsläppen.',
  },
  {
    id: 'mil-2',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Vilken åtgärd minskar bränsleförbrukningen mest?',
    options: [
      'Köra med öppna fönster istället för AC',
      'Hålla jämn hastighet och undvika kraftiga accelerationer',
      'Alltid köra på lägsta växel',
    ],
    correctIndex: 1,
    explanation:
      'Jämn hastighet och mjuka accelerationer är de mest effektiva sätten att minska bränsleförbrukningen. Kraftiga gasningar ökar förbrukningen markant.',
  },
  {
    id: 'mil-3',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Hur påverkar tomgångskörning miljön?',
    options: [
      'Den har ingen påverkan eftersom motorn knappt arbetar',
      'Den orsakar onödiga utsläpp och bränsleförbrukning utan att fordonet rör sig',
      'Den är bra för motorn och minskar slitage',
    ],
    correctIndex: 1,
    explanation:
      'Tomgångskörning förbrukar bränsle och producerar utsläpp helt i onödan. Stäng av motorn om du väntar mer än 30 sekunder.',
  },
  {
    id: 'mil-4',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vad är en miljözon?',
    options: [
      'Ett område med gratis parkering för elbilar',
      'Ett avgränsat område i en stad där fordon med höga utsläpp inte får köra',
      'En laddstation för elbilar',
    ],
    correctIndex: 1,
    explanation:
      'Miljözoner finns i större svenska städer och begränsar vilka fordon som får köra där baserat på fordonets utsläppsklassificering.',
  },
  {
    id: 'mil-5',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Vilken fördel har elbilar jämfört med bensinbilar?',
    options: [
      'De kräver aldrig service',
      'De har inga avgasutsläpp vid körning',
      'De är alltid billigare att köpa',
    ],
    correctIndex: 1,
    explanation:
      'Elbilar producerar inga avgasutsläpp vid körning. De bidrar till bättre luftkvalitet i städer, även om elproduktionen kan ha miljöpåverkan.',
  },
  {
    id: 'mil-6',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vad är en laddhybrid?',
    options: [
      'En bil som bara drivs av bränsle men har en stor generator',
      'En bil med både elmotor och förbränningsmotor som kan laddas via elnätet',
      'En elbil med extra batteri',
    ],
    correctIndex: 1,
    explanation:
      'En laddhybrid har både elmotor och förbränningsmotor. Batteriet kan laddas via elnätet och ger möjlighet att köra kortare sträckor helt på el.',
  },
  {
    id: 'mil-7',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vilken utsläppsklass krävs minst för att få köra i miljözon klass 2?',
    options: [
      'Euro 3',
      'Euro 5',
      'Euro 6',
    ],
    correctIndex: 1,
    explanation:
      'I miljözon klass 2 krävs minst Euro 5 för dieselfordon. Kraven kan variera beroende på bränsletyp och fordonskategori.',
  },
  {
    id: 'mil-8',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Hur kan du minska bilens bränsleförbrukning genom underhåll?',
    options: [
      'Använda tjockare motorolja',
      'Hålla rätt däcktryck och serva bilen regelbundet',
      'Köra med tungt takräcke monterat',
    ],
    correctIndex: 1,
    explanation:
      'Rätt däcktryck minskar rullmotståndet. Regelbunden service säkerställer att motor, filter och tändstift fungerar optimalt.',
  },
  {
    id: 'mil-9',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Varför bör du använda motorvärmare på vintern?',
    options: [
      'Bara för att få det varmt i kupén',
      'Det minskar utsläpp och slitage vid kallstart samt sänker bränsleförbrukningen',
      'Det ökar motorns effekt permanent',
    ],
    correctIndex: 1,
    explanation:
      'En motorvärmare gör att motorn snabbare når arbetstemperatur, vilket minskar utsläpp, bränsleförbrukning och motorslitage vid kallstart.',
  },
  {
    id: 'mil-10',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Hur lång tid innan avfärd bör motorvärmaren slås på?',
    options: [
      'Minst 2 timmar',
      'Cirka 1–2 timmar beroende på temperatur',
      'Det räcker med 15 minuter',
    ],
    correctIndex: 1,
    explanation:
      'Motorvärmaren bör slås på 1–2 timmar innan avfärd beroende på utetemperatur. En timer är energieffektivt och praktiskt.',
  },
  {
    id: 'mil-11',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vilken körstrategi sparar mest bränsle i stadstrafik?',
    options: [
      'Accelerera snabbt upp till rätt hastighet och sedan rulla',
      'Förutse trafikrytmen och accelerera mjukt, utnyttja motorbroms',
      'Hålla låg växel och hög motorvarv',
    ],
    correctIndex: 1,
    explanation:
      'Genom att förutse trafikrytmen och köra jämnt med mjuka accelerationer och motorbroms kan du minska bränsleförbrukningen avsevärt i stad.',
  },
  {
    id: 'mil-12',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Hur påverkar ett tungt lastat takräcke bränsleförbrukningen?',
    options: [
      'Det har ingen påverkan',
      'Det ökar luftmotståndet och bränsleförbrukningen',
      'Det minskar förbrukningen genom bättre balans',
    ],
    correctIndex: 1,
    explanation:
      'Ett takräcke ökar luftmotståndet markant, särskilt vid högre hastigheter. Ta av takräcket när det inte används.',
  },
  {
    id: 'mil-13',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vilka gaser i bilens avgaser bidrar mest till växthuseffekten?',
    options: [
      'Syre och kväve',
      'Koldioxid (CO₂) och metan',
      'Argon och helium',
    ],
    correctIndex: 1,
    explanation:
      'Koldioxid (CO₂) är den dominerande växthusgasen från fordon. Metan kan också bildas. Dessa gaser bidrar till global uppvärmning.',
  },
  {
    id: 'mil-14',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vad bör du göra med växeln vid ecodriving?',
    options: [
      'Alltid köra på lägsta möjliga växel',
      'Växla upp tidigt till högre växel för att hålla varvtalet lågt',
      'Aldrig använda högsta växeln',
    ],
    correctIndex: 1,
    explanation:
      'Vid ecodriving bör du växla upp tidigt (runt 2000–2500 varv) och köra på högsta möjliga växel. Lägre varvtal ger lägre bränsleförbrukning.',
  },
  {
    id: 'mil-15',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vilken av följande åtgärder ger störst minskning av koldioxidutsläpp?',
    options: [
      'Byta till syntetolja',
      'Minska hastigheten från 120 till 100 km/h på motorväg',
      'Byta till bredare däck',
    ],
    correctIndex: 1,
    explanation:
      'Att sänka hastigheten från 120 till 100 km/h minskar bränsleförbrukningen med cirka 20 %, vilket ger en betydande minskning av CO₂-utsläpp.',
  },
  {
    id: 'mil-16',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Vilken drivmedelstyp ger lägst koldioxidutsläpp vid körning?',
    options: ['Bensin', 'El (nollutsläpp vid körning)', 'Diesel'],
    correctIndex: 1,
    explanation: 'Elbilar har noll direkta utsläpp vid körning. Totalt beror miljöpåverkan på hur elen produceras.',
  },
  {
    id: 'mil-17',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Vad är den enklaste åtgärden för att minska bilens utsläpp?',
    options: ['Byta bil', 'Köra mindre och samåka', 'Tanka premium'],
    correctIndex: 1,
    explanation: 'Att minska körningen och samåka minskar utsläppen per person direkt.',
  },
  {
    id: 'mil-18',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Hur påverkar AC (luftkonditionering) bränsleförbrukningen?',
    options: ['Ingen påverkan', 'Ökar förbrukningen med ca 5-10%', 'Minskar förbrukningen'],
    correctIndex: 1,
    explanation: 'AC-kompressorn belastar motorn och ökar bränsleförbrukningen, särskilt i stadstrafik.',
  },
  {
    id: 'mil-19',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vad innebär "well-to-wheel" (brunn till hjul)?',
    options: ['Oljebrunnens djup', 'Totala utsläpp från produktion av drivmedel till körning', 'Bilens livslängd'],
    correctIndex: 1,
    explanation: 'Well-to-wheel räknar in alla utsläpp — från produktion av drivmedlet till det som släpps ut vid körning.',
  },
  {
    id: 'mil-20',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vad är HVO100?',
    options: ['Högviskös olja', 'Förnybart dieselbränsle gjort av t.ex. tallolja', 'En sorts motorolja'],
    correctIndex: 1,
    explanation: 'HVO100 är ett förnybart dieselbränsle som kan minska CO₂-utsläppen med upp till 90% jämfört med fossil diesel.',
  },
  {
    id: 'mil-21',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Varför ska du undvika snabba accelerationer?',
    options: ['Det sliter på bromsarna', 'Det ökar bränsleförbrukningen avsevärt', 'Det påverkar inte förbrukningen'],
    correctIndex: 1,
    explanation: 'Snabba accelerationer kräver mycket bränsle. Mjuk gasning sparar bränsle och minskar utsläpp.',
  },
  {
    id: 'mil-22',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Hur påverkar öppna fönster i hög hastighet bränsleförbrukningen?',
    options: ['Minskar den', 'Ökar den — luftmotståndet ökar', 'Ingen påverkan'],
    correctIndex: 1,
    explanation: 'Öppna fönster vid motorvägshastighet ökar luftmotståndet och bränsleförbrukningen. Använd AC istället.',
  },
  {
    id: 'mil-23',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vad är "Bonus Malus"-systemet?',
    options: ['Bilförsäkring', 'Skattesystem där miljöbilar får bonus och utsläppsbilar får malus (högre skatt)', 'Parkeringssystem'],
    correctIndex: 1,
    explanation: 'Bonus Malus ger lägre skatt/bonus för bilar med låga utsläpp och högre skatt för bilar med höga utsläpp.',
  },
  {
    id: 'mil-24',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Varför bör du planera din rutt före resan?',
    options: ['Bara för att spara tid', 'Kortare och bättre rutt sparar bränsle', 'Det gör ingen skillnad'],
    correctIndex: 1,
    explanation: 'Planering hjälper dig undvika omvägar och trafikstockningar, vilket sparar bränsle och tid.',
  },
  {
    id: 'mil-25',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vad är E85?',
    options: ['Motorolja', 'Bränsle bestående av 85% etanol och 15% bensin', 'Bilmodell'],
    correctIndex: 1,
    explanation: 'E85 är ett bränsle med hög andel etanol (85%). Det kräver en anpassad motor (flexifuel) och ger lägre fossila utsläpp.',
  },
  {
    id: 'mil-26',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vad innebär "miljözon klass 3" i Sverige?',
    options: ['Bara eldrivna fordon tillåtna', 'Bara fordon som uppfyller Euro 6 eller nyare', 'Alla fordon tillåtna'],
    correctIndex: 0,
    explanation: 'Miljözon klass 3 (den striktaste) tillåter bara nollutsläppsfordon — elbilar, bränslecellsbilar osv.',
  },
  {
    id: 'mil-27',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Vad händer med bränsleförbrukningen om du kör med underuppumpade däck?',
    options: ['Minskar', 'Ökar — mer rullmotstånd', 'Ingen skillnad'],
    correctIndex: 1,
    explanation: 'Lågt däcktryck ökar rullmotståndet, vilket kräver mer energi och bränsle.',
  },
  {
    id: 'mil-28',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Hur påverkar bilens vikt bränsleförbrukningen?',
    options: ['Ingen påverkan', 'Tyngre bil förbrukar mer — ta bort onödig last', 'Tyngre bil förbrukar mindre'],
    correctIndex: 1,
    explanation: 'Varje extra kilo kräver mer energi att accelerera och flytta. Ta bort onödig last ur bilen.',
  },
  {
    id: 'mil-29',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vad är "livscykelanalys" för en bil?',
    options: ['Service-schema', 'Analys av miljöpåverkan från produktion, användning till skrotning', 'Bilens värdeminskn'],
    correctIndex: 1,
    explanation: 'Livscykelanalys räknar in hela kedjan: materialutvinning, tillverkning, körning och återvinning.',
  },
  {
    id: 'mil-30',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Vad är fördelen med att använda motorvärmare på vintern?',
    options: ['Bara komfort', 'Motorn startar lättare, utsläppen minskar och bränsle sparas', 'Ingen fördel'],
    correctIndex: 1,
    explanation: 'Motorvärmare minskar utsläpp vid kallstart, sparar bränsle och minskar slitage på motorn.',
  },
  {
    id: 'mil-31',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vad innebär "pulsdriving" i ecodriving?',
    options: ['Att gasa i pulser', 'Att accelerera till önskad hastighet och sedan rulla — undvik konstant gasning', 'Att köra oregelbundet'],
    correctIndex: 1,
    explanation: 'Pulsdriving innebär att man accelererar effektivt och sedan rullar utan gas, istället för att gasa konstant.',
  },
  {
    id: 'mil-32',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vilken gas i avgaserna är mest ansvarig för den lokala luftföroreningsproblematiken i städer?',
    options: ['Koldioxid (CO₂)', 'Kvävedioxid (NO₂)', 'Vattenånga'],
    correctIndex: 1,
    explanation: 'NO₂ orsakar luftvägsproblem och bidrar till dålig luftkvalitet i städer. CO₂ är en klimatgas men inte lika hälsofarlig lokalt.',
  },
  {
    id: 'mil-33',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Hur bör du köra i stadstrafik för att spara bränsle?',
    options: ['Accelerera snabbt mellan rödljus', 'Kör jämnt, planera stopp och accelerera mjukt', 'Kör i så hög växel som möjligt hela tiden'],
    correctIndex: 1,
    explanation: 'Jämn körning med mjuka accelerationer och tidiga inbromsningar sparar mest bränsle i stadstrafik.',
  },
  {
    id: 'mil-34',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vad är fördelen med att byta till lågviskös motorolja?',
    options: ['Inget', 'Mindre friktion i motorn = lägre bränsleförbrukning', 'Motorn går sämre'],
    correctIndex: 1,
    explanation: 'Lågviskös olja minskar friktionen i motorn, vilket kan sänka bränsleförbrukningen med 2-5%.',
  },
  {
    id: 'mil-35',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vad är "kolmonoxid" (CO) och varför är det farligt?',
    options: ['En ofarlig gas', 'Giftig gas från ofullständig förbränning — kan döda i slutna utrymmen', 'Samma som koldioxid'],
    correctIndex: 1,
    explanation: 'CO är en giftig, lukt- och färglös gas som bildas vid ofullständig förbränning. Livsfarlig i t.ex. garage med motorn igång.',
  },
  {
    id: 'mil-36',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Varför bör du ta bort takboxen när den inte används?',
    options: ['Den stjäl uppmärksamhet', 'Den ökar luftmotståndet och bränsleförbrukningen', 'Ingen anledning'],
    correctIndex: 1,
    explanation: 'En takbox ökar luftmotståndet kraftigt — bränsleförbrukningen kan öka med 10-20% vid motorvägshastighet.',
  },
  {
    id: 'mil-37',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vad innebär "regenerativ bromsning" för miljön?',
    options: ['Inget speciellt', 'Bromsenergi omvandlas till el som laddar batteriet — mindre energispill', 'Bromsarna blir renare'],
    correctIndex: 1,
    explanation: 'Regenerativ bromsning i el/hybridbilar omvandlar rörelseenergi till el, vilket minskar energiförlust och förbrukning.',
  },
  {
    id: 'mil-38',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vad är en "bränslecellsbil"?',
    options: ['Bil med extra stor tank', 'Bil som omvandlar vätgas till el med vatten som enda utsläpp', 'En dieselbil'],
    correctIndex: 1,
    explanation: 'Bränslecellsbilar använder vätgas som omvandlas till el i en bränslecell. Enda utsläppet är rent vatten.',
  },
  {
    id: 'mil-39',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'I vilken växel bör du köra för bäst bränsleeconomi?',
    options: ['Så låg växel som möjligt', 'Så hög växel som möjligt utan att motorn hackar', 'Alltid 3:an'],
    correctIndex: 1,
    explanation: 'Hög växel vid låga varvtal ger bäst bränsleeconomi. Växla upp tidigt.',
  },
  {
    id: 'mil-40',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vad menas med "koldioxidavtryck" från bilkörning?',
    options: ['Bilens hjulspår', 'Total mängd CO₂ som bilen släpper ut', 'Märket på bilen'],
    correctIndex: 1,
    explanation: 'Koldioxidavtrycket är den totala mängden koldioxid som bilens användning ger upphov till.',
  },
  {
    id: 'mil-41',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vilken EU-avgasklass krävs minst för diesel i miljözon klass 1?',
    options: ['Euro 3', 'Euro 6', 'Euro 4'],
    correctIndex: 1,
    explanation: 'Miljözon klass 1 kräver minst Euro 6 för dieselbilar. Äldre dieslar får inte köra i zonen.',
  },
  {
    id: 'mil-42',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Vad bör du göra med gamla bilbatterier?',
    options: ['Slänga i soporna', 'Lämna in på återvinningsstation', 'Spara hemma'],
    correctIndex: 1,
    explanation: 'Bilbatterier innehåller farliga ämnen (bly, syra). De ska lämnas till en återvinningsstation.',
  },
  {
    id: 'mil-43',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Hur påverkar körning i stadstrafik bränsleförbrukningen jämfört med motorväg?',
    options: ['Staden är billigare', 'Stadskörning förbrukar mer pga konstanta stopp och starter', 'Samma förbrukning'],
    correctIndex: 1,
    explanation: 'Stadskörning med frekventa stopp och starter ger hög förbrukning. Jämn motorvägskörning är effektivare.',
  },
  {
    id: 'mil-44',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vad är "Euro 7"-krav?',
    options: ['Bränsletyp', 'Kommande strängare avgaskrav för alla nya fordon i EU', 'Bilens modellår'],
    correctIndex: 1,
    explanation: 'Euro 7 är nästa nivå av EU:s avgaskrav med strängare gränsvärden för utsläpp, inklusive partiklar och NOx.',
  },
  {
    id: 'mil-45',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Varför ska du serva bilen regelbundet?',
    options: ['Bara för garantin', 'En välservad bil förbrukar mindre och släpper ut mindre', 'Det spelar ingen roll'],
    correctIndex: 1,
    explanation: 'Regelbunden service säkerställer att motorn och avgassystemet fungerar optimalt — lägre förbrukning och utsläpp.',
  },
  {
    id: 'mil-46',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vad innebär "stopp-start" för ecodriving?',
    options: ['Stanna och starta motorn manuellt', 'Stäng av motorn vid stopp längre än 30 sekunder (automatik sköter det)', 'Kör och stanna ofta'],
    correctIndex: 1,
    explanation: 'Vid stopp längre än ca 30 sekunder sparar du bränsle genom att stänga av motorn. Start-stopp-automatik gör detta åt dig.',
  },
  {
    id: 'mil-47',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Hur mycket av bilens energi används faktiskt till att flytta bilen framåt?',
    options: ['Cirka 80%', 'Cirka 20-25% hos en förbränningsmotor', 'Cirka 50%'],
    correctIndex: 1,
    explanation: 'En förbränningsmotor omvandlar bara ca 20-25% av bränslets energi till rörelse. Resten blir värme.',
  },
  {
    id: 'mil-48',
    category: 'miljo-bransle',
    difficulty: 'easy',
    question: 'Vad kan du göra för att minska buller från bilen?',
    options: ['Inget', 'Hålla jämn hastighet och undvika höga varv', 'Köra fort'],
    correctIndex: 1,
    explanation: 'Höga varv och hastighet ger mer buller. Jämn körning och låga varv minskar störande ljud.',
  },
  {
    id: 'mil-49',
    category: 'miljo-bransle',
    difficulty: 'medium',
    question: 'Vad innebär "samåkning" ur miljösynpunkt?',
    options: ['Att köra i kolonne', 'Att dela bil med andra — minskar antal bilar och utsläpp per person', 'Att köra parkallellt'],
    correctIndex: 1,
    explanation: 'Samåkning minskar antal bilar på vägen, minskar utsläpp per person och sparar kostnader.',
  },
  {
    id: 'mil-50',
    category: 'miljo-bransle',
    difficulty: 'hard',
    question: 'Vad är "partiklar" (PM2.5) och varför är de farliga?',
    options: ['Damm i luften', 'Små partiklar från avgaser och däckslitage som tränger djupt in i lungorna', 'Sand på vägen'],
    correctIndex: 1,
    explanation: 'PM2.5 är mikroskopiska partiklar som tränger djupt in i lungorna och blodomloppet. Orsakar hjärt- och lungsjukdomar.',
  },
];
