import { Question } from './types';

export const morkerkorningQuestions: Question[] = [
  {
    id: 'mrk-1',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'När ska du använda halvljus?',
    options: [
      'Bara när det är helt mörkt',
      'Alltid vid körning, även dagtid',
      'Bara utanför tättbebyggt område',
    ],
    correctIndex: 1,
    explanation:
      'I Sverige är det krav att använda halvljus (eller varselljus) under all körning, dygnet runt, oavsett väder och ljusförhållanden.',
  },
  {
    id: 'mrk-2',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'När ska du byta från helljus till halvljus?',
    options: [
      'Bara i tätort',
      'När du möter eller kör nära bakom ett annat fordon, samt vid tillräcklig gatubelysning',
      'Aldrig, helljus ska alltid användas i mörker',
    ],
    correctIndex: 1,
    explanation:
      'Helljus bländar mötande och framförvarande trafikanter. Byt till halvljus i god tid vid möte, när du kör bakom annat fordon eller i belyst område.',
  },
  {
    id: 'mrk-3',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Vad ska du göra om du blir bländad av mötande bils helljus?',
    options: [
      'Tända ditt eget helljus som svar',
      'Titta mot höger vägkant, sakta ner och undvik att titta rakt in i ljuset',
      'Stanna omedelbart mitt på vägen',
    ],
    correctIndex: 1,
    explanation:
      'Vid bländning: rikta blicken mot höger vägkant, sänk farten och undvik att titta rakt in i ljuset. Blinka inte tillbaka med helljus.',
  },
  {
    id: 'mrk-4',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'När får du använda dimljus framtill?',
    options: [
      'Bara vid dimma',
      'Vid dimma, kraftigt regn, snöfall eller liknande siktnedsättande förhållanden',
      'Alltid som extra belysning i mörker',
    ],
    correctIndex: 1,
    explanation:
      'Dimljus framtill får användas vid dimma, kraftigt regn, snöfall eller liknande förhållanden som kraftigt nedsätter sikten.',
  },
  {
    id: 'mrk-5',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Ska fotgängare använda reflex vid mörkerkörning?',
    options: [
      'Nej, det är bara en rekommendation utan lagkrav',
      'Ja, reflexer rekommenderas starkt och kan rädda liv genom att synas upp till 125 meter bort',
      'Bara barn behöver reflexer',
    ],
    correctIndex: 1,
    explanation:
      'En fotgängare utan reflex syns på bara 25 meter i halvljus. Med reflex syns du på upp till 125 meter, vilket ger föraren tid att reagera.',
  },
  {
    id: 'mrk-6',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Vilken belysning krävs på en cykel vid mörkerkörning?',
    options: [
      'Bara en reflex baktill räcker',
      'Vit lampa fram, röd lampa och reflex baktill samt reflexer på sidorna',
      'Ingen belysning behövs om cykeln har reflexer',
    ],
    correctIndex: 1,
    explanation:
      'En cykel ska ha vit lampa fram, röd lampa bak, röd reflex bak och sidoreflexer (eller reflexdäck) vid körning i mörker.',
  },
  {
    id: 'mrk-7',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Hur långt lyser halvljuset ungefär framför bilen?',
    options: [
      'Cirka 20–30 meter',
      'Cirka 30–50 meter',
      'Cirka 100 meter',
    ],
    correctIndex: 1,
    explanation:
      'Halvljuset lyser upp vägen cirka 30–50 meter framåt. Det innebär att du vid 70 km/h kan ha en stoppsträcka som överstiger ljusområdet.',
  },
  {
    id: 'mrk-8',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Varför är risken för viltolyckor extra stor i mörker?',
    options: [
      'Djuren attackerar bilar i mörker',
      'Djur syns sent i strålkastarljuset och kan bländas så de stannar på vägen',
      'Djur rör sig bara på natten',
    ],
    correctIndex: 1,
    explanation:
      'Djur syns mycket sent i halvljuset. De kan dessutom bländas av strålkastarna och stanna mitt på vägen istället för att fly.',
  },
  {
    id: 'mrk-9',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Hur bör du anpassa hastigheten vid mörkerkörning?',
    options: [
      'Kör samma hastighet som dagtid',
      'Sänk hastigheten så att du kan stanna inom det upplysta området',
      'Kör snabbare för att komma hem fortare',
    ],
    correctIndex: 1,
    explanation:
      'Du ska alltid kunna stanna inom den sträcka du ser framför dig. I mörker innebär det ofta lägre hastighet än hastighetsgränsen.',
  },
  {
    id: 'mrk-10',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Vad gäller för dimljus baktill?',
    options: [
      'Det ska alltid vara på i mörker',
      'Det får bara användas vid sikt under 150 meter och måste släckas när sikten förbättras',
      'Det får användas istället för bakljus',
    ],
    correctIndex: 1,
    explanation:
      'Dimbakljus får bara tändas vid kraftigt nedsatt sikt (under 150 meter). Det bländar annars bakomvarande och måste släckas direkt när sikten blir bättre.',
  },
  {
    id: 'mrk-11',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Vad ska du göra om du kör i mörker och inte ser vägen tydligt?',
    options: ['Öka farten', 'Sänka hastigheten tills du kan se tillräckligt', 'Slå på helljuset alltid'],
    correctIndex: 1,
    explanation: 'Du ska alltid kunna stanna inom den sträcka du kan se. Sänk hastigheten i mörker.',
  },
  {
    id: 'mrk-12',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Varför ska du alltid köra med halvljus, även dagtid?',
    options: ['Det är lag i Sverige', 'Bara för att se bättre', 'Det gäller bara på vintern'],
    correctIndex: 0,
    explanation: 'I Sverige ska halvljus eller varselljus alltid vara tända under körning, dygnet runt.',
  },
  {
    id: 'mrk-13',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Hur långt lyser helljuset ungefär?',
    options: ['Cirka 50 meter', 'Cirka 300 meter', 'Cirka 100 meter'],
    correctIndex: 1,
    explanation: 'Helljus lyser ca 200-300 meter framåt beroende på bil och inställning.',
  },
  {
    id: 'mrk-14',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Varför ska du sänka hastigheten mer i mörker än dagtid?',
    options: ['Bilen bromsar sämre', 'Sikten är kraftigt begränsad — du ser faror senare', 'Motorn fungerar sämre'],
    correctIndex: 1,
    explanation: 'I mörker ser du hinder och faror senare. Du behöver lägre hastighet för att hinna reagera och stanna.',
  },
  {
    id: 'mrk-15',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Vad innebär "adaptivt ljus" (kurvatursljus)?',
    options: ['Ljus som lyser i kurvor', 'Strålkastare som svänger åt det håll du styr — lyser bättre i kurvor', 'Extra lampor på taket'],
    correctIndex: 1,
    explanation: 'Adaptivt ljus/kurvljus vrider strålkastarna åt det håll du styr, vilket ger bättre sikt i kurvor.',
  },
  {
    id: 'mrk-16',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Vad ska du göra om en mötande bil inte byter från helljus till halvljus?',
    options: ['Blinka med ditt helljus tillbaka', 'Titta mot höger vägkant och sänk hastigheten', 'Stanna mitt på vägen'],
    correctIndex: 1,
    explanation: 'Undvik att titta in i ljusen. Titta mot höger vägkant för att behålla orienteringen och sänk farten.',
  },
  {
    id: 'mrk-17',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Varför ser du sämre direkt efter att ha blivit bländad?',
    options: ['Ögonen är skadade', 'Pupillerna behöver tid att anpassa sig till mörkret igen', 'Strålkastarna slutar fungera'],
    correctIndex: 1,
    explanation: 'Efter bländning tar det 5-10 sekunder för pupillerna att vidga sig och anpassa sig till mörkret.',
  },
  {
    id: 'mrk-18',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Vid vilken hastighet hinner du stanna inom halvljusets räckvidd (ca 50-60 m)?',
    options: ['90 km/h', 'Cirka 60-70 km/h', '110 km/h'],
    correctIndex: 1,
    explanation: 'Med halvljus som lyser ca 50-60 m hinner du stanna vid ca 60-70 km/h. Att köra fortare innebär att du "kör blind".',
  },
  {
    id: 'mrk-19',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Varför är reflex viktig för fotgängare?',
    options: ['Den ser cool ut', 'En bilist ser en fotgängare med reflex på ca 125 m istället för 25 m utan', 'Den skyddar mot regn'],
    correctIndex: 1,
    explanation: 'Med reflex syns en fotgängare på ca 125 meters håll. Utan reflex bara 25 meter — ofta för sent att stanna.',
  },
  {
    id: 'mrk-20',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Vad ska du göra om du kör på en mörk landsväg utan vägbelysning?',
    options: ['Köra med halvljus hela tiden', 'Använda helljus och byta till halvljus vid mötande trafik', 'Köra med parkeringsljus'],
    correctIndex: 1,
    explanation: 'På mörka vägar utan belysning ska du använda helljus för bäst sikt. Byt till halvljus i god tid vid mötande.',
  },
  {
    id: 'mrk-21',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Vad innebär "night myopia" (nattblindhet)?',
    options: ['Att man ser bättre i mörker', 'Att ögats fokus försämras i mörker — allt ser suddigt ut', 'Att man inte kan köra nattetid'],
    correctIndex: 1,
    explanation: 'I mörker vidgas pupillen, vilket kan ge sämre djupskärpa. Föremål kan verka suddiga, särskilt för äldre förare.',
  },
  {
    id: 'mrk-22',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Vilken belysning ska en cykel ha baktill i mörker?',
    options: ['Ingen krävs', 'Rött ljus baktill', 'Vitt ljus baktill'],
    correctIndex: 1,
    explanation: 'I mörker ska en cykel ha rött bakljus och röd reflex baktill.',
  },
  {
    id: 'mrk-23',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Får du använda helljus i tätort?',
    options: ['Ja, alltid', 'Normalt inte — gatbelysning räcker och helljus bländar', 'Bara efter midnatt'],
    correctIndex: 1,
    explanation: 'I tätort finns vanligen gatubelysning. Helljus bländar andra och behövs normalt inte.',
  },
  {
    id: 'mrk-24',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Vad kan mörka kläder på en fotgängare i mörker betyda för din sikt?',
    options: ['Ingen skillnad', 'Du kan missa fotgängaren helt tills den är bara 20-25 m framför dig', 'Du ser dem på 100 m'],
    correctIndex: 1,
    explanation: 'Mörkt klädda fotgängare utan reflex syns ofta inte förrän på 20-25 meters håll — för sent vid 50+ km/h.',
  },
  {
    id: 'mrk-25',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Vad ska du göra om strålkastarna är dåligt inställda (lyser för högt)?',
    options: ['Inget', 'Justera dem — felriktade strålkastare bländar mötande', 'Köra långsammare'],
    correctIndex: 1,
    explanation: 'Felriktade strålkastare bländar mötande trafik och ger dig sämre sikt. Justera dem.',
  },
  {
    id: 'mrk-26',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Varför är det extra farligt att köra om i mörker?',
    options: ['Bromsdistansen ökar', 'Du har svårare att bedöma avstånd och hastighet på mötande trafik', 'Det tar längre tid'],
    correctIndex: 1,
    explanation: 'I mörker är det svårt att bedöma mötande fordons avstånd och hastighet baserat på enbart ljusen.',
  },
  {
    id: 'mrk-27',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Vad är "matrix LED"-strålkastare?',
    options: ['Vanliga LED', 'System med individuellt styrbara LED-segment som kan släcka delar av ljuskäglan för att inte blända mötande', 'Strålkastare med laserteknik'],
    correctIndex: 1,
    explanation: 'Matrix LED kan maskerah ut mötande fordon ur ljuskäglan och behålla helljus runt dem — bättre sikt utan att blända.',
  },
  {
    id: 'mrk-28',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Vad ska du tända i en tunnel, även dagtid?',
    options: ['Inget', 'Halvljus', 'Helljus'],
    correctIndex: 1,
    explanation: 'I tunnlar ska du alltid tända halvljus, även om tunneln har belysning.',
  },
  {
    id: 'mrk-29',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Hur påverkar regnväta vägar körning i mörker?',
    options: ['Ingen extra risk', 'Reflexer från gatubelysning och strålkastare kan blända och vägmarkeringar syns sämre', 'Du ser bättre'],
    correctIndex: 1,
    explanation: 'Våt väg reflekterar ljus och skapar bländning. Vägmarkeringar kan vara svåra att se i regn och mörker.',
  },
  {
    id: 'mrk-30',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Vad innebär det att du "övrekör ditt ljus" (overdriving your headlights)?',
    options: ['Att du kör med för starkt ljus', 'Att du kör så fort att du inte hinner stanna inom den sträcka ljuset når', 'Att du använder extra lampor'],
    correctIndex: 1,
    explanation: 'Att överköra ljuset innebär att din stoppsträcka är längre än ljusets räckvidd — du kör "blind" i mörkret bortom ljuset.',
  },
  {
    id: 'mrk-31',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Varför ska cykellampor vara laddade och fungerande?',
    options: ['Bara för att se vägen', 'För att synas i trafiken — utan ljus är du nästan osynlig i mörker', 'Det är inte viktigt'],
    correctIndex: 1,
    explanation: 'Utan belysning är en cyklist nästan osynlig för bilister. Fungerande lampor räddar liv.',
  },
  {
    id: 'mrk-32',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Vad bör du göra om en rådjursögon lyser i dina strålkastare?',
    options: ['Tuta högt', 'Sänk hastigheten och var beredd — djuret kan springa ut', 'Blinka med helljusen'],
    correctIndex: 1,
    explanation: 'Djur som bländas av ljus kan frysa eller springa ut. Sänk hastigheten och var beredd.',
  },
  {
    id: 'mrk-33',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Hur påverkas din förmåga att uppfatta färger i mörker?',
    options: ['Ingen skillnad', 'Förmågan att urskilja färger minskar kraftigt — allt ser gråaktigt ut', 'Färgerna blir klarare'],
    correctIndex: 1,
    explanation: 'I mörker dominerar stavarna i ögat (som ser svartvitt) över tapparna (som ser färger). Färguppfattningen minskar.',
  },
  {
    id: 'mrk-34',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Ska du ha halvljus på även vid gryning och skymning?',
    options: ['Nej, det räcker med naturligt ljus', 'Ja, du ska synas och se vägen', 'Bara om det är mulet'],
    correctIndex: 1,
    explanation: 'Gryning och skymning är farliga tider — ljuset förändras snabbt. Halvljus ökar din synlighet.',
  },
  {
    id: 'mrk-35',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Vad gäller för belysning på en släpvagn i mörker?',
    options: ['Ingen belysning krävs', 'Släpvagnen ska ha fungerande bak-, broms- och blinkerljus', 'Bara reflex krävs'],
    correctIndex: 1,
    explanation: 'Släpvagnar ska ha fullständig belysning — bakljus, bromsljus, blinkers och reflexer.',
  },
  {
    id: 'mrk-36',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Vad är "Pedestrian Detection" i moderna bilar?',
    options: ['Fotgängarräknare', 'System som upptäcker fotgängare i mörker med IR-kamera och kan bromsa automatiskt', 'Varning för fotgängare'],
    correctIndex: 1,
    explanation: 'Pedestrian Detection använder infraröd teknik eller kameror för att upptäcka fotgängare, även i mörker, och kan initiera nödbromsning.',
  },
  {
    id: 'mrk-37',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Varför är parkerade bilar utan belysning farliga i mörker?',
    options: ['De blockerar trafiken', 'De kan vara svåra att upptäcka och orsaka kollisioner', 'De luktar avgaser'],
    correctIndex: 1,
    explanation: 'Mörka, oupplysta parkerade bilar kan vara svåra att se, särskilt på vägar utan gatubelysning.',
  },
  {
    id: 'mrk-38',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Hur bör du anpassa ditt blickmönster i mörker?',
    options: ['Titta bara rakt fram', 'Flytta blicken oftare mellan nära och långt fram — utnyttja ljusreflexer', 'Titta bara i spegeln'],
    correctIndex: 1,
    explanation: 'I mörker behöver du aktivt scanna med blicken. Utnyttja reflexer från vägmarkeringar och andra bilars ljus.',
  },
  {
    id: 'mrk-39',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Vad är "head-up display" (HUD) särskilt användbar för i mörker?',
    options: ['Underhållning', 'Du behöver inte titta ner på instrumentpanelen och tappa mörkeranpassning', 'Navigation'],
    correctIndex: 1,
    explanation: 'Att titta ner på ljusa instrument förstör mörkeranpassningen. HUD projicerar info på vindrutan.',
  },
  {
    id: 'mrk-40',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Vad ska du göra om dimljuset framtill inte räcker i tjock dimma?',
    options: ['Slå på helljus', 'Sänk hastigheten ytterligare — du ska kunna stanna inom siktsträckan', 'Kör fortare för att komma igenom snabbare'],
    correctIndex: 1,
    explanation: 'Sänk hastigheten. Helljus reflekteras i dimman och gör det värre. Halvljus + dimljus och anpassad hastighet.',
  },
  {
    id: 'mrk-41',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Vad innebär "cornering lights" (kurvljus)?',
    options: ['Extra bakljus', 'Lampor som tänds vid sväng för att lysa upp sidoområdet', 'Parkeringsljus'],
    correctIndex: 1,
    explanation: 'Kurvljus tänds automatiskt vid sväng och låga hastigheter för att belysa sidan du svänger mot.',
  },
  {
    id: 'mrk-42',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Hur snabbt anpassar sig ögat fullt till mörker efter bländning?',
    options: ['1 sekund', '5-10 sekunder', '15-30 minuter för full anpassning'],
    correctIndex: 2,
    explanation: 'Full mörkeranpassning tar 15-30 minuter. En bländning kan dock temporärt förstöra anpassningen i 5-10 sekunder.',
  },
  {
    id: 'mrk-43',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Varför ska du rengöra strålkastarna vintertid?',
    options: ['Bara för utseendet', 'Smuts och salt kan minska ljusstyrkan med över 50%', 'Det spelar ingen roll'],
    correctIndex: 1,
    explanation: 'Vinterns smuts och salt kan halvera ljusstyrkan. Rengör strålkastarna regelbundet.',
  },
  {
    id: 'mrk-44',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Vad bör du göra om du kommer ut från en upplyst tunnel till mörk väg?',
    options: ['Gasa på', 'Sänk farten — ögonen behöver tid att anpassa sig', 'Slå på helljus direkt'],
    correctIndex: 1,
    explanation: 'Övergången från ljus till mörker tar tid för ögonen. Sänk hastigheten tills du ser ordentligt.',
  },
  {
    id: 'mrk-45',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Hur påverkar ålder (50+ år) mörkerseende?',
    options: ['Ingen skillnad', 'Mörkerseendet försämras — en 60-åring behöver 2-3 gånger mer ljus', 'Det blir bättre'],
    correctIndex: 1,
    explanation: 'Med åldern minskar pupillens storlek och ögats ljuskänslighet. Äldre behöver mer ljus och mer tid för anpassning.',
  },
  {
    id: 'mrk-46',
    category: 'morkerkörning',
    difficulty: 'easy',
    question: 'Vad ska du göra om du tappar sikten helt i mörker (t.ex. alla lampor slocknar)?',
    options: ['Bromsa tvärt', 'Släpp gasen, bromsa försiktigt och försök stanna säkert vid sidan', 'Kör vidare'],
    correctIndex: 1,
    explanation: 'Utan ljus: släpp gasen, bromsa försiktigt, slå på varningsblinkers och styr mot vägkanten.',
  },
  {
    id: 'mrk-47',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Hur kan du se om mötande bilar kommer i mörker innan du ser deras ljus?',
    options: ['Du kan inte', 'Ljusskenet kan synas ovanför kullar och runt kurvor', 'Bara med specialutrustning'],
    correctIndex: 1,
    explanation: 'Före en kulle eller kurva kan du ofta se ljusskenet från en bil innan själva bilen syns. Var beredd.',
  },
  {
    id: 'mrk-48',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Vad innebär "glare recovery time"?',
    options: ['Tid att byta lampa', 'Tiden det tar för ögonen att återhämta sig efter bländning', 'Bilens återhämtningstid'],
    correctIndex: 1,
    explanation: 'Glare recovery time varierar från person till person. Äldre behöver ofta längre tid att återhämta sig efter bländning.',
  },
  {
    id: 'mrk-49',
    category: 'morkerkörning',
    difficulty: 'medium',
    question: 'Varför är det viktigt att inner- och ytterbackspeglarna har anti-bländfunktion?',
    options: ['För utseendets skull', 'De minskar bländning från bakomvarande bilars ljus', 'De ökar sikten framåt'],
    correctIndex: 1,
    explanation: 'Anti-bländspeglar (automatiskt dimmande) minskar bländning från bakomvarande fordon nattetid.',
  },
  {
    id: 'mrk-50',
    category: 'morkerkörning',
    difficulty: 'hard',
    question: 'Du kör i mörker på en 70-väg med halvljus. Ungefär hur långt innan ett hinder bör du kunna upptäcka det?',
    options: ['20 meter', 'Minst 50-60 meter (halvljusets räckvidd)', '200 meter'],
    correctIndex: 1,
    explanation: 'Halvljuset lyser ca 50-60 meter. Vid 70 km/h (≈19 m/s) behöver du ca 50 m stoppsträcka — det är precis på gränsen.',
  },
];
