import { Question } from './types';

export const motorvagQuestions: Question[] = [
  {
    id: 'mot-1',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vad ska du göra på accelerationsfältet vid påfart till motorväg?',
    options: [
      'Stanna och vänta på lucka',
      'Accelerera till motorvägens hastighet och anpassa dig till trafikflödet',
      'Köra in långsamt och sedan öka hastigheten',
    ],
    correctIndex: 1,
    explanation:
      'På accelerationsfältet ska du öka hastigheten för att nå samma fart som övrig trafik och smidigt flyta in i trafikströmmen.',
  },
  {
    id: 'mot-2',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vad ska du göra på retardationsfältet vid avfart från motorväg?',
    options: [
      'Bromsa redan på motorvägen innan du svänger av',
      'Byta till retardationsfältet och sedan sänka hastigheten',
      'Stanna och blinka innan du kör av',
    ],
    correctIndex: 1,
    explanation:
      'Byt till retardationsfältet i god tid och sänk hastigheten där – inte i genomfartsfilen. Signalera i tid med blinkers.',
  },
  {
    id: 'mot-3',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vilka fordon får INTE köra på motorväg?',
    options: [
      'Lastbilar över 3,5 ton',
      'Mopeder, cyklar, traktorer och fordon som inte kan hålla minst 40 km/h',
      'Husbilar och husvagnar',
    ],
    correctIndex: 1,
    explanation:
      'Fordon som inte kan hålla minst 40 km/h får inte köra på motorväg. Det gäller mopeder, cyklar, traktorer och gående.',
  },
  {
    id: 'mot-4',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vad är högsta tillåtna hastighet på motorväg i Sverige?',
    options: [
      '100 km/h',
      '110 km/h (120 km/h på vissa sträckor)',
      '130 km/h',
    ],
    correctIndex: 1,
    explanation:
      'Normalt är högsta hastigheten på motorväg 110 km/h. På vissa sträckor tillåts 120 km/h, men det anges med skyltar.',
  },
  {
    id: 'mot-5',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Får du stanna på motorvägens vägren?',
    options: [
      'Ja, om du vill ringa ett samtal',
      'Nej, bara vid nödstopp eller fordonshaveri',
      'Ja, om du stannar kortare än 5 minuter',
    ],
    correctIndex: 1,
    explanation:
      'Det är förbjudet att stanna på motorvägens vägren utom vid nödstopp eller haveri. Använd istället nästa avfart eller rastplats.',
  },
  {
    id: 'mot-6',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad bör du göra vid nödstopp på motorväg?',
    options: [
      'Stanna i vänstra körfältet och vänta på hjälp',
      'Stanna på vägrenen, slå på varningsblinkers, sätt ut varningstriangel och gå bakom räcket',
      'Ring polisen och vänta i bilen',
    ],
    correctIndex: 1,
    explanation:
      'Vid nödstopp: styr ut på vägrenen, aktivera varningsblinkers, sätt ut varningstriangel minst 200 m bakom bilen och gå bakom vägräcket.',
  },
  {
    id: 'mot-7',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vilken sida ska du köra om på motorväg?',
    options: [
      'Höger sida',
      'Vänster sida',
      'Vilken sida som helst',
    ],
    correctIndex: 1,
    explanation:
      'Omkörning ska alltid ske på vänster sida på motorväg. Omkörning på höger sida (smitning) är förbjuden.',
  },
  {
    id: 'mot-8',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vilken fil ska du normalt köra i på en motorväg med två körfält i din riktning?',
    options: [
      'Vänster fil',
      'Höger fil',
      'Valfri fil',
    ],
    correctIndex: 1,
    explanation:
      'Du ska normalt köra i höger fil. Vänster fil används för omkörning. När omkörningen är klar ska du återgå till höger fil.',
  },
  {
    id: 'mot-9',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Hur långt avstånd bör du hålla till framförvarande vid 110 km/h på motorväg?',
    options: [
      'Cirka 30 meter',
      'Minst 3 sekunders avstånd, ungefär 90 meter',
      'Cirka 50 meter',
    ],
    correctIndex: 1,
    explanation:
      'Vid 110 km/h färdas du ca 30 meter per sekund. Med 3-sekundersregeln blir avståndet ungefär 90 meter.',
  },
  {
    id: 'mot-10',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad skiljer en motortrafikled från en motorväg?',
    options: [
      'Det finns ingen skillnad',
      'Motortrafikled kan ha korsningar i plan och saknar ibland mitträcke',
      'Motortrafikled har alltid högre hastighetsgräns',
    ],
    correctIndex: 1,
    explanation:
      'En motortrafikled kan ha plankorsningar, sakna mitträcke och ha anslutningar utan accelerationsfält. Den har ofta lägre hastighetsgräns.',
  },
  {
    id: 'mot-11',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vad ska du göra om du missar din avfart på motorvägen?',
    options: [
      'Stanna och backa tillbaka',
      'Fortsätta till nästa avfart och köra tillbaka',
      'Köra i nödstoppsfilen tillbaka',
    ],
    correctIndex: 1,
    explanation:
      'Det är strängt förbjudet att backa eller vända på motorväg. Kör vidare till nästa avfart och ta dig tillbaka via det vanliga vägnätet.',
  },
  {
    id: 'mot-12',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Får du göra U-sväng på motorväg?',
    options: [
      'Ja, om det inte kommer trafik',
      'Nej, det är strängt förbjudet',
      'Ja, vid mittremsor och öppningar',
    ],
    correctIndex: 1,
    explanation:
      'U-sväng och vändning är strängt förbjudet på motorväg. Öppningarna i mitträcket är enbart avsedda för räddningsfordon.',
  },
  {
    id: 'mot-13',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad innebär "dragsugseffekt" vid omkörning av lastbilar på motorväg?',
    options: [
      'Att din bil accelererar av sig själv',
      'Att luft- och vinddrag från lastbilen kan påverka styrningen på ditt fordon',
      'Att lastbilen suger åt sig din bil',
    ],
    correctIndex: 1,
    explanation:
      'Stora fordon skapar turbulens. Vid omkörning kan du först dras mot lastbilen och sedan tryckas utåt, vilket kräver korrigerande styrrörelser.',
  },
  {
    id: 'mot-14',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vad bör du göra innan du byter fil på motorväg?',
    options: [
      'Bara titta i backspegeln',
      'Kontrollera backspegel, ytterbackspegel, döda vinkeln och blinka i god tid',
      'Blinka och byta direkt',
    ],
    correctIndex: 1,
    explanation:
      'Kontrollera alla speglar, vrid på huvudet för att se döda vinkeln, blinka i god tid och byt fil mjukt när det är fritt.',
  },
  {
    id: 'mot-15',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad gäller om ett fordon på accelerationsfältet inte hinner komma upp i rätt hastighet?',
    options: [
      'Fordonet ska stanna och vänta',
      'Fordonet ska använda vägrenen och öka hastigheten där om det är säkert',
      'Fordonet ska köra in i trafiken ändå, övriga ska anpassa sig',
    ],
    correctIndex: 1,
    explanation:
      'Om du inte hinner komma upp i rätt fart kan du i nödfall använda vägrenen för att fortsätta accelerera, men undvik att stanna helt.',
  },
  {
    id: 'mot-16',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vilken minsta hastighet krävs generellt för att få köra på motorväg?',
    options: ['30 km/h', '40 km/h', '60 km/h'],
    correctIndex: 1,
    explanation: 'Fordon som inte kan köra minst 40 km/h får inte använda motorväg.',
  },
  {
    id: 'mot-17',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Får du cykla på motorväg?',
    options: ['Ja, om det finns vägren', 'Nej, cyklar är förbjudna på motorväg', 'Ja, i nödfall'],
    correctIndex: 1,
    explanation: 'Cyklar, mopeder klass II, gående och andra fordon som inte kan hålla 40 km/h är förbjudna på motorväg.',
  },
  {
    id: 'mot-18',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vad ska du göra om du ser att det bildas kö framför dig på motorvägen?',
    options: ['Byta fil snabbt', 'Slå på varningsblinkers för att varna bakomvarande', 'Tuta'],
    correctIndex: 1,
    explanation: 'Slå på varningsblinkers för att varna bakomvarande om plötsligt stopp. Detta minskar risken för påkörning.',
  },
  {
    id: 'mot-19',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vad innebär "zipper merge" (blixtlåsprincipen) vid filsammanfogning?',
    options: ['Att alla byter fil tidigt', 'Att fordon turas om — varannan bil från varje fil', 'Att den snabbaste kör först'],
    correctIndex: 1,
    explanation: 'Blixtlåsprincipen innebär att fordon turas om att köra in, varannan bil. Det ger bäst flöde.',
  },
  {
    id: 'mot-20',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad gäller om du hamnar på motorvägens vägren efter ett motorstopp nattetid?',
    options: ['Stanna i bilen', 'Ta dig ut ur bilen på rätt sida, bort från trafiken, tänd varningsblinkers och placera varningstriangel', 'Ring och vänta i bilen'],
    correctIndex: 1,
    explanation: 'Lämna bilen på sidan bort från trafiken. Slå på varningsblinkers, ställ ut varningstriangel 200 m bakom och ring hjälp.',
  },
  {
    id: 'mot-21',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vad innebär de gröna avståndsprickarna på motorvägen?',
    options: ['Hastighetsmarkeringar', 'Avståndsmätning — håll minst 3 prickar till framförvarande', 'Filmarkeringar'],
    correctIndex: 1,
    explanation: 'Avståndsprickarna hjälper dig att kontrollera avståndet till bilen framför. Håll minst 3 prickar vid 110 km/h.',
  },
  {
    id: 'mot-22',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vilken fil ska du använda för att köra om på motorväg?',
    options: ['Höger fil', 'Vänster fil (omkörningsfilen)', 'Vilken fil som helst'],
    correctIndex: 1,
    explanation: 'Omkörning ska ske till vänster på motorväg. Omkörning till höger är normalt förbjuden.',
  },
  {
    id: 'mot-23',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Får du köra om till höger på motorväg?',
    options: ['Aldrig', 'Ja, om trafiken i alla filer går i samma låga hastighet', 'Bara lastbilar'],
    correctIndex: 1,
    explanation: 'I tät, långsam trafik får du passera fordon på höger sida om alla filer rullar i ungefär samma hastighet.',
  },
  {
    id: 'mot-24',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vad ska du göra innan du byter fil på motorväg?',
    options: ['Bara blinka', 'Spegla, blinka, kontrollera dödvinkel och byt fil', 'Tuta'],
    correctIndex: 1,
    explanation: 'Kontrollera speglar, blinka i god tid, kontrollera dödvinkeln och byt fil först när det är säkert.',
  },
  {
    id: 'mot-25',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Hur långt före avfarten bör du lägga dig i rätt fil?',
    options: ['50 meter', 'Minst 500 meter', 'Precis innan avfarten'],
    correctIndex: 1,
    explanation: 'Lägg dig i rätt fil i god tid — minst 500 meter före avfarten. Sena filbyten är farliga.',
  },
  {
    id: 'mot-26',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad gäller vid dimma på motorväg?',
    options: ['Kör i samma hastighet med dimljus', 'Sänk hastigheten kraftigt, öka avstånd, använd halvljus och dimljus', 'Stanna på vägrenen'],
    correctIndex: 1,
    explanation: 'Dimma på motorväg är extremt farligt. Sänk hastigheten, öka avståndet och använd halvljus (inte helljus).',
  },
  {
    id: 'mot-27',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Får du stanna för att rasta hunden på motorvägens vägren?',
    options: ['Ja, kortare stopp är okej', 'Nej, du får bara stanna vid nödsituation', 'Ja, om du sätter på varningsblinkers'],
    correctIndex: 1,
    explanation: 'Motorvägens vägren får bara användas vid nödstopp. Rasta hunden vid rastplats eller avfart.',
  },
  {
    id: 'mot-28',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vad innebär en "acceleration lane" (accelerationsfält)?',
    options: ['Körfält för snabba bilar', 'Fält vid påfart där du ska öka till motorvägshastighet', 'Fält för att stanna'],
    correctIndex: 1,
    explanation: 'Accelerationsfältet vid påfart ger dig utrymme att öka hastigheten till motorvägens flöde innan du kör in.',
  },
  {
    id: 'mot-29',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad händer om du kör för sakta i vänsterfilen på motorväg?',
    options: ['Inget', 'Du hindrar trafiken och kan orsaka farliga situationer med filbyten', 'Du sparar bränsle'],
    correctIndex: 1,
    explanation: 'Vänsterfilen är till för omkörning. Att ligga kvar långsamt tvingar andra till farliga manövrer.',
  },
  {
    id: 'mot-30',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Får du backa på en motorväg?',
    options: ['Ja, om du missar avfarten', 'Nej, det är förbjudet', 'Bara på vägrenen'],
    correctIndex: 1,
    explanation: 'Backning är strängt förbjuden på motorväg. Missar du avfarten, kör till nästa och vänd.',
  },
  {
    id: 'mot-31',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Varför ska du inte plötsligt sänka hastigheten på motorväg?',
    options: ['Det sliter på bromsarna', 'Bakomvarande kan inte hinna reagera — risk för masskrock', 'Det påverkar inte säkerheten'],
    correctIndex: 1,
    explanation: 'Plötsliga hastighetssänkningar på motorväg kan orsaka kedjekollisioner. Bromsa gradvis och använd varningsblinkers.',
  },
  {
    id: 'mot-32',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad är "räddningskorridor" på motorväg vid köbildning?',
    options: ['En fil reserverad för ambulanser', 'Fordon i vänster fil kör åt vänster och höger fil åt höger för att skapa fri väg för utryckningsfordon', 'En nödavfart'],
    correctIndex: 1,
    explanation: 'Vid kö på motorväg ska du skapa en räddningskorridor: vänster fil drar åt vänster, höger åt höger.',
  },
  {
    id: 'mot-33',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vad ska du göra om du ser ett djur på motorvägen?',
    options: ['Tuta och kör förbi', 'Sänk hastigheten, var försiktig och ring 112 vid behov', 'Stanna och skrämma bort det'],
    correctIndex: 1,
    explanation: 'Djur på motorväg är farligt. Sänk farten, undvik kraftig undanmanöver och ring 112.',
  },
  {
    id: 'mot-34',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Hur bör du bete dig vid en olycka på motorvägen?',
    options: ['Stanna mitt i vägen', 'Stanna säkert, varna trafiken, hjälp skadade och ring 112', 'Köra förbi'],
    correctIndex: 1,
    explanation: 'Stanna säkert på vägrenen, slå på varningsblinkers, placera varningstriangel, hjälp drabbade och ring 112.',
  },
  {
    id: 'mot-35',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad gäller vid körning i en motorvägstunnel?',
    options: ['Inget speciellt', 'Tänd halvljus, notera nödutgångar, stäng fönster vid brand', 'Kör i maxhastighet'],
    correctIndex: 1,
    explanation: 'I tunnlar: tänd halvljus, notera var nödutgångar finns, öka avstånd och vid brand — stanna, stäng av motorn, lämna bilen.',
  },
  {
    id: 'mot-36',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Får du gå längs motorvägen?',
    options: ['Ja, på vägrenen', 'Nej, gående är förbjudna', 'Bara i nödsituation'],
    correctIndex: 2,
    explanation: 'Gående är normalt förbjudna på motorväg, men vid nödsituation (motorstopp) måste du ta dig till säkerhet.',
  },
  {
    id: 'mot-37',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vad ska du tänka på vid stark sidvind på motorväg?',
    options: ['Inget', 'Håll fast ratten, var beredd vid broöppningar och vid passage av stora fordon', 'Öka hastigheten'],
    correctIndex: 1,
    explanation: 'Sidvind kan plötsligt påverka bilens kurs, särskilt vid broar, öppna landskap och vid passage av lastbilar.',
  },
  {
    id: 'mot-38',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad innebär "platooning" på motorväg?',
    options: ['Att köra i grupp på rad', 'Fordon som kör i kolonn med kort avstånd via teknik (radar/V2V)', 'Att köra parallellt'],
    correctIndex: 1,
    explanation: 'Platooning innebär att fordon kör i tät kolonn med hjälp av teknik, vilket minskar luftmotstånd och bränsleförbrukning.',
  },
  {
    id: 'mot-39',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vilken skylt anger att motorvägen upphör?',
    options: ['Grön skylt med rött kryss', 'Samma motorvägssymbol med rött diagonalt streck', 'Röd stoppskylt'],
    correctIndex: 1,
    explanation: 'Märket "Slut på motorväg" (E2) visar motorvägssymbolen med ett rött diagonalt streck genom.',
  },
  {
    id: 'mot-40',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vad bör du göra om du kör i vänsterfilen och en snabbare bil närmar sig bakifrån?',
    options: ['Öka farten', 'Flytta dig till höger fil och låt den passera', 'Ignorera den'],
    correctIndex: 1,
    explanation: 'Vänsterfilen är till för omkörning. Byt till höger fil när du är klar med din omkörning.',
  },
  {
    id: 'mot-41',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Du kör på en trefilig motorväg. Vilken fil ska du normalt befinna dig i?',
    options: ['Mittfilen', 'Höger fil om du inte kör om', 'Vänster fil'],
    correctIndex: 1,
    explanation: 'På flerfilig motorväg ska du normalt köra i höger fil. Mittfilen och vänster fil är för omkörning.',
  },
  {
    id: 'mot-42',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vad ska du göra efter att du kört om på motorväg?',
    options: ['Stanna i vänster fil', 'Byta tillbaka till höger fil när det är säkert', 'Det spelar ingen roll'],
    correctIndex: 1,
    explanation: 'Efter omkörning ska du snarast byta tillbaka till höger fil. Att ligga kvar i vänster fil hindrar trafiken.',
  },
  {
    id: 'mot-43',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Hur bör du anpassa hastigheten vid avfart från motorväg?',
    options: ['Bromsa på motorvägen', 'Vänta med att sänka hastigheten tills du är på retardationsfältet', 'Kör i samma hastighet hela vägen'],
    correctIndex: 1,
    explanation: 'Sänk inte hastigheten på motorvägen — vänta tills du är på retardationsfältet och bromsa där.',
  },
  {
    id: 'mot-44',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Varför uppstår "fantomköer" (köer utan synbar orsak) på motorväg?',
    options: ['Vägen är för smal', 'Små inbromsningar förstärks bakåt genom kedjereaktion', 'Förarna kör för sakta'],
    correctIndex: 1,
    explanation: 'En liten inbromsning förstärks bakåt genom kedjereaktion — varje bil bromsar lite mer. Resultatet är kö utan synlig orsak.',
  },
  {
    id: 'mot-45',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vad gäller om det finns en hastighetsbegränsning på 100 km/h på motorvägen?',
    options: ['110 gäller ändå', '100 km/h gäller — skyltat begränsar den generella gränsen', 'Bara för lastbilar'],
    correctIndex: 1,
    explanation: 'Skyltat hastighetsgräns gäller alltid oavsett vägtyp. 100 km/h betyder max 100 km/h.',
  },
  {
    id: 'mot-46',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Får mopeder klass I köra på motorväg?',
    options: ['Ja', 'Nej, de kan inte hålla minst 40 km/h konstant', 'Bara på vägrenen'],
    correctIndex: 1,
    explanation: 'Mopeder klass I (max 45 km/h) uppfyller normalt inte kravet på att kunna hålla 40 km/h och är inte tillåtna.',
  },
  {
    id: 'mot-47',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Du kör på motorvägen och ser att trafiken framför saktar in. Vad gör du?',
    options: ['Bromsar direkt', 'Saktar ner gradvis och sätter på varningsblinkers för att varna bakomvarande', 'Byter fil direkt'],
    correctIndex: 1,
    explanation: 'Gradvis inbromsning med varningsblinkers varnar bakomvarande och minskar risken för krockar bakifrån.',
  },
  {
    id: 'mot-48',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Varför är det farligt att köra i dödvinkeln hos en lastbil på motorväg?',
    options: ['Lastbilen kan bromsa plötsligt', 'Lastbilsföraren ser dig inte och kan byta fil rakt in i dig', 'Avgaserna är skadliga'],
    correctIndex: 1,
    explanation: 'Lastbilar har stora dödvinklar. Om du ligger i en, ser föraren dig inte — passera kvickt eller håll avstånd.',
  },
  {
    id: 'mot-49',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vad finns normalt vid rastplatser längs motorvägen?',
    options: ['Parkeringsplats, toalett och ibland bensinstation', 'Bara en bänk', 'Poliskontroller'],
    correctIndex: 0,
    explanation: 'Rastplatser erbjuder normalt parkering och toalett. Större rastplatser har även bensin och mat.',
  },
  {
    id: 'mot-50',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad gäller vid en olycka på en motorvägstunnel?',
    options: ['Kör ut ur tunneln', 'Stanna, stäng av motorn, lämna bilen olåst med nyckel i och gå mot nödutgång', 'Backa ut'],
    correctIndex: 1,
    explanation: 'I en tunnel vid olycka/brand: stanna, stäng av motorn, lämna bilen med nyckeln i, gå mot närmaste nödutgång. Kör aldrig genom brand.',
  },
  {
    id: 'mot-51',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Hur bör du agera om du kör in i kraftigt regn på motorväg?',
    options: ['Stanna direkt', 'Sänk hastigheten, öka avstånd, undvik häftiga rattröresler', 'Kör i samma hastighet'],
    correctIndex: 1,
    explanation: 'Vid kraftigt regn på motorväg: sänk hastigheten, öka avståndet och undvik plötsliga manövrer pga halkrisken.',
  },
  {
    id: 'mot-52',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vad markerar de nedräknande strecken (3-2-1) innan en avfart?',
    options: ['Antal filer', 'Avstånd till avfarten: 300, 200 och 100 meter', 'Hastighetsgränser'],
    correctIndex: 1,
    explanation: 'Nedräkningsmärkena visar avståndet till avfarten. 3 streck = 300 m, 2 = 200 m, 1 = 100 m.',
  },
  {
    id: 'mot-53',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Vad gäller om du behöver byta däck på motorvägen?',
    options: ['Byt på vägrenen', 'Försök ta dig till nästa avfart om möjligt — om inte, stanna så långt från körfältet som möjligt', 'Ring och vänta'],
    correctIndex: 1,
    explanation: 'Det är farligt att byta däck på motorvägen. Försök ta dig till en säkrare plats. Om det inte går — stanna så långt från trafiken som möjligt.',
  },
  {
    id: 'mot-54',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Vad innebär nödtelefoner längs motorvägen?',
    options: ['Telefoner för att ringa hem', 'SOS-telefoner för att kontakta räddningstjänst vid nödsituation', 'Trafikinformationstelefoner'],
    correctIndex: 1,
    explanation: 'Nödtelefoner finns utplacerade längs motorvägen för att du ska kunna kontakta räddningstjänst om din mobil inte fungerar.',
  },
  {
    id: 'mot-55',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vilken skylt visar att det finns en rastplats framöver?',
    options: ['Grön skylt med bord och bänk', 'Blå skylt med P', 'Brun turistskylt'],
    correctIndex: 0,
    explanation: 'Rastplatser markeras med en grön skylt med symbol för bord och bänk, eller med text "Rastplats".',
  },
  {
    id: 'mot-56',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Du kör på motorväg och ser blåljus bakom dig i backspegeln. Trafiken är tät. Vad gör du?',
    options: ['Ökar farten', 'Försöker flytta dig åt höger och sakta ner för att skapa plats', 'Stannar direkt'],
    correctIndex: 1,
    explanation: 'Flytta dig åt höger och sakta ner för att skapa utrymme. Om trafiken är helt stilla, skapa räddningskorridor.',
  },
  {
    id: 'mot-57',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Varför ska du undvika att köra med farthållare vid våt vägbana på motorväg?',
    options: ['Det ökar bränsleförbrukningen', 'Farthållaren kan ge gas vid vattenplaning och göra det farligare', 'Det är förbjudet'],
    correctIndex: 1,
    explanation: 'Vid vattenplaning kan farthållaren accelerera okontrollerat. Stäng av den vid våt eller hal väg.',
  },
  {
    id: 'mot-58',
    category: 'motorvag',
    difficulty: 'easy',
    question: 'Vad är retardationsfältet?',
    options: ['Fältet där du ökar hastigheten', 'Fältet vid avfart där du sänker hastigheten', 'Nödfält'],
    correctIndex: 1,
    explanation: 'Retardationsfältet vid avfarten ger dig utrymme att sänka hastigheten utan att påverka motorvägstrafiken.',
  },
  {
    id: 'mot-59',
    category: 'motorvag',
    difficulty: 'hard',
    question: 'Varför uppstår "accordion-effekten" i motorvägstrafik?',
    options: ['Vägen är för smal', 'Små hastighetsvariationer ackumuleras bakåt och skapar vågrörelser i trafikflödet', 'Förarna kör oförsiktigt'],
    correctIndex: 1,
    explanation: 'Små hastighetsskillnader förstärks bakåt genom trafiken. Jämn hastighet och lagom avstånd minskar effekten.',
  },
  {
    id: 'mot-60',
    category: 'motorvag',
    difficulty: 'medium',
    question: 'Hur bör du agera om ett fordon kommer emot dig i fel riktning på motorväg?',
    options: ['Blinka med helljusen', 'Flytta dig till höger fil, sänk hastigheten och var beredd att köra av', 'Försök blockera fordonet'],
    correctIndex: 1,
    explanation: 'Spökkörare är extremt farliga. Kör så långt till höger som möjligt, sänk farten och ring 112 när du kan.',
  },
];
