import { Question } from './types';

export const parkeringQuestions: Question[] = [
  {
    id: 'par-1',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Hur nära en korsning får du parkera?',
    options: ['5 meter', '10 meter', '15 meter'],
    correctIndex: 1,
    explanation: 'Du får inte parkera närmare en korsning än 10 meter från korsande körbanas närmaste ytterkant.',
  },
  {
    id: 'par-2',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Hur nära ett övergångsställe får du parkera?',
    options: ['5 meter', '10 meter', '15 meter'],
    correctIndex: 1,
    explanation: 'Du får inte parkera närmare ett övergångsställe eller en cykelpassage än 10 meter före och 10 meter efter.',
  },
  {
    id: 'par-3',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad innebär datumparkering?',
    options: [
      'Att man bara får parkera på helger',
      'Att man parkerar på den sida av gatan som har jämna husnummer på jämna datum och udda på udda datum',
      'Att parkeringstiden begränsas till ett visst datum',
    ],
    correctIndex: 1,
    explanation: 'Datumparkering innebär att du parkerar på sidan med jämna husnummer på jämna datum och sidan med udda husnummer på udda datum. Byte sker mellan kl 00–06.',
  },
  {
    id: 'par-4',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad innebär 24-timmarsregeln för parkering?',
    options: [
      'Du måste flytta bilen var 24:e timme på gator med parkeringsförbud',
      'Du får parkera i högst 24 timmar i följd på samma plats på allmän väg om inget annat anges',
      'Parkeringsböter fördubblas efter 24 timmar',
    ],
    correctIndex: 1,
    explanation: 'På allmän väg gäller att du inte får parkera mer än 24 timmar i följd på vardagar, om inget annat anges med skylt.',
  },
  {
    id: 'par-5',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Vad betyder vägmärket "Förbud mot att parkera" (P med snedstreck)?',
    options: [
      'Du får inte stanna alls',
      'Du får stanna för av- och påstigning men inte parkera',
      'Du får parkera i högst 5 minuter',
    ],
    correctIndex: 1,
    explanation: 'Förbud mot att parkera innebär att du inte får parkera, men du får stanna kortvarigt för av- och påstigning eller i- och urlastning.',
  },
  {
    id: 'par-6',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad gäller vid "Förbud mot att stanna och parkera"?',
    options: [
      'Du får stanna för att släppa av passagerare',
      'Du får varken stanna eller parkera fordonet',
      'Du får stanna i högst 1 minut',
    ],
    correctIndex: 1,
    explanation: 'Vid förbud mot att stanna och parkera får du varken stanna eller parkera. Undantag gäller vid trafikljus, vid kö eller för att undvika fara.',
  },
  {
    id: 'par-7',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Hur nära en busshållplats får du parkera?',
    options: [
      '10 meter före och efter',
      '20 meter före och 5 meter efter',
      '20 meter',
    ],
    correctIndex: 2,
    explanation: 'Du får inte parkera inom 20 meter från en busshållplatsskylts plats vid hållplats med markering. Detta för att bussar ska kunna stanna och passagerare ska ha fri sikt.',
  },
  {
    id: 'par-8',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad gäller för parkering på huvudled?',
    options: [
      'Du får parkera om det finns en ficka',
      'Parkering är förbjuden på huvudled',
      'Du får parkera om du har varningstriangel',
    ],
    correctIndex: 1,
    explanation: 'Det råder parkeringsförbud på huvudled. Du får dock stanna kortvarigt vid nödsituation. Parkera istället på anvisade parkeringsplatser.',
  },
  {
    id: 'par-9',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Var ska du parkera om det finns en markerad P-ruta?',
    options: [
      'Du kan parkera bredvid rutan om den är full',
      'Inom den markerade rutan enligt anvisning',
      'Var som helst inom 10 meter från rutan',
    ],
    correctIndex: 1,
    explanation: 'Du ska parkera helt inom den markerade P-rutan. Parkering utanför rutorna kan ge parkeringsanmärkning.',
  },
  {
    id: 'par-10',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad gäller för parkering på plats reserverad för rörelsehindrad (handikapplats)?',
    options: [
      'Alla får parkera där om platsen är ledig',
      'Bara den som har parkeringstillstånd för rörelsehindrad får parkera där',
      'Man får parkera där kortvarigt utan tillstånd',
    ],
    correctIndex: 1,
    explanation: 'Platser reserverade för rörelsehindrade får bara användas av den som har giltigt parkeringstillstånd för rörelsehindrad utfärdat av kommunen.',
  },
  {
    id: 'par-11',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Du parkerar på en gata utan skyltar i ett bostadsområde. Hur länge får du stå?',
    options: [
      'Så länge du vill',
      'Högst 24 timmar i följd på vardagar',
      'Högst 7 dagar',
    ],
    correctIndex: 1,
    explanation: 'Grundregeln på allmän väg är att du inte får parkera mer än 24 timmar i följd på vardagar. På helger/helgdagar gäller 24-timmarsregeln från nästa vardag.',
  },
  {
    id: 'par-12',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Får du parkera på en cykelbana?',
    options: [
      'Ja, om det inte finns cykeltrafikskyltar',
      'Ja, om du stannar i högst 5 minuter',
      'Nej, det är förbjudet att parkera på cykelbana',
    ],
    correctIndex: 2,
    explanation: 'Det är förbjudet att parkera och stanna på cykelbanor. Det hindrar cyklister och skapar trafikfara.',
  },
  {
    id: 'par-13',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad kan bli konsekvensen om du parkerar fel upprepade gånger?',
    options: [
      'Bilen kan bli flyttad (borttapt) på din bekostnad',
      'Du förlorar körkortet',
      'Du får bara böter',
    ],
    correctIndex: 0,
    explanation: 'Vid upprepad felparkering eller om fordonet står till hinder kan det bli föremål för flygning (bortforsling) på ägarens bekostnad, utöver parkeringsanmärkningar.',
  },
  {
    id: 'par-14',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Hur ska du parkera i en uppförsbacke utan kantsten?',
    options: [
      'Med hjulen rakt fram',
      'Med framhjulen vridna åt höger (mot vägkanten)',
      'Med framhjulen vridna åt vänster (mot vägen)',
    ],
    correctIndex: 1,
    explanation: 'I uppförsbacke utan kantsten bör du vrida framhjulen åt höger (mot vägkanten) och dra åt handbromsen, så att bilen inte rullar ut i vägen om den skulle börja röra sig.',
  },
  {
    id: 'par-15',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Får du parkera mot färdriktningen (på vänster sida av vägen)?',
    options: [
      'Ja, det är alltid tillåtet',
      'Nej, du ska alltid parkera i färdriktningen på höger sida',
      'Ja, men bara på enkelriktade gator',
    ],
    correctIndex: 2,
    explanation: 'På dubbelriktade gator ska du parkera på höger sida i färdriktningen. På enkelriktade gator får du parkera på båda sidor.',
  },
];
