import { Question } from './types';

export const parkeringQuestions: Question[] = [
  {
    id: 'par-1',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Hur nära en korsning får du parkera?',
    options: ['5 meter', '10 meter', '15 meter'],
    correctIndex: 1,
    explanation: 'Du får inte parkera närmare en korsning än 10 meter från korsande körbanas närmaste ytterkant.',
  },
  {
    id: 'par-2',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Hur nära ett övergångsställe får du parkera?',
    options: ['5 meter', '10 meter', '15 meter'],
    correctIndex: 1,
    explanation: 'Du får inte parkera närmare ett övergångsställe eller en cykelpassage än 10 meter före och 10 meter efter.',
  },
  {
    id: 'par-3',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad innebär datumparkering?',
    options: [
      'Att man bara får parkera på helger',
      'Att man parkerar på den sida av gatan som har jämna husnummer på jämna datum och udda på udda datum',
      'Att parkeringstiden begränsas till ett visst datum',
    ],
    correctIndex: 1,
    explanation: 'Datumparkering innebär att du parkerar på sidan med jämna husnummer på jämna datum och sidan med udda husnummer på udda datum. Byte sker mellan kl 00–06.',
  },
  {
    id: 'par-4',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad innebär 24-timmarsregeln för parkering?',
    options: [
      'Du måste flytta bilen var 24:e timme på gator med parkeringsförbud',
      'Du får parkera i högst 24 timmar i följd på samma plats på allmän väg om inget annat anges',
      'Parkeringsböter fördubblas efter 24 timmar',
    ],
    correctIndex: 1,
    explanation: 'På allmän väg gäller att du inte får parkera mer än 24 timmar i följd på vardagar, om inget annat anges med skylt.',
  },
  {
    id: 'par-5',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Vad betyder vägmärket "Förbud mot att parkera" (P med snedstreck)?',
    options: [
      'Du får inte stanna alls',
      'Du får stanna för av- och påstigning men inte parkera',
      'Du får parkera i högst 5 minuter',
    ],
    correctIndex: 1,
    explanation: 'Förbud mot att parkera innebär att du inte får parkera, men du får stanna kortvarigt för av- och påstigning eller i- och urlastning.',
  },
  {
    id: 'par-6',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad gäller vid "Förbud mot att stanna och parkera"?',
    options: [
      'Du får stanna för att släppa av passagerare',
      'Du får varken stanna eller parkera fordonet',
      'Du får stanna i högst 1 minut',
    ],
    correctIndex: 1,
    explanation: 'Vid förbud mot att stanna och parkera får du varken stanna eller parkera. Undantag gäller vid trafikljus, vid kö eller för att undvika fara.',
  },
  {
    id: 'par-7',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Hur nära en busshållplats får du parkera?',
    options: [
      '10 meter före och efter',
      '20 meter före och 5 meter efter',
      '20 meter',
    ],
    correctIndex: 2,
    explanation: 'Du får inte parkera inom 20 meter från en busshållplatsskylts plats vid hållplats med markering. Detta för att bussar ska kunna stanna och passagerare ska ha fri sikt.',
  },
  {
    id: 'par-8',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad gäller för parkering på huvudled?',
    options: [
      'Du får parkera om det finns en ficka',
      'Parkering är förbjuden på huvudled',
      'Du får parkera om du har varningstriangel',
    ],
    correctIndex: 1,
    explanation: 'Det råder parkeringsförbud på huvudled. Du får dock stanna kortvarigt vid nödsituation. Parkera istället på anvisade parkeringsplatser.',
  },
  {
    id: 'par-9',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Var ska du parkera om det finns en markerad P-ruta?',
    options: [
      'Du kan parkera bredvid rutan om den är full',
      'Inom den markerade rutan enligt anvisning',
      'Var som helst inom 10 meter från rutan',
    ],
    correctIndex: 1,
    explanation: 'Du ska parkera helt inom den markerade P-rutan. Parkering utanför rutorna kan ge parkeringsanmärkning.',
  },
  {
    id: 'par-10',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad gäller för parkering på plats reserverad för rörelsehindrad (handikapplats)?',
    options: [
      'Alla får parkera där om platsen är ledig',
      'Bara den som har parkeringstillstånd för rörelsehindrad får parkera där',
      'Man får parkera där kortvarigt utan tillstånd',
    ],
    correctIndex: 1,
    explanation: 'Platser reserverade för rörelsehindrade får bara användas av den som har giltigt parkeringstillstånd för rörelsehindrad utfärdat av kommunen.',
  },
  {
    id: 'par-11',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Du parkerar på en gata utan skyltar i ett bostadsområde. Hur länge får du stå?',
    options: [
      'Så länge du vill',
      'Högst 24 timmar i följd på vardagar',
      'Högst 7 dagar',
    ],
    correctIndex: 1,
    explanation: 'Grundregeln på allmän väg är att du inte får parkera mer än 24 timmar i följd på vardagar. På helger/helgdagar gäller 24-timmarsregeln från nästa vardag.',
  },
  {
    id: 'par-12',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Får du parkera på en cykelbana?',
    options: [
      'Ja, om det inte finns cykeltrafikskyltar',
      'Ja, om du stannar i högst 5 minuter',
      'Nej, det är förbjudet att parkera på cykelbana',
    ],
    correctIndex: 2,
    explanation: 'Det är förbjudet att parkera och stanna på cykelbanor. Det hindrar cyklister och skapar trafikfara.',
  },
  {
    id: 'par-13',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad kan bli konsekvensen om du parkerar fel upprepade gånger?',
    options: [
      'Bilen kan bli flyttad (borttapt) på din bekostnad',
      'Du förlorar körkortet',
      'Du får bara böter',
    ],
    correctIndex: 0,
    explanation: 'Vid upprepad felparkering eller om fordonet står till hinder kan det bli föremål för flygning (bortforsling) på ägarens bekostnad, utöver parkeringsanmärkningar.',
  },
  {
    id: 'par-14',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Hur ska du parkera i en uppförsbacke utan kantsten?',
    options: [
      'Med hjulen rakt fram',
      'Med framhjulen vridna åt höger (mot vägkanten)',
      'Med framhjulen vridna åt vänster (mot vägen)',
    ],
    correctIndex: 1,
    explanation: 'I uppförsbacke utan kantsten bör du vrida framhjulen åt höger (mot vägkanten) och dra åt handbromsen, så att bilen inte rullar ut i vägen om den skulle börja röra sig.',
  },
  {
    id: 'par-15',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Får du parkera mot färdriktningen (på vänster sida av vägen)?',
    options: [
      'Ja, det är alltid tillåtet',
      'Nej, du ska alltid parkera i färdriktningen på höger sida',
      'Ja, men bara på enkelriktade gator',
    ],
    correctIndex: 2,
    explanation: 'På dubbelriktade gator ska du parkera på höger sida i färdriktningen. På enkelriktade gator får du parkera på båda sidor.',
  },
  {
    id: 'par-16',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Hur nära en infart eller utfart får du parkera?',
    options: ['5 meter', 'Du får inte parkera så att du hindrar in- och utfart', '2 meter'],
    correctIndex: 1,
    explanation: 'Du får inte parkera så att in- eller utfart hindras. Det finns inget specifikt meteravstånd — bedöm om fordon kan passera.',
  },
  {
    id: 'par-17',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Får du parkera på en trottoar?',
    options: ['Ja, om det finns plats', 'Nej, om inte skylt tillåter det', 'Bara halvvägs upp'],
    correctIndex: 1,
    explanation: 'Parkering på trottoar är förbjuden om det inte finns vägmärke som tillåter det.',
  },
  {
    id: 'par-18',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad gäller vid parkering i en backe utan kantsten?',
    options: ['Vrid rattren åt vänster', 'Dra handbromsen och lägg i lämplig växel', 'Inget speciellt'],
    correctIndex: 1,
    explanation: 'I backe: dra handbromsen. Med manuell: lägg i ettan (uppförsbacke) eller backen (nedförsbacke). Vrid hjulen mot trottoarkanten.',
  },
  {
    id: 'par-19',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad innebär parkeringszonens "P-skiva"?',
    options: ['En app', 'En urtavla du ställer in på ankomsttid och lägger synlig i vindruitan', 'En betalningsmetod'],
    correctIndex: 1,
    explanation: 'P-skivan visar ankomsttid. Du ställer in klockslaget och lägger den synlig. Kontrollanterna ser hur länge du stått.',
  },
  {
    id: 'par-20',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad gäller om det finns en tilläggstavla "1 tim" under ett parkeringskylten?',
    options: ['Du får parkera max 1 timme', 'Du måste parkera minst 1 timme', 'Parkeringen kostar 1 kr/timme'],
    correctIndex: 0,
    explanation: 'Tilläggstavlan anger att parkering är tillåten i max 1 timme. Ofta krävs p-skiva.',
  },
  {
    id: 'par-21',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Vad är skillnaden mellan att stanna och att parkera?',
    options: ['Ingen skillnad', 'Stanna = kortvarigt stopp (t.ex. av/på-stigande). Parkering = lämna fordonet', 'Stanna = på natten, parkera = på dagen'],
    correctIndex: 1,
    explanation: 'Stannande är kortvarigt (av/på-stigande, i/ur-lastning). Parkering innebär att du lämnar fordonet eller stannar längre.',
  },
  {
    id: 'par-22',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Var får du inte stanna ditt fordon?',
    options: ['Vid en busshållplats', 'På övergångsställe eller cykelpassage', 'Framför en port'],
    correctIndex: 1,
    explanation: 'Du får aldrig stanna eller parkera på ett övergångsställe eller en cykelpassage.',
  },
  {
    id: 'par-23',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad innebär "parkeringsförbud jämna datum"?',
    options: ['Parkering förbjuden jämna dagar i månaden', 'Parkering förbjuden jämna veckonummer', 'Parkering förbjuden på helger'],
    correctIndex: 0,
    explanation: 'Datumparkering med jämna datum innebär att parkering är förbjuden på dagar med jämna datum (2, 4, 6 osv.).',
  },
  {
    id: 'par-24',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Vad ska du tänka på när du parkerar i en garage?',
    options: ['Inget speciellt', 'Kör sakta, var uppmärksam på gående och andra fordon', 'Kör fort för att hitta plats'],
    correctIndex: 1,
    explanation: 'I parkeringsgarage: kör mycket sakta, var uppmärksam på gående, backa försiktigt och respektera pilmarkeringar.',
  },
  {
    id: 'par-25',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Hur nära spårvagnsspår får du parkera?',
    options: ['1 meter', 'Du får inte parkera så att spårvagnen hindras', '5 meter'],
    correctIndex: 1,
    explanation: 'Parkering nära spårvagnsspår är förbjuden om den hindrar spårvagnstrafiken.',
  },
  {
    id: 'par-26',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad innebär "gatuparkeringsavgift" och vad händer om du inte betalar?',
    options: ['Inget händer', 'Du riskerar kontrollavgift (parkeringsbot)', 'Du får rabatt nästa gång'],
    correctIndex: 1,
    explanation: 'Obetald parkeringsavgift ger kontrollavgift. På kommunal mark kallas det felparkeringsavgift.',
  },
  {
    id: 'par-27',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Får du stanna vid ett övergångsställe för att släppa av en passagerare?',
    options: ['Ja, det är bara att stanna', 'Nej, stannande är förbjudet på övergångsställe', 'Ja, om det går snabbt'],
    correctIndex: 1,
    explanation: 'Stannande och parkering är förbjudet på övergångsställen — det skymmer sikten och är farligt för fotgängare.',
  },
  {
    id: 'par-28',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad gäller för parkering vid en korsning med vägmärke "Parkering tillåten 8-17"?',
    options: ['Parkering tillåten dygnet runt', 'Parkering tillåten bara 8-17', 'Parkering förbjuden 8-17'],
    correctIndex: 1,
    explanation: 'Tidsbegränsningen anger när parkering är tillåten. Utanför dessa tider kan andra regler gälla.',
  },
  {
    id: 'par-29',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad gäller om du parkerar och blockerar en brandpost?',
    options: ['Inga konsekvenser', 'Fordonet kan bogseras bort och du får böter', 'Bara böter'],
    correctIndex: 1,
    explanation: 'Att blockera en brandpost kan leda till att fordonet bogseras bort omedelbart plus böter. Räddningstjänsten behöver åtkomst.',
  },
  {
    id: 'par-30',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Vad ska du göra innan du öppnar bildörren vid parkering?',
    options: ['Inget speciellt', 'Kontrollera att ingen cyklist eller bil kommer', 'Tuta'],
    correctIndex: 1,
    explanation: 'Kontrollera alltid spegel och dödvinkel innan du öppnar dörren — cyklister och andra kan komma oväntat.',
  },
  {
    id: 'par-31',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad innebär "boendeparkering"?',
    options: ['Gratis parkering för alla', 'Parkeringsplatser reserverade för boende i området med tillstånd', 'Parkering i garage'],
    correctIndex: 1,
    explanation: 'Boendeparkering kräver ett särskilt tillstånd från kommunen för att parkera i det angivna området.',
  },
  {
    id: 'par-32',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad gäller om du ska parkera på natten längs en väg utan gatubelysning?',
    options: ['Inget speciellt', 'Parkeringsljus ska vara tända om fordonet kan vara svårt att se', 'Parkering förbjuden'],
    correctIndex: 1,
    explanation: 'Om bilen kan vara svår att upptäcka (mörk väg utan gatubelysning) ska parkeringsljus vara tända.',
  },
  {
    id: 'par-33',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Hur nära ett vägarbete får du parkera?',
    options: ['10 meter', 'Du får inte parkera så att du hindrar vägarbetet', 'Bredvid om det finns plats'],
    correctIndex: 1,
    explanation: 'Du får inte parkera så att du hindrar vägarbete eller utgör en fara för arbetare.',
  },
  {
    id: 'par-34',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad händer om du står parkerad i mer än 7 dygn på samma plats på offentlig väg?',
    options: ['Inget', 'Fordonet kan anses övergivet och flyttas av kommunen', 'Du får rabatt'],
    correctIndex: 1,
    explanation: 'Kommunen kan flytta fordon som stått stilla längre tid (vanligen 7 dygn) på offentlig väg.',
  },
  {
    id: 'par-35',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Du parkerar i ett bostadsområde med skylt "P 2 tim 8-18 (8-14)". Vad gäller kl 10 på en lördag?',
    options: ['Max 2 timmar', 'Max 2 timmar (lördagsregler 8-14)', 'Fri parkering'],
    correctIndex: 1,
    explanation: 'Tiden inom parentes gäller lördag. Kl 10 en lördag gäller 2-timmarsbegränsningen (8-14). Söndagar fritt.',
  },
  {
    id: 'par-36',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Får du parkera vid en järnvägskorsning?',
    options: ['Ja', 'Nej, minst 30 meter avstånd krävs', 'Bara om bommarna är uppe'],
    correctIndex: 1,
    explanation: 'Parkering inom 30 meter från en järnvägskorsning är förbjuden.',
  },
  {
    id: 'par-37',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad gäller om du parkerar på en privat parkeringsplats utan att betala?',
    options: ['Inget händer — det är privat mark', 'Markägaren kan utfärda kontrollavgift', 'Bara kommunen kan bötfälla'],
    correctIndex: 1,
    explanation: 'Privata parkeringsbolag har rätt att utfärda kontrollavgift om du inte följer villkoren.',
  },
  {
    id: 'par-38',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Du hittar en ledig plats men den har skylt "Laddplats — elbil". Du har en bensinbil. Får du parkera?',
    options: ['Ja, om inga elbilar kommer', 'Nej, platsen är reserverad för laddning av elfordon', 'Ja, om du betalar'],
    correctIndex: 1,
    explanation: 'Platser skyltade för elbilsladdning är reserverade. Andra fordon får inte parkera där.',
  },
  {
    id: 'par-39',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Vad ska du göra om du skadar en parkerad bil?',
    options: ['Köra därifrån', 'Lämna dina kontaktuppgifter eller kontakta polisen', 'Vänta tills ägaren kommer'],
    correctIndex: 1,
    explanation: 'Du måste lämna dina uppgifter på ett synligt ställe eller kontakta polisen. Att köra smitning är brottsligt.',
  },
  {
    id: 'par-40',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad innebär "fickparkering"?',
    options: ['Att parkera i fickan', 'Parkering i en vik/ficka vid sidan av vägen', 'Att parkera snett'],
    correctIndex: 1,
    explanation: 'Fickparkering är en utbuktning vid sidan av vägen avsedd för parkering.',
  },
  {
    id: 'par-41',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad gäller för parkering utanför ett utryckningsfordongarage (brandstation)?',
    options: ['Samma regler som vanligt', 'Stannande och parkering förbjudet framför utfarten', 'Bara kortare stopp tillåtet'],
    correctIndex: 1,
    explanation: 'Du får aldrig stanna eller parkera framför utfarten till en brandstation eller annan utryckningsstation.',
  },
  {
    id: 'par-42',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Vad betyder skylt "P" med en pil som pekar åt höger?',
    options: ['Parkering åt höger', 'Parkeringsplatsen börjar i pilens riktning', 'Sväng höger till parkering'],
    correctIndex: 1,
    explanation: 'Pilen anger i vilken riktning parkeringsplatsen eller parkeringsreglerna gäller.',
  },
  {
    id: 'par-43',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad gäller för "stopplast-zon" (gult markerad)?',
    options: ['Parkering tillåten', 'Kortvarigt stannande för i- och urlastning tillåtet, men inte parkering', 'Bara bussar'],
    correctIndex: 1,
    explanation: 'I en lastzon (gula markeringar) är kortvarigt stannande för lastning/lossning tillåtet men inte parkering.',
  },
  {
    id: 'par-44',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Du parkerar och lämnar bilen. Måste du låsa den?',
    options: ['Nej, det är frivilligt', 'Ja, du ska vidta åtgärder mot obehörigt bruk (lås, ta nyckeln)', 'Bara om det finns värdesaker'],
    correctIndex: 1,
    explanation: 'Enligt lag ska du vidta åtgärder för att förhindra obehörigt bruk — lås bilen och ta med nyckeln.',
  },
  {
    id: 'par-45',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Hur ska du parkera i en uppförsbacke med kantsten?',
    options: ['Hjulen rakt framåt', 'Vrid hjulen från kantsten (åt vänster)', 'Vrid hjulen mot kantsten'],
    correctIndex: 1,
    explanation: 'I uppförsbacke med kantsten: vrid hjulen bort från kantsten. Om bilen rullar bakåt, fångar kantsten hjulet.',
  },
  {
    id: 'par-46',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad innebär skylt "P avgift" med tidsbegränsning?',
    options: ['Gratis parkering', 'Betald parkering med maximal parkertid', 'Bara för prenumeranter'],
    correctIndex: 1,
    explanation: 'Du måste betala parkeringsavgift och respektera den maximala parkeringstiden.',
  },
  {
    id: 'par-47',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Får du parkera en husbil på en vanlig parkeringsplats?',
    options: ['Ja, om den får plats', 'Beror på lokala regler — vissa platser förbjuder fordon över viss längd/höjd', 'Nej, aldrig'],
    correctIndex: 1,
    explanation: 'Husbilar får ofta parkera på vanliga platser men lokala regler kan begränsa fordonsstorlek eller tid.',
  },
  {
    id: 'par-48',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Vad ska du göra om parkeringsautomaten inte fungerar?',
    options: ['Parkera gratis', 'Hitta en annan automat eller använd alternativ betalmetod (app)', 'Parkera utan att betala'],
    correctIndex: 1,
    explanation: 'En trasig automat ger dig inte rätt att parkera gratis. Sök alternativ betalning eller flytta bilen.',
  },
  {
    id: 'par-49',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad gäller om du parkerar och det blir snö — måste du flytta bilen?',
    options: ['Nej, snö ändrar inget', 'Ja, om kommunen behöver plöja måste du flytta bilen', 'Bara om det snöar mycket'],
    correctIndex: 1,
    explanation: 'Kommunen kan skylta tillfälligt parkeringsförbud för snöröjning. Du ansvarar för att flytta bilen.',
  },
  {
    id: 'par-50',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad innebär kontrollavgift vs felparkeringsavgift?',
    options: ['Samma sak', 'Kontrollavgift = privat mark. Felparkeringsavgift = kommunal mark', 'Felparkeringsavgift = privat'],
    correctIndex: 1,
    explanation: 'Felparkeringsavgift utfärdas av kommunen. Kontrollavgift utfärdas av privata parkeringsbolag.',
  },
  {
    id: 'par-51',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Hur nära en hörna/korsning får du parkera?',
    options: ['5 meter', '10 meter', '2 meter'],
    correctIndex: 1,
    explanation: 'Du får inte parkera inom 10 meter från en korsning om sikten kan skymas.',
  },
  {
    id: 'par-52',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad gäller om du hittar en ledig handikapparkering men saknar tillstånd?',
    options: ['Du kan parkera kort', 'Du får absolut inte parkera där utan giltigt tillstånd', 'Bara om det är tomt'],
    correctIndex: 1,
    explanation: 'Handikapparkering kräver giltigt parkeringstillstånd för rörelsehindrade. Utan tillstånd riskerar du höga böter.',
  },
  {
    id: 'par-53',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Du parkerar snett i en ficka. Bilen sticker ut i körbanan. Är detta tillåtet?',
    options: ['Ja, om bilen står i fickan', 'Nej, bilen får inte sticka ut i körbanan', 'Bara under dagtid'],
    correctIndex: 1,
    explanation: 'Fordonet ska vara helt inom den markerade parkeringsrutan. Att sticka ut i körbanan är förbjudet.',
  },
  {
    id: 'par-54',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Vad ska du göra om du behöver stanna kort vid vägen (t.ex. släppa av passagerare)?',
    options: ['Stanna var som helst', 'Stanna på en säker plats utan att hindra trafik, om det inte är förbjudet', 'Dubbelparekra'],
    correctIndex: 1,
    explanation: 'Kortvarigt stannande (av/påstigning) är tillåtet där stannande inte är förbjudet, men du ska inte hindra trafiken.',
  },
  {
    id: 'par-55',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad gäller vid parkering i nedförsbacke med kantsten?',
    options: ['Vrid hjulen åt höger (mot kantsten)', 'Hjulen rakt', 'Vrid hjulen åt vänster'],
    correctIndex: 0,
    explanation: 'I nedförsbacke med kantsten: vrid hjulen åt höger (mot kantsten). Om bilen rullar, stoppas den av kantsten.',
  },
  {
    id: 'par-56',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Vad gäller om du parkerar vid en vändplats?',
    options: ['Parkering tillåten', 'Parkering förbjuden — vändplatsen måste vara fri', 'Bara kortare stopp'],
    correctIndex: 1,
    explanation: 'Vändplatser ska hållas fria så att fordon kan vända. Parkering är förbjuden.',
  },
  {
    id: 'par-57',
    category: 'parkering',
    difficulty: 'easy',
    question: 'Får du lämna motorn igång när du parkerat?',
    options: ['Ja, alltid', 'Nej, tomgångskörning i mer än 1 minut är vanligen förbjuden', 'Ja, om det är kallt'],
    correctIndex: 1,
    explanation: 'De flesta kommuner har tomgångsförbud — max 1 minut. Det är dåligt för miljön och kan ge böter.',
  },
  {
    id: 'par-58',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad innebär "gatuparkeringsföreskrifter"?',
    options: ['Nationella regler', 'Lokala bestämmelser som kommunen satt för parkering på gatorna', 'EU-regler'],
    correctIndex: 1,
    explanation: 'Kommunen bestämmer lokala parkeringsregler — tider, avgifter och begränsningar. Dessa kan skilja mellan olika gator.',
  },
  {
    id: 'par-59',
    category: 'parkering',
    difficulty: 'hard',
    question: 'Du parkerar och ser att det står "P 30 min" med p-skiva. Du har ingen p-skiva. Vad gör du?',
    options: ['Parkerar ändå', 'Skaffar en p-skiva eller parkerar på annat ställe', 'Skriver ankomsttid på en lapp'],
    correctIndex: 1,
    explanation: 'Utan p-skiva riskerar du böter. Skaffa en (finns gratis hos bilprovning/parkeringsbolag) eller parkera annorstädes.',
  },
  {
    id: 'par-60',
    category: 'parkering',
    difficulty: 'medium',
    question: 'Vad gäller vid "infartsparkering" (pendlarparkering)?',
    options: ['Bara för boende', 'Avsedd för att parkera bilen och resa vidare med kollektivtrafik', 'Parkering max 1 timme'],
    correctIndex: 1,
    explanation: 'Infartsparkeringar är avsedda för pendlare som parkerar och tar buss/tåg vidare.',
  },
];
