import { Question } from './types';

export const riskbeteendeQuestions: Question[] = [
  {
    id: 'risk-1',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad är den vanligaste orsaken till olyckor i trafiken?',
    options: [
      'Fordonstekniska fel',
      'Mänskliga faktorer som ouppmärksamhet och trötthet',
      'Dåligt vägunderlag',
    ],
    correctIndex: 1,
    explanation:
      'Cirka 90 % av alla trafikolyckor beror på den mänskliga faktorn, till exempel ouppmärksamhet, trötthet eller riskfyllt beteende.',
  },
  {
    id: 'risk-2',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad bör du göra om du känner dig trött under körning?',
    options: [
      'Öppna fönstret och fortsätta köra',
      'Stanna och vila minst 20 minuter',
      'Dricka kaffe och köra vidare direkt',
    ],
    correctIndex: 1,
    explanation:
      'Att öppna fönstret eller dricka kaffe ger bara kortvarig effekt. Det enda säkra är att stanna och sova eller vila ordentligt, minst 20 minuter.',
  },
  {
    id: 'risk-3',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Hur påverkar mobilanvändning din körförmåga?',
    options: [
      'Den påverkar inte om du har handsfree',
      'Reaktionstiden ökar kraftigt och uppmärksamheten minskar',
      'Den förbättrar din förmåga att multitaska',
    ],
    correctIndex: 1,
    explanation:
      'Att prata i mobil, även med handsfree, försämrar uppmärksamheten. Att skriva meddelanden är ännu farligare och jämförbart med rattfylleri.',
  },
  {
    id: 'risk-4',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad innebär 3-sekundersregeln?',
    options: [
      'Du ska kunna stanna inom 3 sekunder',
      'Avståndet till framförvarande bör motsvara minst 3 sekunders körtid',
      'Du ska reagera inom 3 sekunder på en fara',
    ],
    correctIndex: 1,
    explanation:
      '3-sekundersregeln innebär att du ska hålla minst 3 sekunders avstånd till bilen framför. Välj en fast punkt och räkna tiden tills du når den.',
  },
  {
    id: 'risk-5',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Hur lång är en normal reaktionstid för en uppmärksam förare?',
    options: [
      'Cirka 0,5 sekunder',
      'Cirka 1 sekund',
      'Cirka 3 sekunder',
    ],
    correctIndex: 1,
    explanation:
      'En uppmärksam förare har en reaktionstid på cirka 1 sekund. Trötthet, stress och distraktioner kan förlänga den avsevärt.',
  },
  {
    id: 'risk-6',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vid 90 km/h och normal reaktionstid – hur långt hinner du köra innan du börjar bromsa?',
    options: [
      'Cirka 10 meter',
      'Cirka 25 meter',
      'Cirka 50 meter',
    ],
    correctIndex: 1,
    explanation:
      'Vid 90 km/h färdas du 25 meter per sekund. Med 1 sekunds reaktionstid hinner du alltså köra ca 25 meter innan du ens börjar bromsa.',
  },
  {
    id: 'risk-7',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Hur påverkas bromssträckan på en våt väg jämfört med torr väg?',
    options: [
      'Den förblir ungefär lika lång',
      'Den kan bli dubbelt så lång',
      'Den minskar tack vare vattnets kyleffekt',
    ],
    correctIndex: 1,
    explanation:
      'På en våt väg minskar friktionen markant, vilket kan göra bromssträckan upp till dubbelt så lång som på torr väg.',
  },
  {
    id: 'risk-8',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är aquaplaning?',
    options: [
      'När bromsskivorna överhettas vid kraftig inbromsning',
      'När däcken tappar kontakten med vägen på grund av ett vattenlager',
      'När bilen glider på is i kurvor',
    ],
    correctIndex: 1,
    explanation:
      'Aquaplaning uppstår när vatten samlas framför däcken snabbare än det leds bort, så att bilen "flyter" på vattnet och du tappar styrförmågan.',
  },
  {
    id: 'risk-9',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vilka trafikanter är extra utsatta och kräver särskild uppmärksamhet?',
    options: [
      'Lastbilsförare',
      'Barn, cyklister och äldre',
      'Andra bilister med nya bilar',
    ],
    correctIndex: 1,
    explanation:
      'Barn kan plötsligt springa ut i gatan, cyklister och äldre är oskyddade. Dessa grupper kräver extra försiktighet och lägre hastighet.',
  },
  {
    id: 'risk-10',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad ska du göra om du ser barn leka nära vägen?',
    options: [
      'Tuta för att uppmärksamma barnen',
      'Sänka hastigheten kraftigt och vara beredd att stanna',
      'Byta fil och köra förbi snabbt',
    ],
    correctIndex: 1,
    explanation:
      'Barn har svårt att bedöma hastighet och avstånd. Sänk hastigheten rejält och var alltid beredd att stanna helt.',
  },
  {
    id: 'risk-11',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad är en dödvinkel?',
    options: [
      'Ett område framför bilen som sikten inte når',
      'Ett område bredvid eller bakom bilen som inte syns i backspeglarna',
      'Området direkt under bilen',
    ],
    correctIndex: 1,
    explanation:
      'Dödvinkeln är det område bredvid och snett bakom fordonet som inte syns i backspeglarna. Kontrollera alltid genom att vrida på huvudet innan filbyte.',
  },
  {
    id: 'risk-12',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför är det extra farligt att köra fort i mörker?',
    options: [
      'Bilen drar mer bränsle i mörker',
      'Sikten är begränsad och stoppsträckan kan överstiga ljusområdet',
      'Vägbanan blir mjukare på natten',
    ],
    correctIndex: 1,
    explanation:
      'I mörker ser du kortare sträckor framför dig. Om du kör för fort kan du behöva stanna på en längre sträcka än vad strålkastarna lyser upp.',
  },
  {
    id: 'risk-13',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Hur lång kan den totala stoppsträckan bli vid 80 km/h på isig väg?',
    options: [
      'Cirka 50 meter',
      'Cirka 100 meter',
      'Över 200 meter',
    ],
    correctIndex: 2,
    explanation:
      'På isig väg kan friktionen vara så låg att bromssträckan blir 5–10 gånger längre. Vid 80 km/h kan total stoppsträcka överstiga 200 meter.',
  },
  {
    id: 'risk-14',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vilken är den största risken med aggressiv körning?',
    options: [
      'Ökad bränsleförbrukning',
      'Kraftigt ökad olycksrisk på grund av sämre beslutsfattande',
      'Större slitage på bromsar',
    ],
    correctIndex: 1,
    explanation:
      'Aggressiv körning leder till riskfyllt beteende som för kort avstånd, plötsliga filbyten och för hög hastighet, vilket kraftigt ökar olycksrisken.',
  },
  {
    id: 'risk-15',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Hur påverkar grupptryck unga förares beteende i trafiken?',
    options: [
      'Det gör dem mer försiktiga',
      'Det kan leda till högre risktagande och farligare körning',
      'Det har ingen påverkan alls',
    ],
    correctIndex: 1,
    explanation:
      'Unga förare tar ofta större risker med passagerare i bilen, särskilt jämnåriga. Grupptryck kan leda till högre hastigheter och farligare beteenden.',
  },
  {
    id: 'risk-16',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du göra om ett djur plötsligt dyker upp på vägen?',
    options: [
      'Alltid väja kraftigt åt sidan',
      'Bromsa och försöka behålla kontrollen – undvik kraftig väjning vid hög hastighet',
      'Accelerera för att passera snabbt',
    ],
    correctIndex: 1,
    explanation:
      'Kraftig väjning vid hög hastighet kan leda till att du förlorar kontrollen eller hamnar i mötande körfält. Bromsa kontrollerat istället.',
  },
  {
    id: 'risk-17',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Var är risken störst för viltolyckor?',
    options: [
      'I stadsmiljö nära parker',
      'Vid gryning och skymning, nära skog och åkermark',
      'På motorvägar mitt på dagen',
    ],
    correctIndex: 1,
    explanation:
      'Vilt är mest aktivt vid gryning och skymning. Sträckor nära skog och åkermark är särskilt riskfyllda, ofta markerade med viltvarningsmärken.',
  },
  {
    id: 'risk-18',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad händer med stoppsträckan om hastigheten fördubblas?',
    options: [
      'Stoppsträckan fördubblas',
      'Stoppsträckan fyrdubblas',
      'Stoppsträckan tredubblas',
    ],
    correctIndex: 1,
    explanation:
      'Bromssträckan ökar med hastigheten i kvadrat. Om hastigheten fördubblas blir bromssträckan fyra gånger längre.',
  },
  {
    id: 'risk-19',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vilken tidsperiod på dygnet är olycksrisken störst?',
    options: [
      'Mitt på dagen (12–14)',
      'Natten och tidiga morgontimmarna (02–06)',
      'Kvällstid (18–20)',
    ],
    correctIndex: 1,
    explanation:
      'Under natten och tidiga morgontimmarna är olycksrisken störst på grund av trötthet, dålig sikt och eventuell alkoholpåverkan.',
  },
  {
    id: 'risk-20',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Hur mycket ökar risken att dödas i en kollision om hastigheten ökar från 30 till 50 km/h?',
    options: [
      'Risken fördubblas',
      'Risken ökar med cirka 5 gånger',
      'Risken ökar med cirka 10 gånger',
    ],
    correctIndex: 1,
    explanation:
      'Risken att en fotgängare dödas ökar dramatiskt vid högre hastigheter. Vid 30 km/h överlever de flesta, vid 50 km/h är risken att dö ca 5 gånger högre.',
  },
  {
    id: 'risk-21',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad menas med "säkerhetsavstånd"?',
    options: [
      'Avståndet mellan bilens sida och vägkanten',
      'Avståndet till framförvarande fordon som ger dig tid att reagera och stanna',
      'Minsta avstånd till mötande trafik',
    ],
    correctIndex: 1,
    explanation:
      'Säkerhetsavstånd är det avstånd du behöver hålla till framförvarande fordon för att hinna reagera och bromsa om något oväntat händer.',
  },
  {
    id: 'risk-22',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Varför är risken för singelolyckor större i kurvor?',
    options: [
      'Hastighetsmätaren visar fel i kurvor',
      'Centrifugalkraften kan dra ut bilen ur kurvan vid för hög hastighet',
      'Sikten alltid är sämre i kurvor',
    ],
    correctIndex: 1,
    explanation:
      'I kurvor verkar centrifugalkraft på fordonet. Vid för hög hastighet kan bilen inte följa kurvan och köra av vägen, särskilt på hal vägbana.',
  },
  {
    id: 'risk-23',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad bör du göra om en förare bakom dig kör aggressivt och ligger tätt?',
    options: [
      'Bromsa plötsligt för att lära dem en läxa',
      'Hålla jämn fart och låta föraren köra om när det är möjligt',
      'Accelerera för att öka avståndet',
    ],
    correctIndex: 1,
    explanation:
      'Undvik konflikter i trafiken. Håll lugn, kör i jämn fart och låt den aggressiva föraren passera säkert när tillfälle ges.',
  },
  {
    id: 'risk-24',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vilken av följande faktorer ökar reaktionstiden mest?',
    options: [
      'Att lyssna på musik',
      'Att vara trött eller påverkad av läkemedel',
      'Att köra i regn',
    ],
    correctIndex: 1,
    explanation:
      'Trötthet och läkemedel har störst påverkan på reaktionstiden. Musik i sig påverkar normalt inte reaktionstiden lika kraftigt.',
  },
  {
    id: 'risk-25',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vid vilken temperatur är risken för halka störst?',
    options: [
      'Vid minus 15 grader eller kallare',
      'Runt 0 grader, när vägbanan ligger nära fryspunkten',
      'Vid plus 5 grader',
    ],
    correctIndex: 1,
    explanation:
      'Runt 0 grader växlar vägbanan mellan att vara våt och isig, vilket gör den extra hal. Blixthalka kan uppstå snabbt och oväntat.',
  },
  {
    id: 'risk-26',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad är den viktigaste åtgärden för att undvika olyckor i trafiken?',
    options: ['Köra en dyr bil', 'Hålla uppmärksamheten på trafiken', 'Köra i vänsterfilen'],
    correctIndex: 1,
    explanation: 'Uppmärksamhet är den viktigaste faktorn för trafiksäkerhet. De flesta olyckor beror på bristande uppmärksamhet.',
  },
  {
    id: 'risk-27',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Hur bör du hålla händerna på ratten för bäst kontroll?',
    options: ['Med en hand längst upp', 'I "kvart i tre"-position (9 och 3)', 'Längst ner på ratten'],
    correctIndex: 1,
    explanation: 'Händerna i position 9 och 3 (kvart i tre) ger bäst kontroll och möjlighet att reagera snabbt.',
  },
  {
    id: 'risk-28',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad innebär "tunnelseende"?',
    options: ['Att man bara ser rakt framåt och missar saker i periferin', 'Att sikten blir dålig i tunnlar', 'Att ögonen tröttnar vid körning'],
    correctIndex: 0,
    explanation: 'Tunnelseende innebär att synfältet smalnar av, ofta p.g.a. hög hastighet, trötthet eller stress. Man missar saker i periferin.',
  },
  {
    id: 'risk-29',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Hur påverkar stress din körförmåga?',
    options: ['Den blir bättre, adrenalinet hjälper', 'Du tar fler risker och är mindre uppmärksam', 'Ingen påverkan'],
    correctIndex: 1,
    explanation: 'Stress leder ofta till aggressiv körning, bristande uppmärksamhet och sämre beslutsfattande i trafiken.',
  },
  {
    id: 'risk-30',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför är det extra farligt att använda handhållen mobil under körning?',
    options: ['Mobilen kan tappa signal', 'Uppmärksamheten flyttas från trafiken och reaktionstiden ökar markant', 'Mobilen stör radion'],
    correctIndex: 1,
    explanation: 'Mobilanvändning tar uppmärksamhet, syn och händer från körningen. Reaktionstiden kan öka lika mycket som vid 0,8 promille.',
  },
  {
    id: 'risk-31',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad är den största risken vid körning i starkt regn?',
    options: ['Att bilens färg bleknar', 'Vattenplaning och kraftigt minskad sikt', 'Att motorn skadar sig'],
    correctIndex: 1,
    explanation: 'Starkt regn minskar sikten dramatiskt och vattenansamlingar kan orsaka vattenplaning där däcken tappar kontakten med vägen.',
  },
  {
    id: 'risk-32',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Du kör i 90 km/h. Ungefär hur långt kör du under en sekunds reaktionstid?',
    options: ['10 meter', '25 meter', '50 meter'],
    correctIndex: 1,
    explanation: '90 km/h = 25 m/s. Under en sekunds reaktionstid kör du alltså cirka 25 meter innan du ens börjar bromsa.',
  },
  {
    id: 'risk-33',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad bör du göra om du märker att du blivit arg i trafiken?',
    options: ['Köra snabbare för att lugna ner dig', 'Ta ett djupt andetag och fokusera på säker körning', 'Tuta åt andra förare'],
    correctIndex: 1,
    explanation: 'Ilska påverkar omdömet. Försök lugna dig, fokusera på körningen och undvik att agera impulsivt.',
  },
  {
    id: 'risk-34',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Varför är broar extra hala på vintern?',
    options: ['Broar saltas inte', 'Kall luft cirkulerar under bron vilket gör den kallare och isigare', 'Trafiken är tätare på broar'],
    correctIndex: 1,
    explanation: 'Broar kyls av från både ovan och under, vilket gör att is bildas snabbare där än på vanlig väg.',
  },
  {
    id: 'risk-35',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad innebär begreppet "understeering" (understyrning)?',
    options: ['Bilen svänger mer än du vill', 'Bilen svänger mindre än du styr — framhjulen tappar grepp', 'Bilen accelererar okontrollerat'],
    correctIndex: 1,
    explanation: 'Understyrning innebär att framhjulen tappar grepp och bilen går rakare än du styr. Vanligt vid framhjulsdrivna bilar i kurvor.',
  },
  {
    id: 'risk-36',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du göra om bilen börjar sladda bakåt (överstyrning)?',
    options: ['Bromsa hårt', 'Styra åt samma håll som bakänden glider (motstyrning)', 'Accelerera snabbt'],
    correctIndex: 1,
    explanation: 'Vid överstyrning (sladd) ska du styra åt det håll bakänden glider (motstyrning) och undvika hårda bromsningar.',
  },
  {
    id: 'risk-37',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför ska du inte köra om strax innan ett övergångsställe?',
    options: ['Det är alltid olagligt', 'Du kan dölja en fotgängare som en annan bil stannat för', 'Det tar för lång tid'],
    correctIndex: 1,
    explanation: 'Om en bil stannat vid ett övergångsställe kan det finnas en fotgängare du inte ser. Att köra om kan vara livsfarligt.',
  },
  {
    id: 'risk-38',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad händer med risken vid en frontalkollision om båda bilarna kör i 70 km/h?',
    options: ['Kraften motsvarar en krock i 70 km/h mot en vägg', 'Kraften motsvarar 140 km/h mot en vägg', 'Kraften är halva av 70 km/h'],
    correctIndex: 0,
    explanation: 'Vid frontalkollision mellan två lika tunga bilar i samma hastighet motsvarar kraften ungefär en krock mot en fast vägg i samma hastighet.',
  },
  {
    id: 'risk-39',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Hur påverkar passagerare unga förares riskbeteende?',
    options: ['Passagerare gör körningen säkrare', 'Unga förare tar fler risker med jämnåriga passagerare', 'Ingen påverkan'],
    correctIndex: 1,
    explanation: 'Studier visar att unga förare tar fler risker med jämnåriga passagerare i bilen — grupptryck ökar riskbeteendet.',
  },
  {
    id: 'risk-40',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför ska du inte äta mat under körning?',
    options: ['Det är olagligt', 'Det tar uppmärksamhet och en hand från ratten', 'Det är ohygieniskt'],
    correctIndex: 1,
    explanation: 'Att äta under körning tar uppmärksamhet och frigör en hand från ratten, vilket ökar olycksrisken.',
  },
  {
    id: 'risk-41',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Du kör i dimma. Vilken belysning ska du använda?',
    options: ['Helljus', 'Halvljus (eventuellt med dimljus)', 'Parkeringsljus'],
    correctIndex: 1,
    explanation: 'I dimma ska du använda halvljus. Helljus reflekteras i dimman och försämrar sikten. Dimljus framtill kan komplettera.',
  },
  {
    id: 'risk-42',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är "sekundärsömn"?',
    options: ['Att man somnar efter midnatt', 'Korta episoder av sömn (mikrosömn) utan att man märker det', 'Att man drömmer under sömn'],
    correctIndex: 1,
    explanation: 'Sekundärsömn/mikrosömn är korta sömnepisoder (1-30 sekunder) som kan inträffa utan förvarning. Extremt farligt vid körning.',
  },
  {
    id: 'risk-43',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför är det viktigt att spegla ofta?',
    options: ['För att kontrollera sitt utseende', 'För att ha koll på trafiksituationen runt bilen', 'Det krävs bara vid filbyte'],
    correctIndex: 1,
    explanation: 'Regelbunden spegling ger dig kontroll över trafiksituationen och förbereder dig för plötsliga händelser.',
  },
  {
    id: 'risk-44',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du tänka på vid körning i kraftig sidvind?',
    options: ['Inget speciellt', 'Håll ett fast grepp om ratten och var beredd på att bilen kan dras åt sidan', 'Öka hastigheten för att bli stabilare'],
    correctIndex: 1,
    explanation: 'Sidvind kan dra bilen åt sidan, särskilt vid broar, skogsöppningar och vid passering av lastbilar.',
  },
  {
    id: 'risk-45',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Varför är "look-but-failed-to-see"-olyckor (tittade men såg inte) så vanliga?',
    options: ['Bilister har dålig syn', 'Hjärnan filtrerar bort information den inte förväntar sig', 'Bilarna kör för fort'],
    correctIndex: 1,
    explanation: 'Hjärnan söker aktivt efter det den förväntar sig. Motorcyklister och cyklister kan därför "bli osynliga" trots att du tittade.',
  },
  {
    id: 'risk-46',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad är viktigast när du ska köra om ett annat fordon?',
    options: ['Att köra så fort som möjligt', 'Att försäkra dig om att det finns fri sikt och tillräckligt utrymme', 'Att tuta först'],
    correctIndex: 1,
    explanation: 'Säker omkörning kräver fri sikt, tillräckligt utrymme och att du kan avsluta omkörningen utan fara.',
  },
  {
    id: 'risk-47',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad innebär "defensive körning"?',
    options: ['Att köra långsamt', 'Att förutse faror och ha en plan för att undvika dem', 'Att alltid väja för andra'],
    correctIndex: 1,
    explanation: 'Defensiv körning handlar om att förutse risker, ha marginaler och vara beredd på andras misstag.',
  },
  {
    id: 'risk-48',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad händer med kroppen vid en frontalolycka i 50 km/h utan bälte?',
    options: ['Man hålls fast av stolen', 'Man kastas framåt med en kraft motsvarande flera gånger sin egen kroppsvikt', 'Krockkudden skyddar helt'],
    correctIndex: 1,
    explanation: 'Vid 50 km/h utan bälte kastas kroppen framåt med enorm kraft. En 70 kg tung person upplevs väga flera ton.',
  },
  {
    id: 'risk-49',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Varför ska du hålla extra stort avstånd till lastbilar?',
    options: ['Lastbilar har längre bromssträcka och större dödvinklar', 'Lastbilar kör alltid för fort', 'Det är olagligt att köra nära lastbilar'],
    correctIndex: 0,
    explanation: 'Lastbilar har längre bromssträcka, större dödvinklar och kan skymma sikten. Håll extra avstånd.',
  },
  {
    id: 'risk-50',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad är det första du bör göra om du kommer till en trafikolycka?',
    options: ['Flytta den skadade direkt', 'Varna andra trafikanter och ring 112', 'Köra vidare och inte störa'],
    correctIndex: 1,
    explanation: 'Säkra olycksplatsen och ring 112. Flytta inte skadade om det inte är livsfara (t.ex. brand).',
  },
  {
    id: 'risk-51',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Hur långt bör du placera en varningstriangel på en 70-väg?',
    options: ['10 meter bakom bilen', 'Cirka 100-200 meter bakom bilen', '50 meter framför bilen'],
    correctIndex: 1,
    explanation: 'På en väg med högre hastighet ska varningstriangeln placeras 100-200 meter bakom fordonet.',
  },
  {
    id: 'risk-52',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Varför kallas 0,2 promille för "nollgräns" trots att det inte är 0,0?',
    options: ['Mätinstrumenten har en felmarginal', 'Det krävs en liten marginal för naturlig alkoholproduktion i kroppen', 'Det är en politisk kompromiss'],
    correctIndex: 1,
    explanation: 'Kroppen kan producera små mängder alkohol naturligt. Gränsen 0,2 promille tar hänsyn till detta.',
  },
  {
    id: 'risk-53',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Hur undviker du bäst att somna vid ratten under en lång resa?',
    options: ['Skruva upp musiken', 'Ta regelbundna pauser och vila', 'Öppna fönstret'],
    correctIndex: 1,
    explanation: 'Det enda som verkligen hjälper mot trötthet är att stanna och vila. Musik och frisk luft ger bara kortvarig effekt.',
  },
  {
    id: 'risk-54',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad är "fixering" vid körning och varför är det farligt?',
    options: ['Att man fixerar blicken på en punkt och missar annan trafik', 'Att man reparerar bilen under körning', 'Att man kör med låst ratt'],
    correctIndex: 0,
    explanation: 'Fixering innebär att blicken fastnar på ett objekt. Du slutar scanna trafiken och missar faror.',
  },
  {
    id: 'risk-55',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är "olycksparadoxen" — att folk kör farligare på säkrare vägar?',
    options: ['Förare kompenserar säkerhet med högre risktagande', 'Säkrare vägar har mer trafik', 'Det finns ingen olycksparadox'],
    correctIndex: 0,
    explanation: 'Riskkompensation innebär att förare känner sig tryggare på bra vägar och kompenserar med högre hastighet och mindre uppmärksamhet.',
  },
  {
    id: 'risk-56',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför ska du alltid ha bilbältet på, även vid korta resor?',
    options: ['Det är bara viktigt på långa resor', 'De flesta olyckor sker nära hemmet, ofta vid låg hastighet', 'Det är bara för komfort'],
    correctIndex: 1,
    explanation: 'Majoriteten av trafikolyckor sker inom kort avstånd från hemmet. Bältet räddar liv även vid låga hastigheter.',
  },
  {
    id: 'risk-57',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du göra om dina bromsar plötsligt inte fungerar?',
    options: ['Dra i handbromsen kraftigt', 'Pumpa bromspedalen, växla ner och använd handbromsen försiktigt', 'Stäng av motorn'],
    correctIndex: 1,
    explanation: 'Pumpa pedalen (kan återställa tryck), växla ner för motorbroms och använd handbromsen försiktigt.',
  },
  {
    id: 'risk-58',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Varför är vänstersvängar en av de farligaste manövrarna i trafiken?',
    options: ['Man glömmer ofta att blinka', 'Man korsar mötande trafik och måste bedöma hastighet och avstånd', 'Vänster ratt gör det svårt'],
    correctIndex: 1,
    explanation: 'Vänstersväng kräver att du korsar mötande körfält och samtidigt bedömer hastighet och avstånd hos mötande fordon.',
  },
  {
    id: 'risk-59',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad innebär "blindspot" (dödvinkel)?',
    options: ['En solskadad punkt på vindrutan', 'Områden runt bilen som inte syns i speglarna', 'En blind korsning'],
    correctIndex: 1,
    explanation: 'Dödvinkeln är området bredvid och snett bakom bilen som inte täcks av speglarna. Kontrollera alltid med en blick över axeln.',
  },
  {
    id: 'risk-60',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Hur fungerar antisladdsystemet (ESC)?',
    options: ['Det förhindrar alla olyckor', 'Det bromsar enskilda hjul för att motverka sladd', 'Det sänker hastigheten automatiskt'],
    correctIndex: 1,
    explanation: 'ESC registrerar om bilen sladdar och bromsar enskilda hjul för att återställa stabiliteten.',
  },
  {
    id: 'risk-61',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är "2-sekundersregeln" vid omkörning?',
    options: ['Du ska vara klar med omkörningen inom 2 sekunder', 'Du ska se framförvarandes bakre stötfångare i din spegel minst 2 sekunder innan du byter tillbaka', 'Du ska vänta 2 sekunder innan du kör om'],
    correctIndex: 1,
    explanation: 'Innan du svänger tillbaka efter omkörning ska du se det omköras fordon i innerbackspegeln, med god marginal.',
  },
  {
    id: 'risk-62',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad ska du göra om ett däck exploderar under körning?',
    options: ['Bromsa hårt omedelbart', 'Håll ratten stadigt, släpp gasen försiktigt och styra bilen åt sidan', 'Sväng snabbt åt höger'],
    correctIndex: 1,
    explanation: 'Vid en däckexplosion — håll ratten stadigt, släpp gasen gradvis och styr försiktigt mot vägkanten. Bromsa inte hårt.',
  },
  {
    id: 'risk-63',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad innebär "road rage" (vägrade)?',
    options: ['Ilska och aggressivt beteende i trafiken', 'Att vägen är i dåligt skick', 'Att man är rädd att köra'],
    correctIndex: 0,
    explanation: 'Road rage är aggressivt beteende som kan leda till farliga situationer — tailgating, tuta, skrika, eller avsiktligt farlig körning.',
  },
  {
    id: 'risk-64',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Hur påverkas din körförmåga om du inte sovit på 24 timmar?',
    options: ['Ingen märkbar påverkan', 'Liknande påverkan som vid 1,0 promille alkohol', 'Lite sämre reflexer'],
    correctIndex: 1,
    explanation: 'Forskning visar att 24 timmars vakenhet ger en påverkan jämförbar med 1,0 promille alkohol.',
  },
  {
    id: 'risk-65',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad är vanligaste orsaken till upphinnandeolyckor (påkörning bakifrån)?',
    options: ['Dåliga bromsar', 'För kort avstånd till framförvarande', 'Dåligt väder'],
    correctIndex: 1,
    explanation: 'Upphinnandeolyckor orsakas oftast av för kort avstånd. Håll alltid säkerhetsavstånd.',
  },
  {
    id: 'risk-66',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför är det farligt att köra med slitna vindrutetorkare?',
    options: ['Bilen rostrar', 'Sikten försämras kraftigt vid regn', 'Vindrutetorkarna låter'],
    correctIndex: 1,
    explanation: 'Slitna torkare lämnar ränder och ger dålig sikt vid regn, vilket ökar olycksrisken avsevärt.',
  },
  {
    id: 'risk-67',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad innebär "krokodilhjärnan" i trafiksammanhang?',
    options: ['Att reptiler på vägen är farliga', 'Att primitiva instinkter (fight/flight) tar över vid stress och leder till impulsiva beslut', 'Att man kör som en krokodil'],
    correctIndex: 1,
    explanation: 'I stressade trafiksituationer kan primitiva instinkter ta över — man reagerar impulsivt istället för rationellt.',
  },
  {
    id: 'risk-68',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Varför är det extra farligt att köra om i en kurva?',
    options: ['Bilen accelererar sämre i kurvor', 'Du har begränsad sikt och riskerar att möta trafik', 'Bromsarna fungerar sämre'],
    correctIndex: 1,
    explanation: 'I kurvor har du begränsad sikt framåt. Mötande trafik kan dyka upp utan förvarning.',
  },
  {
    id: 'risk-69',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad ska du göra om en passagerare inte vill ta på sig bilbältet?',
    options: ['Köra ändå', 'Vägra att köra tills alla har bälte på sig', 'Köra långsamt istället'],
    correctIndex: 1,
    explanation: 'Föraren ansvarar för att passagerare under 15 år bär bälte. Vuxna bär eget ansvar men en obältad passagerare blir en projektil vid krock.',
  },
  {
    id: 'risk-70',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad innebär "comfort zone"-effekten vid daglig pendling?',
    options: ['Att bilen blir bekvämare', 'Att man blir för van vid sträckan och tappar uppmärksamhet', 'Att man kör i rätt temperatur'],
    correctIndex: 1,
    explanation: 'Rutinkörning leder till att hjärnan går på "autopilot" — man slutar aktivt scanna efter faror på välkända sträckor.',
  },
  {
    id: 'risk-71',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad ska du göra om du kör och det blir kraftig dimma?',
    options: ['Sätt på helljus', 'Sänk hastigheten, tänd halvljus/dimljus och öka avståndet', 'Kör i samma hastighet med varningsblinkers'],
    correctIndex: 1,
    explanation: 'Vid dimma ska du sänka hastigheten, använda halvljus (inte helljus) och öka avståndet till framförvarande.',
  },
  {
    id: 'risk-72',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du tänka på vid körning i stadstrafik med många parkerade bilar?',
    options: ['Köra snabbt förbi', 'Var beredd på att bildörrar kan öppnas och barn kan springa ut', 'Parkerade bilar är inget problem'],
    correctIndex: 1,
    explanation: 'Bakom parkerade bilar kan barn springa ut och dörrar kan öppnas plötsligt. Håll avstånd och sänk farten.',
  },
  {
    id: 'risk-73',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Hur lång är den totala stoppsträckan vid 110 km/h på torr väg med normal reaktionstid?',
    options: ['Cirka 60 meter', 'Cirka 100 meter', 'Cirka 150 meter'],
    correctIndex: 1,
    explanation: 'Vid 110 km/h: reaktionssträcka ca 30 m + bromssträcka ca 70 m = total stoppsträcka ca 100 meter på torr väg.',
  },
  {
    id: 'risk-74',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Varför är korsningar de farligaste platserna i trafiken?',
    options: ['Vägen är sämre där', 'Många trafikanter möts och korsar varandras väg', 'Korsningar är alltid dåligt upplysta'],
    correctIndex: 1,
    explanation: 'I korsningar möts och korsar bilar, cyklister och fotgängare varandras vägar, vilket skapar konfliktsituationer.',
  },
  {
    id: 'risk-75',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför ska lösa föremål i bilen säkras?',
    options: ['De kan skramla', 'De blir farliga projektiler vid en krock', 'De tar plats'],
    correctIndex: 1,
    explanation: 'Vid en kollision fortsätter lösa föremål framåt med samma hastighet som bilen. En laptop eller väska kan orsaka allvarliga skador.',
  },
  {
    id: 'risk-76',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du göra om bilen framför dig plötsligt svänger ut åt sidan?',
    options: ['Köra om snabbt', 'Bromsa — det kan finnas ett hinder du inte ser', 'Följa efter'],
    correctIndex: 1,
    explanation: 'Om bilen framför dig plötsligt svänger kan det finnas ett hinder (fotgängare, djur, hinder) du inte ser. Bromsa och var beredd.',
  },
  {
    id: 'risk-77',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är den vanligaste orsaken till dödsolyckor bland unga förare (18-24 år)?',
    options: ['Tekniska fel', 'Hög hastighet i kombination med oerfarenhet', 'Dålig vägbeläggning'],
    correctIndex: 1,
    explanation: 'Unga förare har högst olycksrisk. Kombinationen av höga hastigheter, bristande erfarenhet och riskbenägenhet är huvudorsaken.',
  },
  {
    id: 'risk-78',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad gäller för telefonisamtal med handsfree under körning?',
    options: ['Det är helt säkert', 'Det är tillåtet men samtalet tar ändå uppmärksamhet', 'Det är förbjudet'],
    correctIndex: 1,
    explanation: 'Handsfree är tillåtet men samtalet tar mental uppmärksamhet från trafiken. Undvik långa eller komplicerade samtal.',
  },
  {
    id: 'risk-79',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad innebär "karuselleffekten" vid alkoholpåverkan?',
    options: ['Att man kör i cirklar', 'Att balans och rumsuppfattning störs kraftigt', 'Att bilen roterar'],
    correctIndex: 1,
    explanation: 'Alkohol påverkar innerörat och balanssinnet, vilket gör att rummet kan upplevas snurra — särskilt farligt vid körning.',
  },
  {
    id: 'risk-80',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är "scanning" som körteknik?',
    options: ['Att skanna biljetten', 'Att systematiskt flytta blicken för att övervaka hela trafikmiljön', 'Att använda radar'],
    correctIndex: 1,
    explanation: 'Scanning innebär att regelbundet flytta blicken mellan speglar, långt fram, nära fram och sidor för total situationsuppfattning.',
  },
  {
    id: 'risk-81',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför ska du inte parkera i en nedförsbacke utan att dra handbromsen?',
    options: ['Bilen kan blekna', 'Bilen kan börja rulla', 'Det sliter på däcken'],
    correctIndex: 1,
    explanation: 'Utan handbroms och med automatväxel i P (eller manuell i växel) kan bilen rulla iväg i en backe.',
  },
  {
    id: 'risk-82',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad är den vanligaste skadan vid påkörning bakifrån?',
    options: ['Benbrott', 'Whiplash (pisksnärtskada)', 'Hjärnskakning'],
    correctIndex: 1,
    explanation: 'Whiplash är den vanligaste skadan vid påkörning bakifrån. Nackstödet ska vara rätt inställt för att minska risken.',
  },
  {
    id: 'risk-83',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Varför ökar olycksrisken kraftigt vid hastigheter över 80 km/h på landsväg?',
    options: ['Bilen förbrukar mer bränsle', 'Reaktionstiden räcker inte, sikten begränsas och krockenergin ökar dramatiskt', 'Vägarna är sämre vid hög hastighet'],
    correctIndex: 1,
    explanation: 'Över 80 km/h hinner du inte reagera och stoppa i tid vid oväntade händelser, och krockenergin växer kvadratiskt med hastigheten.',
  },
  {
    id: 'risk-84',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du göra om din passagerare plötsligt mår illa och du behöver stanna snabbt?',
    options: ['Bromsa tvärt i körfältet', 'Blinka höger, sakta ner och sväng av på en säker plats', 'Öppna fönstret och fortsätt köra'],
    correctIndex: 1,
    explanation: 'Stanna inte plötsligt i trafiken. Blinka, sakta ner och hitta en säker plats att stanna på.',
  },
  {
    id: 'risk-85',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför ska du inte lägga fötterna på instrumentbrädan som passagerare?',
    options: ['Det är oartigt', 'Krockkudden kan orsaka livshotande skador om den utlöses', 'Det smutsar ner'],
    correctIndex: 1,
    explanation: 'Om krockkudden utlöses med fötterna uppe slungas benen uppåt med enorm kraft. Det kan leda till livshotande skador.',
  },
  {
    id: 'risk-86',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad menas med "SMOG"-principen vid filbyte?',
    options: ['Miljöpåverkan vid körning', 'Spegel-Medtrafikanter-Om-Gör (systematisk kontroll vid manöver)', 'Signal-Motor-Oil-Gas'],
    correctIndex: 1,
    explanation: 'SMOG står för Spegel-Medtrafikanter-Om (bedöm)-Gör (genomför). En metod för säkra filbyten och manövrer.',
  },
  {
    id: 'risk-87',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du göra om du hör ett konstigt ljud från bilen under körning?',
    options: ['Ignorera det', 'Stanna säkert och undersök', 'Höj musiken'],
    correctIndex: 1,
    explanation: 'Ovanliga ljud kan tyda på tekniska problem. Stanna på en säker plats och undersök eller kontakta verkstad.',
  },
  {
    id: 'risk-88',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Hur bör du sitta i förarstolen för bäst säkerhet?',
    options: ['Så nära ratten som möjligt', 'Upprätt med lagom avstånd till ratten och krockkudden', 'Lutad bakåt'],
    correctIndex: 1,
    explanation: 'Rätt sittposition: upprätt, minst 25 cm till krockkudden, bälte tätt och nackstöd i rätt höjd.',
  },
  {
    id: 'risk-89',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Hur mycket längre blir stoppsträckan vid 50 km/h på isig väg jämfört med torr asfalt?',
    options: ['Dubbelt så lång', 'Ungefär 5-10 gånger längre', 'Lika lång'],
    correctIndex: 1,
    explanation: 'På is kan friktionen vara bara en tiondel av torr asfalt, vilket gör bromssträckan 5-10 gånger längre.',
  },
  {
    id: 'risk-90',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Varför är det farligt att tailgata (ligga tätt bakom) lastbilar?',
    options: ['Lastbilar kör långsamt', 'Du ser inte vägen framför lastbilen och hinner inte reagera vid plötsligt stopp', 'Avgaserna är farliga'],
    correctIndex: 1,
    explanation: 'Bakom en lastbil ser du inget av trafiken framför. Om lastbilen bromsar tvärt har du ingen chans att reagera i tid.',
  },
  {
    id: 'risk-91',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad ska du kontrollera innan du börjar köra?',
    options: ['Bara att du har nyckeln', 'Speglar, bälte, sittposition och att sikten är fri', 'Bara bränslet'],
    correctIndex: 1,
    explanation: 'Innan körning: justera speglar och sits, spänn bälte, kontrollera att vindrutor och speglar är rena.',
  },
  {
    id: 'risk-92',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad menas med "smitteffekt" i trafiken?',
    options: ['Att bilar sprider sjukdomar', 'Att man anpassar sin hastighet och beteende efter andra trafikanter', 'Att bilen rostar'],
    correctIndex: 1,
    explanation: 'Smitteffekt innebär att man omedvetet anpassar sitt beteende efter andra — kör andra fort gör du det också.',
  },
  {
    id: 'risk-93',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är "IPOAT-modellen" i riskhantering?',
    options: ['En bilmodell', 'Information-Perception-Omgivning-Aktion-Tilltro (modell för beslutsfattande i trafik)', 'Ingen officiell modell'],
    correctIndex: 1,
    explanation: 'IPOAT beskriver processen: inhämta information, uppfatta den rätt, bedöma omgivningen, välja aktion och ha tilltro till beslutet.',
  },
  {
    id: 'risk-94',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad bör du göra vid kraftig åska under körning?',
    options: ['Stanna under ett träd', 'Stanna bilen säkert — bilen fungerar som en Faradaybur som skyddar', 'Köra fortare'],
    correctIndex: 1,
    explanation: 'Bilen är en bra skyddad plats vid åska. Stanna säkert, rör inte metalldelar och vänta ut åskan.',
  },
  {
    id: 'risk-95',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad är "black ice" (svartis)?',
    options: ['Svartfärgad is på sjöar', 'Tunn is på vägen som är nästan osynlig', 'Is i motorblocket'],
    correctIndex: 1,
    explanation: 'Svartis är ett tunt lager is som ser ut som fuktig asfalt. Extremt halt och svårt att upptäcka.',
  },
  {
    id: 'risk-96',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad innebär "fading" av bromsarna?',
    options: ['Att bromsljusen slocknar', 'Att bromsarna överhettas och tappar effekt', 'Att bromsvätska läcker'],
    correctIndex: 1,
    explanation: 'Fading uppstår vid långvarig bromsning (t.ex. i långa nedförsbackar) — bromsarna överhettas och tappar bromskraft.',
  },
  {
    id: 'risk-97',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du göra för att undvika fading i en lång nedförsbacke?',
    options: ['Bromsa hela tiden', 'Växla ner och utnyttja motorbromsning', 'Stäng av motorn'],
    correctIndex: 1,
    explanation: 'Genom att växla ner och utnyttja motorbromsen avlastar du hjulbromsarna och undviker överhettning.',
  },
  {
    id: 'risk-98',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad händer om du kör över en stor vattenpöl i hög hastighet?',
    options: ['Inget farligt', 'Risk för vattenplaning — däcken tappar kontakt med vägen', 'Bilen stannar'],
    correctIndex: 1,
    explanation: 'Vid vattenplaning bildas ett vattenfilter mellan däck och vägbana. Du tappar grepp och styrförmåga.',
  },
  {
    id: 'risk-99',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vilken är den statistiskt farligaste manövern på motorväg?',
    options: ['Att köra rakt fram', 'Filbyte och omkörning', 'Att köra i höger fil'],
    correctIndex: 1,
    explanation: 'Filbyten och omkörningar på motorväg är de farligaste manövrarna — dödvinklar och hastighetsskillnader skapar risker.',
  },
  {
    id: 'risk-100',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Varför ska du inte stanna omedelbart efter en kurva om du fått problem?',
    options: ['Det är inte vackert', 'Andra trafikanter ser dig sent och kan inte hinna stanna', 'Marken är ojämn i kurvor'],
    correctIndex: 1,
    explanation: 'Strax efter en kurva har bakomvarande trafik begränsad sikt. Kör vidare till en raksträcka om möjligt.',
  },
  {
    id: 'risk-101',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför är det viktigt att ha rätt lufttryck i däcken?',
    options: ['Bara för komfort', 'Fel tryck påverkar grepp, bromssträcka och bränsleförbrukning', 'Det spelar ingen roll'],
    correctIndex: 1,
    explanation: 'Felaktigt däcktryck ger sämre grepp, längre bromssträcka, ojämnt slitage och ökad bränsleförbrukning.',
  },
  {
    id: 'risk-102',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du göra om du kör i en lång tunnel och det börjar brinna i bilen framför?',
    options: ['Köra om den brinnande bilen', 'Stanna, stäng av motorn, lämna bilen och gå mot närmaste nödutgång', 'Backa ut ur tunneln'],
    correctIndex: 1,
    explanation: 'Vid brand i tunnel: stanna, stäng av motorn, lämna bilen olåst med nyckeln kvar och gå mot nödutgång.',
  },
  {
    id: 'risk-103',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är "saccader" och hur påverkar de körning?',
    options: ['Typen av bränsle', 'Ögonrörelser som gör att vi är blinda under en bråkdel av en sekund vid blickförflyttning', 'En typ av däck'],
    correctIndex: 1,
    explanation: 'Saccader är snabba ögonrörelser. Under dessa korta stunder bearbetar hjärnan ingen visuell information — vi är tillfälligt blinda.',
  },
  {
    id: 'risk-104',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför ska du aldrig backa på en motorväg?',
    options: ['Det sliter på växellådan', 'Det är extremt farligt — andra fordon kör i hög hastighet', 'Det är bara förbjudet på natten'],
    correctIndex: 1,
    explanation: 'Backning på motorväg är livsfarligt och förbjudet. Andra fordon kör i hög hastighet och förväntar sig inte backande fordon.',
  },
  {
    id: 'risk-105',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Hur påverkas bromssträckan om du har slitna däck?',
    options: ['Ingen skillnad', 'Bromssträckan ökar avsevärt, särskilt på våt väg', 'Bromssträckan minskar'],
    correctIndex: 1,
    explanation: 'Slitna däck har sämre vattenavledning och grepp, vilket förlänger bromssträckan markant — särskilt på vått underlag.',
  },
  {
    id: 'risk-106',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad innebär "the Smith System" för defensiv körning?',
    options: ['En bilförsäkring', 'Fem principer: titta långt fram, se helheten, flytta blicken, ha flyktväg, bli sedd', 'En motortyp'],
    correctIndex: 1,
    explanation: 'Smith System: 1) Titta långt framåt 2) Se hela bilden 3) Flytta blicken 4) Ha alltid en flyktväg 5) Se till att bli sedd.',
  },
  {
    id: 'risk-107',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad bör du göra om du ser en olycka har hänt men hjälp redan kommit fram?',
    options: ['Stanna och titta', 'Köra förbi försiktigt utan att stanna — undvik att blockera räddningsarbete', 'Ta foton'],
    correctIndex: 1,
    explanation: 'Om hjälp redan finns på plats, kör försiktigt förbi utan att stanna. Att stanna skapar bara mer trafikproblem.',
  },
  {
    id: 'risk-108',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Varför ökar olycksrisken under de första 15 minuterna av körning?',
    options: ['Motorn är inte varm', 'Föraren har inte hunnit anpassa sig till trafikmiljön ännu', 'Däcken är kalla'],
    correctIndex: 1,
    explanation: 'Det tar en stund för föraren att komma in i körläge och anpassa sig till trafiksituationen.',
  },
  {
    id: 'risk-109',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är "inattentional blindness" (ouppmärksamhetsblindhet)?',
    options: ['Att man inte kan se i mörker', 'Att man missar uppenbara saker för att uppmärksamheten är på annat', 'Att man är färgblind'],
    correctIndex: 1,
    explanation: 'Ouppmärksamhetsblindhet innebär att du kan titta rakt på något men inte se det för att din uppmärksamhet är fokuserad på annat.',
  },
  {
    id: 'risk-110',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför ska du inte följa en GPS-instruktion blint om den säger att du ska svänga?',
    options: ['GPS är alltid fel', 'Du måste fortfarande följa trafikregler och använda eget omdöme', 'GPS fungerar bara i stadstrafik'],
    correctIndex: 1,
    explanation: 'GPS kan ge felaktiga eller farliga instruktioner. Följ alltid trafikregler och använd ditt eget omdöme.',
  },
  {
    id: 'risk-111',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du göra om du hamnar i vattenplaning?',
    options: ['Bromsa hårt', 'Släpp gasen försiktigt och håll ratten rakt — bromsa inte', 'Öka hastigheten'],
    correctIndex: 1,
    explanation: 'Vid vattenplaning: släpp gasen, håll ratten rakt och styr inte kraftigt. Bromsa inte — det förvärrar situationen.',
  },
  {
    id: 'risk-112',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Hur mycket ökar olycksrisken om du tittar på mobilen i 5 sekunder i 90 km/h?',
    options: ['Du kör 50 meter blind', 'Du kör 125 meter blind', 'Du kör 25 meter blind'],
    correctIndex: 1,
    explanation: '90 km/h = 25 m/s. Tittar du ner 5 sekunder kör du 125 meter utan att se vägen — som att köra en hel fotbollsplan med ögonen slutna.',
  },
  {
    id: 'risk-113',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad gäller om du orsakat en trafikolycka med enbart materiella skador?',
    options: ['Du kan köra därifrån', 'Du måste stanna, byta uppgifter med den andra parten eller anmäla till polis', 'Ring bara försäkringsbolaget'],
    correctIndex: 1,
    explanation: 'Vid materiella skador ska du stanna och byta kontaktuppgifter. Om motparten inte är tillgänglig, kontakta polis.',
  },
  {
    id: 'risk-114',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad är den vanligaste orsaken till singelolyckor?',
    options: ['Dåliga vägar', 'Hög hastighet och trötthet', 'Dåliga bilar'],
    correctIndex: 1,
    explanation: 'Singelolyckor orsakas oftast av hög hastighet, trötthet eller bristande uppmärksamhet — inte yttre faktorer.',
  },
  {
    id: 'risk-115',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är "change blindness" och hur kan det orsaka olyckor?',
    options: ['Att man inte ser färgskillnader', 'Att man missar förändringar i trafikmiljön om de sker gradvis', 'Att man bländas av ljus'],
    correctIndex: 1,
    explanation: 'Change blindness innebär att man inte uppmärksammar förändringar som sker gradvis — t.ex. en bil som sakta byter fil mot dig.',
  },
  {
    id: 'risk-116',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad ska du göra om du ser ett fordon som kör i fel riktning på en motorväg?',
    options: ['Blinka med ljusen', 'Kör åt sidan, stanna om möjligt och ring 112', 'Försök stoppa fordonet'],
    correctIndex: 1,
    explanation: 'Flytta dig undan, stanna säkert och ring 112 omedelbart. Försök aldrig stoppa fordonet själv.',
  },
  {
    id: 'risk-117',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför ska barn under 135 cm alltid sitta i godkänd barnstol?',
    options: ['Det är bara en rekommendation', 'Bilbältet passar inte och kan orsaka skador utan barnstol', 'Barnet sitter bekvämare'],
    correctIndex: 1,
    explanation: 'Bilbältet är designat för vuxna. Utan barnstol kan bältet hamna fel och orsaka allvarliga skador vid krock.',
  },
  {
    id: 'risk-118',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad innebär "SIPDE"-metoden?',
    options: ['En motortyp', 'Search-Identify-Predict-Decide-Execute — en metod för trafikbedömning', 'En typ av bilförsäkring'],
    correctIndex: 1,
    explanation: 'SIPDE: Sök-Identifiera-Förutsäg-Bestäm-Genomför. En systematisk metod för att hantera trafiksituationer.',
  },
  {
    id: 'risk-119',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Varför ska du aldrig använda farthållare på hal väg?',
    options: ['Det sliter på motorn', 'Farthållaren kan ge gas just när hjulen tappar grepp, vilket förvärrar sladden', 'Det är bara farligt på motorväg'],
    correctIndex: 1,
    explanation: 'På hal väg kan farthållaren ge gas vid felaktigt tillfälle, orsaka hjulspinn och sladd. Stäng av den vid dåligt väglag.',
  },
  {
    id: 'risk-120',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Hur mycket ökar bränsleförbrukningen om du ökar hastigheten från 90 till 110 km/h?',
    options: ['Cirka 5%', 'Cirka 20-30%', 'Ingen skillnad'],
    correctIndex: 1,
    explanation: 'Luftmotståndet ökar kraftigt med hastigheten. 90→110 km/h kan öka bränsleförbrukningen med 20-30%.',
  },
  {
    id: 'risk-121',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad ska du göra om du ser att en medtrafikant kör konstigt (vinglar, kör oregelbundet)?',
    options: ['Köra om snabbt', 'Hålla avstånd och eventuellt ringa polisen', 'Tuta och vinka'],
    correctIndex: 1,
    explanation: 'Föraren kan vara sjuk, trött eller påverkad. Håll avstånd och ring polisen om du misstänker fara.',
  },
  {
    id: 'risk-122',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Varför har bakhjulsdrivna bilar större tendens att överstyrning (sladd med bakänden)?',
    options: ['De är tyngre bak', 'Drivkraften på bakhjulen kan bryta lös dem i kurvor', 'De har sämre bromsar'],
    correctIndex: 1,
    explanation: 'Bakhjulsdrift kan orsaka att bakhjulen förlorar grepp i kurvor eller vid gasning, vilket leder till överstyrning.',
  },
  {
    id: 'risk-123',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad är varningstriangeln till för?',
    options: ['Att markera din parkeringsplats', 'Att varna annan trafik om att det finns ett stillastående fordon/hinder', 'Att lysa upp vägen'],
    correctIndex: 1,
    explanation: 'Varningstriangeln ska placeras bakom ditt fordon för att varna andra trafikanter om hindret.',
  },
  {
    id: 'risk-124',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad menas med "olyckskvot" och varför är den viktig?',
    options: ['Antal olyckor per driven mil', 'Antal olyckor per 100 miljoner fordonskilometer — används för att jämföra vägsäkerhet', 'Antal bilar per olycka'],
    correctIndex: 1,
    explanation: 'Olyckskvoten mäter antal olyckor i relation till körsträcka och används för att bedöma hur farliga olika vägar är.',
  },
  {
    id: 'risk-125',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför bör du undvika att köra om i närheten av en vägkorsning?',
    options: ['Det tar för lång tid', 'Fordon kan plötsligt svänga in på din väg', 'Korsningar har sämre asfalt'],
    correctIndex: 1,
    explanation: 'Vid korsningar kan fordon svänga ut eller byta fil oväntat. Omkörning nära korsningar är riskfyllt.',
  },
  {
    id: 'risk-126',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad ska du tänka på vid körning i kolonnkörning (följer en rad bilar)?',
    options: ['Håll samma avstånd som bilen framför', 'Se till att du kan se förbi bilen framför dig och håll eget säkerhetsavstånd', 'Kör så nära som möjligt'],
    correctIndex: 1,
    explanation: 'I kolonn behöver du se förbi bilen framför för att reagera i tid. Håll eget säkerhetsavstånd.',
  },
  {
    id: 'risk-127',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är "overconfidence bias" bland erfarna förare?',
    options: ['Att man köper för dyr bil', 'Att erfarenhet ger falsk trygghet och minskad uppmärksamhet', 'Att man kör för långsamt'],
    correctIndex: 1,
    explanation: 'Erfarna förare kan bli övermodiga och ta risker de inte borde. Erfarenhet kompenserar inte allt.',
  },
  {
    id: 'risk-128',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Varför är det extra farligt att köra i skymning?',
    options: ['Bilens ljus fungerar sämre', 'Ögonen hinner inte anpassa sig till det skiftande ljuset', 'Vägen blir hal'],
    correctIndex: 1,
    explanation: 'I skymning har ögonen svårt att anpassa sig. Sikten är dålig trots att det inte är helt mörkt.',
  },
  {
    id: 'risk-129',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad bör du göra om du kör vilse?',
    options: ['Stanna plötsligt och kolla kartan', 'Kör vidare lugnt och stanna på en säker plats för att orientera dig', 'Ring och fråga någon'],
    correctIndex: 1,
    explanation: 'Stanna aldrig plötsligt i trafiken. Kör lugnt vidare tills du hittar en säker plats att stanna på.',
  },
  {
    id: 'risk-130',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad händer med en kropp som väger 80 kg vid en frontalkollision i 50 km/h utan bälte?',
    options: ['Den väger fortfarande 80 kg', 'Den utsätts för en kraft motsvarande 2-3 ton', 'Den bör klara sig utan skador'],
    correctIndex: 1,
    explanation: 'Vid 50 km/h utsätts en obältad kropp för en kraft motsvarande 20-30 gånger kroppsvikten, dvs. 1600-2400 kg.',
  },
  {
    id: 'risk-131',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du göra om du märker att du sakta glider in mot vägkanten vid monoton motorvägskörning?',
    options: ['Sväng tillbaka snabbt', 'Ta en rast så snart som möjligt — du visar tecken på trötthet', 'Stäng av musiken'],
    correctIndex: 1,
    explanation: 'Att glida ur fil är ett allvarligt tecken på trötthet eller bristande uppmärksamhet. Ta en paus snarast.',
  },
  {
    id: 'risk-132',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför ska du inte stanna ratten i "12-position" (händer högst upp)?',
    options: ['Det ser konstigt ut', 'Vid krockkuddeutlösning kan händerna slungas in i ansiktet', 'Det är obekvämt'],
    correctIndex: 1,
    explanation: 'Om krockkudden utlöses med händerna vid 12 kan de kastas tillbaka med kraft och skada ansiktet.',
  },
  {
    id: 'risk-133',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Varför är "rusningstrafik" statistiskt säkrare per fordon än glesare trafik?',
    options: ['Fler poliser ute', 'Lägre hastigheter — olyckorna blir lindrigare trots fler fordon', 'Bättre belysning i rusningstid'],
    correctIndex: 1,
    explanation: 'I rusning tvingas folk köra långsammare, vilket minskar skadornas allvarlighetsgrad per olycka.',
  },
  {
    id: 'risk-134',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad bör du göra om en hjort springer ut på vägen framför dig?',
    options: ['Sväng undan', 'Bromsa kontrollerat och försök stanna — undvik kraftig undanmanöver', 'Tuta högt'],
    correctIndex: 1,
    explanation: 'Undvik kraftig undanmanöver — du riskerar att krocka med mötande trafik eller köra av vägen. Bromsa kontrollerat.',
  },
  {
    id: 'risk-135',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad ska du göra efter en viltolycka?',
    options: ['Flytta djuret från vägen', 'Varna andra trafikanter, markera platsen och ring polis', 'Köra vidare'],
    correctIndex: 1,
    explanation: 'Vid viltolycka: varna andra, markera platsen där djuret sprang in i skogen, ring polis. Närma dig inte ett skadat djur.',
  },
  {
    id: 'risk-136',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad innebär "Nollvisionen" i svensk trafikpolitik?',
    options: ['Noll bilar på vägarna', 'Att ingen ska dödas eller skadas allvarligt i trafiken', 'Nollutsläpp från bilar'],
    correctIndex: 1,
    explanation: 'Nollvisionen antogs 1997 och innebär att det långsiktiga målet är att ingen ska omkomma eller skadas allvarligt i trafiken.',
  },
  {
    id: 'risk-137',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är den viktigaste faktorn i "Safe System"-ansatsen?',
    options: ['Bättre bilar', 'Att systemet ska vara utformat så att mänskliga misstag inte leder till döden', 'Fler trafikpoliser'],
    correctIndex: 1,
    explanation: 'Safe System-ansatsen accepterar att människor gör misstag och designar vägsystemet så att misstagen inte blir dödliga.',
  },
  {
    id: 'risk-138',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad ska du göra om bilens motor plötsligt stannar på en trafikerad väg?',
    options: ['Lämna bilen direkt', 'Sätt på varningsblinkers, försök styra åt sidan och stanna säkert', 'Försök starta om genast'],
    correctIndex: 1,
    explanation: 'Motorstopp: slå på varningsblinkers, utnyttja farten för att styra åt sidan, broms och ratt fungerar fortfarande men kräver mer kraft.',
  },
  {
    id: 'risk-139',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad är det viktigaste att tänka på vid körning i regn efter en lång torrperiod?',
    options: ['Att vindrutan blir smutsig', 'Vägen är extra hal de första minuterna — olja och damm blandas med vatten', 'Att torkarna fungerar'],
    correctIndex: 1,
    explanation: 'Efter lång torrperiod ligger olja och damm på vägbanan. Blandas det med vatten blir vägen extremt hal.',
  },
  {
    id: 'risk-140',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Hur påverkar mediciner mot allergi (antihistaminer) körförmågan?',
    options: ['Inte alls', 'Vissa typer kan orsaka dåsighet och nedsatt reaktionsförmåga', 'De förbättrar koncentrationen'],
    correctIndex: 1,
    explanation: 'Äldre typer av antihistaminer kan orsaka dåsighet. Läs alltid bipacksedeln och kontrollera om medicinen påverkar körförmågan.',
  },
  {
    id: 'risk-141',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Varför bör du inte köra med bara parkeringsljus i mörker?',
    options: ['Det är lagligt', 'Parkeringsljus ger för dålig belysning för att du ska se och synas ordentligt', 'Det sliter på batteriet'],
    correctIndex: 1,
    explanation: 'Parkeringsljus räcker inte för att se vägen eller bli sedd. Använd halvljus vid all körning i mörker.',
  },
  {
    id: 'risk-142',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Varför ska du anpassa hastigheten vid skolor och lekplatser?',
    options: ['Det finns kameror', 'Barn beter sig oförutsägbart och kan springa ut utan att titta', 'Det är bara en rekommendation'],
    correctIndex: 1,
    explanation: 'Barn saknar trafikvana och kan plötsligt springa ut. Låg hastighet ger dig tid att reagera.',
  },
  {
    id: 'risk-143',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vid 30 km/h överlever ca 90% av fotgängare en påkörning. Vid 50 km/h sjunker det till cirka:',
    options: ['80%', '50%', '70%'],
    correctIndex: 1,
    explanation: 'Vid 50 km/h överlever bara ca 50% av fotgängare en påkörning. Skillnaden mellan 30 och 50 km/h är dramatisk.',
  },
  {
    id: 'risk-144',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad är den bästa metoden för att undvika att bli bländad av mötande bilar nattetid?',
    options: ['Titta rakt på ljusen', 'Titta mot höger vägkant och undvik att stirra in i ljusen', 'Blinka med helljusen'],
    correctIndex: 1,
    explanation: 'Tittar du mot höger vägkant undviker du bländning. Ögonen hinner inte anpassa sig om du tittar rakt in i ljusen.',
  },
  {
    id: 'risk-145',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad ska du göra om du kör och det börjar hagla kraftigt?',
    options: ['Köra snabbare för att komma igenom', 'Sakta ner, sätta på varningsblinkers och stanna säkert om sikten försvinner', 'Stanna mitt på vägen'],
    correctIndex: 1,
    explanation: 'Kraftigt hagel kan förstöra sikten helt. Sakta ner, slå på varningsblinkers och stanna säkert vid sidan.',
  },
  {
    id: 'risk-146',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad är "target fixation" vid en nödsituation?',
    options: ['Att man fixerar blicken på hindret man vill undvika — och kör rakt in i det', 'Att man fokuserar på målet', 'Att GPS visar fel'],
    correctIndex: 0,
    explanation: 'Target fixation innebär att man omedvetet styr mot det man tittar på. Titta istället dit du vill styra.',
  },
  {
    id: 'risk-147',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Hur bör du hantera en lastbil som kör om dig på motorvägen?',
    options: ['Öka farten', 'Håll jämn fart och var beredd på tryckskillnader/drag', 'Bromsa tvärt'],
    correctIndex: 1,
    explanation: 'När en lastbil passerar kan det uppstå lufttrycksförändringar och drag. Håll stadigt i ratten och kör jämnt.',
  },
  {
    id: 'risk-148',
    category: 'riskbeteende',
    difficulty: 'easy',
    question: 'Vad ska du göra om passagerarna bråkar eller är högljudda under körning?',
    options: ['Ignorera det', 'Be dem lugna sig — distraktioner ökar olycksrisken', 'Kör fortare för att komma fram snabbt'],
    correctIndex: 1,
    explanation: 'Bråkiga passagerare är en allvarlig distraktion. Be dem lugna sig eller stanna och ta hand om situationen.',
  },
  {
    id: 'risk-149',
    category: 'riskbeteende',
    difficulty: 'hard',
    question: 'Vad innebär "Yerkes-Dodsons lag" för körning?',
    options: ['En trafiklag', 'Optimal prestation kräver lagom stressnivå — för lite eller för mycket stress försämrar körningen', 'En lag om hastighet'],
    correctIndex: 1,
    explanation: 'Yerkes-Dodson: en viss stressnivå (alerthet) förbättrar prestationen, men för mycket eller för lite stress gör dig till en sämre förare.',
  },
  {
    id: 'risk-150',
    category: 'riskbeteende',
    difficulty: 'medium',
    question: 'Vad ska du göra om du plötsligt kör in i en rökridå (t.ex. från bränder vid sidan av vägen)?',
    options: ['Bromsa tvärt', 'Sänk hastigheten, tänd halvljus/dimljus och kör försiktigt igenom', 'Kör snabbt igenom'],
    correctIndex: 1,
    explanation: 'I en rökridå kan sikten försvinna helt. Sänk hastigheten, tänd ljus och kör försiktigt. Stanna inte mitt i röken.',
  },
];
