import { Question } from './types';

export const vagmarkeringarQuestions: Question[] = [
  {
    id: 'vmk-1',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad betyder en heldragen mittlinje på vägen?',
    options: [
      'Förbud mot att köra om genom att passera linjen',
      'Rekommenderad körbana',
      'Att hastigheten är begränsad',
    ],
    correctIndex: 0,
    explanation: 'En heldragen mittlinje (spärrlinje) får inte passeras eller köras på. Det innebär förbud mot omkörning genom att korsa linjen.',
  },
  {
    id: 'vmk-2',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad betyder en streckad mittlinje?',
    options: [
      'Omkörning är tillåten om det kan ske säkert',
      'Omkörning är förbjuden',
      'Vägen är enkelriktad',
    ],
    correctIndex: 0,
    explanation: 'En streckad mittlinje innebär att man får korsa linjen för omkörning, förutsatt att det kan göras utan fara.',
  },
  {
    id: 'vmk-3',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Det finns en heldragen linje på din sida och en streckad på motstående sida. Får du köra om?',
    options: [
      'Nej, den heldragna linjen på din sida gäller för dig',
      'Ja, den streckade linjen gäller alltid',
      'Ja, om hastigheten är under 50 km/h',
    ],
    correctIndex: 0,
    explanation: 'Det är linjen närmast dig som gäller. En heldragen linje på din sida betyder att du inte får korsa den, oavsett vad som finns på motstående sida.',
  },
  {
    id: 'vmk-4',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar gula linjer i vägkanten?',
    options: [
      'Förbud mot att stanna eller parkera',
      'Busshållplats',
      'Cykelbana',
    ],
    correctIndex: 0,
    explanation: 'Gula kantlinjer anger att stannande och/eller parkering är förbjuden. Heldragen gul linje = förbud mot stannande. Streckad gul linje = förbud mot parkering.',
  },
  {
    id: 'vmk-5',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad anger vita sicksacklinjer i vägkanten?',
    options: [
      'Förbud mot att stanna och parkera vid busshållplats',
      'Övergångsställe för cyklister',
      'Hastighetsbegränsning',
    ],
    correctIndex: 0,
    explanation: 'Vita sicksacklinjer markerar en busshållplats och innebär att det är förbjudet att stanna eller parkera på det markerade området.',
  },
  {
    id: 'vmk-6',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad betyder ett målat övergångsställe (zebraränder)?',
    options: [
      'Fotgängare har företräde att korsa vägen',
      'Cyklister har företräde',
      'Genomfart förbjuden',
    ],
    correctIndex: 0,
    explanation: 'Breda vita ränder tvärs över vägen markerar ett övergångsställe där fotgängare har företräde. Förare måste stanna och släppa fram fotgängare.',
  },
  {
    id: 'vmk-7',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad betyder en bred heldragen linje tvärs över körbanan vid en korsning?',
    options: [
      'Stopplinje — du måste stanna helt innan du fortsätter',
      'Hastighetsbegränsning',
      'Cykelfält börjar',
    ],
    correctIndex: 0,
    explanation: 'En stopplinje visar var du ska stanna vid en korsning med stoppskylt eller rött trafikljus. Du måste stanna helt med framhjulen bakom linjen.',
  },
  {
    id: 'vmk-8',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad betyder trianglar (hajtänder) målade på vägen?',
    options: [
      'Väjningsplikt — du måste lämna företräde',
      'Varning för ojämn väg',
      'Farthinder',
    ],
    correctIndex: 0,
    explanation: 'Trianglar (hajtänder) på vägen markerar väjningsplikt. Du måste sakta ner och lämna företräde åt trafik på den korsande vägen.',
  },
  {
    id: 'vmk-9',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad innebär en spärrlinje med dubbelheldragna linjer?',
    options: [
      'Ingen trafik får passera linjen oavsett riktning',
      'Bara bussar får passera',
      'Bara vid nödsituationer',
    ],
    correctIndex: 0,
    explanation: 'Dubbelheldragna linjer innebär total spärr — ingen trafik i någon riktning får korsa dem. Detta används på vägar med hög trafikintensitet.',
  },
  {
    id: 'vmk-10',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'En cykelpassage markeras med vita rutor (fyrkanter) på vägen. Vilken skyldighet har bilföraren?',
    options: [
      'Anpassa hastigheten så att det inte uppstår fara för cyklister',
      'Alltid stanna och ge cyklister företräde',
      'Cyklisterna måste ge bilisten företräde',
    ],
    correctIndex: 0,
    explanation: 'Vid cykelpassage (vita rutor) ska bilföraren anpassa hastigheten och visa hänsyn till cyklister. Cyklister har dock inte automatisk företräde som vid övergångsställe — men föraren måste visa aktsamhet.',
  },
  {
    id: 'vmk-11',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar en målad pil i körfältet?',
    options: [
      'Vilken riktning du ska eller får köra i det körfältet',
      'Att hastigheten ska ökas',
      'Att vägen snart tar slut',
    ],
    correctIndex: 0,
    explanation: 'Pilar i körfältet visar vilken körriktning som gäller. Du måste följa pilen och välja rätt körfält i god tid.',
  },
  {
    id: 'vmk-12',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad anger en streckad kantlinje (vit, längs vägen)?',
    options: [
      'Vägbanans kant — du bör hålla dig innanför linjen',
      'Cykelfält',
      'Parkeringszon',
    ],
    correctIndex: 0,
    explanation: 'En streckad vit kantlinje markerar vägbanans begränsning. Den hjälper föraren att hålla sig på vägen, särskilt i mörker och dålig sikt.',
  },
  {
    id: 'vmk-13',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad innebär en varningslinje (lång streckad linje med korta mellanrum)?',
    options: [
      'Varning — heldragen spärrlinje kommer snart, avsluta ev. omkörning',
      'Att du ska byta fil',
      'Att hastigheten ökar',
    ],
    correctIndex: 0,
    explanation: 'En varningslinje har längre streck och kortare mellanrum än en vanlig streckad linje. Den varnar om att en heldragen linje närmar sig — avsluta omkörning i tid.',
  },
  {
    id: 'vmk-14',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad markerar rutnätsmönster målat på vägen i en korsning?',
    options: [
      'Du får inte stanna i det markerade området',
      'Parkering tillåten',
      'Farthinder',
    ],
    correctIndex: 0,
    explanation: 'Rutnätsmönster (gult eller vitt) i en korsning innebär att du inte får stanna i det området, även om du har grönt ljus. Syftet är att förhindra att korsningen blockeras.',
  },
  {
    id: 'vmk-15',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar texten "BUS" målad på ett körfält?',
    options: [
      'Körfältet är reserverat för bussar',
      'Busshållplats ahead',
      'Buss får inte köra här',
    ],
    correctIndex: 0,
    explanation: 'Texten "BUS" eller "BUSS" på körfältet anger att det är ett bussfält. Andra fordon får normalt inte använda bussfält under de tider det gäller.',
  },
  {
    id: 'vmk-16',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad innebär en bred vit heldragen linje längs vägkanten?',
    options: ['Körbanan slutar', 'Kantlinje — skiljer körbanan från vägrenen', 'Parkering tillåten'],
    correctIndex: 1,
    explanation: 'Kantlinjen markerar vägbanans yttre begränsning och skiljer körbanan från vägrenen.',
  },
  {
    id: 'vmk-17',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar vita pilar på vägen i ett körfält?',
    options: ['Rekommenderad riktning', 'Obligatorisk körriktning i körfältet', 'Parkering'],
    correctIndex: 1,
    explanation: 'Pilar på vägen anger vilken riktning du ska köra i det körfältet.',
  },
  {
    id: 'vmk-18',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad innebär en streckad linje med korta streck och långa mellanrum?',
    options: ['Körfältslinje', 'Du får byta fil', 'Mittlinje — du får köra om'],
    correctIndex: 0,
    explanation: 'Korta streck med långa mellanrum är körfältslinjer som skiljer filer i samma riktning.',
  },
  {
    id: 'vmk-19',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad markerar texten "30" målad på vägbanan?',
    options: ['Hastighetsbegränsning 30 km/h', 'Avstånd 30 meter', '30 meter till nästa korsning'],
    correctIndex: 0,
    explanation: 'Siffror målade på vägbanan anger hastighetsbegränsning och förstärker skyltar.',
  },
  {
    id: 'vmk-20',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad innebär en punktlinje (mycket korta streck, nästan som prickar)?',
    options: ['Körfältslinje', 'Markering vid cirkulationsplats eller korsning', 'Stopplinje'],
    correctIndex: 1,
    explanation: 'Punktlinjer används ofta vid rondellinfarter och korsningar för att visa körfältens fortsättning.',
  },
  {
    id: 'vmk-21',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar zebraränder (vita tvärstreck) på vägen?',
    options: ['Farthinder', 'Övergångsställe', 'Parkeringsplats'],
    correctIndex: 1,
    explanation: 'Zebraränder markerar övergångsställe. Fotgängare har företräde.',
  },
  {
    id: 'vmk-22',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad innebär en dubbel heldragen mittlinje?',
    options: ['Samma som enkel heldragen', 'Extra tydlig spärrlinje — absolut förbjudet att passera', 'Dubbelriktat körfält'],
    correctIndex: 1,
    explanation: 'Dubbel heldragen linje är en spärrlinje som inte får passeras under några omständigheter.',
  },
  {
    id: 'vmk-23',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Du ser en bred streckad linje tvärs över körbanan. Vad innebär det?',
    options: ['Stanna helt', 'Väjningslinje — du har väjningsplikt', 'Hastighetsanpassning'],
    correctIndex: 1,
    explanation: 'En bred streckad tvärslinje (väjningslinje) markerar var du ska vara beredd att stanna för att lämna företräde.',
  },
  {
    id: 'vmk-24',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad anger en vit pil som pekar snett i ett körfält?',
    options: ['Att filen ska sluta — byt fil åt pilens riktning', 'Att du ska svänga', 'Att hastigheten ska öka'],
    correctIndex: 0,
    explanation: 'En snedpil anger att körfältet avsmalnar eller tar slut. Byt fil åt pilens riktning.',
  },
  {
    id: 'vmk-25',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad markerar gula dubbla heldragna linjer i vägkanten?',
    options: ['Kantmarkering', 'Stannande och parkering förbjudet', 'Cykelväg'],
    correctIndex: 1,
    explanation: 'Gula dubbla heldragna kantlinjer anger att stannande och parkering är förbjudet.',
  },
  {
    id: 'vmk-26',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad innebär en accelerationsmarkering (bred streckad linje) vid en motorvägspåfart?',
    options: ['Stopplinje', 'Markering av accelerationsfältets slut', 'Väjningslinje'],
    correctIndex: 1,
    explanation: 'Den breda streckade linjen markerar var accelerationsfältet slutar och du bör ha kommit in i motorvägstrafiken.',
  },
  {
    id: 'vmk-27',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar vita cirklar på vägen vid en korsning?',
    options: ['Ingen speciell markering', 'Platsen för en minirondell', 'Hål i vägen'],
    correctIndex: 1,
    explanation: 'En målad cirkel i en korsning markerar en minirondell. Du ska köra runt den medurs.',
  },
  {
    id: 'vmk-28',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad innebär en varningslinje (långa streck, korta mellanrum)?',
    options: ['Du får inte köra om', 'Varning — heldragen linje kommer snart, förbered dig', 'Hastighetsbegränsning'],
    correctIndex: 1,
    explanation: 'Varningslinjen (långa streck, korta mellanrum) varnar om att en heldragen linje närmar sig — avsluta omkörning.',
  },
  {
    id: 'vmk-29',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad markerar en bred heldragen tvärslinje på vägen?',
    options: ['Väjningslinje', 'Stopplinje — du ska stanna före linjen', 'Farthinder'],
    correctIndex: 1,
    explanation: 'En bred heldragen tvärslinje är en stopplinje. Du ska stanna helt innan du passerar den.',
  },
  {
    id: 'vmk-30',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar en gul streckad kantlinje?',
    options: ['Cykelväg', 'Parkering förbjuden', 'Bussfilsmarkering'],
    correctIndex: 1,
    explanation: 'Gul streckad kantlinje anger att parkering är förbjuden, men kortvarigt stannande kan vara tillåtet.',
  },
  {
    id: 'vmk-31',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad anger rutmönster (rutor) målat i en korsning?',
    options: ['Parkering', 'Spärrområde — du får inte stanna i det markerade området', 'Cykelpassage'],
    correctIndex: 1,
    explanation: 'Rutnätsmönster i korsningar markerar att du inte får stanna inom området — det ska hållas fritt.',
  },
  {
    id: 'vmk-32',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad markerar orangea/gula tillfälliga vägmarkeringar?',
    options: ['Permanenta markeringar', 'Tillfälliga markeringar vid vägarbete — de gäller före vita markeringar', 'Cykelmarkeringar'],
    correctIndex: 1,
    explanation: 'Tillfälliga orangea/gula markeringar vid vägarbete har högre prioritet än permanenta vita markeringar.',
  },
  {
    id: 'vmk-33',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar en bred vit pil med texten "SVÄNG" i ett körfält?',
    options: ['Du måste svänga', 'Rekommenderad sväng', 'Du får inte svänga'],
    correctIndex: 0,
    explanation: 'Pilar med text anger obligatorisk körriktning i det körfältet.',
  },
  {
    id: 'vmk-34',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad markerar reflexstolpar (vita/röda) längs vägen?',
    options: ['Hastighetsbegränsning', 'Vägens sträckning — vita på höger sida, röda på vänster', 'Busshållplats'],
    correctIndex: 1,
    explanation: 'Reflexstolpar visar vägens sträckning i mörker. Vita reflexer sitter på höger sida, röda på vänster.',
  },
  {
    id: 'vmk-35',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad innebär en "räfflad markering" (snedstreckad yta) på vägbanan?',
    options: ['Parkeringszon', 'Spärrat område — du får inte köra eller stanna på det', 'Farthinder'],
    correctIndex: 1,
    explanation: 'Snedstreckad/räfflad yta är ett spärrat område. Du får varken köra eller stanna på det.',
  },
  {
    id: 'vmk-36',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar symbolen för cykel målad på vägen?',
    options: ['Cykelaffär i närheten', 'Cykelkörfält eller cykelpassage', 'Cykelparkering'],
    correctIndex: 1,
    explanation: 'Cykelsymbolen markerar att delen av vägen är avsedd för cyklar.',
  },
  {
    id: 'vmk-37',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad innebär vita fyrkanter (rutor) i rad tvärs över körbanan?',
    options: ['Stopplinje', 'Cykelpassage/cykelöverfart', 'Farthinder'],
    correctIndex: 1,
    explanation: 'Vita fyrkanter i rad markerar en cykelpassage. Var uppmärksam på cyklister.',
  },
  {
    id: 'vmk-38',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad är "smalningsmarkering" på vägen?',
    options: ['Farthinder', 'Markeringar som visar att vägbanan smalnar av — byt fil i tid', 'Stopplinje'],
    correctIndex: 1,
    explanation: 'Smalningsmarkeringar visar att vägbanan smalnar. Pilar anger åt vilket håll du ska flytta dig.',
  },
  {
    id: 'vmk-39',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Får du korsa en heldragen kantlinje?',
    options: ['Nej, aldrig', 'Ja, vid nödsituationer eller om du ska parkera vid vägkanten', 'Ja, alltid'],
    correctIndex: 1,
    explanation: 'Kantlinjen är normalt bara en vägledning. Du får korsa den vid parkering, nödstopp eller liknande.',
  },
  {
    id: 'vmk-40',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad markerar texten "SKOLA" målad på vägen?',
    options: ['Skolbyggnad', 'Varning — skola i närheten, var extra försiktig', 'Skolzon med 20 km/h'],
    correctIndex: 1,
    explanation: 'Texten "SKOLA" på vägen varnar om att det finns en skola i närheten. Var extra uppmärksam på barn.',
  },
  {
    id: 'vmk-41',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad innebär en heldragen linje parallellt med en streckad linje (din sida heldragen)?',
    options: ['Du får köra om', 'Du får INTE passera linjen — det är den heldragna på din sida som gäller', 'Du kan välja fritt'],
    correctIndex: 1,
    explanation: 'Det är din sida av markeringen som gäller. Heldragen = du får inte passera. Mötande (streckad sida) får.',
  },
  {
    id: 'vmk-42',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar vägbultar (katter ögon) i vägbanan?',
    options: ['Hinder', 'Reflexer som syns i mörker och visar vägens sträckning', 'Farthinder'],
    correctIndex: 1,
    explanation: 'Vägbultar med reflexer hjälper dig se vägen och körfälten i mörker och dåligt väder.',
  },
  {
    id: 'vmk-43',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad anger en pil som pekar rakt fram OCH åt höger i ett körfält?',
    options: ['Du kan välja att köra rakt eller svänga höger', 'Du måste köra rakt', 'Du måste svänga höger'],
    correctIndex: 0,
    explanation: 'Dubbelpilen anger att du i det körfältet kan välja att köra rakt fram eller svänga höger.',
  },
  {
    id: 'vmk-44',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vid vägarbete finns både vita permanenta och gula tillfälliga markeringar. Vilka gäller?',
    options: ['De vita', 'De gula tillfälliga — de har högre prioritet', 'Båda gäller'],
    correctIndex: 1,
    explanation: 'Tillfälliga gula/orangea markeringar vid vägarbete har alltid prioritet framför permanenta vita.',
  },
  {
    id: 'vmk-45',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar en bred vit tvärslinje vid en korsning med ljussignal?',
    options: ['Parkering', 'Stopplinje — du ska stanna före denna linje vid rött ljus', 'Cykelpassage'],
    correctIndex: 1,
    explanation: 'Stopplinjen vid signalreglerad korsning anger var du ska stanna vid rött eller gult ljus.',
  },
  {
    id: 'vmk-46',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad anger markeringar som liknar "hajtänder" (trianglar) framför ett övergångsställe?',
    options: ['Farthinder', 'Förvarning om övergångsställe — var beredd att stanna', 'Väjningslinje'],
    correctIndex: 1,
    explanation: 'Hajtänder framför övergångsställe förstärker budskapet att du ska vara beredd att stanna.',
  },
  {
    id: 'vmk-47',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad innebär "edge line rumble strips" (vibrerande kantlinjer)?',
    options: ['Dekorativa markeringar', 'Upphöjda markeringar som vibrerar och varnar om du kör av vägen', 'Cykelbanemarkeringar'],
    correctIndex: 1,
    explanation: 'Vibrerande kantlinjer (rumble strips) skapar vibrationer och ljud om du kör över dem — varnar vid ouppmärksamhet.',
  },
  {
    id: 'vmk-48',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar en bred vit yta i formen av en pil på vägbanan?',
    options: ['Landningsbana', 'Körfältets riktning — du ska följa pilen', 'Parkeringsplats'],
    correctIndex: 1,
    explanation: 'Pilar på vägbanan anger obligatorisk eller rekommenderad körriktning i körfältet.',
  },
  {
    id: 'vmk-49',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad gäller om vägmarkeringar är bortnötta och knappt syns?',
    options: ['Inga regler gäller', 'Reglerna gäller fortfarande — vägmärken och trafikregler styr', 'Du kan köra fritt'],
    correctIndex: 1,
    explanation: 'Bortnötta markeringar ändrar inte trafikreglerna. Skyltar och generella regler gäller oavsett.',
  },
  {
    id: 'vmk-50',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad innebär "kanalisation" vid en korsning?',
    options: ['Vatten under vägen', 'Målad vägmarkering som leder trafiken i bestämda banor genom korsningen', 'En typ av avlopp'],
    correctIndex: 1,
    explanation: 'Kanalisation är vägmarkeringar (ofta med refuger) som styr trafikflödet genom en korsning på ett ordnat sätt.',
  },
];
