import { Question } from './types';

export const vagmarkenQuestions: Question[] = [
  // === EASY (12 frågor) ===
  {
    id: 'vag-1',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad betyder en röd triangel med spetsen uppåt och ett utropstecken?',
    options: ['Varning för fara', 'Stopp', 'Parkering förbjuden'],
    correctIndex: 0,
    explanation: 'En röd triangel med spetsen uppåt och ett utropstecken är varningsmärket "Varning för fara" (A40). Det varnar för fara som inte har något eget varningsmärke.',
  },
  {
    id: 'vag-2',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en rund skylt med röd kant och siffran 50?',
    options: ['Rekommenderad hastighet 50 km/h', 'Högsta tillåtna hastighet 50 km/h', 'Minsta tillåtna hastighet 50 km/h'],
    correctIndex: 1,
    explanation: 'En rund skylt med röd kant och siffran 50 är förbudsmärket "Hastighetsbegränsning" (C31). Det anger att högsta tillåtna hastighet är 50 km/h.',
  },
  {
    id: 'vag-3',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad betyder en röd åttkantig skylt med texten STOP?',
    options: ['Sänk hastigheten', 'Stanna och lämna företräde', 'Väjningsplikt vid korsning'],
    correctIndex: 1,
    explanation: 'Stoppmärket (B2) är en röd åttkantig skylt. Det innebär att du måste stanna helt vid stopplinjen och lämna företräde åt korsande trafik.',
  },
  {
    id: 'vag-4',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en blå rund skylt med en vit pil som pekar rakt fram?',
    options: ['Enkelriktat', 'Påbjuden körriktning rakt fram', 'Motorväg börjar'],
    correctIndex: 1,
    explanation: 'En blå rund skylt med vit pil rakt fram är påbudsmärket "Påbjuden körriktning" (D1). Du måste köra i den riktning pilen visar.',
  },
  {
    id: 'vag-5',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en rund skylt med röd kant och ett rött snedstreck över en P-symbol?',
    options: ['Parkeringsplats', 'Parkering förbjuden', 'Datumparkering'],
    correctIndex: 1,
    explanation: 'Märket "Parkering förbjuden" (C35) är en rund skylt med röd kant och ett rött diagonalt streck över en P-symbol. Parkering är inte tillåten.',
  },
  {
    id: 'vag-6',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad betyder en gul triangel med spetsen nedåt?',
    options: ['Varning för fara', 'Väjningsplikt', 'Stopp vid korsning'],
    correctIndex: 1,
    explanation: 'En gul (vit med röd kant) triangel med spetsen nedåt är märket "Väjningsplikt" (B1). Du måste lämna företräde åt korsande trafik.',
  },
  {
    id: 'vag-7',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en grön rektangulär skylt med en vit motorvägs-symbol?',
    options: ['Motortrafikled börjar', 'Motorväg börjar', 'Snabbväg börjar'],
    correctIndex: 1,
    explanation: 'Märket "Motorväg" (E1) anger att motorväg börjar. Minsta hastighet är 40 km/h, gående och cyklister är förbjudna.',
  },
  {
    id: 'vag-8',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en röd triangel med en bild av barn?',
    options: ['Lekplats i närheten', 'Varning för barn', 'Skola, sänk hastigheten till 30 km/h'],
    correctIndex: 1,
    explanation: 'Varningsmärket "Varning för barn" (A15) varnar för att barn kan vistas i närheten, t.ex. vid skolor eller lekplatser. Var extra uppmärksam.',
  },
  {
    id: 'vag-9',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad betyder en rund skylt med röd kant och ett kryss av röda streck (X)?',
    options: ['Korsning förbjuden', 'Stannande och parkering förbjuden', 'Förbud mot alla fordon'],
    correctIndex: 1,
    explanation: 'Märket "Stannande och parkering förbjuden" (C36) har ett kryss av röda streck. Varken stannande eller parkering är tillåten.',
  },
  {
    id: 'vag-10',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en blå rektangulär skylt med ett vitt P?',
    options: ['Parkering förbjuden', 'Parkeringsplats', 'Privat parkering'],
    correctIndex: 1,
    explanation: 'Upplysningsskylten "Parkeringsplats" (E19) anger att parkering är tillåten på angiven plats.',
  },
  {
    id: 'vag-11',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en rund skylt med röd kant och symbolen för infart förbjuden (ett vitt streck)?',
    options: ['Enkelriktat', 'Infart förbjuden', 'Vägen stängd'],
    correctIndex: 1,
    explanation: 'Märket "Infart förbjuden" (C2) har ett vitt horisontellt streck mot röd bakgrund. Fordonstrafik i denna riktning är förbjuden.',
  },
  {
    id: 'vag-12',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en röd triangel med en bild av en älg?',
    options: ['Viltreservat', 'Varning för vilt', 'Jaktområde'],
    correctIndex: 1,
    explanation: 'Varningsmärket "Varning för vilt" (A18) varnar för att älg eller annat vilt kan korsa vägen. Var uppmärksam, särskilt i gryning och skymning.',
  },

  // === MEDIUM (14 frågor) ===
  {
    id: 'vag-13',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en blå rund skylt med en vit cykel?',
    options: ['Cykelparkering', 'Påbjuden cykelbana', 'Cykling förbjuden'],
    correctIndex: 1,
    explanation: 'Påbudsmärket "Påbjuden cykelbana" (D4) innebär att cyklister ska använda cykelbanan. Andra fordon får inte köra där.',
  },
  {
    id: 'vag-14',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en grön skylt med symbolen för motortrafikled (en väg med ett streck)?',
    options: ['Motorväg börjar', 'Motortrafikled börjar', 'Huvudled börjar'],
    correctIndex: 1,
    explanation: 'Märket "Motortrafikled" (E3) anger att motortrafikled börjar. Samma regler som motorväg gäller, men vägen kan ha korsningar i plan.',
  },
  {
    id: 'vag-15',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad betyder tilläggstavlan "100 m" under ett varningsmärke?',
    options: ['Varningen gäller i 100 meter', 'Faran finns om 100 meter', 'Hastigheten bör vara 100 km/h'],
    correctIndex: 1,
    explanation: 'En tilläggstavla med avstånd under ett varningsmärke anger avståndet till den fara som märket varnar för.',
  },
  {
    id: 'vag-16',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en rund skylt med röd kant och en bild av en lastbil?',
    options: ['Varning för lastbilar', 'Förbud mot tung trafik', 'Lastbilsparkering'],
    correctIndex: 1,
    explanation: 'Förbudsmärket "Förbud mot trafik med tung lastbil" (C7) innebär att lastbilar med totalvikt över 3,5 ton inte får passera.',
  },
  {
    id: 'vag-17',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'En rektangulär blå skylt med texten "Gångfartsområde" anger att du ska:',
    options: ['Köra i högst 30 km/h', 'Anpassa hastigheten till gångfart', 'Köra i högst 20 km/h'],
    correctIndex: 1,
    explanation: 'Märket "Gångfartsområde" (E9) innebär att fordon ska anpassa hastigheten till gångfart (ca 5-7 km/h). Gående har företräde.',
  },
  {
    id: 'vag-18',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en rund skylt med blå bakgrund och siffran 30?',
    options: ['Högsta tillåtna hastighet 30 km/h', 'Lägsta tillåtna hastighet 30 km/h', 'Rekommenderad hastighet 30 km/h'],
    correctIndex: 1,
    explanation: 'En blå rund skylt med vit siffra är påbudsmärket "Lägsta tillåtna hastighet" (D8). Fordon måste hålla minst 30 km/h.',
  },
  {
    id: 'vag-19',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad betyder en röd triangel med två pilar som möts (en röd och en svart)?',
    options: ['Dubbelriktat', 'Möte med mötande trafik', 'Varning för smal väg'],
    correctIndex: 1,
    explanation: 'Varningsmärket "Möte med mötande trafik" (A22) varnar för att vägen smalnar och att mötande trafik kan förekomma.',
  },
  {
    id: 'vag-20',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en rektangulär blå skylt med symbolen för mötesplats?',
    options: ['Rastplats', 'Mötesplats (för att möta fordon på smal väg)', 'Busshållplats'],
    correctIndex: 1,
    explanation: 'Upplysningsskylten "Mötesplats" (E13) anger en breddning av vägen där fordon kan mötas på smala vägar.',
  },
  {
    id: 'vag-21',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'En heldragen linje i vägens mitt innebär att du:',
    options: ['Får köra om om det är säkert', 'Inte får korsa eller köra om', 'Ska köra i mitten av vägen'],
    correctIndex: 1,
    explanation: 'En heldragen mittlinje (spärrlinje) får inte korsas. Det innebär förbud mot omkörning och byte av körfält.',
  },
  {
    id: 'vag-22',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en rund skylt med röd kant och en pil som svänger vänster med ett rött streck?',
    options: ['Sväng vänster', 'Förbud mot vänstersväng', 'Enkelriktat åt vänster'],
    correctIndex: 1,
    explanation: 'Förbudsmärket "Förbud mot vänstersväng" (C17) innebär att det inte är tillåtet att svänga vänster.',
  },
  {
    id: 'vag-23',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'En streckad mittlinje på vägen innebär att du:',
    options: ['Får korsa linjen om det kan ske säkert', 'Inte får korsa linjen', 'Måste byta körfält'],
    correctIndex: 0,
    explanation: 'En streckad mittlinje (varningslinje) får korsas om det kan ske på ett säkert sätt, t.ex. vid omkörning.',
  },
  {
    id: 'vag-24',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en röd triangel med en bild av en kurva?',
    options: ['Sväng åt höger', 'Varning för farlig kurva', 'Cirkulationsplats framöver'],
    correctIndex: 1,
    explanation: 'Varningsmärket "Varning för farlig kurva" (A1/A2) varnar för en kurva som kan vara svår att ta i normal hastighet.',
  },
  {
    id: 'vag-25',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en blå rund skylt med en vit pil som pekar åt höger i en cirkel?',
    options: ['Sväng åt höger', 'Påbjuden körriktning i rondellen', 'Enkelriktat höger'],
    correctIndex: 1,
    explanation: 'Påbudsmärket "Påbjuden körriktning" (D1) med cirkelformad pil anger att du ska köra i den angivna riktningen, vanligt vid cirkulationsplatser.',
  },
  {
    id: 'vag-26',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad betyder tilläggstavlan med en klocksymbol och texten "8-17"?',
    options: ['Huvudmärket gäller mellan kl. 8 och 17', 'Parkering tillåten i 8-17 minuter', 'Vägarbete pågår 8-17 timmar'],
    correctIndex: 0,
    explanation: 'En tilläggstavla med tidsangivelse anger under vilka tider det överordnade märket gäller. I detta fall mellan kl. 8:00 och 17:00.',
  },

  // === HARD (9 frågor) ===
  {
    id: 'vag-27',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad innebär en kombination av heldragen och streckad mittlinje, där den heldragna linjen är närmast dig?',
    options: ['Du får korsa linjen för att köra om', 'Du får inte korsa linjen, men mötande trafik får', 'Båda sidor får korsa linjen'],
    correctIndex: 1,
    explanation: 'Vid en kombination av heldragen och streckad linje gäller den linje som är närmast ditt fordon. Heldragen linje på din sida innebär att du inte får korsa den.',
  },
  {
    id: 'vag-28',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En tilläggstavla med en lastbilssymbol under ett förbudsmärke innebär att förbudet:',
    options: ['Inte gäller lastbilar', 'Bara gäller lastbilar', 'Gäller alla fordon utom lastbilar'],
    correctIndex: 1,
    explanation: 'En tilläggstavla med ett fordonssymbol anger att huvudmärket bara gäller den fordonstyp som visas. Lastbilssymbolen innebär att förbudet specifikt gäller lastbilar.',
  },
  {
    id: 'vag-29',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser märket "Huvudled" (gul romb). Vad gäller vid nästa korsning utan andra vägmärken?',
    options: ['Du har företräde framför trafik från sidovägar', 'Högerregeln gäller', 'Väjningsplikt för alla'],
    correctIndex: 0,
    explanation: 'Märket "Huvudled" (B4) innebär att du kör på en huvudled och har företräde framför fordon som kommer in från sidovägar, såvida inget annat anges.',
  },
  {
    id: 'vag-30',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad innebär en rektangulär skylt med texten "Zon" och en P med ett rött kryss?',
    options: ['Parkering förbjuden i hela zonen', 'Parkeringszon med avgift', 'Tidsbegränsad parkering i zonen'],
    correctIndex: 0,
    explanation: 'Zonmärket "Zon med parkeringsförbud" (E20) innebär att parkering är förbjuden inom hela det angivna området, tills slutmärket.',
  },
  {
    id: 'vag-31',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad anger en bred spärrlinje (bred heldragen linje) vid sidan av vägen?',
    options: ['Förbud mot att stanna', 'Förbud mot att korsa linjen med fordon', 'Bussfil börjar'],
    correctIndex: 1,
    explanation: 'En bred spärrlinje (kantlinje) vid sidan av vägen markerar vägbanans kant och får inte korsas av fordon, till skillnad från en smal kantlinje.',
  },
  {
    id: 'vag-32',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser märket "Förbjuden omkörning" (C25). När upphör förbudet om inget slutmärke finns?',
    options: ['Vid nästa korsning med väg', 'Efter 500 meter', 'Vid nästa hastighetsskylt'],
    correctIndex: 0,
    explanation: 'Förbudet mot omkörning upphör vid nästa korsning med väg (om inget slutmärke eller nytt märke sätts upp dessförinnan), enligt Vägmärkesförordningen.',
  },
  {
    id: 'vag-33',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad innebär det om en tilläggstavla visar "0,5 km" under ett varningsmärke för vägarbete?',
    options: ['Vägarbetet pågår under 0,5 km', 'Vägarbetet börjar om 0,5 km', 'Hastigheten ska vara 0,5 km/h lägre'],
    correctIndex: 1,
    explanation: 'Tilläggstavlan med avstånd anger avståndet till den fara eller företeelse som märket varnar för. Vägarbetet börjar om 0,5 km.',
  },
  {
    id: 'vag-34',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du möter märkena "Huvudled upphör" följt av en korsning. Vad gäller?',
    options: ['Du har fortfarande företräde', 'Högerregeln gäller', 'Mötande trafik har företräde'],
    correctIndex: 1,
    explanation: 'När huvudled upphör (B4 slutmärke) gäller högerregeln vid nästa korsning, om inga andra vägmärken anger annat. Du har inte längre automatiskt företräde.',
  },
  {
    id: 'vag-35',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En vägmarkering med sicksacklinje längs trottoarkanten innebär:',
    options: ['Förbud mot parkering men stannande tillåtet', 'Busshållplats, stannande och parkering förbjuden', 'Lastzon, parkering tillåten max 10 min'],
    correctIndex: 1,
    explanation: 'En sicksacklinje längs trottoarkanten markerar busshållplats. Det är förbjudet att både stanna och parkera inom det markerade området.',
  },
];
