import { Question } from './types';

export const vagmarkenQuestions: Question[] = [
  // === EASY (12 frågor) ===
  {
    id: 'vag-1',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad betyder detta vägmärke?',
    signKey: 'varning-fara',
    options: ['Varning för fara', 'Stopp', 'Parkering förbjuden'],
    correctIndex: 0,
    explanation: 'En röd triangel med spetsen uppåt och ett utropstecken är varningsmärket "Varning för fara" (A40). Det varnar för fara som inte har något eget varningsmärke.',
  },
  {
    id: 'vag-2',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär detta vägmärke?',
    signKey: 'hastighet-50',
    options: ['Rekommenderad hastighet 50 km/h', 'Högsta tillåtna hastighet 50 km/h', 'Minsta tillåtna hastighet 50 km/h'],
    correctIndex: 1,
    explanation: 'En rund skylt med röd kant och siffran 50 är förbudsmärket "Hastighetsbegränsning" (C31). Det anger att högsta tillåtna hastighet är 50 km/h.',
  },
  {
    id: 'vag-3',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad betyder detta vägmärke?',
    signKey: 'stopp',
    options: ['Sänk hastigheten', 'Stanna och lämna företräde', 'Väjningsplikt vid korsning'],
    correctIndex: 1,
    explanation: 'Stoppmärket (B2) är en röd åttkantig skylt. Det innebär att du måste stanna helt vid stopplinjen och lämna företräde åt korsande trafik.',
  },
  {
    id: 'vag-4',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger detta vägmärke?',
    signKey: 'påbjuden-rakt-fram',
    options: ['Enkelriktat', 'Påbjuden körriktning rakt fram', 'Motorväg börjar'],
    correctIndex: 1,
    explanation: 'En blå rund skylt med vit pil rakt fram är påbudsmärket "Påbjuden körriktning" (D1). Du måste köra i den riktning pilen visar.',
  },
  {
    id: 'vag-5',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär detta vägmärke?',
    signKey: 'parkering-forbjuden',
    options: ['Parkeringsplats', 'Parkering förbjuden', 'Datumparkering'],
    correctIndex: 1,
    explanation: 'Märket "Parkering förbjuden" (C35) är en rund skylt med röd kant och ett rött diagonalt streck över en P-symbol. Parkering är inte tillåten.',
  },
  {
    id: 'vag-6',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad betyder detta vägmärke?',
    signKey: 'väjningsplikt',
    options: ['Varning för fara', 'Väjningsplikt', 'Stopp vid korsning'],
    correctIndex: 1,
    explanation: 'En vit triangel med röd kant och spetsen nedåt är märket "Väjningsplikt" (B1). Du måste lämna företräde åt korsande trafik.',
  },
  {
    id: 'vag-7',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger detta vägmärke?',
    signKey: 'motorväg',
    options: ['Motortrafikled börjar', 'Motorväg börjar', 'Snabbväg börjar'],
    correctIndex: 1,
    explanation: 'Märket "Motorväg" (E1) anger att motorväg börjar. Minsta hastighet är 40 km/h, gående och cyklister är förbjudna.',
  },
  {
    id: 'vag-8',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär detta vägmärke?',
    signKey: 'varning-barn',
    options: ['Lekplats i närheten', 'Varning för barn', 'Skola, sänk hastigheten till 30 km/h'],
    correctIndex: 1,
    explanation: 'Varningsmärket "Varning för barn" (A15) varnar för att barn kan vistas i närheten, t.ex. vid skolor eller lekplatser. Var extra uppmärksam.',
  },
  {
    id: 'vag-9',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad betyder detta vägmärke?',
    signKey: 'stannande-forbjuden',
    options: ['Korsning förbjuden', 'Stannande och parkering förbjuden', 'Förbud mot alla fordon'],
    correctIndex: 1,
    explanation: 'Märket "Stannande och parkering förbjuden" (C36) har ett kryss av röda streck. Varken stannande eller parkering är tillåten.',
  },
  {
    id: 'vag-10',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger detta vägmärke?',
    signKey: 'parkering',
    options: ['Parkering förbjuden', 'Parkeringsplats', 'Privat parkering'],
    correctIndex: 1,
    explanation: 'Upplysningsskylten "Parkeringsplats" (E19) anger att parkering är tillåten på angiven plats.',
  },
  {
    id: 'vag-11',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär detta vägmärke?',
    signKey: 'infart-forbjuden',
    options: ['Enkelriktat', 'Infart förbjuden', 'Vägen stängd'],
    correctIndex: 1,
    explanation: 'Märket "Infart förbjuden" (C2) har ett vitt horisontellt streck mot röd bakgrund. Fordonstrafik i denna riktning är förbjuden.',
  },
  {
    id: 'vag-12',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger detta vägmärke?',
    signKey: 'varning-vilt',
    options: ['Viltreservat', 'Varning för vilt', 'Jaktområde'],
    correctIndex: 1,
    explanation: 'Varningsmärket "Varning för vilt" (A18) varnar för att älg eller annat vilt kan korsa vägen. Var uppmärksam, särskilt i gryning och skymning.',
  },

  // === MEDIUM (14 frågor) ===
  {
    id: 'vag-13',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger detta vägmärke?',
    signKey: 'cykelbana',
    options: ['Cykelparkering', 'Påbjuden cykelbana', 'Cykling förbjuden'],
    correctIndex: 1,
    explanation: 'Påbudsmärket "Påbjuden cykelbana" (D4) innebär att cyklister ska använda cykelbanan. Andra fordon får inte köra där.',
  },
  {
    id: 'vag-14',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär detta vägmärke?',
    signKey: 'motortrafikled',
    options: ['Motorväg börjar', 'Motortrafikled börjar', 'Huvudled börjar'],
    correctIndex: 1,
    explanation: 'Märket "Motortrafikled" (E3) anger att motortrafikled börjar. Samma regler som motorväg gäller, men vägen kan ha korsningar i plan.',
  },
  {
    id: 'vag-15',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad betyder tilläggstavlan "100 m" under ett varningsmärke?',
    options: ['Varningen gäller i 100 meter', 'Faran finns om 100 meter', 'Hastigheten bör vara 100 km/h'],
    correctIndex: 1,
    explanation: 'En tilläggstavla med avstånd under ett varningsmärke anger avståndet till den fara som märket varnar för.',
  },
  {
    id: 'vag-16',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär detta vägmärke?',
    signKey: 'tung-trafik-forbjuden',
    options: ['Varning för lastbilar', 'Förbud mot tung trafik', 'Lastbilsparkering'],
    correctIndex: 1,
    explanation: 'Förbudsmärket "Förbud mot trafik med tung lastbil" (C7) innebär att lastbilar med totalvikt över 3,5 ton inte får passera.',
  },
  {
    id: 'vag-17',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger detta vägmärke?',
    signKey: 'gångfartsområde',
    options: ['Köra i högst 30 km/h', 'Anpassa hastigheten till gångfart', 'Köra i högst 20 km/h'],
    correctIndex: 1,
    explanation: 'Märket "Gångfartsområde" (E9) innebär att fordon ska anpassa hastigheten till gångfart (ca 5-7 km/h). Gående har företräde.',
  },
  {
    id: 'vag-18',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger detta vägmärke?',
    signKey: 'lägsta-hastighet-30',
    options: ['Högsta tillåtna hastighet 30 km/h', 'Lägsta tillåtna hastighet 30 km/h', 'Rekommenderad hastighet 30 km/h'],
    correctIndex: 1,
    explanation: 'En blå rund skylt med vit siffra är påbudsmärket "Lägsta tillåtna hastighet" (D8). Fordon måste hålla minst 30 km/h.',
  },
  {
    id: 'vag-19',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad betyder detta vägmärke?',
    signKey: 'varning-mötande',
    options: ['Dubbelriktat', 'Möte med mötande trafik', 'Varning för smal väg'],
    correctIndex: 1,
    explanation: 'Varningsmärket "Möte med mötande trafik" (A22) varnar för att vägen smalnar och att mötande trafik kan förekomma.',
  },
  {
    id: 'vag-20',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär detta vägmärke?',
    signKey: 'mötesplats',
    options: ['Rastplats', 'Mötesplats (för att möta fordon på smal väg)', 'Busshållplats'],
    correctIndex: 1,
    explanation: 'Upplysningsskylten "Mötesplats" (E13) anger en breddning av vägen där fordon kan mötas på smala vägar.',
  },
  {
    id: 'vag-21',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'En heldragen linje i vägens mitt innebär att du:',
    options: ['Får köra om om det är säkert', 'Inte får korsa eller köra om', 'Ska köra i mitten av vägen'],
    correctIndex: 1,
    explanation: 'En heldragen mittlinje (spärrlinje) får inte korsas. Det innebär förbud mot omkörning och byte av körfält.',
  },
  {
    id: 'vag-22',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger detta vägmärke?',
    signKey: 'vänstersväng-forbjuden',
    options: ['Sväng vänster', 'Förbud mot vänstersväng', 'Enkelriktat åt vänster'],
    correctIndex: 1,
    explanation: 'Förbudsmärket "Förbud mot vänstersväng" (C17) innebär att det inte är tillåtet att svänga vänster.',
  },
  {
    id: 'vag-23',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'En streckad mittlinje på vägen innebär att du:',
    options: ['Får korsa linjen om det kan ske säkert', 'Inte får korsa linjen', 'Måste byta körfält'],
    correctIndex: 0,
    explanation: 'En streckad mittlinje (varningslinje) får korsas om det kan ske på ett säkert sätt, t.ex. vid omkörning.',
  },
  {
    id: 'vag-24',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär detta vägmärke?',
    signKey: 'varning-kurva',
    options: ['Sväng åt höger', 'Varning för farlig kurva', 'Cirkulationsplats framöver'],
    correctIndex: 1,
    explanation: 'Varningsmärket "Varning för farlig kurva" (A1/A2) varnar för en kurva som kan vara svår att ta i normal hastighet.',
  },
  {
    id: 'vag-25',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger detta vägmärke?',
    signKey: 'cirkulationsplats',
    options: ['Sväng åt höger', 'Påbjuden körriktning i rondellen', 'Enkelriktat höger'],
    correctIndex: 1,
    explanation: 'Påbudsmärket "Påbjuden körriktning" (D1) med cirkelformad pil anger att du ska köra i den angivna riktningen, vanligt vid cirkulationsplatser.',
  },
  {
    id: 'vag-26',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad betyder tilläggstavlan med en klocksymbol och texten "8-17"?',
    options: ['Huvudmärket gäller mellan kl. 8 och 17', 'Parkering tillåten i 8-17 minuter', 'Vägarbete pågår 8-17 timmar'],
    correctIndex: 0,
    explanation: 'En tilläggstavla med tidsangivelse anger under vilka tider det överordnade märket gäller. I detta fall mellan kl. 8:00 och 17:00.',
  },

  // === HARD (9 frågor) ===
  {
    id: 'vag-27',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad innebär en kombination av heldragen och streckad mittlinje, där den heldragna linjen är närmast dig?',
    options: ['Du får korsa linjen för att köra om', 'Du får inte korsa linjen, men mötande trafik får', 'Båda sidor får korsa linjen'],
    correctIndex: 1,
    explanation: 'Vid en kombination av heldragen och streckad linje gäller den linje som är närmast ditt fordon. Heldragen linje på din sida innebär att du inte får korsa den.',
  },
  {
    id: 'vag-28',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En tilläggstavla med en lastbilssymbol under ett förbudsmärke innebär att förbudet:',
    options: ['Inte gäller lastbilar', 'Bara gäller lastbilar', 'Gäller alla fordon utom lastbilar'],
    correctIndex: 1,
    explanation: 'En tilläggstavla med ett fordonssymbol anger att huvudmärket bara gäller den fordonstyp som visas. Lastbilssymbolen innebär att förbudet specifikt gäller lastbilar.',
  },
  {
    id: 'vag-29',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser detta märke. Vad gäller vid nästa korsning utan andra vägmärken?',
    signKey: 'huvudled',
    options: ['Du har företräde framför trafik från sidovägar', 'Högerregeln gäller', 'Väjningsplikt för alla'],
    correctIndex: 0,
    explanation: 'Märket "Huvudled" (B4) innebär att du kör på en huvudled och har företräde framför fordon som kommer in från sidovägar, såvida inget annat anges.',
  },
  {
    id: 'vag-30',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad innebär detta vägmärke?',
    signKey: 'zon-parkering-forbjuden',
    options: ['Parkering förbjuden i hela zonen', 'Parkeringszon med avgift', 'Tidsbegränsad parkering i zonen'],
    correctIndex: 0,
    explanation: 'Zonmärket "Zon med parkeringsförbud" (E20) innebär att parkering är förbjuden inom hela det angivna området, tills slutmärket.',
  },
  {
    id: 'vag-31',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad anger en bred spärrlinje (bred heldragen linje) vid sidan av vägen?',
    options: ['Förbud mot att stanna', 'Förbud mot att korsa linjen med fordon', 'Bussfil börjar'],
    correctIndex: 1,
    explanation: 'En bred spärrlinje (kantlinje) vid sidan av vägen markerar vägbanans kant och får inte korsas av fordon, till skillnad från en smal kantlinje.',
  },
  {
    id: 'vag-32',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser detta märke. När upphör förbudet om inget slutmärke finns?',
    signKey: 'omkörning-forbjuden',
    options: ['Vid nästa korsning med väg', 'Efter 500 meter', 'Vid nästa hastighetsskylt'],
    correctIndex: 0,
    explanation: 'Förbudet mot omkörning upphör vid nästa korsning med väg (om inget slutmärke eller nytt märke sätts upp dessförinnan), enligt Vägmärkesförordningen.',
  },
  {
    id: 'vag-33',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad innebär det om en tilläggstavla visar "0,5 km" under ett varningsmärke för vägarbete?',
    signKey: 'varning-vägarbete',
    options: ['Vägarbetet pågår under 0,5 km', 'Vägarbetet börjar om 0,5 km', 'Hastigheten ska vara 0,5 km/h lägre'],
    correctIndex: 1,
    explanation: 'Tilläggstavlan med avstånd anger avståndet till den fara eller företeelse som märket varnar för. Vägarbetet börjar om 0,5 km.',
  },
  {
    id: 'vag-34',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du möter märkena "Huvudled upphör" följt av en korsning. Vad gäller?',
    options: ['Du har fortfarande företräde', 'Högerregeln gäller', 'Mötande trafik har företräde'],
    correctIndex: 1,
    explanation: 'När huvudled upphör (B4 slutmärke) gäller högerregeln vid nästa korsning, om inga andra vägmärken anger annat. Du har inte längre automatiskt företräde.',
  },
  {
    id: 'vag-35',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En vägmarkering med sicksacklinje längs trottoarkanten innebär:',
    options: ['Förbud mot parkering men stannande tillåtet', 'Busshållplats, stannande och parkering förbjuden', 'Lastzon, parkering tillåten max 10 min'],
    correctIndex: 1,
    explanation: 'En sicksacklinje längs trottoarkanten markerar busshållplats. Det är förbjudet att både stanna och parkera inom det markerade området.',
  },
  {
    id: 'vag-36',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en rund skylt med blå bakgrund och en vit pil som pekar åt höger?',
    options: ['Påbjuden körriktning höger', 'Enkelriktat åt höger', 'Rekommenderad väg åt höger'],
    correctIndex: 0,
    explanation: 'Påbudsmärket "Påbjuden körriktning" (D1) med pil åt höger anger att du måste svänga åt höger.',
  },
  {
    id: 'vag-37',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad betyder en rund skylt med röd kant och en bild av en motorcykel?',
    options: ['Motorcykelväg', 'Förbud mot motorcykel', 'Parkering för motorcykel'],
    correctIndex: 1,
    explanation: 'En rund skylt med röd kant och en motorcykelsymbol anger förbud mot motorcykeltrafik (C5).',
  },
  {
    id: 'vag-38',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en rektangulär blå skylt med en vit pil uppåt?',
    options: ['Enkelriktat', 'Påbjuden körriktning', 'Motorväg börjar'],
    correctIndex: 0,
    explanation: 'Den rektangulära blå skylten med vit pil uppåt är märket "Enkelriktat" (E11). Det visar att gatan är enkelriktad i pilens riktning.',
  },
  {
    id: 'vag-39',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en röd triangel med en bild av en kö/trafikstockning?',
    options: ['Varning för trafikstockning', 'Köbildning förbjuden', 'Avtagsväg framåt'],
    correctIndex: 0,
    explanation: 'Varningsmärket med kösymbol (A34) varnar för risk för kö eller trafikstockning framöver.',
  },
  {
    id: 'vag-40',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en rund skylt med röd kant och en fotgängare?',
    options: ['Övergångsställe', 'Förbud mot gångtrafik', 'Gångväg börjar'],
    correctIndex: 1,
    explanation: 'En rund skylt med röd kant och en fotgängarsymbol är förbudsmärket "Förbud mot gångtrafik" (C15).',
  },
  {
    id: 'vag-41',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en blå rektangulär skylt med symbolen för sjukhus (H)?',
    options: ['Sjukhus i närheten', 'Läkarmottagning', 'Första hjälpen-station'],
    correctIndex: 0,
    explanation: 'Den blåa informationsskylten med H-symbol (E22) anger att det finns ett sjukhus i närheten.',
  },
  {
    id: 'vag-42',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en röd triangel med en bild av en järnvägsbom?',
    options: ['Varning för järnvägskorsning med bommar', 'Vägbom framöver', 'Bro med vägbom'],
    correctIndex: 0,
    explanation: 'Varningsmärket (A27) med en järnvägsbom varnar för plankorsning med järnväg som har bommar.',
  },
  {
    id: 'vag-43',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad betyder en grön skylt med vita siffror (t.ex. E4)?',
    options: ['Hastighet på vägen', 'Riksvägens nummer', 'Avstånd till nästa stad'],
    correctIndex: 1,
    explanation: 'Gröna skyltar med vita siffror och bokstäver anger europavägs- eller riksvägsnummer.',
  },
  {
    id: 'vag-44',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en rund skylt med blå bakgrund och en vit fotgängare?',
    options: ['Gångväg', 'Övergångsställe', 'Gångfartsområde'],
    correctIndex: 0,
    explanation: 'Påbudsmärket "Gångbana" (D5) med blå bakgrund och vit fotgängare anger att vägen är avsedd för gående.',
  },
  {
    id: 'vag-45',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en röd triangel med en bild av dubbelriktad trafik?',
    options: ['Varning för mötande trafik', 'Vägen delas i två', 'Omkörning förbjuden'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Mötande trafik" (A24) varnar om att vägen framöver har dubbelriktad trafik.',
  },
  {
    id: 'vag-46',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en rund skylt med röd kant och texten "3,5 t"?',
    options: ['Förbud mot fordon tyngre än 3,5 ton', 'Rekommenderad vikt 3,5 ton', 'Maxvikt per axel 3,5 ton'],
    correctIndex: 0,
    explanation: 'Förbudsmärket (C20) med viktangivelse anger att fordon med totalvikt över angiven vikt inte får passera.',
  },
  {
    id: 'vag-47',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en rund skylt med röd kant och texten "2,5 m"?',
    options: ['Maximal bredd 2,5 m', 'Maximal höjd 2,5 m', 'Minsta avstånd 2,5 m'],
    correctIndex: 0,
    explanation: 'Förbudsmärket "Begränsad fordonsbredd" (C18) anger att fordon bredare än 2,5 m inte får passera.',
  },
  {
    id: 'vag-48',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad betyder en röd triangel med en bild av en sluttning (pil nedåt)?',
    options: ['Varning för brant nedförsbacke', 'Vägen lutar åt sidan', 'Varning för hinder'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Brant nedförsbacke" (A4) varnar för en brant nerförsbacke framöver. Procentsatsen kan anges.',
  },
  {
    id: 'vag-49',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en röd triangel med en bild av stenar som faller?',
    options: ['Varning för ras', 'Bergarbete pågår', 'Stenbrott i närheten'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Varning för ras" (A11) varnar för risk för sten- eller jordras.',
  },
  {
    id: 'vag-50',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en röd triangel med en bild av en öppningsbar bro?',
    options: ['Varning för öppningsbar bro', 'Bro med viktbegränsning', 'Viadukt framöver'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Öppningsbar bro" (A8) varnar om att en bro som kan öppnas finns framöver.',
  },
  {
    id: 'vag-51',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en rund skylt med röd kant och en bild av en traktor?',
    options: ['Förbud mot traktortrafik', 'Varning för långsamtgående fordon', 'Jordbruksväg'],
    correctIndex: 0,
    explanation: 'Förbudsmärket med traktorsymbol anger att traktortrafik inte är tillåten på vägen.',
  },
  {
    id: 'vag-52',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en blå rektangulär skylt med bokstaven "M" och en tunnelsymbol?',
    options: ['Metrostation i närheten', 'Tunnel framöver', 'Mötesplats i tunnel'],
    correctIndex: 0,
    explanation: 'Den blå informationsskylten med M-symbol anger att det finns en tunnelbane- eller metrostation i närheten.',
  },
  {
    id: 'vag-53',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en röd triangel med en bild av ett flygplan?',
    options: ['Varning för lågtflygande flygplan', 'Flygplats i närheten', 'Startbana korsar vägen'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Lågtflygande flygplan" (A16) varnar om att flygplan kan flyga lågt över vägen.',
  },
  {
    id: 'vag-54',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'En tilläggstavla med texten "50 m" under ett parkeringsförbudsmärke betyder:',
    options: ['Förbudet gäller 50 meter framåt', 'Närmsta parkering är 50 m bort', 'Parkering tillåten efter 50 m'],
    correctIndex: 0,
    explanation: 'Tilläggstavlan med avstånd anger att förbudet gäller inom en sträcka av 50 meter från skylten.',
  },
  {
    id: 'vag-55',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en tilläggstavla med en pil som pekar nedåt under ett förbudsmärke?',
    options: ['Förbudet slutar här', 'Förbudet gäller under skylten', 'Förbudet gäller framåt'],
    correctIndex: 0,
    explanation: 'En pil nedåt på tilläggstavlan anger att förbudet slutar vid skylten.',
  },
  {
    id: 'vag-56',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en rund skylt med röd kant och bokstaven "S" med ett rött streck?',
    options: ['Förbud mot stannande', 'Förbud mot sväng', 'Skolzon slutar'],
    correctIndex: 0,
    explanation: 'Förbudsmärket med "S" och rött streck är "Förbud mot att stanna och parkera" (C36). Varken stannande eller parkering är tillåtet.',
  },
  {
    id: 'vag-57',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en rund skylt med röd kant och två bilar bredvid varandra?',
    options: ['Omkörning förbjuden', 'Dubbelriktat körfält', 'Parallellkörning tillåten'],
    correctIndex: 0,
    explanation: 'Förbudsmärket "Omkörning förbjuden" (C25) anger att du inte får köra om andra motorfordon.',
  },
  {
    id: 'vag-58',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad betyder en rund skylt med röd kant och en pil som pekar uppåt och en nedåt (en röd och en svart)?',
    options: ['Mötande trafik har företräde', 'Dubbelriktat', 'Företräde vid möte'],
    correctIndex: 0,
    explanation: 'Förbudsmärket "Mötande trafik har företräde" (B6) anger att du måste lämna företräde åt mötande trafik vid t.ex. en smal passage.',
  },
  {
    id: 'vag-59',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en blå rektangulär skylt med ett vitt kryss och siffror?',
    options: ['Kilometermarkering', 'Korsningsnummer', 'Avfartsnummer'],
    correctIndex: 2,
    explanation: 'Blå skyltar med avfartsnummer anger vilken avfart du närmar dig på motorvägen.',
  },
  {
    id: 'vag-60',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en röd triangel med en bild av en sned väg/ojämn vägbana?',
    options: ['Varning för ojämn väg', 'Varning för vägarbete', 'Vägen lutar'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Ojämn väg" (A6) varnar om att vägbanan är ojämn, t.ex. gropar eller gupp.',
  },
  {
    id: 'vag-61',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad betyder en rund skylt med röd kant och texten "4,0 m"?',
    options: ['Maximal höjd 4,0 m', 'Maximal bredd 4,0 m', 'Minsta avstånd 4,0 m'],
    correctIndex: 0,
    explanation: 'Förbudsmärket "Begränsad fordonshöjd" (C19) anger att fordon högre än 4,0 meter inte får passera.',
  },
  {
    id: 'vag-62',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en rektangulär vit skylt med svart text som visar ett ortnamn?',
    options: ['Tättbebyggt område börjar', 'Informationsskylt', 'Kommungräns'],
    correctIndex: 0,
    explanation: 'Ortstavlan (E7) anger att du kör in i tättbebyggt område. Hastighetsgränsen 50 km/h gäller om inget annat anges.',
  },
  {
    id: 'vag-63',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en vit rektangulär skylt med ortnamnet genomstruket med ett rött streck?',
    options: ['Tättbebyggt område upphör', 'Orten existerar inte längre', 'Omväg rekommenderas'],
    correctIndex: 0,
    explanation: 'Slutmärket för ortstavla anger att tättbebyggt område upphör. Hastighetsgränsen kan ändras, vanligen till 70 km/h.',
  },
  {
    id: 'vag-64',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en rund skylt med blå bakgrund och vita pilar i en cirkel (cirkulationsplats)?',
    options: ['Påbjuden cirkulationsplats (rondell)', 'Vändplats', 'Parkeringszon'],
    correctIndex: 0,
    explanation: 'Påbudsmärket "Cirkulationsplats" (D2) anger att du kör in i en rondell och ska följa pilarna.',
  },
  {
    id: 'vag-65',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en röd triangel med en bild av en vägkorsning med sidoväg?',
    options: ['Varning för vägkorsning', 'Sidoväg från höger', 'Avfart framöver'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Vägkorsning" (A29) varnar om att en korsning med sidoväg finns framöver.',
  },
  {
    id: 'vag-66',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en röd triangel med en bild av en cyklistsymbol?',
    options: ['Varning för cyklister', 'Cykelväg börjar', 'Cykelpassage framöver'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Varning för cyklande" (A17) varnar om att cyklister kan korsa eller finnas på vägen.',
  },
  {
    id: 'vag-67',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en rund skylt med blå bakgrund, en fotgängare och en cyklist med en skiljelinje?',
    options: ['Gemensam gång- och cykelbana', 'Separerad gång- och cykelbana', 'Förbud mot gång och cykel'],
    correctIndex: 1,
    explanation: 'Påbudsmärket "Separerad gång- och cykelbana" (D6) anger att gående och cyklister har separata banor.',
  },
  {
    id: 'vag-68',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En blå skylt med texten "Sammanvävning" anger att:',
    options: ['Trafik från två filer ska varvas in i en', 'Du har företräde', 'Vänsterfilen stängs av'],
    correctIndex: 0,
    explanation: 'Märket "Sammanvävning" anger att trafik från flera filer ska sammanfogas. Bägge parter ska samarbeta — ingen har företräde.',
  },
  {
    id: 'vag-69',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad innebär en tilläggstavla med pilar som pekar åt båda håll under ett parkeringsförbudsmärke?',
    options: ['Förbudet gäller på bägge sidor', 'Förbudet sträcker sig åt båda hållen', 'Parkeringen är dubbelsidig'],
    correctIndex: 1,
    explanation: 'Pilar åt båda håll på en tilläggstavla anger att förbudet gäller i båda riktningarna från skylten.',
  },
  {
    id: 'vag-70',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad anger märket "Företräde vid möte" (en rund skylt med blå bakgrund, en röd och en vit pil)?',
    options: ['Du har företräde framför mötande trafik', 'Mötande trafik har företräde', 'Dubbelriktat körfält'],
    correctIndex: 0,
    explanation: 'Märket "Företräde vid möte" (B5) anger att du har företräde vid passage av t.ex. en smal bro eller vägavsnitt.',
  },
  {
    id: 'vag-71',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En röd triangel med en bild av vindstrut anger:',
    options: ['Varning för sidvind', 'Flygfält i närheten', 'Varning för storm'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Sidvind" (A19) varnar om risk för kraftig sidvind, t.ex. vid broar eller öppna landskap.',
  },
  {
    id: 'vag-72',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en brun rektangulär skylt med en turistsymbol?',
    options: ['Turistmål eller sevärdheter', 'Rastplats', 'Campingplats'],
    correctIndex: 0,
    explanation: 'Bruna skyltar med turistsymboler (turistmål) anger sevärdheter, besöksmål och liknande.',
  },
  {
    id: 'vag-73',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en rektangulär skylt med en bensinpumpsymbol?',
    options: ['Bensinstation i närheten', 'Tankning förbjuden', 'Eldfarligt område'],
    correctIndex: 0,
    explanation: 'Informationsskylten med bensinpumpsymbol anger att det finns en bensinstation i närheten.',
  },
  {
    id: 'vag-74',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en rektangulär blå skylt med en sängsymbol?',
    options: ['Hotell eller övernattning i närheten', 'Rastplats med vilomöjlighet', 'Sjukhus'],
    correctIndex: 0,
    explanation: 'Informationsskylten med sängsymbol anger att det finns hotell eller övernattning i närheten.',
  },
  {
    id: 'vag-75',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en röd triangel med en bild av snö/halka?',
    options: ['Varning för slirig väg', 'Vinterväg', 'Snöröjning pågår'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Slirig väg" (A10) varnar om att vägbanan kan vara hal, t.ex. vid regn, is eller snö.',
  },
  {
    id: 'vag-76',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en röd triangel med en bild av ett vägarbetshinder?',
    options: ['Varning för vägarbete', 'Vägen är avstängd', 'Omledning pågår'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Vägarbete" (A20) varnar för att vägarbete pågår framöver. Var extra försiktig.',
  },
  {
    id: 'vag-77',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en röd triangel med en bild av en tunnel?',
    options: ['Varning för tunnel', 'Tunnel stängd', 'Bro framöver'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Tunnel" (A23) varnar om att en tunnel börjar framöver. Tänd halvljuset.',
  },
  {
    id: 'vag-78',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger märket med en gul romb med vit kant?',
    options: ['Huvudled', 'Förkörsrätt', 'Motorväg'],
    correctIndex: 0,
    explanation: 'Märket "Huvudled" (B3) anger att du befinner dig på en huvudled och har företräde i korsningar.',
  },
  {
    id: 'vag-79',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en rund skylt med röd kant och två bilar bredvid varandra varav den ena är en lastbil?',
    options: ['Omkörning med lastbil förbjuden', 'Lastbilar förbjudna', 'Tung trafik varnas'],
    correctIndex: 0,
    explanation: 'Förbudsmärket "Omkörningsförbud för tung lastbil" (C26) anger att lastbilar inte får köra om.',
  },
  {
    id: 'vag-80',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en rund skylt med blå bakgrund och texten "70" i vitt?',
    options: ['Rekommenderad hastighet 70 km/h', 'Minsta tillåtna hastighet 70 km/h', 'Högsta hastighet 70 km/h'],
    correctIndex: 0,
    explanation: 'Rund blå skylt med vit siffra anger rekommenderad hastighet, inte tvingande. Det är en vägledning om lämplig hastighet.',
  },
  {
    id: 'vag-81',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En tilläggstavla visar en bild på en personbil och en lastbil. Vad innebär detta under ett förbudsmärke?',
    options: ['Förbudet gäller både personbilar och lastbilar', 'Förbudet gäller bara lastbilar', 'Personbilar undantas'],
    correctIndex: 0,
    explanation: 'Tilläggstavlan med fordonstyper specificerar vilka fordon förbudet gäller. Visar den både personbil och lastbil gäller det bägge.',
  },
  {
    id: 'vag-82',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad innebär en rund skylt med blå bakgrund, vita pilar som visar att man ska köra runt ett hinder?',
    options: ['Påbjuden passage åt den sida pilen visar', 'Rondell', 'Vändplats'],
    correctIndex: 0,
    explanation: 'Påbudsmärket "Påbjuden passage" anger att du måste köra förbi hindret/refugen på den sida pilen visar.',
  },
  {
    id: 'vag-83',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En blå rektangulär skylt med en bild av en bil med släpvagn och texten "Uppställning". Vad innebär det?',
    options: ['Uppställningsplats för fordon med släp', 'Parkering för husbilar', 'Fordon med släp förbjudna'],
    correctIndex: 0,
    explanation: 'Skylten anger en särskild uppställningsplats avsedd för fordon med släpvagn.',
  },
  {
    id: 'vag-84',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en röd triangel med bilden av en farthinder/gupp?',
    options: ['Varning för farthinder', 'Vägen är ojämn', 'Brant backe framöver'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Farthinder" (A5) varnar om att det finns ett farthinder (t.ex. ett gupp) framöver.',
  },
  {
    id: 'vag-85',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en rektangulär skylt med texten "Återvändsgata"?',
    options: ['Gatan har ingen genomfart', 'Gatan är enkelriktad', 'Gatan är privat'],
    correctIndex: 0,
    explanation: 'Märket "Återvändsgata" (E17) anger att vägen inte leder vidare — den är en återvändsgränd.',
  },
  {
    id: 'vag-86',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'En röd triangel med en bild av ett spår (järnväg utan bom). Vad anger den?',
    options: ['Varning för järnvägskorsning utan bommar', 'Spårvagn korsar', 'Industrispår'],
    correctIndex: 0,
    explanation: 'Varningsmärket (A28) varnar för en plankorsning utan bommar. Var extra försiktig och var beredd att stanna.',
  },
  {
    id: 'vag-87',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär avståndstavlor (röda och vita streck) vid en järnvägskorsning?',
    options: ['Visar avståndet till korsningen — tre streck = 300 m, två = 200 m, ett = 100 m', 'Visar hur många spår', 'Anger maxhastighet'],
    correctIndex: 0,
    explanation: 'Avståndstavlor (A30-32) visar avståndet till järnvägskorsningen. Tre streck = ca 300 m, två = 200 m, ett = 100 m.',
  },
  {
    id: 'vag-88',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en rund skylt med röd kant och siffran "10 t"?',
    options: ['Förbud mot fordon med högre axeltryck än 10 ton', 'Maxvikt 10 ton', 'Rekommenderat axeltryck'],
    correctIndex: 0,
    explanation: 'Förbudsmärket "Begränsat axeltryck" (C21) anger att fordon med högre axeltryck än angivet värde inte får passera.',
  },
  {
    id: 'vag-89',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en rund skylt med röd kant och texten "8 m"?',
    options: ['Begränsad fordonslängd', 'Maxbredd 8 m', 'Avstånd till hinder'],
    correctIndex: 0,
    explanation: 'Förbudsmärket "Begränsad fordonslängd" (C22) anger att fordon längre än 8 meter inte får passera.',
  },
  {
    id: 'vag-90',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser ett märke som visar "Slut på 70-zon" (70 med diagonala streck). Vilken hastighet gäller nu?',
    options: ['50 km/h om du är i tätort, annars 70 km/h', 'Alltid 70 km/h', 'Alltid 50 km/h'],
    correctIndex: 0,
    explanation: 'När en zonhastighetsbegränsning upphör gäller den generella hastighetsgränsen — 50 km/h i tätort eller 70 km/h utanför.',
  },
  {
    id: 'vag-91',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En rund skylt med röd kant och diagonala streck (inga symboler). Vad innebär det?',
    options: ['Alla förbuds upphör', 'Alla restriktioner upphör (C40)', 'Vägen är fri'],
    correctIndex: 1,
    explanation: 'Märket "Slut på alla begränsningar" (C40) upphäver samtliga gällande förbudsmärken.',
  },
  {
    id: 'vag-92',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad anger märket "Krockudde" (gult och rött snedrandigt märke på en vägdelning)?',
    options: ['Hinder/refug, kör åt angiven sida', 'Varning för olycka', 'Vägarbete pågår'],
    correctIndex: 0,
    explanation: 'Krockuddemärket visar att det finns ett fast hinder eller en refug. Du ska köra åt den sida pilar eller markeringar anger.',
  },
  {
    id: 'vag-93',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser en skylt med texten "2 km" under ett upphörandemärke. Vad innebär det?',
    options: ['Begränsningen upphör om 2 km', 'Begränsningen har gällt i 2 km', 'Det är 2 km till nästa skylt'],
    correctIndex: 0,
    explanation: 'Tilläggstavla med avstånd under ett slutmärke anger att begränsningen upphör om det angivna avståndet.',
  },
  {
    id: 'vag-94',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en rektangulär skylt med en telefonsymbol?',
    options: ['Telefon finns i närheten', 'Ring för hjälp', 'Mobilförbud'],
    correctIndex: 0,
    explanation: 'Informationsskylten med telefonsymbol anger att det finns en nödtelefon eller telefon i närheten.',
  },
  {
    id: 'vag-95',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en skylt med en kaffekopp-symbol?',
    options: ['Rastplats med servering i närheten', 'Vänta här', 'Viloplats utan service'],
    correctIndex: 0,
    explanation: 'Skylten anger att det finns en rastplats med servering eller café i närheten.',
  },
  {
    id: 'vag-96',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en röd triangel med en bild av en ko?',
    options: ['Varning för kreatur', 'Lantgård i närheten', 'Jordbruksområde'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Varning för kreatur" (A18) varnar om att tamdjur kan befinna sig på eller nära vägen.',
  },
  {
    id: 'vag-97',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en röd triangel med en bild av en kajkant/brygga?',
    options: ['Varning för kaj eller strand', 'Hamn i närheten', 'Badplats framöver'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Kaj, strand eller brygga" (A9) varnar om att det finns risk att köra ut i vatten.',
  },
  {
    id: 'vag-98',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'En tilläggstavla med texten "Gäller ej behörig trafik" under ett förbudsmärke innebär:',
    options: ['Fordon med tillstånd undantas från förbudet', 'Förbudet gäller alla', 'Buss undantas'],
    correctIndex: 0,
    explanation: 'Tilläggstavlan undantar behörig trafik (t.ex. boende, leveranser) från förbudet.',
  },
  {
    id: 'vag-99',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser märket "Rekommenderad lägre hastighet" (blå rund, vit siffra) följt av en skarp kurva. Vad gäller?',
    options: ['Du bör sänka hastigheten till angiven nivå, men det är inte tvingande', 'Du måste sänka till angiven hastighet', 'Det är maxhastighet i kurvan'],
    correctIndex: 0,
    explanation: 'Rekommenderad hastighet är inte tvingande som en hastighetsbegränsning, men du bör följa den för säkerhetens skull.',
  },
  {
    id: 'vag-100',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En tilläggstavla med symboler för regn och sol under ett hastighetsmärke. Vad innebär det?',
    options: ['Hastigheten gäller vid visst väderlag', 'Hastigheten varierar beroende på tid', 'Skylten gäller bara dagtid'],
    correctIndex: 0,
    explanation: 'Tilläggstavlan anger att hastighetsbegränsningen gäller vid det specifika väderlaget (t.ex. vid regn).',
  },
  {
    id: 'vag-101',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en rektangulär skylt med bokstaven "i" (information)?',
    options: ['Turistinformation', 'Sjukhus', 'Informationsplats'],
    correctIndex: 2,
    explanation: 'Skylten med "i" anger att det finns en informationsplats, t.ex. för turistinformation.',
  },
  {
    id: 'vag-102',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en rektangulär skylt med en tältsymbol?',
    options: ['Campingplats i närheten', 'Scoutläger', 'Naturreservat'],
    correctIndex: 0,
    explanation: 'Informationsskylten med tältsymbol anger att det finns en campingplats i närheten.',
  },
  {
    id: 'vag-103',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en röd triangel med bilden av en ryttare på häst?',
    options: ['Varning för ridande', 'Ridväg korsar', 'Hästsport pågår'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Varning för ridande" varnar om att ryttare kan finnas på eller nära vägen.',
  },
  {
    id: 'vag-104',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'En rektangulär vit skylt med ett svart kryss anger:',
    options: ['Andreaskorset — järnvägskorsning utan bom', 'Korsning framöver', 'Avstängd väg'],
    correctIndex: 0,
    explanation: 'Andreaskorset placeras vid järnvägskorsning och anger att du ska vara beredd att stanna för tåg.',
  },
  {
    id: 'vag-105',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en röd triangel med en bild av en trafikljussignal?',
    options: ['Varning för trafikljus', 'Trafikljus ur funktion', 'Ny trafikljusanläggning'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Trafikljus" (A22) varnar om att det finns trafikljus framöver som du kanske inte förväntar dig.',
  },
  {
    id: 'vag-106',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser en gul romb med vit kant som har ett svart kryss igenom. Vad innebär det?',
    options: ['Huvudled upphör', 'Korsning utan företräde', 'Motorväg upphör'],
    correctIndex: 0,
    explanation: 'Märket "Huvudled upphör" (B4) anger att du inte längre har företräde. Högerregeln gäller vid kommande korsningar.',
  },
  {
    id: 'vag-107',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En tilläggstavla med en uppåtpil och texten "100 m" anger:',
    options: ['Märkets verkan börjar om 100 m', 'Märket har gällt i 100 m', 'Sträckan är 100 m lång'],
    correctIndex: 0,
    explanation: 'Uppåtpilen anger att märkets verkan börjar om det angivna avståndet.',
  },
  {
    id: 'vag-108',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vad innebär en skylt med texten "Frivillig väg" (blå skylt)?',
    options: ['En väg som du inte behöver följa men som rekommenderas', 'En väg utan regler', 'En kostnadsfri väg'],
    correctIndex: 0,
    explanation: 'Frivillig väg innebär en rekommenderad omväg eller alternativ rutt, men du är inte tvungen att följa den.',
  },
  {
    id: 'vag-109',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en rektangulär skylt med en pil och texten "Omledning"?',
    options: ['Tillfällig omledning av trafiken', 'Alternativ väg', 'Utflyktsmål'],
    correctIndex: 0,
    explanation: 'Omledningsskylten anger att trafiken leds om på en annan väg, t.ex. vid vägarbete.',
  },
  {
    id: 'vag-110',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en rund skylt med röd kant och ett rött kryss (X) över en bild av fordon?',
    options: ['Förbud mot fordonstrafik', 'Korsning framöver', 'Vägarbete pågår'],
    correctIndex: 0,
    explanation: 'Förbudsmärket med rött kryss anger att fordonstrafik inte är tillåten.',
  },
  {
    id: 'vag-111',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en rund skylt med röd kant och en husvagn?',
    options: ['Förbud mot fordon med tillkopplad släpvagn', 'Campingplats', 'Parkeringsplats för husvagn'],
    correctIndex: 0,
    explanation: 'Förbudsmärket med husvagnssymbol anger att fordon med tillkopplad släpvagn inte får passera.',
  },
  {
    id: 'vag-112',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du kör i 90 km/h och ser varningsskylt med tilläggstavla "500 m". Ungefär hur lång tid har du på dig att reagera?',
    options: ['Cirka 20 sekunder', 'Cirka 5 sekunder', 'Cirka 40 sekunder'],
    correctIndex: 0,
    explanation: 'Vid 90 km/h kör du 25 m/s. 500 m tar alltså ca 20 sekunder — det är tiden du har att anpassa hastigheten.',
  },
  {
    id: 'vag-113',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En tilläggstavla med "Tid 8-16 (7-9)" under ett parkeringsförbudsmärke innebär:',
    options: ['Förbudet gäller 8-16 vardagar, 7-9 lördag', 'Förbudet gäller 8-16 och 7-9 varje dag', 'Parkering tillåten dessa tider'],
    correctIndex: 0,
    explanation: 'Tiden inom parentes anger lördag. Förbudet gäller 8-16 vardagar och 7-9 lördagar. Söndagar gäller det inte.',
  },
  {
    id: 'vag-114',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en skylt med symbolen för handikapparkering?',
    options: ['Parkering reserverad för rörelsehindrade', 'Sjukhus i närheten', 'Handikappanpassad väg'],
    correctIndex: 0,
    explanation: 'Skylten anger att parkeringsplatsen är reserverad för fordon med parkeringstillstånd för rörelsehindrade.',
  },
  {
    id: 'vag-115',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en röd triangel med en bild av en rondell?',
    options: ['Varning för cirkulationsplats', 'Cirkulationsplats börjar', 'Rondell med företräde'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Cirkulationsplats" varnar om att det finns en rondell framöver.',
  },
  {
    id: 'vag-116',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser märket "Farligt vägavsnitt" med tilläggstavla "Sträcka 3 km". Vad innebär det?',
    options: ['Faran sträcker sig 3 km framåt', 'Faran är 3 km bort', 'Du ska köra 3 km/h'],
    correctIndex: 0,
    explanation: 'Tilläggstavlan "Sträcka" anger att faran eller förbudet gäller under den angivna sträckan.',
  },
  {
    id: 'vag-117',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en rund skylt med röd kant och en bild av en moped?',
    options: ['Förbud mot mopedtrafik', 'Mopedväg börjar', 'Parkering för moped'],
    correctIndex: 0,
    explanation: 'Förbudsmärket med mopedsymbol anger att mopedtrafik inte är tillåten på vägen.',
  },
  {
    id: 'vag-118',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en rektangulär skylt med texten "Laddplats" och en elbilssymbol?',
    options: ['Laddstation för elfordon i närheten', 'Förbud mot bensinbilar', 'Elväg börjar'],
    correctIndex: 0,
    explanation: 'Skylten anger att det finns en laddstation för elfordon i närheten.',
  },
  {
    id: 'vag-119',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En tilläggstavla med en pil som pekar uppåt och en som pekar nedåt under samma vägmärke. Vad innebär det?',
    options: ['Märket gäller i båda riktningar', 'Märket gäller härifrån och fortsätter', 'Märket gäller mellan två punkter'],
    correctIndex: 1,
    explanation: 'En uppåtpil och nedåtpil anger att märket börjar och fortsätter från denna punkt.',
  },
  {
    id: 'vag-120',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en blå skylt med en vit pil som pekar snett åt höger?',
    options: ['Rekommenderad led åt höger', 'Påbjuden körriktning snett höger', 'Avfart åt höger'],
    correctIndex: 1,
    explanation: 'Påbudsmärket anger att du ska följa den riktning pilen visar — i detta fall snett åt höger.',
  },
  {
    id: 'vag-121',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en röd triangel med en bild av en bro?',
    options: ['Varning för smal bro', 'Bro med vägbom', 'Bro stängd'],
    correctIndex: 0,
    explanation: 'Varningsmärket "Smal bro" (A7) varnar om att bron framöver är smal och att du kan behöva mötas.',
  },
  {
    id: 'vag-122',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du passerar märket "Hastighetsbegränsning 60 km/h" och sedan en ortstavla. Vilken hastighet gäller i orten?',
    options: ['50 km/h om inte annan skylt anger annat', '60 km/h som det senaste märket angav', '70 km/h generellt'],
    correctIndex: 0,
    explanation: 'Ortstavlan anger tättbebyggt område där 50 km/h gäller generellt. Ortstavlan upphäver den föregående hastighetsskylten.',
  },
  {
    id: 'vag-123',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en röd triangel med en bild av en fotgängare på ett övergångsställe?',
    options: ['Varning för övergångsställe', 'Övergångsställe framöver', 'Gångfartsområde börjar'],
    correctIndex: 0,
    explanation: 'Varningsmärket varnar om att det finns ett övergångsställe framöver. Var beredd att stanna för fotgängare.',
  },
  {
    id: 'vag-124',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser en blå skylt med texten "Tättbebyggt område" men inget ortnamn. Vad gäller?',
    options: ['50 km/h generellt gäller', '70 km/h gäller', 'Ingen hastighetsbegränsning ändras'],
    correctIndex: 0,
    explanation: 'Skylten "Tättbebyggt område" fungerar som ortstavla — 50 km/h gäller om inte annan skylt anger annat.',
  },
  {
    id: 'vag-125',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en röd triangel med en bild av ett övergångsställe och en cykel?',
    options: ['Varning för cykelöverfart', 'Gång- och cykelväg', 'Cykelpassage med företräde'],
    correctIndex: 0,
    explanation: 'Varningsmärket varnar om att det finns en cykelöverfart framöver där cyklister kan korsa vägen.',
  },
  {
    id: 'vag-126',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en rund skylt med röd kant och en nedåtriktad svart pil?',
    options: ['Förbud mot trafik i denna riktning', 'Vägen slutar', 'Backning förbjuden'],
    correctIndex: 0,
    explanation: 'En rund skylt med röd kant och pil nedåt (infart förbjuden) anger att du inte får köra in på vägen från denna riktning.',
  },
  {
    id: 'vag-127',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En tilläggstavla visar "Gäller ej cykel". Under vilket märke påverkar detta dig som bilist?',
    options: ['Det påverkar inte dig — undantaget gäller bara cyklister', 'Du ska också undantas', 'Cyklister har företräde'],
    correctIndex: 0,
    explanation: 'Tilläggstavlan undantar bara cyklister från förbudet. Som bilist gäller förbudet fortfarande fullt ut.',
  },
  {
    id: 'vag-128',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en skylt med en grön ruta och en vit bil (motortrafikledssymbol)?',
    options: ['Motortrafikled börjar', 'Motorväg börjar', 'Snabbväg'],
    correctIndex: 0,
    explanation: 'Märket "Motortrafikled" (E3) anger att motortrafikled börjar. Minsta hastighet är 40 km/h.',
  },
  {
    id: 'vag-129',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser ett hastighetsmärke med "40" inuti en röd ring OCH texten "Zon" under. Vad innebär det?',
    options: ['En 40-zon börjar där alla gator har max 40 km/h', 'Bara denna gata har 40 km/h', 'Rekommenderad hastighet i området'],
    correctIndex: 0,
    explanation: 'Zonmärke för hastighet innebär att hela området/zonen har den angivna maxhastigheten, tills du passerar slutmärket.',
  },
  {
    id: 'vag-130',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en blå rektangulär skylt med symbolen för övergångsställe?',
    options: ['Övergångsställe finns här', 'Gångfartsområde', 'Varning för fotgängare'],
    correctIndex: 0,
    explanation: 'Informationsskylten anger att det finns ett övergångsställe på platsen.',
  },
  {
    id: 'vag-131',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'En pilskylt med texten "Avfart 500 m" på motorväg. Vad anger den?',
    options: ['Avfarten är om 500 meter', 'Avfarten är 500 meter lång', 'Hastigheten ska vara 500 m/s'],
    correctIndex: 0,
    explanation: 'Skylten förvarnar om att avfarten från motorvägen är om 500 meter.',
  },
  {
    id: 'vag-132',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en rund skylt med blå bakgrund, vit cykel och fotgängare utan skiljelinje?',
    options: ['Gemensam gång- och cykelbana', 'Separerad gång- och cykelbana', 'Cykelväg med gångförbud'],
    correctIndex: 0,
    explanation: 'Påbudsmärket "Gemensam gång- och cykelbana" (D7) anger att gående och cyklister delar samma bana.',
  },
  {
    id: 'vag-133',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En tilläggstavla visar "Ma-Fr" under ett förbudsmärke. Vad innebär det?',
    options: ['Förbudet gäller måndag till fredag', 'Förbudet gäller mars till fredag', 'Förbudet gäller permanent'],
    correctIndex: 0,
    explanation: 'Ma-Fr anger att förbudet gäller vardagar, dvs. måndag till fredag. Helger är undantagna.',
  },
  {
    id: 'vag-134',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en rektangulär skylt med pilar som pekar åt båda sidor och texten "Vägval"?',
    options: ['Du kan välja mellan två vägar', 'Dubbelriktad väg', 'Korsning framöver'],
    correctIndex: 0,
    explanation: 'Vägvalsskylten anger att du kan välja mellan olika vägar/destinationer.',
  },
  {
    id: 'vag-135',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser märket "Påbjuden körriktning rakt fram och höger" (blå rund med två pilar). Får du svänga vänster?',
    options: ['Nej, du får bara köra rakt fram eller svänga höger', 'Ja, om det finns plats', 'Ja, om du blinkar'],
    correctIndex: 0,
    explanation: 'Påbudsmärket anger exakt vilka riktningar du får köra. Vänstersväng är inte tillåten.',
  },
  {
    id: 'vag-136',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en rund skylt med blå bakgrund och ett vitt rakt streck (lodrät)?',
    options: ['Påbjuden körriktning rakt fram', 'Enkelriktat', 'Stanna här'],
    correctIndex: 0,
    explanation: 'Påbudsmärket anger att du enbart får köra rakt fram genom korsningen.',
  },
  {
    id: 'vag-137',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du kör förbi ett "Slut på motorväg"-märke (E2). Vilken hastighet gäller omedelbart efter?',
    options: ['70 km/h om inte annan skylt anger annat', '110 km/h fortfarande', '50 km/h'],
    correctIndex: 0,
    explanation: 'När motorvägen upphör gäller normalt 70 km/h (landsväg) om inte annan skylt anger en annan hastighet.',
  },
  {
    id: 'vag-138',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad innebär en skylt med en grön pil nedåt och ett rött kryss?',
    options: ['Körfältssignaler — grönt fält öppet, rött stängt', 'Trafikljus framöver', 'Avfart stängd'],
    correctIndex: 0,
    explanation: 'Körfältssignaler visar vilka körfält som är öppna (grön pil) och vilka som är stängda (rött kryss).',
  },
  {
    id: 'vag-139',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Vilken av följande skyltformer anger ett förbudsmärke?',
    options: ['Rund med röd kant', 'Triangulär med spetsen uppåt', 'Rektangulär med blå bakgrund'],
    correctIndex: 0,
    explanation: 'Förbudsmärken är runda med röd kant. Trianglar varnar och rektangulära blå ger information.',
  },
  {
    id: 'vag-140',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en röd triangel med en bild av en vägkorsning i T-form?',
    options: ['Varning för T-korsning', 'Vägen tar slut', 'Rastplats framöver'],
    correctIndex: 0,
    explanation: 'Varningsmärket varnar om en T-korsning framöver där du måste svänga höger eller vänster.',
  },
  {
    id: 'vag-141',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad innebär en skylt med bokstäverna "WC"?',
    options: ['Toalett i närheten', 'Vattenkälla', 'Vårdcentral'],
    correctIndex: 0,
    explanation: 'Skylten anger att det finns en toalett/WC i närheten, t.ex. vid en rastplats.',
  },
  {
    id: 'vag-142',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du passerar en ortstavla och sedan en 30-zon-skylt. Vilken hastighet gäller?',
    options: ['30 km/h — zonmärket gäller', '50 km/h — ortstavlan gäller', 'Den lägsta av de två'],
    correctIndex: 0,
    explanation: 'Zonmärket gäller och sätter den specifika begränsningen. 30-zonen gäller tills slutmärke.',
  },
  {
    id: 'vag-143',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en skylt med texten "Miljözon"?',
    options: ['Område med utsläppskrav för fordon', 'Naturskyddsområde', 'Cykelzon'],
    correctIndex: 0,
    explanation: 'Skylten "Miljözon" anger att området har krav på fordonets utsläppsklass. Fordon som inte uppfyller kraven får inte köra där.',
  },
  {
    id: 'vag-144',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en skylt med en vänd pil (U-sväng-symbol) och rött streck?',
    options: ['U-sväng förbjuden', 'Sväng vänster förbjuden', 'Backning förbjuden'],
    correctIndex: 0,
    explanation: 'Förbudsmärket anger att U-sväng inte är tillåten på denna plats.',
  },
  {
    id: 'vag-145',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Du ser en "Stopplinje" på vägen men ingen stopskylt. Vad gäller?',
    options: ['Du måste stanna vid linjen om trafikljus eller annan signal kräver det', 'Du måste alltid stanna', 'Stopplinjen gäller inte utan skylt'],
    correctIndex: 0,
    explanation: 'En stopplinje utan stoppskylt anger var du ska stanna om trafikljus, polisman eller annan signal kräver stopp.',
  },
  {
    id: 'vag-146',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger numrerade avfartsskyltar (vit siffra på blå bakgrund) på motorväg?',
    options: ['Avfartens nummer', 'Avstånd till avfarten i km', 'Hastighetsgräns vid avfarten'],
    correctIndex: 0,
    explanation: 'Siffran anger avfartens nummer, inte avstånd. Använd den för att identifiera rätt avfart.',
  },
  {
    id: 'vag-147',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'En tilläggstavla med symbolen "10 t BK1" anger:',
    options: ['Bärighetsklass — vägens maximala belastning', 'Maxvikt 10 ton per fordon', 'Fordon över 10 ton betalar avgift'],
    correctIndex: 0,
    explanation: 'BK (bärighetsklass) anger vägens maximala belastningskapacitet. BK1 tillåter tyngst trafik.',
  },
  {
    id: 'vag-148',
    category: 'vagmarken',
    difficulty: 'easy',
    question: 'Vad anger en rektangulär gul skylt med en svart pil?',
    options: ['Kurvpil — visar vägkurvans riktning', 'Omledning', 'Avfart'],
    correctIndex: 0,
    explanation: 'Kurvpilar (gula med svart pil) placeras i skarpa kurvor för att visa kurvans riktning.',
  },
  {
    id: 'vag-149',
    category: 'vagmarken',
    difficulty: 'medium',
    question: 'Vad anger en skylt med texten "Bom" och en röd triangel?',
    options: ['Varning för vägbom framöver', 'Bomstängning pågår', 'Vägtull framöver'],
    correctIndex: 0,
    explanation: 'Varningsmärket varnar om att det finns en vägbom framöver som kan vara stängd.',
  },
  {
    id: 'vag-150',
    category: 'vagmarken',
    difficulty: 'hard',
    question: 'Två förbudsmärken sitter på samma stolpe — "Parkering förbjuden" och "Gäller ej 19-07". Får du parkera kl. 21?',
    options: ['Ja, undantaget gäller kl. 19-07', 'Nej, förbudet gäller dygnet runt', 'Bara om det finns lediga platser'],
    correctIndex: 0,
    explanation: 'Tilläggstavlan "Gäller ej 19-07" undantar tidsperioden. Kl. 21 är inom undantaget, så parkering är tillåten.',
  },
];
