import { Question } from './types';

export const vagmarkeringarQuestions: Question[] = [
  {
    id: 'vmk-1',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad betyder en heldragen mittlinje på vägen?',
    options: [
      'Förbud mot att köra om genom att passera linjen',
      'Rekommenderad körbana',
      'Att hastigheten är begränsad',
    ],
    correctIndex: 0,
    explanation: 'En heldragen mittlinje (spärrlinje) får inte passeras eller köras på. Det innebär förbud mot omkörning genom att korsa linjen.',
  },
  {
    id: 'vmk-2',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad betyder en streckad mittlinje?',
    options: [
      'Omkörning är tillåten om det kan ske säkert',
      'Omkörning är förbjuden',
      'Vägen är enkelriktad',
    ],
    correctIndex: 0,
    explanation: 'En streckad mittlinje innebär att man får korsa linjen för omkörning, förutsatt att det kan göras utan fara.',
  },
  {
    id: 'vmk-3',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Det finns en heldragen linje på din sida och en streckad på motstående sida. Får du köra om?',
    options: [
      'Nej, den heldragna linjen på din sida gäller för dig',
      'Ja, den streckade linjen gäller alltid',
      'Ja, om hastigheten är under 50 km/h',
    ],
    correctIndex: 0,
    explanation: 'Det är linjen närmast dig som gäller. En heldragen linje på din sida betyder att du inte får korsa den, oavsett vad som finns på motstående sida.',
  },
  {
    id: 'vmk-4',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar gula linjer i vägkanten?',
    options: [
      'Förbud mot att stanna eller parkera',
      'Busshållplats',
      'Cykelbana',
    ],
    correctIndex: 0,
    explanation: 'Gula kantlinjer anger att stannande och/eller parkering är förbjuden. Heldragen gul linje = förbud mot stannande. Streckad gul linje = förbud mot parkering.',
  },
  {
    id: 'vmk-5',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad anger vita sicksacklinjer i vägkanten?',
    options: [
      'Förbud mot att stanna och parkera vid busshållplats',
      'Övergångsställe för cyklister',
      'Hastighetsbegränsning',
    ],
    correctIndex: 0,
    explanation: 'Vita sicksacklinjer markerar en busshållplats och innebär att det är förbjudet att stanna eller parkera på det markerade området.',
  },
  {
    id: 'vmk-6',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad betyder ett målat övergångsställe (zebraränder)?',
    options: [
      'Fotgängare har företräde att korsa vägen',
      'Cyklister har företräde',
      'Genomfart förbjuden',
    ],
    correctIndex: 0,
    explanation: 'Breda vita ränder tvärs över vägen markerar ett övergångsställe där fotgängare har företräde. Förare måste stanna och släppa fram fotgängare.',
  },
  {
    id: 'vmk-7',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad betyder en bred heldragen linje tvärs över körbanan vid en korsning?',
    options: [
      'Stopplinje — du måste stanna helt innan du fortsätter',
      'Hastighetsbegränsning',
      'Cykelfält börjar',
    ],
    correctIndex: 0,
    explanation: 'En stopplinje visar var du ska stanna vid en korsning med stoppskylt eller rött trafikljus. Du måste stanna helt med framhjulen bakom linjen.',
  },
  {
    id: 'vmk-8',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad betyder trianglar (hajtänder) målade på vägen?',
    options: [
      'Väjningsplikt — du måste lämna företräde',
      'Varning för ojämn väg',
      'Farthinder',
    ],
    correctIndex: 0,
    explanation: 'Trianglar (hajtänder) på vägen markerar väjningsplikt. Du måste sakta ner och lämna företräde åt trafik på den korsande vägen.',
  },
  {
    id: 'vmk-9',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad innebär en spärrlinje med dubbelheldragna linjer?',
    options: [
      'Ingen trafik får passera linjen oavsett riktning',
      'Bara bussar får passera',
      'Bara vid nödsituationer',
    ],
    correctIndex: 0,
    explanation: 'Dubbelheldragna linjer innebär total spärr — ingen trafik i någon riktning får korsa dem. Detta används på vägar med hög trafikintensitet.',
  },
  {
    id: 'vmk-10',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'En cykelpassage markeras med vita rutor (fyrkanter) på vägen. Vilken skyldighet har bilföraren?',
    options: [
      'Anpassa hastigheten så att det inte uppstår fara för cyklister',
      'Alltid stanna och ge cyklister företräde',
      'Cyklisterna måste ge bilisten företräde',
    ],
    correctIndex: 0,
    explanation: 'Vid cykelpassage (vita rutor) ska bilföraren anpassa hastigheten och visa hänsyn till cyklister. Cyklister har dock inte automatisk företräde som vid övergångsställe — men föraren måste visa aktsamhet.',
  },
  {
    id: 'vmk-11',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar en målad pil i körfältet?',
    options: [
      'Vilken riktning du ska eller får köra i det körfältet',
      'Att hastigheten ska ökas',
      'Att vägen snart tar slut',
    ],
    correctIndex: 0,
    explanation: 'Pilar i körfältet visar vilken körriktning som gäller. Du måste följa pilen och välja rätt körfält i god tid.',
  },
  {
    id: 'vmk-12',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad anger en streckad kantlinje (vit, längs vägen)?',
    options: [
      'Vägbanans kant — du bör hålla dig innanför linjen',
      'Cykelfält',
      'Parkeringszon',
    ],
    correctIndex: 0,
    explanation: 'En streckad vit kantlinje markerar vägbanans begränsning. Den hjälper föraren att hålla sig på vägen, särskilt i mörker och dålig sikt.',
  },
  {
    id: 'vmk-13',
    category: 'vagmarkeringar',
    difficulty: 'hard',
    question: 'Vad innebär en varningslinje (lång streckad linje med korta mellanrum)?',
    options: [
      'Varning — heldragen spärrlinje kommer snart, avsluta ev. omkörning',
      'Att du ska byta fil',
      'Att hastigheten ökar',
    ],
    correctIndex: 0,
    explanation: 'En varningslinje har längre streck och kortare mellanrum än en vanlig streckad linje. Den varnar om att en heldragen linje närmar sig — avsluta omkörning i tid.',
  },
  {
    id: 'vmk-14',
    category: 'vagmarkeringar',
    difficulty: 'medium',
    question: 'Vad markerar rutnätsmönster målat på vägen i en korsning?',
    options: [
      'Du får inte stanna i det markerade området',
      'Parkering tillåten',
      'Farthinder',
    ],
    correctIndex: 0,
    explanation: 'Rutnätsmönster (gult eller vitt) i en korsning innebär att du inte får stanna i det området, även om du har grönt ljus. Syftet är att förhindra att korsningen blockeras.',
  },
  {
    id: 'vmk-15',
    category: 'vagmarkeringar',
    difficulty: 'easy',
    question: 'Vad markerar texten "BUS" målad på ett körfält?',
    options: [
      'Körfältet är reserverat för bussar',
      'Busshållplats ahead',
      'Buss får inte köra här',
    ],
    correctIndex: 0,
    explanation: 'Texten "BUS" eller "BUSS" på körfältet anger att det är ett bussfält. Andra fordon får normalt inte använda bussfält under de tider det gäller.',
  },
];
