import { Question } from './types';

export const vajningspliktQuestions: Question[] = [
  // === EASY (10 questions) ===
  {
    id: 'vaj-1',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad innebär högerregeln?',
    options: [
      'Du ska väja för fordon som kommer från höger',
      'Du ska alltid köra till höger på vägen',
      'Du ska väja för fordon som kommer från vänster',
    ],
    correctIndex: 0,
    explanation:
      'Högerregeln innebär att du ska lämna företräde åt fordon som närmar sig från höger i en korsning där inga andra trafikregler gäller.',
  },
  {
    id: 'vaj-2',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad betyder en triangelformad skylt med spetsen nedåt (väjningspliktsskylten)?',
    options: [
      'Du har företräde',
      'Du ska lämna företräde åt trafik på den korsande vägen',
      'Du ska stanna helt innan du kör vidare',
    ],
    correctIndex: 1,
    explanation:
      'Väjningspliktsskylten (omvänd triangel) innebär att du ska lämna företräde åt fordon på den korsande vägen. Du behöver inte stanna helt om det är fritt.',
  },
  {
    id: 'vaj-3',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad gäller när du kör ut från en parkeringsplats?',
    options: [
      'Du har företräde framför trafiken på vägen',
      'Du ska väja för all trafik på vägen du kör ut på',
      'Högerregeln avgör vem som har företräde',
    ],
    correctIndex: 1,
    explanation:
      'När du kör ut från en parkeringsplats, bensinstation, gårdsplan eller liknande ska du alltid väja för all trafik på vägen du kör ut på.',
  },
  {
    id: 'vaj-4',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vilken skylt innebär att du måste stanna helt innan du kör vidare?',
    options: [
      'Väjningspliktsskylten (omvänd triangel)',
      'Stoppskylt (oktagon med texten STOP)',
      'Huvudledsskylt (gul romb)',
    ],
    correctIndex: 1,
    explanation:
      'Stoppskylt (oktagonformad med texten STOP) innebär att du måste stanna helt vid stopplinje eller korsningen, och sedan lämna företräde åt korsande trafik.',
  },
  {
    id: 'vaj-5',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad gäller vid en cirkulationsplats (rondell)?',
    options: [
      'Du som kör inne i rondellen ska väja för inkommande trafik',
      'Du ska alltid väja för trafik som redan är inne i cirkulationsplatsen',
      'Högerregeln gäller alltid i en rondell',
    ],
    correctIndex: 1,
    explanation:
      'Vid infart till en cirkulationsplats finns normalt väjningspliktsskylt. Du ska lämna företräde åt fordon som redan befinner sig i cirkulationsplatsen.',
  },
  {
    id: 'vaj-6',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad gäller när en spårvagn korsar din väg?',
    options: [
      'Du har alltid företräde framför spårvagnen',
      'Spårvagn har som regel företräde i korsningar',
      'Högerregeln gäller även för spårvagnar',
    ],
    correctIndex: 1,
    explanation:
      'Spårvagnar har som huvudregel företräde i korsningar, oavsett från vilket håll de kommer. Undantag är om spårvagnen har rött ljus eller väjningsplikt.',
  },
  {
    id: 'vaj-7',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad ska du göra när ett utryckningsfordon närmar sig med blåljus och siren?',
    options: [
      'Stanna omedelbart var du än befinner dig',
      'Lämna fri väg genom att köra åt sidan och om nödvändigt stanna',
      'Öka farten för att komma undan snabbare',
    ],
    correctIndex: 1,
    explanation:
      'Du ska lämna fri väg för utryckningsfordon med påslagna blåljus och siren. Kör åt sidan och stanna om nödvändigt, men gör det på ett säkert sätt.',
  },
  {
    id: 'vaj-8',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad innebär det att köra på en huvudled?',
    options: [
      'Du har företräde i korsningar mot anslutande vägar',
      'Du måste alltid hålla minst 70 km/h',
      'Du får inte svänga vänster',
    ],
    correctIndex: 0,
    explanation:
      'På en huvudled har du företräde mot korsande och anslutande vägar. Fordon som ska in på huvudleden har väjningsplikt eller stopplikt.',
  },
  {
    id: 'vaj-9',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Du kör ut från en gångfartsväg till en vanlig väg. Vad gäller?',
    options: [
      'Du har företräde eftersom du kommer från höger',
      'Du ska väja för all trafik på vägen du kör ut på',
      'Samma regler gäller som i vilken korsning som helst',
    ],
    correctIndex: 1,
    explanation:
      'Utfart från en gångfartsväg likställs med utfart från t.ex. parkeringsplats. Du ska väja för all trafik på vägen du kör ut på.',
  },
  {
    id: 'vaj-10',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad skiljer väjningsplikt från stoppplikt?',
    options: [
      'Det finns ingen skillnad',
      'Vid stoppplikt måste du alltid stanna helt, vid väjningsplikt behöver du bara sakta ner och väja',
      'Vid väjningsplikt måste du stanna helt, vid stoppplikt räcker det att sakta ner',
    ],
    correctIndex: 1,
    explanation:
      'Vid stoppplikt (STOP-skylt) måste du alltid stanna helt vid stopplinje. Vid väjningsplikt ska du lämna företräde men behöver inte stanna om vägen är fri.',
  },

  // === MEDIUM (12 questions) ===
  {
    id: 'vaj-11',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du närmar dig en korsning utan vägmärken eller signaler. Från vänster kommer en bil och från höger en cyklist. Vem ska du väja för?',
    options: [
      'Bara bilen från vänster',
      'Bara cyklisten från höger',
      'Cyklisten från höger, men inte bilen från vänster',
    ],
    correctIndex: 2,
    explanation:
      'Högerregeln gäller alla fordon, inklusive cyklister. Du ska väja för cyklisten som kommer från höger. Bilen från vänster ska väja för dig.',
  },
  {
    id: 'vaj-12',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du ska svänga vänster i en korsning. Vad gäller gentemot mötande trafik?',
    options: [
      'Du har företräde om du hunnit ut i korsningen först',
      'Du ska lämna företräde åt mötande trafik som kör rakt fram eller svänger höger',
      'Mötande trafik ska alltid väja för dig',
    ],
    correctIndex: 1,
    explanation:
      'Vid vänstersväng ska du lämna företräde åt mötande fordon som kör rakt fram eller svänger höger. Detta gäller även om du hunnit ut i korsningen.',
  },
  {
    id: 'vaj-13',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Två bilar möts i en brant backe som är för smal för att passera. Vem ska backa?',
    options: [
      'Den som kör uppför backen ska backa',
      'Den som kör nedför backen ska backa',
      'Den som har längst att backa ska backa',
    ],
    correctIndex: 1,
    explanation:
      'Vid möte i backe ska den som kör nedför ge den som kör uppför företräde, eftersom det är svårare att starta i en uppförsbacke. Den som kör nedför backar alltså.',
  },
  {
    id: 'vaj-14',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör ut från en tankstation. En cykel kommer på cykelbanan utanför. Vad gäller?',
    options: [
      'Cyklisten ska väja för dig',
      'Du ska väja för cyklisten',
      'Högerregeln avgör',
    ],
    correctIndex: 1,
    explanation:
      'Vid utfart från tankstation, parkering eller liknande ska du alltid väja för all trafik, inklusive cyklister och gående på gång- och cykelbanor.',
  },
  {
    id: 'vaj-15',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Gäller högerregeln om du kör på en väg med utfartsväg från höger (t.ex. gårdsplan)?',
    options: [
      'Ja, du ska alltid väja för fordon från höger',
      'Nej, fordon som kör ut från utfart har alltid väjningsplikt oavsett riktning',
      'Det beror på om det finns vägmarkeringar',
    ],
    correctIndex: 1,
    explanation:
      'Högerregeln gäller inte vid utfart. Den som kör ut från en gårdsplan, parkeringsplats eller liknande har alltid väjningsplikt mot trafiken på vägen.',
  },
  {
    id: 'vaj-16',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du gör en U-sväng. Vad gäller gentemot övrig trafik?',
    options: [
      'Du har företräde om du visar tecken i tid',
      'Du ska lämna företräde åt all annan trafik',
      'Högerregeln avgör',
    ],
    correctIndex: 1,
    explanation:
      'Den som vänder (gör U-sväng) ska lämna företräde åt all annan trafik. En U-sväng innebär alltid väjningsplikt.',
  },
  {
    id: 'vaj-17',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kommer till en korsning med trafikljus. Ljuset är grönt men en fotgängare är kvar på övergångsstället. Vad gäller?',
    options: [
      'Du kan köra eftersom du har grönt ljus',
      'Du ska låta fotgängaren passera klart innan du kör',
      'Fotgängaren ska skynda sig ur vägen',
    ],
    correctIndex: 1,
    explanation:
      'Även om du har grönt ljus ska du inte köra om en fotgängare fortfarande befinner sig på övergångsstället. Fotgängarens säkerhet går alltid först.',
  },
  {
    id: 'vaj-18',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Två fordon kommer samtidigt till en fyrvägskorsning utan skyltar. Bil A kommer från öster, bil B från söder. Vem har företräde?',
    options: [
      'Bil A, eftersom den kommer från höger sett från bil B',
      'Bil B, eftersom den kommer från höger sett från bil A',
      'Den som kom till korsningen först',
    ],
    correctIndex: 0,
    explanation:
      'Högerregeln gäller. Bil B ska väja för bil A som kommer från höger (från öster sett från bil B som kör norrut).',
  },
  {
    id: 'vaj-19',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Vad gäller i ett gångfartsområde?',
    options: [
      'Bilar har alltid företräde framför gående',
      'Fordonsförare ska anpassa hastigheten till gångtrafik och har väjningsplikt mot gående',
      'Det är förbjudet att köra bil i ett gångfartsområde',
    ],
    correctIndex: 1,
    explanation:
      'I ett gångfartsområde ska fordon köras i gångfart (max ca 7 km/h) och föraren har väjningsplikt mot gående. Gående har företräde men får inte hindra fordon i onödan.',
  },
  {
    id: 'vaj-20',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du har grönt ljus och ska svänga höger. En cyklist har grönt och ska rakt fram i samma riktning. Vem har företräde?',
    options: [
      'Du, eftersom bilar har företräde framför cyklar',
      'Cyklisten, eftersom den kör rakt fram',
      'Den som kommer först till korsningen',
    ],
    correctIndex: 1,
    explanation:
      'Vid högersväng ska du lämna företräde åt cyklister som kör rakt fram på din högra sida, även om ni båda har grönt ljus.',
  },
  {
    id: 'vaj-21',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Trafikljusen i en korsning har slutat fungera. Vad gäller?',
    options: [
      'Du ska stanna och vänta tills ljusen repareras',
      'Högerregeln gäller om inga andra vägmärken finns',
      'Den som kör snabbast har företräde',
    ],
    correctIndex: 1,
    explanation:
      'Om trafikljusen är ur funktion gäller de vägmärken som finns. Saknas vägmärken tillämpas högerregeln.',
  },
  {
    id: 'vaj-22',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör på en väg och en polis dirigerar trafiken i en korsning. Polisen visar att du ska stanna, men trafikljuset är grönt. Vad gäller?',
    options: [
      'Grönt ljus gäller, du kan köra',
      'Polisens tecken gäller före trafikljuset',
      'Du ska köra försiktigt genom korsningen',
    ],
    correctIndex: 1,
    explanation:
      'En polis som dirigerar trafiken har alltid företräde framför trafikljus och vägmärken. Du ska följa polisens anvisningar.',
  },

  // === HARD (8 questions) ===
  {
    id: 'vaj-23',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör på en huvudled och ska svänga vänster in på en mindre väg. Mötande bil kör rakt fram. Vem har företräde?',
    options: [
      'Du, eftersom du kör på huvudleden',
      'Mötande bil, eftersom du svänger vänster och ska lämna företräde åt mötande',
      'Den som hinner först in i korsningen',
    ],
    correctIndex: 1,
    explanation:
      'Trots att du kör på huvudleden måste du vid vänstersväng lämna företräde åt mötande trafik som kör rakt fram. Huvudled ger företräde mot korsande vägar, inte mot mötande.',
  },
  {
    id: 'vaj-24',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du och en spårvagn närmar er en korsning utan signaler eller vägmärken. Spårvagnen kommer från vänster. Vem har företräde?',
    options: [
      'Du, eftersom spårvagnen kommer från vänster',
      'Spårvagnen, eftersom spårvagnar i princip alltid har företräde i obevakade korsningar',
      'Ingen har företräde, ni måste samsas',
    ],
    correctIndex: 1,
    explanation:
      'Spårvagnar har som huvudregel företräde oavsett från vilket håll de kommer i korsningar utan trafikljus, även om de kommer från vänster.',
  },
  {
    id: 'vaj-25',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du ska köra in i en cirkulationsplats och har väjningsplikt. Inne i rondellen kör en bil som blinkar höger för att lämna rondellen precis före din infart. Får du köra in?',
    options: [
      'Ja, du kan köra in direkt eftersom bilen lämnar rondellen',
      'Nej, du måste fortfarande försäkra dig om att bilen verkligen lämnar och att ingen annan trafik kommer',
      'Ja, blinkern räcker som garanti',
    ],
    correctIndex: 1,
    explanation:
      'Även om ett fordon blinkar höger kan det ändra sig eller ha fel blinker. Du har väjningsplikt och måste försäkra dig om att det verkligen är säkert innan du kör in.',
  },
  {
    id: 'vaj-26',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör på en väg med väjningspliktsskylt och närmar dig korsningen. En ambulans med blåljus och siren kommer på den korsande vägen. Vad gäller?',
    options: [
      'Du har redan väjningsplikt, så du stannar som vanligt',
      'Du ska stanna och ge företräde, men av dubbla skäl: väjningsplikt och utryckningsfordon',
      'Ambulansen ska väja för dig eftersom du redan stannat',
    ],
    correctIndex: 1,
    explanation:
      'Du har väjningsplikt mot korsande trafik, och utryckningsfordon med blåljus och siren ska dessutom alltid lämnas fri väg. Stanna och låt ambulansen passera.',
  },
  {
    id: 'vaj-27',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'I en korsning gäller högerregeln. Du kör rakt fram. Från höger kommer en bil, och från vänster kommer ytterligare en bil. Bilen från höger ska svänga vänster (in på din väg). Vad händer?',
    options: [
      'Du väjer för bilen från höger, och den väjer i sin tur för bilen från vänster som kör rakt fram',
      'Alla tre kan köra samtidigt utan problem',
      'Du har företräde framför båda bilarna',
    ],
    correctIndex: 0,
    explanation:
      'Du ska väja för bilen från höger (högerregeln). Men den bilen ska i sin tur vid vänstersväng lämna företräde åt mötande (bilen från din vänstra sida). Alla måste respektera sina egna väjningsplikter.',
  },
  {
    id: 'vaj-28',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör på en väg där hastigheten är 50 km/h. En buss har stannat vid en busshållplats och blinkar för att köra ut. Vad gäller?',
    options: [
      'Du ska alltid lämna företräde åt bussen',
      'Du ska ge bussen möjlighet att köra ut om hastighetsbegränsningen är högst 50 km/h',
      'Bussen har aldrig företräde',
    ],
    correctIndex: 1,
    explanation:
      'Om hastighetsbegränsningen är högst 50 km/h ska du ge bussen möjlighet att lämna hållplatsen. Du ska sakta ner och om nödvändigt stanna.',
  },
  {
    id: 'vaj-29',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör och ser ett vägmärke som anger slutet på huvudled. Kort därefter kommer en korsning utan skyltar. Vad gäller?',
    options: [
      'Du har fortfarande företräde i nästa korsning',
      'Högerregeln gäller i nästa korsning eftersom huvudleden har upphört',
      'Du har väjningsplikt i nästa korsning',
    ],
    correctIndex: 1,
    explanation:
      'När skylt anger att huvudled upphör gäller inte längre företräde. I efterföljande korsning utan vägmärken tillämpas högerregeln.',
  },
  {
    id: 'vaj-30',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör på en smal väg och möter en lastbil. Bredvid dig finns en mötesplats (ficka) på din sida. Vad gäller?',
    options: [
      'Lastbilen ska backa eftersom den är störst',
      'Du ska använda mötesplatsen och lämna företräde åt lastbilen',
      'Den som kör fortast har företräde',
    ],
    correctIndex: 1,
    explanation:
      'På smala vägar ska du använda mötesplatsen om den finns på din sida. Tyngre eller större fordon har svårare att manövrera, och du bör underlätta för mötande trafik.',
  },
  {
    id: 'vaj-31',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Du kör mot en korsning och ser en väjningspliktsskylt. Vägen är fri. Måste du stanna?',
    options: ['Ja, du måste alltid stanna vid väjningsplikt', 'Nej, du behöver bara sakta ner och köra vidare om det är fritt', 'Ja, i minst 3 sekunder'],
    correctIndex: 1,
    explanation: 'Vid väjningsplikt ska du lämna företräde, men du behöver inte stanna helt om vägen är fri. Vid stoppplikt måste du dock alltid stanna.',
  },
  {
    id: 'vaj-32',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vem har företräde vid ett övergångsställe?',
    options: ['Bilisten om det inte finns trafikljus', 'Fotgängaren som gått ut eller tydligt visar att den vill gå ut', 'Den som kom först'],
    correctIndex: 1,
    explanation: 'Fotgängare har företräde vid övergångsställe. Du ska stanna och låta fotgängaren passera.',
  },
  {
    id: 'vaj-33',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Du ska köra ut från en gård eller fastighet. Vem ska du väja för?',
    options: ['Bara bilar', 'All trafik på vägen — bilar, cyklister och gående', 'Bara gående'],
    correctIndex: 1,
    explanation: 'När du kör ut från en gård, parkering, fastighet eller liknande har du väjningsplikt mot all trafik på vägen.',
  },
  {
    id: 'vaj-34',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad innebär stopplinjen vid en korsning?',
    options: ['Du ska stanna innan du passerar linjen', 'Du ska sakta ner', 'Du ska blinka'],
    correctIndex: 0,
    explanation: 'Stopplinjen markerar var du ska stanna. Vid stoppskylt måste du stanna helt vid stopplinjen.',
  },
  {
    id: 'vaj-35',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'En polis dirigerar trafiken och vinkar dig framåt. Trafikljuset visar rött. Vad gör du?',
    options: ['Stannar, rött ljus gäller', 'Kör, polisens tecken gäller', 'Väntar tills ljuset blir grönt'],
    correctIndex: 1,
    explanation: 'Polisens anvisningar gäller alltid före trafikljus och vägmärken.',
  },
  {
    id: 'vaj-36',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Du backar ut från en parkeringsruta. Vem har företräde?',
    options: ['Du, eftersom du redan började backa', 'All övrig trafik, du har väjningsplikt', 'Den som tutar först'],
    correctIndex: 1,
    explanation: 'Den som backar har alltid väjningsplikt mot övrig trafik.',
  },
  {
    id: 'vaj-37',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör på en väg med skyltad hastighetsbegränsning 70 km/h. En buss blinkar ut från hållplats. Vad gäller?',
    options: ['Du ska ge bussen möjlighet att köra ut', 'Du har företräde, bussen ska vänta', 'Bussen har bara företräde vid 50 km/h'],
    correctIndex: 2,
    explanation: 'Regeln om att ge buss företräde vid uthållplats gäller bara där hastighetsbegränsningen är högst 50 km/h. Vid 70 km/h har du företräde.',
  },
  {
    id: 'vaj-38',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör i en rondell och ska lämna den vid tredje avfarten. Hur blinkar du?',
    options: ['Vänster in, höger ut', 'Ingen blinker behövs', 'Höger hela vägen'],
    correctIndex: 0,
    explanation: 'I en rondell blinkar du vänster så länge du ska fortsätta runt, och höger när du ska ut.',
  },
  {
    id: 'vaj-39',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Två bilar möts vid en korsning. Bil A kör rakt fram, bil B ska svänga vänster. Båda har grönt. Vem har företräde?',
    options: ['Bil A, den som kör rakt fram', 'Bil B, den som svänger', 'Ingen, båda har grönt'],
    correctIndex: 0,
    explanation: 'Den som svänger vänster ska lämna företräde åt mötande trafik som kör rakt fram, även om båda har grönt.',
  },
  {
    id: 'vaj-40',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör på en gata och ska svänga höger. En cyklist cyklar i samma riktning på cykelbanans fortsättning. Vem har företräde?',
    options: ['Du, bilen har alltid företräde', 'Cyklisten, du ska lämna företräde vid sväng', 'Den som kom först'],
    correctIndex: 1,
    explanation: 'Vid höger- eller vänstersväng ska du lämna företräde åt cyklister som korsar den väg du svänger in på.',
  },
  {
    id: 'vaj-41',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör in på en gångfartsväg. Vilka har företräde?',
    options: ['Gående har företräde framför fordon', 'Du har företräde som bilist', 'Ingen har företräde, alla samsas'],
    correctIndex: 0,
    explanation: 'På gångfartsvägar har gående företräde framför fordon. Du ska anpassa hastigheten till gångtakt.',
  },
  {
    id: 'vaj-42',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Vid en signalreglerad korsning visar ljuset blinkande gult. Vad gäller?',
    options: ['Kör försiktigt, högerregeln eller vägmärken gäller', 'Stopp', 'Kör som vanligt på grönt'],
    correctIndex: 0,
    explanation: 'Blinkande gult betyder att trafikljusen inte fungerar normalt. Kör försiktigt och följ eventuella vägmärken eller högerregeln.',
  },
  {
    id: 'vaj-43',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör och ser att en skolbuss har stannat med varningsblinkers. Vad bör du göra?',
    options: ['Köra förbi i normal hastighet', 'Sakta ner rejält och vara beredd att stanna — barn kan korsa', 'Stanna helt och vänta'],
    correctIndex: 1,
    explanation: 'En skolbuss med blinkande varningsljus betyder att barn kan korsa vägen. Var extra försiktig och sänk hastigheten.',
  },
  {
    id: 'vaj-44',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du ska svänga vänster i en korsning. En mötande bil blinkar höger. Får du köra?',
    options: ['Ja, den mötande bilen svänger undan', 'Nej, du ska vänta tills du är helt säker på vad mötande gör', 'Ja, blinker ger dig företräde'],
    correctIndex: 1,
    explanation: 'Lita inte blint på blinkers — föraren kan ha fel blinker eller ändra sig. Säkerställ att det verkligen är fritt innan du svänger.',
  },
  {
    id: 'vaj-45',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör rakt fram i en korsning. Från höger kommer en bil som också kör rakt fram, men den befinner sig på en utfartsväg (skyltad som utfart). Vem har företräde?',
    options: ['Bilen från höger (högerregeln)', 'Du, eftersom utfartsvägar inte ger högerregelsföreträde', 'Ingen, ni ska stanna båda'],
    correctIndex: 1,
    explanation: 'Utfarter (garageinfarter, parkeringsutfarter osv.) ger inte högerregelsföreträde. Du på genomfartsgatan har företräde.',
  },
  {
    id: 'vaj-46',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'En cykel och en bil närmar sig samma korsning utan vägmärken. Cykeln kommer från höger. Vem har företräde?',
    options: ['Bilen, cyklister räknas inte i högerregeln', 'Cykeln, högerregeln gäller alla fordon inklusive cyklar', 'Den som är snabbast'],
    correctIndex: 1,
    explanation: 'Högerregeln gäller för alla fordon, inklusive cyklar. Cykeln som kommer från höger har företräde.',
  },
  {
    id: 'vaj-47',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör i en korsning med separata svängsignaler. Du har grön svängpil åt vänster. Har du företräde mot mötande?',
    options: ['Ja, grön svängpil ger fullt företräde', 'Nej, du ska ändå väja för mötande', 'Bara om mötande har rött'],
    correctIndex: 0,
    explanation: 'En separat grön svängpil ger dig företräde — mötande trafik har rött i din svängriktning.',
  },
  {
    id: 'vaj-48',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Tre bilar möts i en korsning med högerregeln. Bil A har bil B till höger, bil B har bil C till höger, bil C har bil A till höger. Vad händer?',
    options: ['Alla ska väja för varandra — en dödläge-situation', 'Bil A kör först', 'Bil C kör först'],
    correctIndex: 0,
    explanation: 'Det uppstår ett dödläge. I praktiken löser man det genom att en förare visar med tecken att den andra får köra först.',
  },
  {
    id: 'vaj-49',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör i fil 2 och ska byta till fil 1 (höger fil). En annan bil kör i fil 1. Vem har företräde?',
    options: ['Du, vänster fil har företräde', 'Bilen i fil 1 — den som byter fil har väjningsplikt', 'Den som kör snabbast'],
    correctIndex: 1,
    explanation: 'Den som byter fil har alltid väjningsplikt mot trafik i det fält man byter till.',
  },
  {
    id: 'vaj-50',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du närmar dig en cykelpassage. Måste du stanna?',
    options: ['Ja, precis som vid övergångsställe', 'Nej, men du ska anpassa hastigheten så att du inte hindrar cyklister', 'Nej, cyklister ska stanna'],
    correctIndex: 1,
    explanation: 'Vid en cykelpassage (markerad med fyrkanter) ska du anpassa hastigheten, men cyklister har inte automatiskt företräde som fotgängare vid övergångsställe.',
  },
  {
    id: 'vaj-51',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Du kör mot en korsning med stoppskylt. Du stannar vid stopplinjen. Vägen är helt fri. Får du köra direkt?',
    options: ['Nej, du måste vänta minst 5 sekunder', 'Ja, du har stannat och sett att det är fritt', 'Nej, du måste vänta på grön signal'],
    correctIndex: 1,
    explanation: 'Vid stoppskylt ska du stanna helt. När du konstaterat att det är fritt får du köra vidare.',
  },
  {
    id: 'vaj-52',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du ska svänga vänster i en korsning. Framför dig i mötande riktning ska en bil också svänga vänster. Hur passerar ni varandra?',
    options: ['Ni svänger framför varandra', 'Ni svänger bakom varandra', 'Den som kom först svänger'],
    correctIndex: 0,
    explanation: 'Huvudregeln i Sverige är att två mötande vänstersvängande bilar passerar framför varandra (nosa mot nosa).',
  },
  {
    id: 'vaj-53',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör rakt fram genom en korsning. En gående vill korsa gatan men det finns inget övergångsställe. Vem har företräde?',
    options: ['Du, det finns inget övergångsställe', 'Gående har alltid företräde oavsett', 'Du, men du bör visa hänsyn'],
    correctIndex: 2,
    explanation: 'Utan övergångsställe har gående inte laglig företräde, men du ska alltid visa hänsyn och var beredd att stanna.',
  },
  {
    id: 'vaj-54',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'En ambulans med blåljus och siren närmar sig bakifrån. Du kör i vänsterfilen. Vad gör du?',
    options: ['Ökar farten för att komma undan', 'Kör åt höger och stannar om möjligt', 'Stannar direkt i din fil'],
    correctIndex: 1,
    explanation: 'Du ska flytta dig åt höger och om nödvändigt stanna för att ge ambulansen fri väg.',
  },
  {
    id: 'vaj-55',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör på en enskild väg som ansluter till en allmän väg. Vem har företräde?',
    options: ['Du, om det inte finns någon skylt', 'Trafik på den allmänna vägen, du har väjningsplikt', 'Den som kom först'],
    correctIndex: 1,
    explanation: 'Fordon på enskild väg som kör ut på allmän väg har väjningsplikt mot all trafik på den allmänna vägen.',
  },
  {
    id: 'vaj-56',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör i en rondell. En annan bil kör in utan att väja. Vad bör du göra?',
    options: ['Tuta och kör vidare', 'Bromsa och undvik kollision, även om du har rätt', 'Kör fortare för att hinna före'],
    correctIndex: 1,
    explanation: 'Oavsett vem som har företräde ska du alltid undvika en olycka. Företräde betyder inte att man kan orsaka en krock.',
  },
  {
    id: 'vaj-57',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Du gör en vänstersväng. Var ska du hålla dig på vägen?',
    options: ['Nära vänsterkanten/mitten av vägen', 'I högra körfältet', 'Var som helst'],
    correctIndex: 0,
    explanation: 'Vid vänstersväng ska du placera dig nära mittlinjen eller i det vänstra körfältet.',
  },
  {
    id: 'vaj-58',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör på en huvudled och ser en tilläggstavla med pilar som visar att huvudleden svänger åt höger. Du ska köra rakt fram. Vad gäller?',
    options: ['Du har fortfarande företräde', 'Du lämnar huvudleden och högerregeln kan gälla', 'Alla har företräde'],
    correctIndex: 1,
    explanation: 'Om huvudleden svänger och du kör rakt fram lämnar du huvudleden. Vid korsningen gäller de skyltar som finns, annars högerregeln.',
  },
  {
    id: 'vaj-59',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör ut ur en tunnel och in i en korsning. Gäller högerregeln?',
    options: ['Nej, tunnelutfarter har alltid företräde', 'Ja, om inga skyltar anger annat', 'Nej, du har väjningsplikt'],
    correctIndex: 1,
    explanation: 'Att köra ut ur en tunnel ändrar inte trafikreglerna. Högerregeln gäller om inga vägmärken anger annat.',
  },
  {
    id: 'vaj-60',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad ska du göra om du missar att se ett stoppmärke och kör ut i korsningen?',
    options: ['Stanna direkt i korsningen', 'Kör vidare försiktigt — att stanna mitt i korsningen är farligare', 'Backa tillbaka'],
    correctIndex: 1,
    explanation: 'Att stanna mitt i en korsning kan vara livsfarligt. Kör vidare försiktigt och var beredd på annan trafik.',
  },
  {
    id: 'vaj-61',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör på en huvudled och ska svänga höger in på en mindre väg. En fotgängare vill gå över den väg du svänger in på. Vem har företräde?',
    options: ['Du, du kör på huvudled', 'Fotgängaren, vid sväng ska du väja för korsande gående', 'Ingen av er'],
    correctIndex: 1,
    explanation: 'Vid sväng ska du lämna företräde åt gående som korsar den väg du svänger in på.',
  },
  {
    id: 'vaj-62',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Två fordon ska båda byta fil — du åt höger och den andra åt vänster, och ni hamnar i samma fil. Vem väjer?',
    options: ['Den som byter till höger', 'Den som byter till vänster', 'Båda har väjningsplikt, den som bäst kan undvika faran'],
    correctIndex: 2,
    explanation: 'Båda har väjningsplikt vid filbyte. I praktiken ska ni vara uppmärksamma och samarbeta för att undvika kollision.',
  },
  {
    id: 'vaj-63',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'En gångfartsväg korsar din gata. Vem har företräde?',
    options: ['Du', 'Fordonen på gångfartsvägen', 'Gående alltid, men fordon på gångfartsvägen ska väja för dig'],
    correctIndex: 2,
    explanation: 'Fordon som kör ut från en gångfartsväg till en vanlig väg har väjningsplikt mot all trafik.',
  },
  {
    id: 'vaj-64',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du står vid rött ljus. Ljuset slår om till grönt, men en fotgängare är fortfarande kvar på övergångsstället. Vad gör du?',
    options: ['Kör, du har grönt', 'Väntar tills fotgängaren passerat', 'Tutar så fotgängaren skyndar sig'],
    correctIndex: 1,
    explanation: 'Du ska alltid låta fotgängaren passera helt innan du kör, även om ljuset blivit grönt.',
  },
  {
    id: 'vaj-65',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör på en väg med grönt ljus. I korsningen har det bildats kö så du inte kan ta dig igenom. Får du köra in?',
    options: ['Ja, du har grönt', 'Nej, du ska inte köra in om du riskerar att blockera korsningen', 'Ja, men bara om du blinkar'],
    correctIndex: 1,
    explanation: 'Du får inte köra in i en korsning om du riskerar att bli stående och blockera korsande trafik, även om du har grönt.',
  },
  {
    id: 'vaj-66',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du ska göra en U-sväng på en tvåfilig väg. Vem ska du väja för?',
    options: ['Bara mötande trafik', 'All trafik — mötande, bakomvarande och korsande', 'Ingen, U-sväng har företräde'],
    correctIndex: 1,
    explanation: 'Vid U-sväng har du väjningsplikt mot all övrig trafik.',
  },
  {
    id: 'vaj-67',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'I en korsning med högerregeln har bilen till höger om dig stannat och blinkar åt dig att köra. Får du?',
    options: ['Nej, lagen säger att du måste väja oavsett', 'Ja, men var försiktig och gör en bedömning', 'Nej, det kan vara en fälla'],
    correctIndex: 1,
    explanation: 'Om föraren tydligt visar att du får köra kan du göra det, men var försiktig — du har formellt väjningsplikt.',
  },
  {
    id: 'vaj-68',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Du kör in i en cirkulationsplats. Vad ska du alltid göra innan?',
    options: ['Blinka höger', 'Kontrollera väjningsplikt och lämna företräde åt trafik i rondellen', 'Öka hastigheten'],
    correctIndex: 1,
    explanation: 'Vid infart till rondell har du normalt väjningsplikt. Kontrollera att det är fritt innan du kör in.',
  },
  {
    id: 'vaj-69',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör och ser en person med vit käpp (syn-hjälpmedel) vid vägkanten. Vad bör du göra?',
    options: ['Tuta för att varna', 'Sakta ner kraftigt och var beredd att stanna', 'Kör förbi i normal hastighet'],
    correctIndex: 1,
    explanation: 'En person med vit käpp är synskadad. Visa extra hänsyn, sakta ner och var beredd att stanna.',
  },
  {
    id: 'vaj-70',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du ska köra in på en motorväg via accelerationsfältet. Trafiken på motorvägen är tät. Vem har företräde?',
    options: ['Du, du befinner dig på accelerationsfältet', 'Trafiken på motorvägen, du ska anpassa din infart', 'Ingen, det är sammanvävning'],
    correctIndex: 1,
    explanation: 'Trafik på motorvägen har företräde. Du ska anpassa hastighet och hitta en lucka under accelerationsfältet.',
  },
  {
    id: 'vaj-71',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör och ett utryckningsfordon med blåljus men utan siren närmar sig. Vad gäller?',
    options: ['Du behöver inte väja utan siren', 'Du ska ändå underlätta passage', 'Du ska öka farten och köra undan'],
    correctIndex: 1,
    explanation: 'Även om siren inte används ska du underlätta för utryckningsfordon med blåljus.',
  },
  {
    id: 'vaj-72',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör i en lång kö. Plötsligt ser du en ambulans i backspegeln. Du kan inte flytta dig åt sidan. Vad gör du?',
    options: ['Kör upp på trottoaren', 'Kör framåt om det går, annars stanna och låt ambulansen hitta en väg', 'Gör ingenting'],
    correctIndex: 1,
    explanation: 'Försök flytta dig om det är säkert. Om du inte kan — stanna och låt ambulansen manövrera förbi.',
  },
  {
    id: 'vaj-73',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Du kör mot grönt ljus i en korsning. Ska du ändå kolla om det är fritt?',
    options: ['Nej, grönt ljus ger dig full rätt', 'Ja, du ska alltid kontrollera att det är säkert', 'Bara om du ser andra fordon'],
    correctIndex: 1,
    explanation: 'Grönt ljus ger dig rätt att passera men inte garanti att det är säkert. Kontrollera alltid.',
  },
  {
    id: 'vaj-74',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du närmar dig en obevakad korsning i 50 km/h. Vilken hastighet bör du ha i korsningen?',
    options: ['50 km/h, det är hastighetsgränsen', 'Anpassad hastighet så du hinner stanna om det behövs', '30 km/h alltid'],
    correctIndex: 1,
    explanation: 'Vid obevakade korsningar ska du anpassa hastigheten så du kan stanna om trafik dyker upp.',
  },
  {
    id: 'vaj-75',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör på en prioriterad väg (huvudled) och den korsas av en gång- och cykelväg utan signalanläggning. Vem har företräde?',
    options: ['Du, huvudled har företräde', 'Gående och cyklister vid markerade övergångar', 'Ingen, alla samsas'],
    correctIndex: 1,
    explanation: 'Vid markerat övergångsställe har gående företräde även om du kör på huvudled. Vid cykelpassage ska du anpassa hastigheten.',
  },
  {
    id: 'vaj-76',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad ska du göra innan du svänger i en korsning?',
    options: ['Blinka i god tid och kontrollera dödvinkel', 'Bara blinka', 'Tuta'],
    correctIndex: 0,
    explanation: 'Innan du svänger ska du blinka i god tid, kontrollera speglar och dödvinkel.',
  },
  {
    id: 'vaj-77',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör på en väg och en fotgängare plötsligt springer ut i gatan utan att titta. Vem bär ansvaret vid en olycka?',
    options: ['Bara fotgängaren', 'Det beror på omständigheterna — bilföraren kan också hållas ansvarig', 'Alltid bilföraren'],
    correctIndex: 1,
    explanation: 'Ansvarsbedömningen beror på omständigheterna. Som förare har du ett ansvar att anpassa hastigheten och vara uppmärksam.',
  },
  {
    id: 'vaj-78',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör i en korsning med trafikljus. Ljuset visar grönt och du ska rakt fram. En spårvagn med grönt korsar din bana. Vem har företräde?',
    options: ['Du', 'Spårvagnen', 'Ingen, ni ska vänta på varandra'],
    correctIndex: 1,
    explanation: 'Spårvagnar har i regel företräde framför andra fordon även vid grönt ljus, om inte signalerna specifikt reglerar annorlunda.',
  },
  {
    id: 'vaj-79',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör och närmar dig ett obevakat övergångsställe. Det finns fotgängare som väntar men inte gått ut. Måste du stanna?',
    options: ['Nej, de har inte gått ut', 'Ja, om de tydligt visar att de vill gå', 'Bara om de tittar på dig'],
    correctIndex: 1,
    explanation: 'Du ska stanna om en fotgängare tydligt visar avsikt att korsa vägen, även om de ännu inte klivit ut.',
  },
  {
    id: 'vaj-80',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör på en fyrleds-korsning med högerregeln. Du och en mötande bil vill båda svänga vänster. Bilen till höger kör rakt fram. Vad gör du?',
    options: ['Väntar tills bilen till höger passerat, sedan svänger du', 'Kör direkt', 'Väjer bara för mötande'],
    correctIndex: 0,
    explanation: 'Du ska först väja för trafik från höger. Sedan, vid din vänstersväng, väja för mötande som kör rakt fram.',
  },
  {
    id: 'vaj-81',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad gäller vid ett markerat övergångsställe utan trafikljus?',
    options: ['Bilisten har företräde', 'Fotgängaren har företräde', 'Ingen har företräde'],
    correctIndex: 1,
    explanation: 'Vid markerade övergångsställen har gående företräde. Du ska stanna och låta dem passera.',
  },
  {
    id: 'vaj-82',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du ska köra om och måste byta fil. Vem har företräde — du eller bilen i filen du ska byta till?',
    options: ['Du, vid omkörning har man företräde', 'Bilen i filen du byter till', 'Den som kör snabbast'],
    correctIndex: 1,
    explanation: 'Vid filbyte har du alltid väjningsplikt mot trafik i den fil du byter till.',
  },
  {
    id: 'vaj-83',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör i ett bostadsområde utan skyltar. En lekande boll rullar ut på gatan. Vad gör du?',
    options: ['Tutar och kör vidare', 'Stannar omedelbart — barn följer ofta efter bollen', 'Saktar ner lite'],
    correctIndex: 1,
    explanation: 'En boll som rullar ut betyder ofta att ett barn kommer efter. Stanna och vänta tills du vet att det är säkert.',
  },
  {
    id: 'vaj-84',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vem har företräde vid en lågtrafikerad korsning med bara högerregel?',
    options: ['Den som kör snabbast', 'Fordonet som kommer från höger', 'Den som är störst'],
    correctIndex: 1,
    explanation: 'Högerregeln gäller — den som kommer från höger har företräde.',
  },
  {
    id: 'vaj-85',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör på en tvåfilig väg i stadstrafik. Filen du kör i ska ta slut och sammanfogas med den andra. Vad gäller?',
    options: ['Blixtlåsprincipen — varannan bil', 'Den som kör i den försvinnande filen har väjningsplikt', 'Den som kör snabbast'],
    correctIndex: 1,
    explanation: 'Den vars fil tar slut har väjningsplikt och ska anpassa sig till den andra filen. Blixtlåsprincipen är artighet, inte lag.',
  },
  {
    id: 'vaj-86',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör i rusningstrafik och stannar vid rött ljus. Ljuset slår om till grönt men korsningen framför är blockerad. Vad gör du?',
    options: ['Kör in i korsningen — du har grönt', 'Väntar tills korsningen är fri, även om du har grönt', 'Kör halvvägs in'],
    correctIndex: 1,
    explanation: 'Du får inte köra in i en korsning om du riskerar att blockera den, oavsett att ljuset är grönt.',
  },
  {
    id: 'vaj-87',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör på en gata med spårvagnsspår. Spårvagnen har eget spår men korsar din körbana vid en korsning. Vem har företräde?',
    options: ['Du', 'Spårvagnen', 'Den som kommer först'],
    correctIndex: 1,
    explanation: 'Spårvagnar har som regel företräde i obevakade korsningar oavsett riktning.',
  },
  {
    id: 'vaj-88',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Du ska svänga höger ut från en parkeringsplats. Från vänster kommer en cyklist. Vem väjer?',
    options: ['Cyklisten', 'Du, du kör ut från parkering', 'Ingen'],
    correctIndex: 1,
    explanation: 'Du kör ut från parkering och har väjningsplikt mot all trafik på vägen.',
  },
  {
    id: 'vaj-89',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du har företräde i en korsning men ser att den andra bilen inte verkar tänka stanna. Vad gör du?',
    options: ['Kör, du har ju rätt', 'Stannar — säkerhet går alltid före rätt', 'Tutar och kör'],
    correctIndex: 1,
    explanation: 'Företräde ger dig rätt, men inte garanti. Din skyldighet att undvika olycka väger tyngre.',
  },
  {
    id: 'vaj-90',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör på en enkelriktad gata och ska svänga vänster. Var placerar du dig?',
    options: ['Längst till vänster på gatan', 'I mitten', 'Längst till höger'],
    correctIndex: 0,
    explanation: 'På enkelriktad gata ska du placera dig längst till vänster vid vänstersväng.',
  },
  {
    id: 'vaj-91',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör på en motorväg och en annan bil kör in från ett accelerationsfält. Bilen hinner inte upp i tillräcklig hastighet. Vad gör du?',
    options: ['Tutar och kör förbi', 'Om möjligt byter du fil för att underlätta infarten', 'Bromsar tvärt'],
    correctIndex: 1,
    explanation: 'Även om du har företräde på motorvägen bör du underlätta genom att byta fil om det är möjligt och säkert.',
  },
  {
    id: 'vaj-92',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Du kör och ljuset slår om till gult. Du är nära korsningen. Vad gör du?',
    options: ['Gasar på för att hinna', 'Stannar om det går säkert, annars kör du genom', 'Stannar alltid'],
    correctIndex: 1,
    explanation: 'Gult ljus betyder att du ska stanna om det är möjligt utan fara. Hinner du inte stanna säkert kan du passera.',
  },
  {
    id: 'vaj-93',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör mot en korsning med väjningslinje (streckad linje) på vägen. Vad innebär det?',
    options: ['Du ska stanna helt', 'Du ska lämna företräde åt korsande trafik', 'Du har företräde'],
    correctIndex: 1,
    explanation: 'Väjningslinjen (streckad triangelmönstrad linje) markerar att du har väjningsplikt mot korsande trafik.',
  },
  {
    id: 'vaj-94',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör in på en väg från en gångfartsväg. Tre bilar, en cyklist och en fotgängare befinner sig på vägen. Vem väjer du för?',
    options: ['Bara bilarna', 'Alla — bilar, cyklist och fotgängare', 'Bara motorfordon'],
    correctIndex: 1,
    explanation: 'Vid utfart från gångfartsväg har du väjningsplikt mot all trafik på den väg du kör ut på.',
  },
  {
    id: 'vaj-95',
    category: 'vajningsplikt',
    difficulty: 'easy',
    question: 'Vad innebär det att ha "företräde"?',
    options: ['Att du alltid kan köra utan att titta', 'Att andra ska lämna dig plats, men du ska ändå vara försiktig', 'Att du får köra hur snabbt du vill'],
    correctIndex: 1,
    explanation: 'Företräde innebär att andra ska väja, men du har alltid ansvar att vara uppmärksam och undvika olyckor.',
  },
  {
    id: 'vaj-96',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'En lastbil med blinkers vill byta till din fil. Du kör i ett blindläge (dödvinkel). Vem bär ansvaret om det blir en olycka?',
    options: ['Du', 'Lastbilsföraren som byter fil', 'Ingen — det är en olycka'],
    correctIndex: 1,
    explanation: 'Den som byter fil har alltid väjningsplikt och ansvar att kontrollera dödvinkeln.',
  },
  {
    id: 'vaj-97',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör i en korsning med "grönt filter" (grön pil åt höger). Vad innebär det?',
    options: ['Du får svänga höger även om rakt-fram-signalen är röd', 'Bara cyklister får svänga höger', 'Du ska stanna och sedan köra'],
    correctIndex: 0,
    explanation: 'Ett grönt filter ger dig tillstånd att svänga i pilens riktning även om huvudsignalen visar rött.',
  },
  {
    id: 'vaj-98',
    category: 'vajningsplikt',
    difficulty: 'medium',
    question: 'Du kör och ser en begravningskortege. Vad gäller?',
    options: ['Du ska stanna och vänta tills hela kortegen passerat', 'Du bör visa hänsyn, men ingen lag kräver att du stannar', 'Du ska köra om snabbt'],
    correctIndex: 1,
    explanation: 'Det finns ingen laglig skyldighet att stanna för begravningskorteger, men det är vanlig hänsyn att inte bryta igenom.',
  },
  {
    id: 'vaj-99',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör i en korsning och gult ljus blinkar. Samtidigt finns en väjningspliktsskylt. Vad gäller?',
    options: ['Blinkande gult upphäver väjningsplikten', 'Väjningspliktsskylten gäller', 'Inget gäller, du kör fritt'],
    correctIndex: 1,
    explanation: 'Blinkande gult betyder att signalen inte fungerar normalt. Vägmärken (väjningsplikt) gäller istället.',
  },
  {
    id: 'vaj-100',
    category: 'vajningsplikt',
    difficulty: 'hard',
    question: 'Du kör i en kö och ser att en buss framför dig blinkar ut från hållplatsen. Bussen är stor och du ser inte vad som finns bakom. Vad bör du tänka på?',
    options: ['Kör om bussen snabbt', 'Var beredd på fotgängare som kan komma framför bussen', 'Tuta så bussen väntar'],
    correctIndex: 1,
    explanation: 'Bakom en buss kan fotgängare dyka upp — särskilt barn. Var extra uppmärksam.',
  },
];
